### ISSUE TITLE
Resize example has a bug when the example is taller than the screen

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#100]
Tested in Chrome, OSX

To reproduce:

1. Find an example taller than the page (or resize one to make it taller)
1. Drag the resize control

Result: the example instantly jumps up so it's very short on the page

Expected: resize the example from the existing size

**Comment by igloosi** [comment]
can't reproduce it any more.
do you still experience it @joelanman ?

**Comment by nickcolley** [comment]
I think this was fixed based on the other related issues to do with overflows, please re-open if not :)
