### ISSUE TITLE
Add lead in line to list example

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-design-system#1013]
The GOV.UK style guide requires that unordered lists have a lead in line. The guidance says as much, but the example doesn't include one. Since it's always expected to be there, I think it would be helpful to include in the example.

## Current:
![Screenshot 2019-08-07 at 12 54 20](https://user-images.githubusercontent.com/2204224/62621020-b47ab000-b912-11e9-8ba7-44321442b2cf.png)

## Proposed:
![Screenshot 2019-08-07 at 12 57 03](https://user-images.githubusercontent.com/2204224/62621100-fc013c00-b912-11e9-8a3f-fb307d172a97.png)

**Comment by edwardhorsford** [comment]
I also raised an issue on the design system backlog about the lead in line being really far from the bullets - but possibly I'm not marking it up correctly - another reason to show a coded example of the lead in line.

**Comment by nickcolley** [comment]
For other [core styles we have some contextual changes](https://github.com/alphagov/govuk-frontend/blob/master/src/govuk/core/_typography.scss#L161), so we could consider doing the same here, it's not without risk but worth thinking about.

**Comment by timpaul** [comment]
Hi @edwardhorsford - thanks for this. Would you be interested in raising a pull request to update the example as per your suggestion ([here's the relevant file](https://github.com/alphagov/govuk-design-system/blob/master/src/styles/typography/list-bullet/index.njk))? We'd like to leave the lead line margin as it is though, as this is currently the style across the whole of GOV.UK and there are currently no plans to change this.

**Comment by edwardhorsford** [comment]
@timpaul pr raised. Thanks!
