### ISSUE TITLE
Guidance/examples on label weight and size can be confusing

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#1021]
Raising as it was raised by someone on Slack.

The examples of radios and checkboxes are in the context where they are the only thing on the page - the legend is the page heading.

Examples of other components like text input and textarea are not in the context where they are the only thing on the page.

This seems inconsistent, possibly we need examples of both contexts in all places?

**Comment by EddieCurtis** [comment]
Screenshot showing example of this issue:
![image](https://user-images.githubusercontent.com/3598645/62945114-02d9f400-bdd6-11e9-84e1-1f6827d08cb5.png)
