### ISSUE TITLE
Colours in code blocks do not meet colour contrast

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#1032]
At least three of the colours we use within code blocks do not meet colour contrast (4.5) against the background (`#f3f2f1`):

- `#dd1144`, which has a colour contrast of 4.43
- `#007f80`, which has a colour contrast of 4.32
- `#999998`, which has a colour contrast of 2.55

**Comment by DebsDee** [comment]
Replacing:

* ```#dd1144``` with ```#912b88``` 
* ```#007f80``` with ```#00703c```
* ```#000080``` with ```#1d70b8```

All have a colour contrast of 4.5 and updates the appearance of the code block from the first image to the second one.

<img width="450" alt="code-blocks" src="https://user-images.githubusercontent.com/7225720/64248516-34dc0300-cf09-11e9-9142-b6475ad46e4b.png">

Another option could be to remove the grey background:

<img width="450" alt="code-block-2" src="https://user-images.githubusercontent.com/7225720/64249585-ebd97e00-cf0b-11e9-82f3-32c94d470649.png">

Or revert the background-color to the overridden grey ```#f8f8f8```

<img width="450" alt="code-block-3" src="https://user-images.githubusercontent.com/7225720/64249744-5db1c780-cf0c-11e9-83af-76ddc92e4f45.png">
