### ISSUE TITLE
Add accessibility information about GOV.UK Frontend

### ISSUE THREAD

**Issue by m-green** [alphagov/govuk-design-system#1060]
## What
We need to publish information about accessibility of GOV.UK Frontend for developers using it in their services. 

## Why
To help developers understand how far GOV.UK Frontend will help make their services accessible.  

## Who needs to know about this
Amy, Tim

## Further detail
This is likely to be one page of documentation, and include [known errors and warnings raised by automated tools](https://github.com/alphagov/govuk-design-system/issues/1048).

## Done when

- [x] We've been through the Post-Its from Amy's exercise about accessibility content, to decided what we must include in this iteration of the information (what 'sections' essentially).
- [x] We've identified who's best to talk to on the team to gather the facts about each thing we include.
- [x] Mark (and Amy) have decided on an appropriate place for the information.
- [x] Mark (and Amy) have written the documentation.
- [x] The documentation has been reviewed by the team.
- [x] The documentation has been 2i'd by a technical writer.
- [x] The documentation has been published.
- [ ] We've updated the Design System accessibility statement to add a link back to these docs

**Comment by m-green** [comment]
@nickcolley Following our chat yesterday - when you have a chance, could you send me a summary list of known accessibility issues if you use compatibility mode?

**Comment by kellylee-gds** [comment]
@m-green can this be closed?

**Comment by m-green** [comment]
@kellylee-gds Yes indeed!
