### ISSUE TITLE
Surface accessibility, guidance etc. in search

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#1062]
We currently only surface published styles, components and patterns in the Design System search.

However we now have a lot more valuable content such as the focus guidance, the accessibility page, the labels, legends and headings guidance etc. which it would be good to make discoverable via search.

As raised by @amyhupe

**Comment by amyhupe** [comment]
Need to scope the work of this and add relevant search terms.

**Comment by edwardhorsford** [comment]
+1 for visibility / more in search - I just failed to find the focus guidance having checked everything except 'getting started'.

**Comment by querkmachine** [comment]
This appears to have been resolved since it was originally opened. All sections of the DS site are now surfaced in the search function.
