### ISSUE TITLE
Make "Experimental" tag more understandable or remove

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#1093]
Body of epic to be completed after a kick off session

**Comment by kellylee-gds** [comment]
## What

Decide if experimental tag is useful to have. If not, remove. 

If the experimental tag is useful, we need to help users understand what it means and how they should be using components or patterns with this tag. 

## Why

We've had some feedback from users that the meaning of "Experimental" can be misunderstood as "completely untested suggestion that you definitely shouldn't use on a real service".

There isn't an establish criteria and process to put things in or move things out of experimental. 

## Done when

- [ ] TBC


--- 
Previous discussion 

I spoke to Amy. We did testing with the the tag and it tested well. At the time we also explored tags like "Alpha", "Beta" and "Live" but these got confused with service phases.  

Amy made the point that a single word will never be enough to explain all the complexities.

We could consider having a page that explains the reasoning behind "Experimental" and link to it from the tag (although I'm aware that the tag isn't designed to act as a link and doesn't have a focus state...). 

We already have 
> Components and patterns which are not proven usable can be published as experimental. But they must be clearly based on relevant user research from other organisations and best practice, and meet the other criteria.

on [Contribution criteria](https://design-system.service.gov.uk/community/contribution-criteria/) but it's not easy to link to.

**Comment by EoinShaughnessy** [comment]
Do we need to create a docs issue if we decide to keep the label? Or would the docs work be part of the acceptance criteria for this epic?

**Comment by joelanman** [comment]
I think a question is, how should teams treat Experimental components or patterns differently to non Experimental? Some suggestions, I have no strong opinion on them:

 - a team shouldn't be required to use them in a service assessment
 - a team should do their own research specifically on this component/pattern

**Comment by joelanman** [comment]
came up on support today, whether you need to start with an experimental pattern in order to [pass assessment](https://www.gov.uk/service-manual/design/making-your-service-look-like-govuk)

**Comment by kellylee-gds** [comment]
Closing this as per https://github.com/alphagov/govuk-design-system/pull/3198#top
