### ISSUE TITLE
Suggestion: mention govuk-text-colour mixin on colours page

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-design-system#1094]
I recently discovered the `govuk-text-colour` mixin, and wondered when to use that vs the variable $govuk-text-colour.

From talking with @nickcolley and @36degrees, it sounds like teams should mostly use the mixin.

The mixin isn't mentioned on the colours page - should it be?

**Comment by nickcolley** [comment]
Hey Ed,

We want to look at documenting mixins in a bigger piece of work, so I'm going to close this in favour of that issue: 

https://github.com/alphagov/govuk-frontend/issues/1634

This will be useful for helping us improve the text colour documentation, thanks!

**Comment by edwardhorsford** [comment]
@nickcolley this was opened at the request of @36degrees

**Comment by nickcolley** [comment]
@edwardhorsford opening this issue was the right thing to do, I'm just closing it to tidy things up since we discussed it and decided there wasnt a smaller piece of work we could do to resolve this, hope that makes sense.
