### ISSUE TITLE
Add guidance to the text input component to help users understand when to use input type="number"

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#1128]
## What

Add guidance to help users understand when it's appropriate to use `input type="number"`

## Why

We have a lot of research that shows that `input type="number"` can be problematic and we believe that it should only be used in very specific contexts.

## Done when…

- [x] We understand whether there are valid use cases for using `input type="number"` that outweigh the negatives (usability and accessibility issues)
- [x] We've drafted guidance to add to the Design System to help users understand when they should use it; when not; and what they should use instead
- [ ] We've updated the html and nunjucks examples
- [ ] Guidance 2i'd
- [ ] Guidance published
- [ ] Old url retired and redirected

**Comment by StephenGill** [comment]
Suggested update to text-input guidance here: https://docs.google.com/document/d/1waXRg1DrwZgMVEQJkjLyNQ2bK5beatTcZPRxNekETtI/edit

Needs a review for accuracy from @hannalaakso

**Comment by hannalaakso** [comment]
Thanks @StephenGill this is a great start! There's a lot to talk about when it comes to `type="number"` so maybe we should write the blog post first and then distil this content from there...
