### ISSUE TITLE
Write a blog post that covers the research done around input type="number" and the changes made

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#1130]
## What

Write a blog post that covers the research done around `input type="number"` and the changes made as a result of it.

We might want to talk about e.g. why we want to use input type="number" (numeric keypad on touchscreen devices), [the various usability and accessibility issues](https://github.com/alphagov/govuk-frontend/issues/1449), the bugs that we've reported to browser vendors, and the changes that we've made as a result.

## Why

Share what we've learnt in our research – although we'll be documenting some of this in the Design System we won't provide as much detail there, so a blog post is a good place to go into more detail.

## Done when

- [x] Contact blogs editor to work out whether we can publish the blog; which blog it should be published on
- [x] Blog post drafted
- [ ] Blog post 2i'd
- [ ] Blog post published

**Comment by hannalaakso** [comment]
Blocked for 2i

**Comment by hannalaakso** [comment]
Blocked for 2i again
