### ISSUE TITLE
step by step guidance update

### ISSUE THREAD

**Issue by kateiw** [alphagov/govuk-design-system#1132]
title: Step by step navigation
description: A starting point for your digital service on GOV.UK
section: Patterns
theme: Pages

We have reviewed the whole page of guidance to update and clarify it, and to change the way people get in touch with us as a team (people now need to go through content support and raise a ticket).

The updated guidance is here in full: https://docs.google.com/document/d/1cDo82BrCV8OHtuG-SAturoG_KEC7_z8h5gXeoMNhMlE/edit?usp=sharing

We gave up doing tracked changes because we tweaked so much, so it's probably easiest to replace the whole lot!

Give me a shout if you have any questions, thanks a bunch!
Kate

**Comment by nickcolley** [comment]
Thanks @kateiw, we'll discuss this as a team at 2pm in our weekly triage session. Could you set the permissions for anyone in GDS to view them please?

**Comment by StephenGill** [comment]
Changes made, with some tweaks for style and clarity. 

Ready for review: https://github.com/alphagov/govuk-design-system/pull/1134

**Comment by StephenGill** [comment]
OK, this should be live now. @kateiw - feel free to re-open if you spot any problems.

And thanks for getting in touch.
