### ISSUE TITLE
Take a look at Uterances project to tie discussions on this repo to the individual pages

### ISSUE THREAD

**Issue by nschonni** [alphagov/govuk-design-system#1133]
## What
> Give a brief description of the style, component or pattern you want to propose.

Since it seems like there is mostly a one-one link between the patterns and issues in this repo, using something like https://utteranc.es/ to display the disucussion in context of the page might be appropriate.

## Why
> Explain why you think this should be added to the GOV.UK Design System.
>
> - What evidence do you have that it's needed by multiple services across government?
> - What evidence do you have that it meets the needs of the users of those services?
> - Have you checked that it doesn't already exist in the GOV.UK Design System? 

This might blur the lines if it isn't a pattern for the Design System itself, but it is helpful to have both the discussion and the documentation in the same context.

## Anything else
> Include links to any examples, research or code to support your proposal, if available.

This is an open source version of what is used on the https://docs.microsoft.com/ platform. EX: their  issues per page through metadata like https://docs.microsoft.com/en-ca/visualstudio/mac/azure-functions?view=vsmac-2019

**Comment by nickcolley** [comment]
Hey @nschonni,

This is a really interesting suggestion...

We've been thinking of ways to better get feedback from the community backlog into the website but think doing something more curated makes more sense for us at the moment.

In the future if we decide to do something more embedded like you're suggesting this will be useful to refer to so thanks for sharing the idea with us.

I'm going to close this for now but will reopen if we decide to explore it more.
