### ISSUE TITLE
Resize in safari jumps to the top of the page

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#114]
If you scroll down a page in safari, then resize the browser, it jumps to the top of the page

**Comment by nickcolley** [comment]
Reproduced in Version 11.0.1 (11604.3.5.1.1)

Confirmed this will happen even when JavaScript is disabled, which may mean this is not fixable

**Comment by nickcolley** [comment]
Also noted that you can't resize horizontally on Safari

**Comment by nickcolley** [comment]
Created a minimal JSBin, where this doesnt seem to happen (and also allows proper resizing).

http://output.jsbin.com/xefilax

**Comment by igloosi** [comment]
fixed in https://github.com/alphagov/govuk-design-system/pull/382

**Comment by nickcolley** [comment]
This is fixed now
