### ISSUE TITLE
Add guidance about optimal line lengths for text

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1140]
There was a recent discussion in our accessibility forum about the optimal line length for body copy. Not sentence length, which is a different issue. There's no guidance in the Design System about this, but it does come up from time to time - and it would help to explain why we set paragraphs in a 2/3rd width column, even if there's no content in the right hand column.

**Comment by StephenGill** [comment]
Sure - we could cover it on the 'layout' page.

What is the rationale - it it just visual consistency with the main GOV.UK platform?

**Comment by nickcolley** [comment]
Is this issue a duplicate of https://github.com/alphagov/govuk-design-system/issues/1126 ?

**Comment by timpaul** [comment]
Aaah good spot - thanks @nickcolley. I'll close this one then. 

@StephenGill - we're occasionally asked about optimum line length, and in service assessments we sometimes see layouts where body copy runs the full width of the GOV.UK page template - which makes it harder to read. We've always recommended using the 2/3rd width column for body text for that reason - but this isn't reflected in our guidance right now.
