### ISSUE TITLE
Add coloured tags to tag component

### ISSUE THREAD

**Issue by StephenGill** [alphagov/govuk-design-system#1143]
## What
Publish updated tag component.

## Why
So Design System users can use the improved component.

## Who needs to know about this
Stephen (guidance), developer, contributor

## Further detail

Additional Tag modifier classes for different colours PR [#1711](https://github.com/alphagov/govuk-frontend/pull/1711)

Guidance for the additional colours for the Tag component PR #1141 

## Done when
- [x] Update component code
- [x] Draft guidance
- [x] Guidance reviewed
- [ ] Pattern published / merge PRs
- [ ] New pattern promoted on GDS and cross-government Slack channels

**Comment by kellylee-gds** [comment]
Blocked until 13 Feb when we will receive full working group feedback.

**Comment by timpaul** [comment]
- [Summary of feedback and decisions](https://github.com/alphagov/govuk-design-system-backlog/issues/62#issuecomment-590800378)
- [Full decision log ](https://docs.google.com/document/d/1EV7kMUam8EUoDyo8M-qg-WfNDc4QAdqaNXiJNOr_WSQ/edit#)
