### ISSUE TITLE
Add guidance on when to underline links and when not to

### ISSUE THREAD

**Issue by christopherthomasdesign** [alphagov/govuk-design-system#1159]
## What

Write guidance on when to underline links and when not to

## Why

We use a mixture of link styles on GOV.UK and don't clearly explain the rationale for things like when to use underlines or not. 

## Who needs to know about this

Tim, Stephen

## Done when

- [x] We have clear rationale and guidance for when not to underline links
- [ ] We've published it to the Design System

**Comment by kellylee-gds** [comment]
@christopherthomasdesign I've added effort and priority labels to this story. Feel free to change if you disagree with what I've assigned.
