### ISSUE TITLE
Gather and analyse feedback about contributions in January 2020

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1169]
## What

Gather feedback from the contributors, stewards and working group members for Feb 2020's 2 contributions, then iterate the model and associated guidance and templates as necessary.

## Done when
- [x] Feedback gathered
- [x] Feedback reviewed and actions taken

## Who needs to know about this

@RosieClayton , @StephenGill , @timpaul , @joelanman

**Comment by RosieClayton** [comment]
Shall we do a remote retro with the stewards and working group? 
I am happy to do the normal interviews with contributors.

**Comment by kellylee-gds** [comment]
Retro to be booked in coming weeks.
