### ISSUE TITLE
Provide code examples for the address lookup pattern

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#1188]
Raised on behalf of a user:

> The Address pattern documentation in GOV.UK Design System (available here: https://design-system.service.gov.uk/patterns/addresses/) shows a video of an example of the address lookup and provide guidance on when to use this pattern, but does not provide a code example of this for prototyping.
>
> Is providing a code example of the address lookup that can be used with the GOV.UK Prototyping Kit something that you could look to add to the documentation for the Address pattern in the future?

**Comment by timpaul** [comment]
Closing as this work will be covered in https://github.com/alphagov/govuk-design-system/issues/1190
