### ISSUE TITLE
Make it clear that `pattern` with `type="text"` requires `novalidate` on form

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#1191]
As we include the `pattern` attribute on `type="text"` when collecting numbers for backwards compatibility with older iOS devices, we should indicate in the guidance that this requires `novalidate` on the form to turn off HTML5 validation. 

When our [awesome new guidance about validation](https://github.com/alphagov/govuk-design-system/pull/1164) is published, we should consider linking to it both from the [Numbers guidance](https://design-system.service.gov.uk/components/text-input/#numbers) and the[ Bank details pattern](https://design-system.service.gov.uk/patterns/bank-details/) to explain this.

**Comment by hannalaakso** [comment]
Also consider adding `novalidate` to the form input itself

**Comment by nickcolley** [comment]
Some components like the date input do really odd HTML5 validation without this so I think perhaps we should consider adding `novalidate` to the components where the HTML5 validation would really alter how we designed the component.

Noticed that the recent corona form work they didnt realise they needed novalidate too...

**Comment by joelanman** [comment]
@nickcolley thanks, looking to add to the corona forms now

**Comment by nickcolley** [comment]
@joelanman is already added to the vulnerable people form, just FYI.

**Comment by 36degrees** [comment]
The `novalidate` attribute can only be added to the `form` element, so we can't add it to the components individually.

We could consider creating a form component that incorporates this stuff, I guess.

**Comment by nickcolley** [comment]
Is it that `formnovalidate` only works on submit buttons?

https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fs-formnovalidate

**Comment by 36degrees** [comment]
Yep, `formnovalidate` is designed for cases where you have e.g. a 'Save Draft' button where you don't want to trigger validation, and a 'Publish' button where you do.

**Comment by nickcolley** [comment]
OK, better guidance it is then. 👍

**Comment by terrysimpson99** [comment]
I support better guidance on this. We have at least one service that shows 'Please match the format requested'. I was told it was there to suit the needs of apple users. A search for 'Please match the format requested' failed to find any guidance that mentions it.

Recently we were developing using the latest out-of-the-box code. We have skilled devs and were confident of getting an implementation that meets our design intent and meets guidance. However I noticed the new code also produced 'Please match the format requested'. I nearly didn't spot it. It may have got all the way into production if the dev and I weren't so determined to challenge it. It took some back and forth on slack with helpful people to work out what was going on.

I welcome any work resolves it. I'd like the term 'Please match the format requested' to be mentioned somewhere. This would provide a destination for searches on that term and would give us something to point at when lobbying for removal of the validation.

**Comment by joelanman** [comment]
@terrysimpson99 I'm not sure if this is what you mean, but we do say explicitly to turn off all html5 validation, using `novalidate`, if you need something to point people to:

https://design-system.service.gov.uk/patterns/validation/

**Comment by terrysimpson99** [comment]
Yes. It is indeed helpful now. But I had no way of finding it. The dev believed the code was correct because it was out-of-the-box and the meme 'it helps apple users' was strong.

I searched the guidance for 'Please match the format requested' and found nothing. 

It would help if `https://design-system.service.gov.uk/patterns/validation/` included a reference to both `pattern="[0-9]*"` and 'Please match the format requested'. Is that possible?

**Comment by hannalaakso** [comment]
Thanks @terrysimpson99 👍 It'd be useful to have your feedback on https://github.com/alphagov/govuk-design-system/pull/1291.

I've tested the HTML5 validation of `pattern` in different browsers and the wording for the validation message varies:

- Chrome: 'Please match the format requested.'
- Safari: 'Match the requested format'
- Firefox: 'Please match the requested format.'
- iOS: 'Match the requested format.'
- IE11: 'You must use this format:'

so it probably wouldn't make sense to use an exact phrase in the guidance.

**Comment by terrysimpson99** [comment]
Looks good to me. Thanks for your work. It'd be great if somebody else could confirm the additional guidance works for them.
