### ISSUE TITLE
Plan 2021 Frontend survey

### ISSUE THREAD

**Issue by RosieClayton** [alphagov/govuk-design-system#1195]
## What
Sending out the 2021 frontend survey 
## Why
To understand what tools, architecture and frameworks are being used across government 
## Who needs to know about this
The frontend community, our team
## Further detail
We sent out the frontend survey last year and its time to do it again. 
Blog post from the last survey https://technology.blog.gov.uk/2019/03/18/learn-the-results-from-the-cross-government-frontend-technology-survey/
## Done when

- [x] reviewed the previous survey questions and drafted the new survey
- [x] presented to the Design System team to give everyone an overview of what the FE survey is and asked for feedback on the draft survey
- [x] presented to the GDS FE community to give everyone an overview of what the FE survey is, asked for feedback on the draft survey and checked if there are other things we should ask about in the survey
- [x] created a card for the comms side of the work
- [x] created a card for publishing the findings
- [ ] finalised the questions for the survey

**Comment by nickcolley** [comment]
You can find all the surveys so far here: Government Frontend Surveys

I have written a document with some notes on how the first one was run, this includes suggestions to change for next time. You should be able to copy and paste the folder and adjust things as necessary for 202X.


How we ran the frontend survey 2018

**Comment by hannalaakso** [comment]
Moving this to blocked as waiting to get feedback from GDS Frontend community.
