### ISSUE TITLE
Not clear what the 'static' spacing scale is.

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-design-system#1210]
The [spacing page](https://design-system.service.gov.uk/styles/spacing/#spacing-on-custom-components) refers to the 'static' spacing scale, but it's not clear what this is. From testing I think it equates to the desktop column of the responsive scale - but it's not possible to know this from the content.

I think either:
* Update the responsive table to specify which column is the static also
* Add a second table for the static scale.

**Comment by 36degrees** [comment]
Pulling this in to the sprint as I believe it needs to be done before we can do #2244. It's hard to document the static spacing overrides without also explaining what the static spacing scale is!
