### ISSUE TITLE
Add guidance and example for numbers with decimals

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#1212]
## What

Add guidance to tell users what to do when asking for numbers that might include a decimal place.

In these cases, they should use `inputmode="decimal"` rather than `inputmode="numeric"`.

We should add additional guidance and an example to the text input component.

## Why

This came up whilst on support:

> "the text-input component for numbers brings up the numeric keyboard for mobiles - however, on iOS it doesn’t seem to show a bullet point on the keyboard (but does for Android)"

## Further detail

Questions we probably need to answer:

- Should they still use the `pattern` attribute with this? Does that trigger the correct keyboard on older iOS devices?
- What example should we use for this? The user who raised the original support query was asking about prices, but that adds complexity around input prefixes and the £ sign etc.

**Comment by hannalaakso** [comment]
Further reason that this is needed: @alex-ju made a good point that we also already have [guidance that talks about decimal numbers](https://design-system.service.gov.uk/components/text-input/#if-the-input-is-not-an-amount-of-money-and-the-field-allows-decimals) so we should cover how to do that with our component.

**Comment by alex-ju** [comment]
We updated a currency input in one of the CV19 services to use [`inputmode="decimal" pattern="[0-9]+([.,][0-9]+)?"`](https://github.com/alphagov/govuk-coronavirus-business-volunteer-form/pull/232) after receiving similar feedback from users that they cannot add decimal separators. I look forward to this being addressed properly.

**Comment by 36degrees** [comment]
@alex-ju do you know if the `pattern` attribute has any effect on the keyboard mode?

As far as I know, iOS only does anything special if the `pattern` attribute [matches `\d*` or `[0-9]*` exactly](https://github.com/WebKit/webkit/blob/ce279990f85656893c57decbffe2b9067176d02e/Source/WebKit/WebProcess/WebPage/ios/WebPageIOS.mm#L2456-L2457), and in your screenshots of iOS 11 it seems to be using the alphanumeric keypad (iOS 12.3 and above support `inputmode`, so pattern won't be doing anything there).

Unless the `pattern` attribute has any effect, I'd be tempted to omit it and just use `inputmode="decimal"` alone.

**Comment by alex-ju** [comment]
> @alex-ju do you know if the `pattern` attribute has any effect on the keyboard mode?
> 
> As far as I know, iOS only does anything special if the `pattern` attribute [matches `\d*` or `[0-9]*` exactly](https://github.com/WebKit/webkit/blob/ce279990f85656893c57decbffe2b9067176d02e/Source/WebKit/WebProcess/WebPage/ios/WebPageIOS.mm#L2456-L2457), and in your screenshots of iOS 11 it seems to be using the alphanumeric keypad (iOS 12.3 and above support `inputmode`, so pattern won't be doing anything there).
> 
> Unless the `pattern` attribute has any effect, I'd be tempted to omit it and just use `inputmode="decimal"` alone.

It may be redundant, indeed. I might have been working under the assumption that if a `pattern` is required for `inputmode="numeric"` it would be similar for a decimal input. Good job digging into the actual objective-c implementation for this.

**Comment by 36degrees** [comment]
After doing further research, we're now going to recommend using `input type="text"` without an `inputmode` or `pattern` attribute when asking for decimal numbers.

See the discussion in https://github.com/alphagov/govuk-design-system/pull/1279 for more information.

**Comment by MalcolmVonMoJ** [comment]
Should there be any guidance on whether we should accept or reject comma separators?  

I'm thinking on the one hand, they are common when typing in large numbers.  e.g. 1,000,000 But on the other they are used in mainland Europe for the decimal separator. 1,5 for 1½. 

If we strip them out, a well-meaning European could enter 1,5 meaning 1.5, and inadvertantly enter 15.  If we error, then someone entering an ordinarily perfectly acceptable 25,000 would be inconvenienced.  

So by that logic we should only accept them in the -3xth position of the string, from the end or decimal point?  

All this assumes that we don't want to go down the road of accepting European separators.

**Comment by peteryates** [comment]
Probably also worth noting that some countries in Europe (Switzerland and Liechtenstein) use `'` as a decimal separator (eg `1'234'567.89`). Plus, there are lots of people within the UK who will be more familiar with the [Indian numbering system](https://en.wikipedia.org/wiki/Indian_numbering_system) which group digits into powers of hundreds (`1,23,45,67.89`).
