### ISSUE TITLE
Address problems with form labels and hint text

### ISSUE THREAD

**Issue by christopherthomasdesign** [alphagov/govuk-design-system#1222]
## What

Help users structure their forms using legends, labels and hint text. Whether they use 'one thing per page' or multiple questions on a page.

## Why

There are a number of issues that have been raised on form labels and hint text that make sense to tackle together. For example:
* we use a mixture of examples for form elements – some where the label is the page heading, some where it is not
* we’re not clear on when to bold and when not to bold form labels
* grey hint text has been flagged on a number of occasions as being hard to read, even though it passes AA colour contrast
* if your form field label is a heading, it seems unnecessary to make the hint text grey
* decisions on these things are seemingly to do with page hierarchy and context – we don’t currently offer much guidance on how to make these decisions
* alternatively we could change the default styling so people don’t have to make these decisions e.g. say all form labels should be bold

## Who needs to know about this

Tim, Joe, most of the team tbh

## Further detail

Related issues and/or comments:
* https://github.com/alphagov/govuk-frontend/issues/1134
* https://github.com/alphagov/govuk-design-system-backlog/issues/51#issuecomment-584223652
* https://github.com/alphagov/govuk-design-system/issues/1150
* https://github.com/alphagov/govuk-design-system/issues/1021

## Done when

- [x] Changes made to examples to make our approach consistent
- [x] Any styling changes made to GOV.UK Frontend

**Comment by StephenGill** [comment]
Happy to have a go a drafting something on this, but feels like we need consensus on some high level design decisions first. I'll put something in the calendar. I think we need to decide:

1. whether we want to rule out abandoning the need for a visual distinction between hint text and other text - ie give everything the same prominence.
2. whether we want to rule out darkening the grey used for the hint text element (I know we've been reluctant to look at one element in isolation in the past).
3. whether we want rule out different approaches to expressing the hierarchy -eg scaling everything up so we can increase the font size of the hint text?

If we don't want to do any of those things, one option would be to draft some general guidance on how to express information on a page - basically start with everything in the standard font colour and weight and only add more complexity if you need to.

**Comment by christopherthomasdesign** [comment]
Had a chat with @timpaul on this today. 

Decided for now to start by slightly darkening the hint text colour for now, as discussed in [Frontend #1134 when we last explored this](https://github.com/alphagov/govuk-frontend/issues/1134). This has the fewest knock-ons to the rest of the system and could improve things in the short term for end users. If we see the hint text readability issue come up again, we could continue looking at the idea of bolding labels and so on.

We'll also make the labels on textarea and text input examples larger so they're consistent with our other form element examples – making 'one thing per page' the default for everything. This should address #1021
