### ISSUE TITLE
Update the 'Emergency banner' pattern based on feedback from the working group

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1229]
Because of urgent timescales we had to publish this [pattern](https://design-system.service.gov.uk/patterns/understand-the-impact-of-an-emergency/) before we'd had time to get feedback from the working group. We [have the feedback](https://docs.google.com/document/d/1hH2o1Vt8j8Lk3PLd4Xh3pQrTGBDt64Ll25Pv_nF_WDg/edit) now, so should review it and update the pattern when we can.

**Comment by kellylee-gds** [comment]
Closing this issue as I have converted feedback from the working group into issues:

https://github.com/alphagov/govuk-design-system/issues/1239
https://github.com/alphagov/govuk-design-system/issues/1240
https://github.com/alphagov/govuk-design-system/issues/1241
https://github.com/alphagov/govuk-design-system/issues/1242
https://github.com/alphagov/govuk-design-system/issues/1243
