### ISSUE TITLE
Help people use tabular numbers

### ISSUE THREAD

**Issue by christopherthomasdesign** [alphagov/govuk-design-system#1233]
## What

We don't mention tabular numbers anywhere in the Design System. We should.

## Why

Because they're a useful feature. Some users might not know how and when to use them, or even know they exist.

## Who needs to know about this

Tim, Joe?

## Further detail

This could take form as guidance on the typography page, the table component, or both.

## Done when

TBC

**Comment by querkmachine** [comment]
As of v5, the only way for a user to manually activate tabular numbers is via [the `govuk-font` mixin](https://frontend.design-system.service.gov.uk/sass-api-reference/#govuk-font) in Sass, which isn't something we usually go into detail about on the Design System website.

Tabular numbers are hardcoded into particular scenarios where they're useful — currently numerical cells in tables, text inputs with extra letter spacing, and the counter of the character count component. We don't provide any utility or override classes to enable them.

Whilst we can explain their purpose, we don't really make it that easy to use tabular numbers on their own terms. I'm not sure how we could really document them in a useful way without first doing something in Frontend.

**Comment by 36degrees** [comment]
I'd like to [split the tabular numbers functionality out from the `govuk-font` mixin](https://github.com/alphagov/govuk-frontend/issues/3778) soon-ish, which would make this easier to document.

**Comment by owenatgov** [comment]
We now mention tabular numbers extremely briefly on the [type scale page](https://design-system.service.gov.uk/styles/type-scale/), specifically in the section on [using the type scale in CSS](https://design-system.service.gov.uk/styles/type-scale/#using-the-type-scale-in-your-own-css) in this line and the proceeding code example:

>You can add additional arguments to control font weight, use tabular font spacing, or to override the line height:
>
>```scss
>@include govuk-font($size 19, $weight: bold, $tabular: true);
>```

This doesn't explain what tabular numbers are and only demonstrates how to use them via `govuk-font` as opposed to using `govuk-font-tabular-numbers`, although I wonder if we necessarily need to state the latter explicitly.
