### ISSUE TITLE
Add an example of the Select component's error state

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#1234]
## What

Provide an example of the Select component's error state in the Design System

## Why

The `govuk-select--error` class is not documented, and users have nothing to show them how to implement the error state, which can be confusing.

See https://github.com/alphagov/govuk-frontend/issues/1787 for an example.

**Comment by peteryates** [comment]
Thanks for this, the omission [bit me](https://github.com/DFE-Digital/govuk_design_system_formbuilder/pull/42) last year.

**Comment by 36degrees** [comment]
That's useful to know, thanks @peteryates 👍

**Comment by 36degrees** [comment]
The current Select example is a sort order, which _probably_ isn't a realistic context to use in an error state example?

We may need to find another example where using a Select makes sense.

**Comment by 36degrees** [comment]
Closing as a duplicate of #1049
