### ISSUE TITLE
Improve error messages guidance for text input when input is not money

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#1235]
## What
Raised by @up-town-down in https://github.com/alphagov/govuk-design-system/pull/1217

We should improve the [text input error messages guidance](https://design-system.service.gov.uk/components/text-input/#error-messages) for the sections

>If the input is not an amount of money and the field needs decimals 

>If the input is not an amount of money and the field allows decimals

The two examples seem very similar - do we need both? If we do, is there a way to differentiate more clearly between the use cases?

We should also improve the examples given for both: the headings say that the use case is **not** about money but the examples are about money.
 
## Why
To help our users follow the guidance where it might currently be unclear.

## Who needs to know about this
Stephen

**Comment by StephenGill** [comment]
Pull request here: https://github.com/alphagov/govuk-design-system/pull/1237

Have suggested removing incorrect examples instead of updating them - and adding relevant information elsewhere on the page.
