### ISSUE TITLE
URLs that do not end in a forwards slash return 502

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#1236]
Steps to reproduce:

1. Visit the homepage
2. Press 'getting started'

You will be sent to [`https://design-system.service.gov.uk/get-started`](https://design-system.service.gov.uk/get-started) with the response of `502 Bad Gateway: Registered endpoint failed to handle the request.`

This seems to be consistent with any URL that does not have a forward slash at the end, as you'll notice the main navigation does not have this problem where it links to [`https://design-system.service.gov.uk/get-started/`](https://design-system.service.gov.uk/get-started/).

**Comment by nickcolley** [comment]
For context I noticed this when visiting the https://design-system.service.gov.uk/get-started/ page on mobile and pressing 'production'.

**Comment by 36degrees** [comment]
Thanks for flagging, @nickcolley. PaaS currently have an outage which is affecting the Design System website, and I believe is causing the errors you’re seeing.

**Comment by nickcolley** [comment]
That makes sense.

This is now resolved, have a nice day :)
