### ISSUE TITLE
Add example of GOV.UK emergency banner to 'Emergency banner' pattern

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1239]
## What
Feedback from the cross-government working group following publication of '[Help users to understand the impact of an emergency on your service](https://design-system.service.gov.uk/patterns/understand-the-impact-of-an-emergency/)' to add an example of GOV.UK's emergency banner.

## Why
So users know what it looks like.

## Done when

**Comment by kellylee-gds** [comment]
This was also suggested by a user on cross-government Slack

**Comment by christopherthomasdesign** [comment]
The 'Help users to understand the impact of an emergency on your service' pattern no longer exists. There are examples of banners of this kind in the notification banner component, so I'm gonna close this.
