### ISSUE TITLE
Rename the 'How it works' section of 'Emergency banner' pattern to 'What to include'

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1241]
## What
Feedback from the cross-government working group following publication of '[Help users to understand the impact of an emergency on your service](https://design-system.service.gov.uk/patterns/understand-the-impact-of-an-emergency/)' to rename the 'How it works' section to 'What to include'.

## Why
'How it works' doesn't reflect the text below which is more of an instruction / recommendation.

## Done when

**Comment by timpaul** [comment]
We're going to close this issue. We use 'How it works' throughout the Design System and don't want to set a precedent of varying it.
