### ISSUE TITLE
Document display override classes

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#1273]
## What
We should consider documenting our display override classes in the Design System as they help with some very common use cases but are currently hard to find. 
```
  .govuk-!-display-inline 
  .govuk-!-display-inline-block 
  .govuk-!-display-block 
  .govuk-!-display-none
  .govuk-!-display-none-print 
```

[Layout](https://design-system.service.gov.uk/styles/layout/) seems like the obvious place, probably under "Display override classes" heading (similar to "Width override classes" heading under "Spacing"). 

## Why
To help our users to use things that already exist and save them time from having create their own classes.

## Who needs to know about this
Stephen, Chris?

## Done when
- [ ] We've documented the classes in Layout

**Comment by timpaul** [comment]
## DRAFT CONTENT
---

### Display override classes

Occasionally, you might need to override the default way that certain elements display on the page. You can use the display override classes for this.

### Using the override classes

Here are the override classes for each of the following CSS display properties:

- inline -  `.govuk-!-display-inline` 
- inline-block -  `.govuk-!-display-inline-block` 
- block -  `.govuk-!-display-block` 
- none - `.govuk-!-display-none`

You can also hide elements from the printed version of the page using `.govuk-!-display-none-print`.

**Comment by m-green** [comment]
I like Tim's suggestion. Suggest rejigging a little so it leads with the user tasks.

## Override how elements display

You can use display override classes if you need to override how elements display on the page.

Use:

- `.govuk-!-display-block` to display as a block
- `.govuk-!-display-inline` to display inline
- `.govuk-!-display-inline-block` to display as an inline block
- `.govuk-!-display-inline-none` to display... (how do you describe this?)

You can also hide elements from the printed version of the page using `.govuk-!-display-none-print`.
