### ISSUE TITLE
Publish a list of known community resources

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1282]
Dependent on completion of [#302](https://github.com/alphagov/design-system-team-internal/issues/302)

## What
Publish a list of known community resources.

## Why
So users can easily find resources that may be useful for them.

## Who needs to know about this
Can be picked up by any member of the team, with consultancy and review by either Mark or Stephen

## Further detail
Epic - [Tell users about the community-developed resources that exist](https://github.com/alphagov/govuk-design-system/issues/1167)

## Done when
- [x] Agreed where to publish
- [x] Agree which community resources to include
- [x] Draft the list
- [x] Review from team
- [x] Decide on whether to link from the Design System
- [ ] Publish list and promote

**Comment by timpaul** [comment]
Using this page on Gatsby as inspiration: https://www.gatsbyjs.org/docs/awesome-gatsby-resources/

**Comment by timpaul** [comment]
Decision: publish the list in the community section, as these are community-developed resources

**Comment by timpaul** [comment]
Draft PR here: https://github.com/alphagov/govuk-design-system/pull/1293

**Comment by timpaul** [comment]
DRAFT LIST:

A curated list of useful resources and community projects.

The GOV.UK Design System team is not responsible for these resources - if you have any support requests or suggestions contact the resource owner. 

If you'd like to suggest something to be added to the list, please [get in touch](https://design-system.service.gov.uk/get-in-touch/).

We reserve the right to remove resources that are no longer relevant, well-maintained or consistent with the [GOV.UK Design System](https://design-system.service.gov.uk/) and [Service Standard](https://www.gov.uk/service-manual/service-standard).

## Design resources

[sketch_wireframing_kit](https://github.com/abbott567/sketch_wireframing_kit)
Quick Sketchapp wireframing tool for UK government digital services

[govuk-design-system-flow-diagrams](https://github.com/dashouse/govuk-design-system-flow-diagrams)
A Sketch file to help you create flow diagrams for the GOV.UK Design System.

[govuk-userflow-icons](https://github.com/alirawashdeh/govuk-userflow-icons)
High resolution vector (SVG) icons to help you create GOV.UK user flow diagrams.

[govuk-design-system-balsamiq](https://github.com/enoranidi/govuk-design-system-balsamiq)
A set of Balsamiq wireframes based on the GOV.UK Design System.

**Comment by timpaul** [comment]
### 2ND DRAFT OF CONTENT

Following a content review by @m-green 

---

A curated list of useful resources and community projects. If you have any support requests or suggestions please contact the owner - the GOV.UK Design System team is not responsible for these resources. 

## Design resources

[govuk-design-system-flow-diagrams](https://github.com/dashouse/govuk-design-system-flow-diagrams)⁠ -
A Sketch file to help you create flow diagrams for the GOV.UK Design System.

[govuk-userflow-icons](https://github.com/alirawashdeh/govuk-userflow-icons)⁠ -
High resolution vector (SVG) icons to help you create GOV.UK user flow diagrams.

[govuk-design-system-balsamiq](https://github.com/enoranidi/govuk-design-system-balsamiq)⁠ -
A set of Balsamiq wireframes based on the GOV.UK Design System.

[sketch_wireframing_kit](https://github.com/abbott567/sketch_wireframing_kit)⁠ -
Quick Sketchapp wireframing tool for UK government digital services.

## Development resources

### C#

[govuk-design-system-dotnet](https://github.com/cabinetoffice/govuk-design-system-dotnet)⁠ -
A collection of GOV.UK Design System components built in C# / ASP.Net Core

### Node.js

[hapi-govuk-examples](https://github.com/DEFRA/hapi-govuk-examples)⁠ -
An introduction to building a hapi service using GOV.UK Frontend

### PHP

[Drupal theme](https://www.drupal.org/project/govuk_design_system)⁠ -
This theme integrates Drupal with the GOV.UK Design System.

### Python

[govuk-frontend-jinja](https://github.com/alphagov/govuk-frontend-jinja)⁠ -
Tools to use the GOV.UK Design System with Python webapps that use Jinja2 and Flask.

[gov.js](https://gist.github.com/andymantell/8b1bb037341f38990a4d019894abd83e)⁠ -
Gulp task to convert govuk-frontend Nunjucks macros to Jinja2.

[python-microservice](https://github.com/willp-bl/python-microservice)⁠ -
Flask/Python implementation of GOV.UK Frontend

### R

[govdown](https://github.com/ukgovdatascience/govdown)⁠ -
GOV.UK Design System theme for R Markdown

### Ruby

[govuk-frontend-rails](https://github.com/mec/govuk-frontend-rails)⁠ -
Shows how to use the GOVUK Frontend in a Rails app.

[govuk-rails-boilerplate](https://github.com/DFE-Digital/govuk-rails-boilerplate)⁠ -
A simple boilerplate built on Ruby on Rails to kick start new services.

[govuk_design_system_formbuilder](https://github.com/DFE-Digital/govuk_design_system_formbuilder)⁠ -
GOV.UK-compliant form builder for Rails.

## Other resources

[govuk-design-system-snippets](https://github.com/daviddotto/govuk-design-system-snippets)⁠ -
GOV.UK Design System Nunjucks macro snippets for popular code editors.


## Help improve this page
To help make sure that this page is useful, relevant and up to date, you can [propose a change](https://github.com/alphagov/govuk-design-system/edit/master/src/components/file-upload/index.md.njk) – read more about [how to propose changes in GitHub](https://design-system.service.gov.uk/community/propose-a-content-change-using-github/).

We're more likely to link to things that are relevant, well-maintained and consistent with the [GOV.UK Design System](https://design-system.service.gov.uk/) and the [Service Standard](https://www.gov.uk/service-manual/service-standard).

For example, we wouldn't link to a resource if:

- it's not relevant to our users
- it's not clear who owns it
- it's really out of date
- it's not easily reusable
- it's poorly documented and supported
- it's incompatible with government standards
- you have to pay for it in some way

**Comment by 36degrees** [comment]
> ### Node.js
> * [An introduction to building a hapi service using GOV.UK Frontend](https://github.com/DEFRA/hapi-govuk-examples)⁠
> 
> ### PHP
> * [A Drupal theme for the GOV.UK Design System](https://www.drupal.org/project/govuk_design_system)

Probably not a blocker to publishing an initial list, but I think this might force us to better define what we mean by 'GOV.UK Frontend', what we mean by 'GOV.UK Design System', and what the difference is between the two.

**Comment by timpaul** [comment]
### 3RD DRAFT OF CONTENT

Following a show-and-tell with the team 

---

A curated list of useful resources and community projects. If you have any support requests or suggestions please contact the owner - the GOV.UK Design System team is not responsible for these resources. 


## Create flow diagrams

- [A Sketch file for creating flow diagrams of GOV.UK services](https://github.com/dashouse/govuk-design-system-flow-diagrams)⁠
- [SVG images for creating flow diagrams of GOV.UK services](https://github.com/alirawashdeh/govuk-userflow-icons)

## Create wireframes

- [Balsamiq wireframes based on the GOV.UK Design System](https://github.com/enoranidi/govuk-design-system-balsamiq)⁠
- [Sketch wireframes based on the GOV.UK Design System](https://github.com/abbott567/sketch_wireframing_kit)⁠

## Use GOV.UK Frontend in different frameworks

### C#

- [A collection of GOV.UK Design System components built in C# / ASP.Net Core](https://github.com/cabinetoffice/govuk-design-system-dotnet)⁠


### Node.js

- [An introduction to building a hapi service using GOV.UK Frontend](https://github.com/DEFRA/hapi-govuk-examples)⁠


### PHP

- [A Drupal theme for the GOV.UK Design System](https://www.drupal.org/project/govuk_design_system)⁠


### Python

- [A Flask/Python implementation of GOV.UK Frontend](https://github.com/willp-bl/python-microservice)⁠
- [ Classes and modules for using GOV.UK Frontend in your Jinja2-powered Python app](https://github.com/alphagov/govuk-frontend-jinja)⁠
- [A Gulp task to convert GOV.UK Frontend Nunjucks macros to Jinja2](https://gist.github.com/andymantell/8b1bb037341f38990a4d019894abd83e)⁠


### R

- [A GOV.UK Design System theme for R Markdown](https://github.com/ukgovdatascience/govdown)⁠

### Ruby

- [A Rails starter app using GOV.UK Frontend](https://github.com/mec/govuk-frontend-rails)⁠
- [A Rails boilerplate app using GOV.UK Frontend](https://github.com/DFE-Digital/govuk-rails-boilerplate)⁠
- [A Rails form builder using GOV.UK Frontend](https://github.com/DFE-Digital/govuk_design_system_formbuilder)


## Write code faster

- [GOV.UK Frontend Nunjucks macro snippets for popular code editors](https://github.com/daviddotto/govuk-design-system-snippets)⁠ 


## Help improve this page
To help make sure that this page is useful, relevant and up to date, you can [propose a change](https://github.com/alphagov/govuk-design-system/edit/master/src/components/file-upload/index.md.njk) – read more about [how to propose changes in GitHub](https://design-system.service.gov.uk/community/propose-a-content-change-using-github/).

We will link to things if they are relevant, well-maintained and consistent with the GOV.UK Design System and the [Service Standard](https://www.gov.uk/service-manual/service-standard).

For example, we're more likely to link to a resource if:

- it's well documented 
- it's well supported
- it's easily reusable
- it's up to date
- it's compatible with government standards
- it's not easily mistaken for an official resource
- it doesn't alter our code or design
- it's not commercially owned
- it's open source
