### ISSUE TITLE
Add an example or explanation of when a check-answers page can be full-width

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1290]
Please consider adding something about why this page is two-thirds and indicate an option to go full width. We have at least one, possibly more, services where we believe full width would suit users better.

After asking on slack comments included:
"It reduces line lengths which makes them easier to read. It means the action links arent so far to the right, so people using screen magnifiers are less likely to miss them."

"In many services, the user's answers will tend to be shorter - which is more suited towards 2/3 layout. I don't think the layout is ideal for displaying paragraph like answers though"

"sure, you can go full width if you need to"

Those answers were very helpful. Please can the information in those comments be considered for inclusion?

_Originally posted by @terrysimpson99 in https://github.com/alphagov/govuk-design-system-backlog/issues/36#issuecomment-619137375_

**Comment by hannalaakso** [comment]
This has also been flagged in https://github.com/alphagov/govuk-design-system-backlog/issues/36#issuecomment-778218553, including a report that using a full-width layout in this context tested well with users.
