### ISSUE TITLE
The home page and community section only talk about a few of the different ways that people can contribute

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1294]
The pages say that you can contribute to the Design System by proposing a new component or pattern or by developing a component or pattern - but they don't mention the other ways that people can contribute - by raising issues or pull requests or by developing ports etc.

**Comment by hannalaakso** [comment]
Also by contributing research findings on the backlog.

**Comment by trang-erskine** [comment]
Some of this will be address with https://github.com/alphagov/govuk-design-system/issues/2349
