### ISSUE TITLE
Some users find it hard to find some GOV.UK Frontend docs

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1304]
3 users expressed in our Slack channel that it was hard to find some of the documentation relating to GOV.UK Frontend:

_"I always find it hard to find the link to the design system sass reference from the Design System website - I expected the link “Sass variables” on https://design-system.service.gov.uk/styles/colour/ to go there, but it doesn’t"_

(This was 'plus-oned')

_"Similarly, easy links to the backlog repo and the govuk-frontend repo."_

**Comment by EoinShaughnessy** [comment]
@timpaul Did the users say where, in particular, they'd like to see links to the backlog and Frontend repos from?
