### ISSUE TITLE
Add guidance about linking to Accessibility Statements, Cookies pages and Ts&Cs to the footer component

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1306]
Add guidance and update our examples, to incorporate linking to Accessibility statements from the footer.

There's more info in [this issue](https://github.com/alphagov/govuk-design-system/issues/1225).

**Comment by EoinShaughnessy** [comment]
Fixed by https://github.com/alphagov/govuk-design-system/pull/2182.
