### ISSUE TITLE
Supporting vueJs

### ISSUE THREAD

**Issue by dimacodecare** [alphagov/govuk-design-system#1324]
Hello! This package support vuejs or reactjs?

**Comment by hannalaakso** [comment]
@dimacodecare 

As far as we know, GOV.UK Frontend – the frontend codebase behind the Design System – should work with React and Vue frameworks.

The community have built some resources which help you use the GOV.UK Design System in your design tool or development environment. One of them is for React so you might wish to review those resources: https://design-system.service.gov.uk/community/resources-and-tools/

The technology agnostic installation instructions for GOV.UK Frontend can be found here:
https://design-system.service.gov.uk/get-started/production/#include-gov-uk-frontend-in-your-project

Unfortunately we are not able to provide more specific guidance for integrating with specific frameworks like React and Vue but hopefully the community resources linked to from above will help you.
