### ISSUE TITLE
Broken anchor link on fieldset component.

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-design-system#1326]
The fieldset component includes a link to `hint-text` - this takes you to the text input component, but with a broken anchor.

![Screenshot 2020-08-11 at 17 12 58](https://user-images.githubusercontent.com/2204224/89921682-ea253980-dbf5-11ea-93ba-1b857947e9d0.png)

**Comment by 36degrees** [comment]
Thanks, @edwardhorsford 👍🏻
