### ISSUE TITLE
Add guidance about multiple error message to Error message component

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1348]
Following [this comment](https://github.com/alphagov/govuk-design-system-backlog/issues/42#issuecomment-681956916) we should add guidance to the [error message component](https://design-system.service.gov.uk/components/error-message/) to help designers understand when they should display multiple error messages at the same time for a field, and when they should only display the most important one.

**Comment by hannalaakso** [comment]
This could be a duplicate: https://github.com/alphagov/govuk-design-system/issues/1305
