### ISSUE TITLE
Add examples of radio and checkbox legends that are not page headings

### ISSUE THREAD

**Issue by fofr** [alphagov/govuk-design-system#1364]
Every example shown has `isPageHeading` set to true:
https://design-system.service.gov.uk/components/radios/
https://design-system.service.gov.uk/components/checkboxes/

It's not clear from the examples:
- that a legend doesn't need to have a heading element within it
- what the markup should be for a legend that is not a page heading

**Comment by joelanman** [comment]
Mentioned here, I think we only tackled part of it:

https://github.com/alphagov/govuk-design-system/issues/1021

**Comment by fofr** [comment]
This had a knock-on effect which meant a formbuilder gem a few services are using has defaulted to using H1s in places that aren't appropriate.

**Comment by kellylee-gds** [comment]
Discussed with the team at triage today.

## What
Add examples of legends that are not page headings to our form components.

## Why
Without these examples some users assume that the only way to add legends is as headings.

## Who needs to know about this
Content designer, developers

## Done when
- [ ] Example and additional guidance added to:
- Checkboxes
- Character count
- Date input
- Radios
- Text input
- Text area
- [ ] 2i'd
- [ ] Published
