### ISSUE TITLE
Review guidance PRs from backlog review

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1371]
## What
During Firebreak, Tim reviewed the details and text input component backlog items - resulting in 4 new guidance PRs.

These now need reviewing by a content designer.

- [Explain how fixed widths are calculated](https://github.com/alphagov/govuk-design-system/pull/1366)
- [Explain why prefixes and suffixes are outside inputs](https://github.com/alphagov/govuk-design-system/pull/1365)
- [Add research findings from backlog](https://github.com/alphagov/govuk-design-system/pull/1363)
- [Add research section to the details component](https://github.com/alphagov/govuk-design-system/pull/1367)

## Why
To agree the best approach to sharing research provided on the backlog for each component.

## Who needs to know about this
Stephen, Tim

## Done when
- [ ] Agreed best approach
- [x] Drafted additions
- [x] 2i'd
- [x] Published

**Comment by 36degrees** [comment]
This has been done.
