### ISSUE TITLE
There's no example that shows a summary list with multiple actions against an item

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1376]
## What

https://design-system.service.gov.uk/components/summary-list/

There's no example given that shows a summary list with multiple actions against an item

## Why

The markup and design for the multiple-actions use case is quite different - it uses a list and the items are separated by bars. If we don't show an example of this people might assume it's not possible, or re-implement it inconsistently.

This is also an opportunity to create a consistent style for horizontal rows of links - do they always have bar separators for example?

## Anything else

We'd need to establish at least 2 genuine use cases for this, by asking the community for examples.

**Comment by edwardhorsford** [comment]
One thing:
On my last project I had a use case for multiple actions - but side by side looked funny. In the end we did something custom so the two actions could be stacked.
