### ISSUE TITLE
Difficulty linking to headings within the Design System website pages

### ISSUE THREAD

**Issue by peteryates** [alphagov/govuk-design-system#1390]
I quite frequently want to link to or reference particular headings on pages of the design system site:

`https://design-system.service.gov.uk/components/text-input/#prefixes-and-suffixes`

Currently I have to create the link manually by inspecting the element and copy/pasting the `id`.

It would be convenient if there was a simpler way. Many websites, including Github, automatically allow header links to be copied by hovering over the heading and clicking the little anchor symbol.

![Screenshot from 2020-10-23 10-21-50](https://user-images.githubusercontent.com/128088/96986567-bf226480-1519-11eb-84e2-fbcfdbe07ff2.png)

 It might not be the perfect solution usability-wise, but it's a fairly common convention. There are probably better alternatives.

**Comment by edwardhorsford** [comment]
I'd really like this too. At least once a day I have to do the same as peter - either inspecting the element, or manually typing out the heading.

**Comment by jbuller** [comment]
A table of contents would help too, though without the UI prompt

**Comment by 36degrees** [comment]
I think this is a duplicate of #425 – @peteryates can you check? If so, can you add any comments to the original issue and I'll close this one?

**Comment by peteryates** [comment]
Ah yes, it looks like they're on the same topic. Didn't find it in my search before raising this one. Thanks.
