### ISSUE TITLE
Non-GOV.UK Page Templates – Research problem unknowns

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#1396]
## What
Research with teams and services that could benefit from [Non-GOV.UK Page Templates](https://github.com/alphagov/govuk-design-system-backlog/issues/185).

## Why
After going through the [User Research Canvas Template](https://docs.google.com/drawings/d/19BUn6PIhWBTpUSa_kli-YvYsJYmwInwdjnQL28tm_b4/edit?pli=1) we identified a number of assumptions which we would like to understand by engaging with users. 

## Who needs to know about this
- Designers, User Research, Product Management
- GOV.UK Policy and Strategy team

## Further detail
- [List of examples of non-GOV.UK services that comply well, or don't comply, with Service Manual branding guidance](https://docs.google.com/spreadsheets/d/1jX_fqBw1b7cRTSeWzoCm0aBL-RP8hty4Yivbp63tP7s/edit#gid=0)

## Done when

- [x] Collected examples of websites exempt from GOV.UK.
- [ ] Identify patterns with exemption.
- [ ] Write research questions.
- [ ] Reach out and engage with users.
- [ ] Playback to team.

**Comment by trang-erskine** [comment]
The team is not doing this right now. We can reopen or rewrite a new ticket when we do.
