### ISSUE TITLE
Clarify how to treat width of notification banner

### ISSUE THREAD

**Issue by christopherthomasdesign** [alphagov/govuk-design-system#1411]
## What

Revisit the content about how wide to make notification banners.

## Why 

A user on Slack raised that the guidance is a bit ambiguous. The guidance currently says "the notification banner should be the same width as the page content".

I think what we mean is if your page content is 2/3, make it 2/3, if its full width, make it full width. But interpretations of 'page content' could differ. Worth seeing if there's a more explicit way to express this.

## Who needs to know about this

Designers, content

**Comment by edwardhorsford** [comment]
@christopherthomasdesign I think one option (this applies to other patterns too) would be to show it in a worked example - the notification banner in the context of a wider page.

**Comment by EoinShaughnessy** [comment]
By 'page content,' do we mean individual bits of a page, or everything-on-the-page-considered-together?

Also, if the page content is full width, does that go against the ['Grid system' section of our Layout guidance](https://design-system.service.gov.uk/styles/layout/#grid-system)?

> Your main content should always be in a two-thirds column even if you’re not using a corresponding one-third column for secondary content.
