### ISSUE TITLE
Support for IE11?

### ISSUE THREAD

**Issue by mgifford** [alphagov/govuk-design-system#1423]
I am curious if there is a date by which the GOV.UK Design System will no longer support IE11.

This may have implications for how much longer CMS like Drupal & Joomla continue support for this legacy software.

**Comment by hannalaakso** [comment]
@mgifford We don’t have a date for dropping IE11 support at the minute.

It has come up in Design System team discussions around our future roadmap. However, we still need to do some investigation work to understand the implications.

Before any decision is made we’ll be getting feedback from the wider community, and we’ll give plenty of notice for any major changes in browser support.

I’m going to close this issue for now as there is no immediate action that we can take on it. Thanks for raising it 👍
