### ISSUE TITLE
Step by step guidance not clear

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#1426]
## What
It wasn't clear that Step by step is only for use on the GOV.UK Publishing site, and that it is only included in the Prototype Kit so you can test your end to end journey. It was not clear that we do not provide the code for it as we do for most other components and patterns in the Design System

## Why
We haven't told users this.

# Who needs to know about this
Joe, Eoin

## Done when
- [x] Eoin drafts Kit documentation improvement
- [x] Eoin drafts additional guidance for Step by step pattern on Design System
- [ ] Updates get SME reviewed
- [ ] Updates published

**Comment by EoinShaughnessy** [comment]
Hey, just want to check my understanding. I know the description above says "only," but would it be fair to say that step by step is _mainly_ intended for use on GOV.UK, but that it's also available in the Kit - albeit only for testing e2e journeys?

Also, if we do not provide the code, then how do users implement step by step in their services?

**Comment by EoinShaughnessy** [comment]
Sounds like these are the pages that require updates:
- [Design System: Step by step navigation](https://design-system.service.gov.uk/patterns/step-by-step-navigation/)
- [Prototype Kit: Tutorials and page templates](https://govuk-prototype-kit.herokuapp.com/docs/tutorials-and-examples)*

*at the end of the page, under 'Page templates'?

**Comment by EoinShaughnessy** [comment]
This issue should also link to [#1029](https://github.com/alphagov/govuk-prototype-kit/pull/1029), from the govuk-prototype-kit repo. I don't know how to link across repos, though. Is this something that can be done/can someone show me how?

**Comment by joelanman** [comment]
fixed by https://github.com/alphagov/govuk-prototype-kit/pull/1029
