### ISSUE TITLE
Review existing internal technical documentation and identify documentation which should be external

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1432]
## What
Review documentation held within our team Google Drive and identify which should be publicly available.

## Why
We believe there are docs which would be beneficial to users.

## Who needs to know about this
Tech Writer, team (for review)

## Done when
- [x] Review team Google Drive
- [x] Remove any duplication
- [x] Agree list of documentation which we would like to host externally

**Comment by EoinShaughnessy** [comment]
The whole team has now fed back about Drive docs that contain publishable content.

This table shows:
- which Drive docs contain useful content
- the corresponding issue to make the content public

| Drive doc  |GitHub issue     | Assignee(s) |
|:----------:|:-------------:|:-------------:|
| [Currency input](https://docs.google.com/document/d/1ADakcyAPIpwgmQab50J4N0neCESt4n68CWl1z6GajG0/edit) |[#1528](https://github.com/alphagov/govuk-design-system/issues/1528): Publish currency input content on Design System | Content Designer
| [Acknowledging contributions](https://docs.google.com/document/d/1WW1c61MHr04BbO9X7KRBw5WWpt3JTGPvbcyV-bLkW5M/edit) | [#1546](https://github.com/alphagov/govuk-design-system/issues/1546): Update Community homepage with content about acknowledging contributors | Content Designer
| [Design System content patterns](https://docs.google.com/document/d/1qyGTwSRW7XYUSKtEeyKgW2nG8YoDl2vDb1YWFCZ5GQo/edit) |  [#1547](https://github.com/alphagov/govuk-design-system/issues/1547): Move patterns content-template from Drive to GitHub | Content Designer and Technical Writer
| [How the Design System team onboards new starters](https://docs.google.com/document/d/1fi8ctdJ_-yPhy-sgfK4WYJejmfCY-hjMP0fjmseMLXE/edit) |[#1579](https://github.com/alphagov/govuk-design-system/issues/1579): Document our onboarding process | ? |
|[How to support our products](https://docs.google.com/document/d/1bBfGr51a_IKFubWTKYRSzKTAQgguCu6xL6nR3W3qZnk/edit) AND [Common redirects/responses](https://docs.google.com/document/d/1NMfYSj-tkQSeg5cvmfXNnT_5_QLRpmHcwXZ6rIsKj_I/edit) |  [#1580](https://github.com/alphagov/govuk-design-system/issues/1580): Publish content to help users understand our support processes | ? |
