### ISSUE TITLE
Discovery into hosting options for internal technical documentation

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1433]
## What
Explore options of where to host internal technical documentation.

## Why
Find a suitable option to host our docs.

## Who needs to know about this
Tech Writer

## Done when
- [x] Speak to other teams in GDS about how they host their docs (GOV.UK Pay, GOV.UK PaaS, GOV.UK)
- [x] Options assessed
- [ ] Workshop with the team to understand how we would arrange the documentation
- [ ] Hosting option agreed

## Next steps
Set up hosting arrangements.

**Comment by EoinShaughnessy** [comment]
Maybe we should tweak this issue's description, as the outcome of the workshop will be about filling docs gaps, instead of about hosting options.

**Comment by trang-erskine** [comment]
Closing this ticket. We're focusing on gaps in documentation first rather than where they should live.
