### ISSUE TITLE
Identify missing internal and external technical documentation

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1434]
## What
Identify key documentation which is currently missing.

## Why
A recent tech and ops health check identified information which currently lives in individual's heads.

## Who needs to know about this
Tech Writer, Developers, Designers

## Done when
- [ ] Session with designers and developers to ideate what we think is missing
- [ ] Add to backlog

## Next steps
Draft and publish resulting documentation

**Comment by trang-erskine** [comment]
Part of this work https://github.com/alphagov/govuk-design-system/issues/2352
