### ISSUE TITLE
Button height

### ISSUE THREAD

**Issue by abbott567** [alphagov/govuk-design-system#1441]
The standard button component is 4px short of meeting the AAA criteria for target size on the height attribute. I know we only work to AA, but I noticed the radio buttons and checkboxes were increased to 44px, and 44px was presumably chosen for that reason?

The back link component also appears to leverage some `:after` css trickery to increase the target size above the threshold of 44px, presumably to hit the same WCAG criterion?

I'm wondering if the standard buttons have just been missed or if there is a deliberate design decision to keep them at 40px rather than 44px?

Thanks

![Screenshot of button component](https://user-images.githubusercontent.com/9450064/103648588-0767f500-4f55-11eb-968a-5c02138bf77e.png)

**Comment by joelanman** [comment]
more discussion here:
https://github.com/alphagov/govuk-frontend/issues/2060

**Comment by abbott567** [comment]
Ah thanks @joelanman - I'm always unsure on what is a Design System issue and what is a GOVUK Frontend issue. Should have looked in both! Apologies.

**Comment by joelanman** [comment]
no problem at all, it's hard to keep track of both

**Comment by 36degrees** [comment]
@abbott567 are you happy that issue covers this as well? If so, can we close this as a duplicate?

**Comment by abbott567** [comment]
Yeah, I think it does, as you specifically mentioned the buttons. Will close this in favour of: [alphagov/govuk-frontend#2060](alphagov/govuk-frontend#2060). Thanks!
