### ISSUE TITLE
Add guidance about leading and trailing whitespace to the validation pattern

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#1450]
## What

As part of the 'Help users to recover from validation errors' pattern, tell users to trim or otherwise ignore leading or trailing spaces where it makes sense to do so – like how we suggest accepting postcodes 'with or without spaces'.

## Why

Some users may accidentally add leading or trailing whitespace as part of their answer. Because these characters are invisible, it can be hard to understand what they need to change when they then cause validation errors.

Some assistive technologies, like [Voice Control on macOS](https://github.com/alphagov/govuk-frontend/issues/2085), can introduce additional leading or trailing whitespace into fields that can cause problems for some users.

## Further detail

There's also an unmatched left parenthesis in 'When to use this pattern' (which [can cause an unresolved tension that will stay with you all day](https://xkcd.com/859/)) that it'd be good to tidy up at the same time.

**Comment by edwardhorsford** [comment]
Another common source of trailing whitespace is users copying data from other documents. I think it's a common thing when double clicking to select a word in Word that it'll include a trailing whitespace. So any service where users may be copying data in to the service is likely to get trailing whitespace.

**Comment by edwardhorsford** [comment]
Something to consider: Voice Dictation on a mac inserts a space between **each** dictated numeral. So for a year it will type `2 0 2 0` - so it might be worth mentioning that numeric input should strip all whitespace, not just leading and trailing.

**Comment by terrysimpson99** [comment]
The problem of validation failure due to additional spaces exists beyond leading and trailing. Oliver mentions postcodes and the guidance there refers to this issue when it mentions 'middle' ("additional spaces at the beginning, middle or end"). For example 'BN12  4AX' versus 'BN12 4AX'. It may be scope creep but I wanted to draw it to your attention so you can triage it.
