### ISSUE TITLE
Draft cookies page pattern

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1453]
## What
Draft of guidance for the cookie page pattern.

## Who needs to know about this
Content Designer, Designer

## Further detail
[Current draft](https://docs.google.com/document/d/1QAA_9GVd5Uxbx9kOXPpYLf6U6yVGb5fnCbLNA60fSII/edit)

## Done when
- [x] Defined relationship with Service Manual guidance
- [x] Shared with team for feedback
- [x] Confirm whether content needs 2i from another content designer
- [x] Update the screenshot example of the cookies page to incorporate [content feedback from working group](https://docs.google.com/document/d/1QAA_9GVd5Uxbx9kOXPpYLf6U6yVGb5fnCbLNA60fSII/edit?disco=AAAALSV6feg)
- [x] 'Keep your cookie page up to date' section reviewed by SME

## Next
[Publish cookies page pattern](https://github.com/alphagov/govuk-design-system/issues/1481)

**Comment by StephenGill** [comment]
When we've finalised the guidance, let Alan Madrell know and he'll update the relevant service manual page (we've already agreed what needs to change).

Most of the team has provided feedback on the draft guidance, but of course people can continue to add comments.

There's no need for another content designer to 2i the guidance (I'd never operate a GOV.UK-style 2i process on something like the design system).
