### ISSUE TITLE
Update backlog entries for cookie banner component and cookies page

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1456]
## What
Update our backlog entries for cookie banner component and cookies page.

## Why
To help users understand our decision making

## Who needs to know about this
Designer, Content Designer

## Done when
- [x] Drafted rationale behind design decisions and approach to building the component and pattern on community backlog entries
- [x] Reviewed by Content Designer
- [x] Removed cookie banner and cookies page from [backlog page on Design System website](https://design-system.service.gov.uk/community/backlog/)

**Comment by CharlotteDowns** [comment]
When we are ready to release I need to [bring the content over from this document](https://docs.google.com/document/d/1BXl2Ifm2lO5YmoTJsDZhFIZX-1Om280NfkdfuBHiYZE/edit?usp=sharing)

Add in links to guidance, and post in the [cookie banner component](https://github.com/alphagov/govuk-design-system-backlog/issues/12) and [cookie page pattern](https://github.com/alphagov/govuk-design-system-backlog/issues/13) backlog items.
