### ISSUE TITLE
Update the Design System to use GOV.UK Frontend v3.11.0

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1468]
## What
Once [GOV.UK Frontend 3.11.0 has been released](https://github.com/alphagov/govuk-frontend/issues/2115), update the Design System to use it.

## Why
So that the Design System reflects the latest release of GOV.UK Frontend.

## Who needs to know about this
Whoever is doing the release

## Done when
[add PR when ready]

**Comment by 36degrees** [comment]
Closed by #1491
