### ISSUE TITLE
Help users discover blog posts, talks, podcasts etc. about the Design System

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1470]
## What
Help users of the Design System website discover blog posts, talks, podcasts and other material relating to it.

## Why

There's no way for users of the Design System website to easily discover the blog posts, talks, podcasts and other related material that current and previous team members (and users) have created.

This is important because there's useful information contained within those resources, particularly for people seeking to understand the rationale behind our products and the challenges involved in building and running a service like ours (which is something we do get asked about).

The resource could also act as a useful onboarding tool for the team, and for new designers in government.

## Who needs to know about this
Content Designer, Designer, Community Manager

## Further detail

[There's a Google Doc in our shared drive](https://docs.google.com/document/d/1075aesu1iz5bUv1RJi1WyDBHSEVVjYA9GL4r-8LKo44/edit?usp=sharing) that lists some of the resources we know about - but there may well be more we don't know about - especially if they've been created by people outside of the team.

## Done when

- [x] Decide which kinds of resources we should link to
- [x] Understanding the information users might be looking for
- [x] Explore the channels which we want to use
- [x] Playback to the team
- [ ] Design and document a process for updating the site with new resources
- [ ] Prototype, test and iterate this feature for the Design System
- [ ] Build and ship the new feature
- [ ] Integrate the process for maintaining this feature into our support model

**Comment by calvin-lau-gds** [comment]
Imran, Tim and I had a good intro chat on the community-building work.

Sounds like a short-term goal is to support community recruitment and  induction: help users understand how to be a part of the Design System community so they can contribute.

Longer-term, find ways to increase engagement, make contributors feel valued (amongst other goals).

**Comment by calvin-lau-sig7** [comment]
Google Doc: https://docs.google.com/document/d/1UMnJ4KTHQ9UaF7cwffyNxJDOLGCV5Axay2rmiScO56I/edit?usp=sharing

- Content ready for page build
- Draft of submission criteria also added

**Comment by CharlotteDowns** [comment]
Maybe we need to create a new card for the final four checkboxes
