### ISSUE TITLE
Kick off work to improve accessibility and usability of conditional reveals

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1473]
## What
Re-familiarise ourselves with the current issues with the 'conditional reveal' functionality of radios and checkboxes.

## Why
So we can resolve the following issues and remove from our accessibility statement:
[#979](https://github.com/alphagov/govuk-frontend/issues/979)
[#1972](https://github.com/alphagov/govuk-frontend/issues/1972)
[#1988](https://github.com/alphagov/govuk-frontend/issues/1988)
[#1989](https://github.com/alphagov/govuk-frontend/issues/1989)

## Who needs to know about this
Developers, Designers, Content Designer, Technical Writer, User Researcher

## Done when
- [x] Re-run conditional reveals show & tell
- [x] Run an ideation session focused on how we can resolve the outstanding issues

## Next
- Cards for actions we agree
- Blog post to communicate changes we have made

**Comment by 36degrees** [comment]
[📽️ &nbsp;Slides](https://docs.google.com/presentation/d/1AaMbTwmj1SMDa8GaLAYKxCR4ZJYdS5qcRdb_aKYFCLA/edit#slide=id.g9e6228d0da_0_15)

[💡&nbsp; Ideation board](https://github.com/alphagov/govuk-design-system/projects/4)

**Comment by kellylee-gds** [comment]
Closing this card as we have written cards for next steps here #1504 #1505 #1508 #1506 [#2147](https://github.com/alphagov/govuk-frontend/issues/2147)
