### ISSUE TITLE
Update the page template guidance to include the cookie banner

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#1475]
## What
Once the cookie banner is published, we should update the [customised page template example](https://design-system.service.gov.uk/styles/page-template/#customised-page-template) to use it.

We could also consider mentioning under `bodyStart` in Options that the cookie banner should be included in this block.

## Why
To help teams to understand how to use the cookie banner with the Design System page template macro.

## Who needs to know about this
Developer, tech writer

## Done when
- [ ] We've added the cookie banner to the customised page template example
- [ ] Optional: We've mentioned the cookie banner under under `bodyStart` in Options

**Comment by hannalaakso** [comment]
This is blocked until the component is published. But we can agree on the wording now.

**Comment by EoinShaughnessy** [comment]
This is the current content for the `bodyStart` Description: 
![image](https://user-images.githubusercontent.com/72507742/106890573-6dc16e00-66e1-11eb-8aec-60c318c170ee.png)

Suggested addition:

"You should include the cookie banner component inside the `bodyStart` block."

And link the words "cookie banner" to the guidance page for cookie banner?

**Comment by EoinShaughnessy** [comment]
There's also a typo to fix on this page, where we should say 'container' instead of 'contain': 
![image](https://user-images.githubusercontent.com/72507742/107045300-450ea680-67bd-11eb-9bef-0912e72c8063.png)

**Comment by hannalaakso** [comment]
We agreed that it would make sense to use the wording from the default cookie banner example for the component that gets added to the customised page template example. We'll link to the cookie banner guidance, as @EoinShaughnessy explains above, so that teams know they'll need to configure both the code and the content to fit their service.
