### ISSUE TITLE
Adding version dates to community resources and tools

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#1479]
## What
Allow users to know when the [community resources and tools](https://design-system.service.gov.uk/community/resources-and-tools/) were published and the [version of GOV.UK Frontend that they support](https://github.com/alphagov/govuk-frontend/releases).

## Why
Users share versions of these resources within their own departments, often these become out of sync with the current release of GOV.UK Frontend. It's hard to know what components they have, what components they've created themselves and which they don't have. 

## Who needs to know about this
Designers

## Done when

- [ ] Design is drafted
- [ ] Design is reviewed by the team
- [ ] Pull request with changes is made and merged

**Comment by trang-erskine** [comment]
Already part of the criteria
