### ISSUE TITLE
Improve cookie banner guidance

### ISSUE THREAD

**Issue by EoinShaughnessy** [alphagov/govuk-design-system#1502]
## What
We've received user feedback about the example text and 'Research on this component' section in the [cookie banner guidance](https://deploy-preview-1484--govuk-design-system-preview.netlify.app/components/cookie-banner/).

## Why
**User feedback 1 (example text)**
"I shared it with the designers...earlier today and it’s resulted in some interesting discussions, one in particular around the content in the banner. We wonder if “…understand how you use the service…” is potentially misleading, as analytics shouldn’t be able to track one user. Maybe something like “We’d also like to store cookies to track visits and find out how people use the website, so we can make improvements.” would be a better option?"

**User feedback 2 ('Research on this component' section)**
"Is there a word missing here?

> We remove the visible focus indicator from when shifting focus to the cookie banner.

I don’t understand the whole section, though, why would it not be operable with a keyboard?"

## Who needs to know about this
Community Manager, Content Designers, Developers, Technical Writer(?)

## Done when
- [x] Team confirms update(s) needed
- [x] Content Designers and/or Technical Writer have drafted update(s)
- [x] Devs have reviewed and approved update(s)
- [ ] Update(s) published

**Comment by EoinShaughnessy** [comment]
Should each piece of feedback have its own issue?

**Comment by EoinShaughnessy** [comment]
Feedback from Content Designer on example text:
"I don't think it's misleading - but on the other hand, "you" might put some people off.
So I'd be inclined to go with their wording, given that it might increase acceptance rates a little.
We talk about services rather than websites, though. And needs to refer to analytics cookies. So I'd go with -

> Cookies on [name of service]
> We'd also like to use analytics cookies to track visits and find out how people use the service, so we can make improvements.
> [Accept analytics cookies]      [Reject analytics cookies]"

**Comment by calvin-lau-gds** [comment]
I've drafted suggested amends in Stephen's Google Doc for the cookie banner. 
Have tagged Stephen and Hanna - would also be good to do a final review with @EoinShaughnessy when it's in better shape.

**Comment by EoinShaughnessy** [comment]
Google Doc for cookie banner: https://docs.google.com/document/d/1QAA_9GVd5Uxbx9kOXPpYLf6U6yVGb5fnCbLNA60fSII/edit

**Comment by calvin-lau-gds** [comment]
Pull request created for 'User feedback 1 (example text)', in review:
https://github.com/alphagov/govuk-design-system/pull/1517
