### ISSUE TITLE
Understand what problems designers are trying to solve when using conditional reveals

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1504]
## What
Research known use cases of conditional reveals to understand what problems teams are trying to solve.

## Why
To help us test whether conditional reveals will work for these use cases and where we can provide guidance.

## Who needs to know about this
Designers, User Researcher

## Further detail
Helps resolve the following issues:
[#979](https://github.com/alphagov/govuk-frontend/issues/979)
[#1972](https://github.com/alphagov/govuk-frontend/issues/1972)
[#1988](https://github.com/alphagov/govuk-frontend/issues/1988)
[#1989](https://github.com/alphagov/govuk-frontend/issues/1989)

## Done when
- [x] Agree how to discover this
- [x] Identified people to contact directly
- [x] Message drafted to send on our support channels to get examples + information about this
- [x] Message sent & responses gathered
- [x] Analysed the results and picked out themes
- [x] Planned a workshop where we can talk about how to solve the problem (should probs be a separate card when we get to that point) UPDATE this is covered by #1505

**Comment by christopherthomasdesign** [comment]
Kick-off meeting 15/02/21

Ask for:
* examples (ideally screenshots) from services to build an inventory
* how well tested the are, particularly with users of assistive tech?
* what alternatives did you try if any?

How to do it:
* look on backlog and message a few people directly (who are those people?)
* message on support channels
* then get people together in a workshop to talk through

Aim to have gathered this info and planned a workshop by end of this sprint

**Comment by christopherthomasdesign** [comment]
Examples collected here: https://docs.google.com/presentation/d/14X_u1ymenFq3Rzs5FtDFXlRmH-2EqwA5UEBTcQMZnSA/edit#slide=id.gbed90473fa_0_86
