### ISSUE TITLE
Prototype potential fixes for known issues with conditional reveals

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1506]
## What
Prototype the following potential fixes:

- Give radios / checkboxes that reveal content additional affordances (e.g. suffixing the label with '…')
- Move conditionally revealed content after fieldset…?
- Add 'Selecting an option reveals additional questions' to hint
- What if we used a button and `aria-pressed` instead?
- What if we used... fake radios and checkboxes?

And any other ideas we come up with.

## Why
To understand if they improve accessibility. 

## Who needs to know about this
Designer, Developer, Content Designer, however anyone can get involved if they have ideas.

## Further detail
Helps resolve the following issues:
[#979](https://github.com/alphagov/govuk-frontend/issues/979)
[#1972](https://github.com/alphagov/govuk-frontend/issues/1972)
[#1988](https://github.com/alphagov/govuk-frontend/issues/1988)
[#1989](https://github.com/alphagov/govuk-frontend/issues/1989)

## Done when
- [x] Prototype hint text with 'Selecting an option reveals additional questions'
- [x] Prototype hidden text to explain that something will expand
- [x] Prototype the revealed content outside of the fieldset
- [x] Explore guard question pattern
- [x] Book in a time for show & tell to playback findings

**Comment by CharlotteDowns** [comment]
Going to find a time to play this back as it's been a little tight to do it for today's show and tell (27 April 2021)

**Comment by CharlotteDowns** [comment]
Note to prototype hidden text in radio and checbox labels.
