### ISSUE TITLE
Comms for renaming default branches

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-design-system#1513]
## What
We will be doing some [work](https://github.com/alphagov/design-system-team-internal/issues/422) to rename our default branches from `master` to `main`. We think we should communicate this change to some of our users, specifically those who make contributions.

## Why
Many communities on GitHub are considering renaming the default branch name of their repository from master, as this terminology can be offensive. Statements and guidance have been published by Git [here](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) and GitHub [here](https://github.com/github/renaming).

New GitHub repositories use `main` as the name for the default branch, so it makes sense that we should follow this convention, as well as matching what other teams within GDS are doing so we are consistent.

## Additional Info
GitHub have made it easier for teams to rename branches. When we rename the branch, we get the following for "free" without having to do anything ourselves:

- Open PRs and branch protection rules changed automatically
- Web requests for the old branch name are redirected to the new branch name
- API requests for the old branch name return a Moved Permanently response
- A notice is shown on the repository homepage to notify contributors, maintainers and admins to update their local copies of the repo
- A notice is shown to contributors who `git push` to the old branch

## Who needs to know about this
Developers
Content
Technical Writer

## Done when

- [x] What will the effect be on our users/contributors?
- [x] Decide what platforms are most appropriate for comms. Slack?
- [x] Decide comms strategy - per repo or one message covering all?
- [x] Comms drafted and reviewed by the team
- [x] Signed off by David Dilley
- [x] Main Github issue with instructions created and pinned in govuk-design-system
- [x] Created individual issues for each repo, also pinned
- [x] Comms sent out on Slack

**Comment by vanitabarrett** [comment]
I've written up the steps that I think we'll need to take to do the actual renaming for each repo; what effect this will have on our users and any actions they'll need to take. We can refer to this when deciding what on comms.

https://docs.google.com/document/d/1pPvGE90d_dyJCy4Sn2nUmxgB0Fwwii0hM0HU7OMNn9A/edit#

**Comment by vanitabarrett** [comment]
This is blocked until I've had a catch-up with Eoin and Calvin - I've put some time in on Tues 16th.

**Comment by EoinShaughnessy** [comment]
Note for Tues: need to look into what internal docs we'll need to adjust.

**Comment by vanitabarrett** [comment]
Had a catch-up with @EoinShaughnessy and @calvin-lau-sig7 today. Full notes here: https://docs.google.com/document/d/1pPvGE90d_dyJCy4Sn2nUmxgB0Fwwii0hM0HU7OMNn9A/edit#

We've decided to draft the following for now, and catch-up next week on how it's gone:

- A Github issue which captures why we're making the change, progress against each repo, and instructions for users that need to take action as a result of these changes
- A Slack message to notify users of the upcoming change. We discussed drafting a one-message-for-all approach to start with, so the same message will go to internal (within GDS, e.g: frontend community) and external users (x-gov Slack).

**Comment by vanitabarrett** [comment]
Have shared the draft comms with Hanna and Ollie for comments.

**Comment by vanitabarrett** [comment]
Moving into blocked while we wait for sign-off

**Comment by vanitabarrett** [comment]
Sign-off given. Have created and pinned the relevant Github issues and posted comms in our support Slack channels.
