### ISSUE TITLE
Publish team style guide on GitHub

### ISSUE THREAD

**Issue by EoinShaughnessy** [alphagov/govuk-design-system#1530]
## What

Update the [Design System team style guide](https://docs.google.com/document/d/13BLKG2xbxdKTNtFUmt1tCShPua_Ahiaxage3fy25v5M/edit#heading=h.f2mj569gq4ot) and move it from Google Drive to GitHub.

## Why

The style guide has only had a few viewers in the last 2.5 years. It might be easier to find on GitHub. If we can refer to it without fuss, that could help us apply GOV.UK content principles. This relocation also makes sense from a docs-as-code point of view.

## Who needs to know about this

Content Designer, Delivery Manager Developers, Senior Product Manager, Technical Writer

## Done when

- [ ] Technical Writer confirms location of content with team
- [ ] Technical Writer talks to previous Technical Writer about current status of content
- [ ] Technical Writer and Content Designer collaborate on any updates
- [ ] Content gets 2i'd, if needed
- [ ] Content published on GitHub

**Comment by EoinShaughnessy** [comment]
@kellylee-gds Should we take the triage label off this issue? If so, do we need to share this issue with a support person so they can prioritise it?

**Comment by kellylee-gds** [comment]
Leave it on for now. I want to give the team a few more days to comment on the proposal and then I'll do sweep of things that have been raised between the last triage session and day 1 of the new process

**Comment by EoinShaughnessy** [comment]
@kellylee-gds Should we relocate this issue to the [design-system-team-docs-repo](https://github.com/alphagov/design-system-team-docs)? That repo contains content on [writing commit messages](https://github.com/alphagov/design-system-team-docs/tree/master/development). So, that might make it a better location for internal docs on our writing conventions.

**Comment by EoinShaughnessy** [comment]
The writer of the style guide only ever intended it for their own use. Not only is it not comprehensive, but publishing it might confuse users who already use the official GOV.UK style guide.
