### ISSUE TITLE
Review Figma port of Design System

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1533]
## What
Review this [Figma port of the Design System](https://www.figma.com/file/NWuFffKvPQhl3aJ9nKU0p3/GOV.UK-Design-System?node-id=23%3A233), and publish it on the Community Resources page.

## Why
To ensure it meets the [criteria](https://design-system.service.gov.uk/community/contribution-criteria/#developing-a-community-resource-or-tool).

## Who needs to know about this
Designer

## Done when

- [x] Checked against community resources criteria
- [x] Contributor / owner informed of decision
- [ ] Published (if applicable)

**Comment by CharlotteDowns** [comment]
Here is the [working draft of the review document](https://docs.google.com/document/d/1s1Hj9SORVebixMTPBC4WH9BWSKPfeSaqm_9GXibG594/edit?usp=sharing)

**Comment by CharlotteDowns** [comment]
Joe and I caught up today, we are going to make three changes before adding and publishing

1. Add link to service manual guidance into the font instructions
2. Add an example of what release comms look like on Slack
3. Add which version of GOV.UK Frontend it supports

**Comment by CharlotteDowns** [comment]
Ongoing work is being collected in [this notion prioritization document](https://www.notion.so/f154e3f57ff04371a068580d8d4b18f3?v=e033cfb5021744efa666e68c7c53517c)
