### ISSUE TITLE
Run a critical review session for equality information

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#1539]
## What

There are any teams in government working on similar problems. 

We want to know who else is working on similar things and what they are doing. Does our new pattern addresses most of the issues and whether there are more things we can improve on the pattern in the future. 

## Who needs to know about this
Community Manager, Content, Designer

## Further detail

Plan for 8 or 9 March, 90 mins. 

## Done when

- [x] Book the session, included any specific people we know that are working on this problem
- [x] Plan the session and decide how we might address feedback
- [ ] Write up feedback and document in the community backlog

**Comment by kellylee-gds** [comment]
@ImranH-GDS @calvin-lau-sig7 following our convo yesterday I have closed this card. If we decide to do a blog post we can write a new card
