### ISSUE TITLE
Update Design System search to include equality information

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#1541]
## What
Update search to include new pattern

## Why
So users can find the component

## Who needs to know about this
Developer, designer

## Done when
- [ ] Identify any synonyms
- [ ] New search terms added

**Comment by vanitabarrett** [comment]
Will be done as part of https://github.com/alphagov/govuk-design-system/pull/1581, but leaving this card open for now so we remember to double check that the aliases etc are working.

**Comment by vanitabarrett** [comment]
Checked on the design system site, all looks good.
