### ISSUE TITLE
Link from text inputs component to width overrides

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#155]
In the text inputs documentation we tell people to set the width appropriately, but it doesn't say how. We could link to the width override section in layout:

https://govuk-design-system-production.cloudapps.digital/styles/layout/#width-override-classes

**Comment by dashouse** [comment]
Great spot. In similar scenarios to this we have included another example on the page itself. Might try adding an example below "Use appropriately-sized text inputs" section.

Once we look at a "number of characters" based constrained input that should probably go here too.

**Comment by dashouse** [comment]
https://github.com/alphagov/govuk-design-system/pull/156

**Comment by dashouse** [comment]
New PR merged, issue closed
