### ISSUE TITLE
Iterate the cookie banner guidance

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#1556]
## What
Following user feedback, we should explain how the cookie banner should be hidden when JavaScript is enabled and the user has previously accepted cookies (we explain how to hide the banner but don't have a code example for the hidden state as the example would be a hidden cookie banner). 

We should add guidance for when it might be appropriate to implement both a server side and a client side cookie banner and how to progressively enhance it with JavaScript.

We should add guidance for how to handle the hiding of the banner if the service is only collecting essential cookies on client and server. 

We should also review the guidance to ensure that teams understand when it's appropriate to only have a client side banner.

## Why 
We want to ensure that the guidance works for teams and covers the relevant scenarios.

## Who needs to know about this
Content designer, technical writer, developer 

## Depends on
https://github.com/alphagov/govuk-frontend/issues/2160

## Done when
- [x] Content writer and tech writer have drafted the additions to the guidance and they've been reviewed by a developer
- [x] Examples added by a developer
- [ ] We've published the guidance

**Comment by calvin-lau-sig7** [comment]
Guidance has been reviewed and ready for release (just needs final check and privacy review).
Moving to blocked so new examples (in Option 2) can be added after new version of Frontend is released.
