### ISSUE TITLE
Review proposed addition to community tools and resources page

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#1562]
## What
Review the following proposed addition to the community tools and resources page: https://github.com/scrambledheads/gov.uk.net

## Why
Decide whether it meets [the criteria](https://design-system.service.gov.uk/community/contribution-criteria/#developing-a-community-resource-or-tool) or not, and provide feedback to the author (via Zendesk).

## Who needs to know about this
Developers

**Comment by hannalaakso** [comment]
We've completed the review. We're just waiting to see whether we'd like to re-word one point in the resources criteria (https://github.com/alphagov/design-system-team-internal/issues/430) before we send feedback to the contributor.

**Comment by hannalaakso** [comment]
We've reviewed the resource and there are a few points of the community resource criteria that it doesn't yet meet. Feedback provided to the contributor via email.
