### ISSUE TITLE
Do we need to use HTML entities in the example code?

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#157]
The HTML examples include HTML entities for example, textarea:

```
Don&#39;t include personal or financial information, eg your National Insurance number or credit card details.
```

I understand modern browsers support the characters directly, so maybe we could use those? They're more readable

**Comment by dashouse** [comment]
Can you find any others? This might be a one off mistake...

**Comment by joelanman** [comment]
I haven't seen others personally, but I'm not too confident with how the examples are generated to know how to look through the code

**Comment by 36degrees** [comment]
I think Nunjucks might be escaping it because it's being passed as an unsafe string. In which case, I'm not sure we'll be able to fix this.

**Comment by dashouse** [comment]
There's a real apostrophe in [this example ](https://govuk-design-system-production.cloudapps.digital/components/details/) so I think it should work... will do worlds smallest PR

**Comment by dashouse** [comment]
PR here - https://github.com/alphagov/govuk-design-system/pull/161
