### ISSUE TITLE
Link size is not clear / defaults don't match normal usage

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-design-system#1571]
It's come up on Slack occasionally that users think links should be 16px rather than 19px. I think because the examples in the typography section use links that are 16px. We've seen repeatedly that people copy the examples verbatim and think they're meant as the standard usage - but here the example is of a link that a user won't want the majority of the time.

Related, I wonder if not setting a default font size is the right approach - I've come across lots of teams with links that are too small because the link is being used in isolation on a page (a cancel link, etc) and so doesn't have a class to set the correct size. The teams didn't know they were wrong though because those links match what the design system shows.

**Comment by vanitabarrett** [comment]
From discussion on Slack, we'd normally expect links to be within a container that sets the font size, e.g: paragraph, list, a component. If a link isn't contained within one of these, one way to set the the font would be to apply the `govuk-body` class.

Could add something like the following to the guidance

> Our default text size is 19px. A link would normally inherit this from a parent element for example <p class="govuk-body"> . If you have a standalone link, apply `govuk-body` to get 19px font size.

**Comment by edwardhorsford** [comment]
@vanitabarrett I think the examples should be updated as well as any guidance changes. We've seen many times that people copy the examples verbatim (not reading the guidance), and assume that they show what the thing is meant to look like.

Right now the link example shows it in a usage that users *shouldn't* be copying.

**Comment by vanitabarrett** [comment]
Suggestion: update link typography examples to be within a paragraph.

**Comment by rorywilsonros** [comment]
I would agree that the example should be within a paragraph, and also some text added to explain that the link should always be within a container.

**Comment by timtops** [comment]
Just to add, the example shown on the Styles>Typography page definitely left me a little confused. I think that could easily be cleared up by implementing the suggestions above.
