### ISSUE TITLE
'Check answers' pattern isn't clear about Change links having hidden text

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#1574]
https://design-system.service.gov.uk/patterns/check-answers/

An important aspect of the Check answers pattern is the use of hidden text in the 'change' links - this makes them accessible for screen reader users. However the guidance doesn't currently mention this.

**Comment by EoinShaughnessy** [comment]
In the guidance, this is the only place that mentions 'change' links:

> You should provide a ‘Change’ link next to each section on your check answers page so that users can add or change the information.

Wonder could we add another sentence after that text? Something like:

> 'Change' links also contain hidden text, which makes them accessible to screen reader users.

**Comment by joelanman** [comment]
I think we need to be clear that you need to do something, the content is not (all) provided in the pattern. So maybe something like
>'Change' links contain hidden text to make them accessible to screen reader users. Update the hidden text to describe what each Change link is for.

**Comment by EoinShaughnessy** [comment]
@joelanman Thanks, that's a really good suggestion. Will raise PR.
