### ISSUE TITLE
Update the API we use to collect support data

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1575]
## What
Update the API to;
- pull response date of a design system team member to a ticket
- pull first message through from user to gauge what it’s for. 
- is there a way to find a number of total tickets we’ve received that incorporates ones we forwarded on to the relevant department?
- remove accessible-autocomplete

## Why
- to help us measure our response KPI
- to collect more contextual information re: support requests
- to feed this data into sprint kick off

## Who needs to know about this
Performance analyst, developers

## Done when
- [ ] Discovered whether the above changes are possible
- [ ] Made the changes
- [ ] Updated any existing documentation

**Comment by trang-erskine** [comment]
Close for now. Reopen if we still want to do this.
