### ISSUE TITLE
Document our onboarding process

### ISSUE THREAD

**Issue by EoinShaughnessy** [alphagov/govuk-design-system#1579]
## What

Write a blog or static external doc about our process for onboarding new starters.

## Why

This information is currently only available in our [Trello board about onboarding new starters](https://trello.com/b/8eTxqiKc/how-the-design-system-team-onboards-new-starters-remotely).

It's easy to forget about Trello boards. A fully-fledged piece of content might be more findable for our team.

If we wrote a blog, it might help other teams to improve their own onboarding processes. It could also get us feedback on how to improve ours.

## Who needs to know about this

Whole team?

## Done when

- [ ] We decide whether this content belongs in a blog / static external doc
- [ ] We decide on location of content
- [ ] Content drafted
- [ ] Content reviewed (DS)
- [ ] Content 2i'd
- [ ] Content published

**Comment by trang-erskine** [comment]
Closing for now. We can reopen if this is needed.
