### ISSUE TITLE
Write blog post about conditional reveals

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#1590]
## What

Write a blog post that outlines the accessibility issues that were raised with conditional reveals, what we've done and learned, and what we're going to do next.

## Why

Share what we've learned about the accessibility of conditional reveals with the wider community.

## Who needs to know about this
Ollie, Calvin, Charlotte, blog editor

## Anything else
Ollie's show and tell presentation on [issues with conditional reveals](https://docs.google.com/presentation/d/1AaMbTwmj1SMDa8GaLAYKxCR4ZJYdS5qcRdb_aKYFCLA/edit#slide=id.g10d42026b8_2_0).

## Done when

- [x] Outline drafted and shared with team for feedback
- [x] Blog post drafted
- [x] 2'ied by blog editor
- [ ] Published

**Comment by CharlotteDowns** [comment]
[Working doc for blog post on conditional reveals](https://docs.google.com/document/d/1II81iOJD3sdm3Neveg37gAEYg8003uaX64SgM7Muiyg/edit#)

**Comment by CharlotteDowns** [comment]
Still awaiting review from Ross Ferguson, this is pushing back publishing by a week. Expected to be published on Tuesday 21 September 2021.

**Comment by CharlotteDowns** [comment]
The blog post is now live at https://accessibility.blog.gov.uk/2021/09/21/an-update-on-the-accessibility-of-conditionally-revealed-questions/
