### ISSUE TITLE
Scope options for mailing list platform

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#1593]
### What

We want to create a release/event based mailing list. Before we do that, we need to scope which platform will be appropriate in terms of functionality and metrics.

### Why
There has been demand for more information on release notes/design decisions. These go into GitHub, but clearly people are not finding them easily. A mailing list will surface important information and send it directly to their inboxes.

### Who
Community manager
Content designer

**Comment by calvin-lau-sig7** [comment]
So far options I'm aware of are:
- Mailchimp - used by cross-gov UCD (send only) and content communities (capture and send)
- Smartsurvey - capture only - used by cross-gov UCD (capture)
- GOV.UK Notify - send only - not sure anyone uses for newsletters

**Comment by kellylee-gds** [comment]
Agreed to use Mailchimp as it meets our needs.
