### ISSUE TITLE
The phase banner's bottom border doesn't look right when immediately above the masthead

### ISSUE THREAD

**Issue by peteryates** [alphagov/govuk-design-system#1612]
When viewing the design system homepage on mobile the phase banner is immediately above the blue 'Design your service...' masthead and the `border-bottom` is flush against it and it stands out.

It's only 1px so it's easy to miss, but it doesn't look intentional so I thought it was worth reporting.

![phase-banner-border](https://user-images.githubusercontent.com/128088/115530963-28e2b780-a28c-11eb-85e7-669cb0d4fe6a.png)

- Operating system: Andorid, Linux
- Browser: Chrome, Firefox
- Browser version: Latest.

**Comment by 36degrees** [comment]
Thanks for taking the time to write this up, @peteryates 🙌🏻
