### ISSUE TITLE
Enhance cookie consent functions with versioning system

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-design-system#1615]
**Depends on https://github.com/alphagov/govuk-design-system/issues/1614**

## What
Add a versioning system to the cookie consent functions that we added to the [design system](https://github.com/alphagov/govuk-design-system/issues/1614).

Example from NHS: https://github.com/nhsuk/cookie-consent/blob/master/src/cookieconsent.js#L11

We should be ok to merge these changes as we're adding a set of functions without using them, so they won't have any effect on users yet.

## Why
If we are likely to move to a sub-domain consent approach in the future, we will need to 'reset' the cookie banner and consent cookie for users who have previously consented as what they have consented to has now changed. This also applies if in the future we add a new cookie category or important new cookie.

## Who needs to know about this
Developers; Technical Writer

## Done when

- [ ] It's possible to bump the version and 'reset' the cookie banner for users
- [ ] Tests added for versioning functionality
- [ ] Technical documentation for developers

**Comment by vanitabarrett** [comment]
There's a couple of specific scenarios around sub-domain consent which need thinking about/testing. If a user has previously consented to cookies on the design system domain only, and then visits the site after we have introduced sub-domain consent, then the version in their existing cookie (design system domain only) should be out of date. At this point, I *think* we'd need the old cookie to be deleted so that they can consent to sub-domain cookies.

The alternative scenario is we don't delete the old cookie, but because the version number is out of date we know to show the banner. However, I think this will lead to the user getting two consent cookies: the existing 'old' design-system domain only cookie, and a new sub-domain consent cookie.

Something to keep an eye out for when we're testing.

**Comment by lfdebrux** [comment]
In the NHS version, if the user has an outdated consent cookie then *all cookies* are deleted on page load... is this the behaviour we want? @vanitabarrett 

https://github.com/nhsuk/cookie-consent/blob/master/src/cookieconsent.js#L243-L246

**Comment by lfdebrux** [comment]
> If we're versioning the banner, that means we want the cookie banner to re-appear and users to re-submit consent even if they have done previously. ... the banner re-appearing implies that they haven't already consented (i.e: we haven't set any cookies yet) ...

From @vanitabarrett

**Comment by lfdebrux** [comment]
@vanitabarrett additional question, are there any scenarios you can imagine where the user might have a consent cookie with a version number *higher* than what our code expects? How do you think we should handle that situation?
