### ISSUE TITLE
Clarification on client side routing

### ISSUE THREAD

**Issue by penx** [alphagov/govuk-design-system#1627]
## Related documentation

I don't think so

## Suggestion

Please can you clarify whether client side routing can be used in a web application and still meet the [UK Government Service Standard](https://www.gov.uk/service-manual/service-standard)?

If it is possible to achieve this, are you able to detail what technical issues must be overcome and any tests developers can do to ensure they are building accessible client side routing?

If it is not possible, can you please outline why, in a way that can be retested in future?

## Evidence (where applicable)

While we were developing [govuk-react](https://github.com/govuk-react/govuk-react), we tried to offer advice on this our accessibility statement here:

https://github.com/govuk-react/govuk-react/blob/master/ACCESSIBILITY.md#client-side-routing

Unfortunately this advice isn't completely clear, and I'm not sure we can make any progress on it.

This was a couple of years ago, but from memory, our understanding (via @nickcolley) was that on certain devices, there was no way to announce navigation to a new route. However, without a list of the devices that exhibit these issues, we are not able to find the current status (e.g. via a software update) or research potential fixes.

Related

- https://almerosteyn.com/2017/03/accessible-react-navigation
- https://simplyaccessible.com/article/react-a11y/
- https://github.com/ReactTraining/react-router/issues/5210
- https://github.com/gatsbyjs/gatsby/issues/5581

**Comment by nickcolley** [comment]
I no longer work at GDS so will unsubscribe but at minimum you'd need to confirm your alternative routing meets the needs of real disabled people in user research to have proper confidence, generally speaking it's just not worth doing, it's better to invest time in maintaining a simpler server-first approach.

**Comment by joelanman** [comment]
Unfortunately the Design System team don’t have extensive experience with React so I’m not sure we can help any further. In addition our team does not look after the Service Manual ourselves. But as you and Nick have said, any service needs to meet the standard, no matter what tech stack it uses, so it needs to be progressively enhanced and accessible to WCAG 2.1 AA

Some related guidance in case you haven’t seen it already:

- https://www.gov.uk/service-manual/technology/using-progressive-enhancement#building-more-complex-services
- https://www.gov.uk/service-manual/technology/accessibility-for-developers-an-introduction

You can submit feedback on these pages using the ‘Report a problem with this page’ links.

**Comment by penx** [comment]
It's important to note that this is not a React-specific issue, but an issue with client side routing in general.

i.e. using the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API) and [history.pushState](https://developer.mozilla.org/en-US/docs/Web/API/History/pushState)

I think it is broadly considered that client side routing can be made to adhere to the WCAG 2.1 AA guidelines - but it's the real world user research that has been done on this that I am hoping to understand better.

I believe there has been research on this within GDS, where the announcing of route changes proved problematic, but only on certain devices.

I am not aware of the specific devices that exhibited these issues, so it would be great to surface this data, if anyone knows which team may have done this testing?

I agree with Nick's point that a server-first architecture would be the way to go, but that would still leave open the question of whether, with a server-first architecture, can I enable client side routing, in a way that passes WCAG 2.1 AA, and still meet the UK Government Service Standard.

I think the design system team may be best placed to enable this question being answered and documented somewhere.

@joelanman I will raise this question via the feedback links you provided above and post back here with any progress. I would have preferred to have this dialog in an open forum, are you aware of another GDS GitHub repository where this question may be more appropriate?

**Comment by joelanman** [comment]
Just to clarify, it's the service team's responsibility to ensure their service is tested for accessibility etc, regardless of approach.

**Comment by penx** [comment]
> Just to clarify, it's the service team's responsibility to ensure their service is tested for accessibility etc, regardless of the technical approach.

Sure, I am just hoping that where there are known issues/pitfalls that are generic to all client side routing approaches, these can be highlighted somewhere so that developers can test for and resolve them in advance of any such testing.

**Comment by joelanman** [comment]
ah cool, gotcha yes. In terms of an open forum, the Service Standard doesn't currently have one. I agree it'd be useful to keep this conversation and investigation open for contribution, so going to move this to the Design System Backlog and edit it to fit better there.
