### ISSUE TITLE
Unclear grammar "providing links users out to the content" in step-by-step-navigation

### ISSUE THREAD

**Issue by bernhard-hofmann** [alphagov/govuk-design-system#1628]
## Related documentation
The start of the step-by-step-navigation states:

> The step by step navigation pattern presents an end to end journey in logical steps, providing links users out to the content that helps them complete each step. 

## Suggestion
Re-write the clause "providing links users out to the content".

## Evidence (where applicable)
N/A

## Affected page (source)
`/src/patterns/step-by-step-navigation/index.md.njk`

**Comment by EoinShaughnessy** [comment]
@bernhard-hofmann Thanks for flagging this issue! We'll revise the text to make it clearer.
