### ISSUE TITLE
Draft Slack and backlog comms for v3.12.0

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#1638]
## What

Draft comms that we will release on Slack and Github issue pages.
Includes new link styles and hover states, and improved cookie banner component.

## Why

Tell our users about what is happening. 

## Who needs to know about this
Content to draft and reviewed by team - possibly GDS comms

## Done when
- [x] Message drafted
- [x] 2i'd by team
- [x] Include acknowledgment of any contributors
- [x] Posted when we've done the release

**Comment by 36degrees** [comment]
https://docs.google.com/document/d/1eJwwkex9rRXhN3GBhrYA8xZINl6kfB2AjyhC4yLbJao/edit#
