### ISSUE TITLE
Consider changing content of the checkboxes: none of the above example

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#1643]
## What
We use a question from the 'register your trailer to take it abroad' service as the current guidance example. Our example asks users

```
## Will you be travelling to any of these countries?
[ ] France
[ ] Portugal
[ ] Spain
or
[ ] No, I will not be travelling to any of these countries
```

We want to explore whether this example could benefit from some content changes. Adding hint text to the question has also been recommended.
 
## Why
As part of the GOV.UK Design System working group feedback we received two suggestions to improve the content:

```
## Which countries are you travelling to?
Select all the countries that apply
[ ] France
[ ] Portugal
[ ] Spain
or
[ ] None, I will not be travelling to any of these countries 
```
and
```
## Which country will you be travelling to?
Select all options that are relevant to you.
[ ] France
[ ] Portugal
[ ] Spain
or
[ ] I will not be travelling to any of these countries
```
## Who needs to know about this
Contributor, Charlotte, Calvin

## Anything else
[Read a background discussion on checkboxes: none of the above](https://github.com/alphagov/govuk-frontend/pull/2151).

**Comment by calvin-lau-sig7** [comment]
I'd lean towards a mix of the two suggestions, aiming to keep the main question and hint text simple whilst repeating the key part of the question (travelling to) in the 'None of the above' option.

Note that GOV.UK style tells us to use plural in situations where the user could use 1 or more (in this case, say countries instead of country or countr(y/ies).

> ## Which countries will you be travelling to?
> Select all the countries that apply.
> [ ] France
> [ ] Portugal
> [ ] Spain
> or
> [ ] I will not be travelling to any of these countries

**Comment by frankieroberto** [comment]
@calvin-lau-sig7 do you think that "Which of these countries will you be travelling to?" might presuppose that you probably _are_ travelling to one of the countries, whereas "Will you be travelling to any of these countries?" is more neutral as to whether you might be travelling to one of the countries or not?

Possibly this is context-dependent (ie on how likely it is that the 'None' option will be used), but I think that the original wording is possibly clearer and more neutral, with "No" being a more expected answer to the question than "None, I will not" which is almost contradicting the question.

However, I agree that the hint text would be helpful in making clear that you must select all:

> ## Will you be travelling to any of these countries?
> Select all countries that apply.
> [ ] France
> [ ] Portugal
> [ ] Spain
> or
> [ ] No, I will not be travelling to any of these countries

Possibly I’m overthinking it though!

**Comment by CharlotteDowns** [comment]
Hey Both, do we have a way of feeding what we are learning here back to the 'register your trailer to take it abroad' service?

**Comment by frankieroberto** [comment]
@CharlotteDowns @calvin-lau-sig7 I've added the hint text as suggested in 838793d662f65d793589203e71b9ae5fce131d0d.

I haven't changed the wording of the question from "Will you be travelling to any of these countries?" to "Which of these countries will you be travelling to?" though, as I think the first one is better for this example, as it better demonstrates the use case for the "No" example, whereas the wording of the second one doesn’t hint at the possibility of "None" being a valid answer.

Ultimately probably both are fine, and the right wording would probably depend on how likely it is that the user will be selecting the No or None option.  In this example, given there’s only 3 countries listed, I think it’s a fair assumption that the No/None option would be quite commonly used!

Do you agree?

**Comment by calvin-lau-sig7** [comment]
Thanks @frankieroberto, that sounds sensible to me. 

The working group member's reason for the wording was the same as yours (to match the answer to the question) so I think we've met that. Also, I'm supportive of keeping the wording as close to what's in "Register your trailer to take it abroad" as possible to keep it as a 'real world' example.

**Comment by CharlotteDowns** [comment]
This has now been included in the [add "None of the above" and "or" divider to checkboxes pull request](https://github.com/alphagov/govuk-frontend/pull/2151).
