### ISSUE TITLE
Determine the styling of 'or' in the checkboxes: none of the above contribution

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#1645]
## What
Determine the font-weight and case of the word 'or'. Look at possible use cases. 

Might need to write additional guidance to advise users to stick to the default styling.
 
## Why
We want to maintain consistency with [radios with a text divider](https://design-system.service.gov.uk/components/radios/#radio-items-with-a-text-divider)

## Who needs to know about this
Contributor, Charlotte (Interaction Designer), Calvin (Content Designer)

## Anything else
[Read a background discussion on checkboxes: none of the above](https://github.com/alphagov/govuk-frontend/pull/2151).

**Comment by frankieroberto** [comment]
I think we should keep this as a lowercase, regular weight "or".  This is consistent with existing practice for Radios. A good rationale for a lowercase "or" is that that is how it would appear written as a sentence:

> Will you be travelling to any of these countries?
> France, Portugal, Spain or “No, I will not be travelling to any of these countries”

**Comment by frankieroberto** [comment]
@CharlotteDowns are you happy with the lowercase, regular weight "or", for the reasons in https://github.com/alphagov/govuk-design-system/issues/1645#issuecomment-841178196?

The draft guidance for the Checkboxes component says:

> Separate it from the other options using an “or” divider.

The existing guidance for the Radios component says:

> The text is usually the word ‘or’.

Could make these more consistent by saying something like:

> Separate it from the other options using a divider. The text is usually the word ‘or’.

Slightly longer, but perhaps clearer?

**Comment by CharlotteDowns** [comment]
@frankieroberto I am happy with the decision to keep it consistent with the divider for radios. 

I also agree with using:

> Separate it from the other options using a divider. The text is usually the word ‘or’.

in the guidance for clarity.
