### ISSUE TITLE
Consider revisiting javascript guidance for checkboxes: none of the above

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#1646]
## What
What is the behaviour of the checkboxes: none of the above when JavaScript is disabled? Does our current guidance need revisiting?

### Proposal
Tie two sentences together on the current JavaScript guidance to make it more explicit that the boxes will not be automatically unchecked. We may also wish to add a `h5` heading 'What to do if JavaScript is unavailable'.

Consider adding a visual example of the error message to provide more context to javascript guidance.
> If JavaScript is unavailable, and a user selects both the ‘none’ checkbox and another checkbox, display an error message.

 
## Why
As part of the GOV.UK Design System working group feedback it seemed that there was still some confusion around the guidance for what happens when a user has JavaScript disabled.

## Who needs to know about this
Contributor, Calvin (Content Designer), Developers, Charlotte (Interaction Designer)

## Anything else
[Read a background discussion on checkboxes: none of the above](https://github.com/alphagov/govuk-frontend/pull/2151).

**Comment by frankieroberto** [comment]
@calvin-lau-sig7 @CharlotteDowns I’ve added an example of the error message that would need to be shown if a user selects both the 'none' checkbox and another checkbox (and has JavaScript disabled) in https://github.com/alphagov/govuk-design-system/pull/1535/commits/d8df5a9ee6ec0f2d104fb88464b89d58a8d20089. Here’s a screenshot:

<img width="870" alt="Screenshot 2021-05-14 at 13 36 47" src="https://user-images.githubusercontent.com/30665/118271787-a5e30480-b4b9-11eb-948d-1c53035b2427.png">

Let me know what you think. I’ve kept the same error message (but without the example) in the "Error messages" section, as people might look for guidance there too – but possibly that could be removed if we want to keep it all within the "Add an option for ‘none’" section.

**Comment by CharlotteDowns** [comment]
That's really nice thank you @frankieroberto

**Comment by frankieroberto** [comment]
@CharlotteDowns are you happy to close this issue?
