### ISSUE TITLE
Consider using JavaScript to remember a user's selection

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#1647]
## What
Could we use JavaScript to remember a user's selection before they tick none of the above?
 
## Why
The GOV.UK Design system working group made a recommendation to save the users preferences just in case 'none of the above' was selected in error.

The Legal Aid Agency has used JavaScript to remember the options ticked - therefore if a user accidentally ticks none of the above and subsequently unticks it, their original options are automatically re-ticked and they don't have to answer the question again.  

## Who needs to know about this
Contributor, Vanita (Developer), Laurence (Developer)

## Anything else
[Read a background discussion on checkboxes: none of the above](https://github.com/alphagov/govuk-frontend/pull/2151).

**Comment by joelanman** [comment]
I'm sure this would be considered but just a note that this might be an accessibility issue - depending on whether screen reader users would expect this behaviour or not. Possibly safer not to do this, as worst case scenario it results in a clear error message 'Please select X'.

**Comment by frankieroberto** [comment]
I'm inclined to agree with @joelanman that this behaviour might be unexpected (for both screen reader users and for sighted users). Not sure we should implement this without some research first, especially as failing to realise that the previous options were restored would have worse consequences (submitting incorrect answer) than failing to realise they weren't restored (which would lead to an error).

**Comment by frankieroberto** [comment]
Here is the code that the Legal Aid Agency use to remember and restore the previous state of the checkboxes when un-ticking the "None" option: https://github.com/ministryofjustice/laa-apply-for-legal-aid/blob/master/app/webpack/src/checkbox_control.js

**Comment by CharlotteDowns** [comment]
## Conclusion

Although the addition of the extra JavaScript to remember a user's selection did not specifically raise any concerns in user research conducted by the Legal Aid Agency, we could not confirm why it had been included and what problem it was designed to solve.

Therefore we have chosen to not include the additional code in this [change to the checkboxes component to include a divider](https://github.com/alphagov/govuk-frontend/pull/2151) but are open to review at a later date if we learn more.
