### ISSUE TITLE
Build a prototype of sign up journey for mailing list subscribers

### ISSUE THREAD

**Issue by RosieClayton** [alphagov/govuk-design-system#1649]
## What
We want to create a mailing list so users can keep up to date with any changes to the Design System 

## Why
We want to build a prototype to test the sign up journey for the mailing list 

## Who needs to know about this
Designer (to build the prototype)

## Done when

- [x] The design of the prototype is agreed 
- [x] The prototype is ready for user research

**Comment by kellylee-gds** [comment]
@CharlotteDowns closing this as I'm assuming it's done as the research has started
