### ISSUE TITLE
Blog about 2021 Frontend survey

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#1659]
## What
Blog about the survey findings on the platforms we published in #1920 

In 2018 we published a blog post.

## Why
Whilst there is a lot of value for the Design System team in finding out what languages and frontend technologies are being used across government, we also want to make the findings publicly available as other government teams might benefit from knowing what the most widely used technologies are and, for example, what legacy browsers are being supported by other teams. 

## Who needs to know about this
Content writer, user researcher, developer

## Done when
- [ ] We've drafted a blog post about the findings
- [ ] We've published the blog post

**Comment by kellylee-gds** [comment]
Removed from Kanban board for now - we will analyse the results when we work on this epic https://github.com/alphagov/govuk-design-system/issues/1752

**Comment by trang-erskine** [comment]
It's too late to do this now.
