### ISSUE TITLE
Sass linting uses deprecated tool

### ISSUE THREAD

**Issue by lfdebrux** [alphagov/govuk-design-system#1663]
## Cause

This repo uses [sass-lint](https://github.com/sasstools/sass-lint) to check Sass files for common mistakes. However sass-lint has been unmaintained since October 2017.

## Consequences

sass-lint will eventually not be able to support the latest features in the Sass language. For instance, if Sass introduces a new syntax which we use, sass-lint may start flagging those lines as invalid, or be unable to read the file at all. More worryingly, there may already be false negatives, where sass-lint is unable to detect mistakes in new syntax or due to bugs in the language that were found since sass-lint stopped being maintained.

## Impact of debt

Low.

There is no evidence to suggest that currently sass-lint is causing any problems. It may cause more problems in the future, at which point the impact can be revised upwards.

## Effort to pay down

Medium.

There are replacement tools available, such as https://stylelint.io/, however we would have to migrate our configuration files to support the same options in the new tool.

## Overall rating

Low.

**Comment by lfdebrux** [comment]
Note: a similar change has already been made in govuk-frontend PR https://github.com/alphagov/govuk-frontend/pull/1902

**Comment by vanitabarrett** [comment]
I had a quick look at this today to see if it was a relatively easy thing to swap sass-lint for stylelint and use stylelint-config-gds. I hit some issues with postcss - I didn't want to spend too much time on it, but it looked like metalsmith-postcss was requires an older version of postcss, but stylelint requires a newer version.
