### ISSUE TITLE
Error Summary component init function is monkeypatched in GOV.UK Design System

### ISSUE THREAD

**Issue by lfdebrux** [alphagov/govuk-design-system#1666]
Copied from Trello ticket https://trello.com/c/VIpSULRT/

## Cause

Error summary component by default takes focus on page load; for examples in the Design System pages this is not desirable, so the behaviour is overridden: 

https://github.com/alphagov/govuk-design-system/blob/61383c31a75aabf45eafe396ea2b5aa03071ebd4/src/javascripts/govuk-frontend.js#L30

## Consequences

- Risk of breaking the error summary examples in the Design System if we updated the init function or refactored the component such that the patched function no longer worked correctly.
- Risk of missing functionality in the Design System if we added new functionality and forgot to update the patched init function.

## Impact of debt

Low, as it should only really affect us.

## Effort to pay down

Low, though we do need to work out a way to deal with this holistically.

## Overall rating

Medium

**Comment by vanitabarrett** [comment]
Once https://github.com/alphagov/govuk-frontend/pull/2494 has been released, we should be able to remove this code and use the `disableAutoFocus` macro option in the error summary component itself instead.
