### ISSUE TITLE
Add security.txt to Design System website

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#1678]
## What

Following [the guidance in the GDS Way](https://gds-way.cloudapps.digital/standards/vulnerability-disclosure.html), add a security.txt file to the Design System, telling researchers how to get in contact with us.

Note that it's not recommended we host the security.txt file ourselves, but instead proxy or redirect to the centrally hosted version.

## Why

In the Cabinet Office, including GDS, the CDIO Cyber Security team run a vulnerability disclosure programme with HackerOne and NCC Group to triage reports from security researchers.

A security.txt file is a way of telling researchers how to get in contact with us via that programme.

## Who needs to know about this

Developers, Cyber security, GaaP Head of Technology?

## Done when

- [ ] Centrally hosted security policy can be accessed by visiting https://design-system.service.gov.uk/.well-known/security.txt

**Comment by querkmachine** [comment]
We've done this for the current DS website, however are keeping this issue open so that it can be looked at again when we've transitioned off PaaS hosting.
