### ISSUE TITLE
Write a brief summary of our findings from conditional reveals investigation on community backlog

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1690]
## What
Write a brief summary of our findings from the investigation we carried out looking at accessibility of conditional reveals.

## Why
This will unblock publishing of the [new guidance](https://github.com/alphagov/govuk-design-system/issues/1362) and provide information for users.

A more detailed report of the investigation will be covered in a later [blog post](https://github.com/alphagov/govuk-design-system/issues/1590).

## Who needs to know about this
Calvin, Ollie and Charlotte (input)

## Done when
- [x] Decide where on community backlog to publish this info
- [x] Decide what should be included in backlog entry
- [x] Update existing issues with feedback from DAC
- [x] Drafted
- [ ] Published

**Comment by calvin-lau-sig7** [comment]
@36degrees To help start, here's an idea to structure the summary of our findings.
If needed, we might want to also add a heading about something like "Findings from our user research"?

> ##We’ve updated some guidance in the checkboxes and radio component
> 
> The updated guidance gives more information about how to use conditionally revealing questions in your service, and what you need to consider.
> > …
> 
> ### Problems we wanted to solve
> 
> ### What we decided and what has changed
> 
> ### How you can help our ongoing user research

**Comment by 36degrees** [comment]
Drafted something here: https://docs.google.com/document/d/1wg-nmXFwa1DvI4tmt8GwIeg_SwhO5we6Hi1obHAnphc/edit?usp=sharing

@calvin-lau-sig7 can you take a look when you get a chance?

**Comment by calvin-lau-sig7** [comment]
Looking good @36degrees! I added some suggested amends.

I ran out of time today, still need to look at how to make the 'how you can help' heading a clear call-to-action to encourage service teams to share their research and experiences.
