### ISSUE TITLE
Link target not clear on error summary examples

### ISSUE THREAD

**Issue by abbott567** [alphagov/govuk-design-system#1696]
## Description of the issue
We've found when accessibility testing some services, there is sometimes weird behaviour on the error summary links. The reason for the weird behaviour is that they're targeting the error messages and not the inputs. So you could argue it's just user error.

However, when we've done some digging, we think it might be that the examples suggest that the links should go to the error message and not the input which caused the issue. 

In the first few examples on the Error Summary component page, the links in the examples suggest that they target the error message in the label, and not the input which caused the error.

For example:
```html
    <ul class="govuk-list govuk-error-summary__list">
      <li>
        <a href="#passport-issued-error">The date your passport was issued must be in the past</a>
      </li>
      <li>
        <a href="#postcode-error">Enter a postcode, like AA1 1AA</a>
      </li>
    </ul>
```

On the later examples which show an input as part of the example, the links are then shown to target the input.

For example:
```html
    <ul class="govuk-list govuk-error-summary__list">
      <li>
        <a href="#name">Enter your full name</a>
      </li>
    </ul>
```

If people target the label, and not the input, then it breaks in Internet Explorer 11. In IE11, when you click the link, IE wont move the focus unless you apply tabindex="-1" to the label. In modern browsers like Chrome and Edge, they will move the focus, under the hood, but it isn't visible on the screen. This is less problematic, as the next time you press tab you're on the input which caused the error, but on IE11 the focus is still where you left it in the error summary.

Not suggesting we add tabindex="-1" it was just part of our attempts to understand what was going on.

What we are suggesting is, the examples in the design system should be consistent to show the correct target, as it's easy to draw the wrong conclusion from the first two examples,  and it could be worth calling out explicitly which elements the links should target in the documentation for how to use the component.

**Comment by 36degrees** [comment]
Thanks for flagging, @abbott567 

> What we are suggesting is, the examples in the design system should be consistent to show the correct target, as it's easy to draw the wrong conclusion from the first two examples…

Just to check we're talking about the same thing, this refers to the IDs used for the inputs and the target anchors used in the links, which contain the word 'error' which may be misleading?

> …and it could be worth calling out explicitly which elements the links should target in the documentation for how to use the component.

There's a section under 'How it works' called '[Linking from the error summary to each answer](https://design-system.service.gov.uk/components/error-summary/#linking-from-the-error-summary-to-each-answer)' which already seems to be pretty prescriptive on this – are there further details that you think are missing from that section?

**Comment by abbott567** [comment]
@36degrees Sorry for the delay in getting back to you.

Yeah, in the first example the ID's suggest you link to the error text, rather than the field or input. If somebody just copies and pastes the code in and doesn't read the guidance it's easy to come to the wrong conclusion as to what the href should actually be targeting.

You're right, it does spell it out quite clearly in the "Linking from the error summary to each answer" section, so I'd say that second comment is already covered, it's just the mismatch in the example and the wording which is likely causing the issue.

**Comment by 36degrees** [comment]
@abbott567 thanks, that's helpful.

In that case, do you think the changes I've suggested in #1721 resolve this issue?

**Comment by 36degrees** [comment]
@abbott567 we've gone ahead and merged that PR, which I think means this issue has been addressed.

However, if there are further changes you think are still needed, please just comment on this issue and we can re-open it and take another look.
