### ISSUE TITLE
Create OKRs to measure community performance

### ISSUE THREAD

**Issue by SaraC19** [alphagov/govuk-design-system#1698]
## What
In order to understand how the community is progressing, a performance framework needs to be created and with this some OKRs. 

## Why
This will give the community some aims and milestones for the community manager to work the strategy towards. This will also influence how to focus user research.  

## Who needs to know about this
Community Manager, User Researcher. 

## Done when

- [x] Prep for OKR kick off meeting
- [ ] Meeting set to run through how to form the OKRs
- [ ] OKRs are set

Linked card re: performance framework: https://github.com/alphagov/govuk-design-system/issues/1697

**Comment by SaraC19** [comment]
This has been started, but the kick off meeting will be held in the next sprint so will keep here for now.

**Comment by trang-erskine** [comment]
@SaraC19 I've move this back to the board. Edit the issue if you need to.
