### ISSUE TITLE
Research for GA4

### ISSUE THREAD

**Issue by SaraC19** [alphagov/govuk-design-system#1700]
## What
Do some research into GA4 to understand how we move forward with it. 

## Why
Google Analytics (Universal Analytics / GA3) is going to at some point become unsupported and the new GA4 will replace it. It's been advised by Google that we move to GA4 by creating a 

Design System are acting as a guinea pig for this and the outcomes will be shared with GOV.UK in order to give them some guidance on how to roll it out (as well as using GTM).  

## Who needs to know about this
Performance Analyst, Frontend Devlopers, Product Manager

## Done when

- [ ] Desk research into installation in GTM, how it works & how it's different to GA3.  
- [ ] Desk research has been written up into a document so everyone can see it
- [ ] Next steps have been written into cards
- [ ] This has been shared with Daisy Wain

**Comment by trang-erskine** [comment]
Superseded by https://github.com/alphagov/govuk-design-system/issues/3822
