### ISSUE TITLE
Workshop guidelines on focus states

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#1701]
## What
We want to improve the consistency of focus states and expected focus behaviour across GOV.UK. As a team, we need to set some principles for our ideal focus states, when and how they are used.
## Why
In order to publish documentation on focus states we need to determine some appropriate rules/guides.
## Who needs to know about this
Designers, Developer, all the team
## Further detail
- [Focus states - an audit ](https://docs.google.com/presentation/d/1kXxnh47Jqw6ZcNzyyTewR_JPwCHyreTMdBGNvE1huWo/edit#slide=id.gdb4961032f_0_30)
- [Understanding focus states](https://design-system.service.gov.uk/get-started/focus-states/) in get started guidance
## Done when

- [x] Collect examples of focus states
- [x] Present back at team show and tell
- [x] Workshop with team

**Comment by 36degrees** [comment]
Related (but previously resolved) issues:

- Inability to tab to accordion plus/minus 'control' flagged in accessibility audit – https://github.com/alphagov/govuk-frontend/issues/1770
- Focus indicator is potentially confusing for tabs and accordion components – https://github.com/alphagov/govuk-frontend/issues/1405

Other useful reference:

- [Colour contrast and Focus for WCAG 2.1 (Presentation, June 2019)](https://docs.google.com/presentation/d/1JnsDY6TjoCxLIpl4SkuIcmVQL4sXXJiIZ2e2kC_0JiM/edit#slide=id.g10d42026b8_2_0)
- [Review of new focus success criteria in initial WCAG 2.2 public draft (Presentation, August 2020)](https://docs.google.com/presentation/d/1ev-8bxwMmQS59WVJd6a7xv7ixEcqY_XTCr6j9oJ78kE/edit#slide=id.g8f34273a21_0_16)
- [Focus States User Research Findings Round One (Presentation, July 2019)](https://docs.google.com/presentation/d/1vw56Y1L0Y6z_v9Z0I3jAv9puVxPlAKg8hofhTgjfC-E/edit#slide=id.g5c9ed264bd_0_0)
- [GitHub Issues relating to WCAG 2.2 2.4.11 focus appearance on the WCAG repo](https://github.com/w3c/wcag/issues?q=is%3Aissue+label%3A%222.4.11+Focus+appearance+%28min%29%22+)

**Comment by 36degrees** [comment]
Related, unresolved, issues that we might end up doing as part of this work:

- Consider adding focus styles guidance on links with large touch areas #1162
- Improve the focus style guidance to include linked images/ videos #1101
- Include extra example of how to style focused items #1317

**Comment by CharlotteDowns** [comment]
The team worked on grouping and establishing some principles for focus states on the 21 Jun 2021. [Here is the padlet from the session](https://padlet.com/charlottedowns/5apruycsoww8cmth).
