### ISSUE TITLE
Add GOV.UK cross domain tracking to design system

### ISSUE THREAD

**Issue by SaraC19** [alphagov/govuk-design-system#1714]
## What
Add design system website to cross domain tracking with GOV.UK. Full instructions here and should speak to a PA in the AAA GOV.UK team before doing.

https://docs.google.com/document/d/1Scq-axCUknouQhKkf5ppqcqljeWSo62njL4p9qGcIjo/edit

## Why
So we can get cross domain data with GOV.UK

## Who needs to know about this
Performance analyst, developer

## Done when

- [ ] Reviewed documentation
- [ ] Implemented cross domain tracking

**Comment by stevenjmesser** [comment]
Replaced by newer work. The Data team will be implementing GA4 for us.
