### ISSUE TITLE
Check for 'Do Not Track' before enabling tracking

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#173]
Many browsers allow you to turn on [DNT](https://www.eff.org/pages/understanding-effs-do-not-track-policy-universal-opt-out-tracking).

It'd be good to only execute the JavaScript that pings third parties if `doNotTrack` is not turned on.

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack

Related files:

- https://github.com/alphagov/govuk-design-system/blob/master/views/partials/_tracking-head.njk
- https://github.com/alphagov/govuk-design-system/blob/master/views/partials/_tracking-body.njk

See a great example of how Medium handles Do Not Track: https://medium.com/policy/how-we-handle-do-not-track-requests-on-medium-f2b4b4fb7c5e

```js
window.userHasDoNotTrackEnabled = (function () {
  var doNotTrack = navigator.doNotTrack || window.doNotTrack || navigator.msDoNotTrack
  return (doNotTrack === 'yes' || doNotTrack === '1')
})()
```

**Comment by joelanman** [comment]
'only execute ...  if this is not set to false' sounds wrong? That would be executing if Do not track is True.

**Comment by nickcolley** [comment]
@joelanman yeah sorry, got caught up in double negatives.

**Comment by joelanman** [comment]
still wrong :)

**Comment by nickcolley** [comment]
you get the point...

**Comment by igloosi** [comment]
shipped

**Comment by 36degrees** [comment]
Original issue was https://github.com/alphagov/govuk-design-system/pull/296
