### ISSUE TITLE
Add guidance on what error message to show for a text input if the input uses characters that are not allowed and the set of allowed characters is very large

### ISSUE THREAD

**Issue by lfdebrux** [alphagov/govuk-design-system#1734]
From [comment on text input backlog by @terrysimpson99](https://github.com/alphagov/govuk-design-system-backlog/issues/51#issuecomment-864051890)

An issue was recently raised on slack that has cropped up before. The guidance says "If the input uses characters that are not allowed and you do not know what the characters are. Say ‘[whatever it is] must only include [list of allowed characters]’."

Challenging example 1: A designer pointed out that following guidance would result in "Business name must only include letters, numbers, hyphens, spaces, apostrophes, exclamation marks, commas, quotation marks, ampersand, underscore, full stop, round brackets and forward slash". The consensus appeared to be that it was not desirable.

Challenging example 2: A service I worked on allowed ~180 char (it was the entire ISO-8859-15 char set). We also believed that listing the characters as per guidance wasn't desirable.

In both examples, the conclusion was to use the example from guidance ‘[whatever it is] must only include letters a to z, hyphens, spaces and apostrophes’.

This scenario is likely to happen again. Can the guidance be updated to indicate that this is acceptable, or suggest a different approach?

## Related documentation

[Guidance on error message if the input uses characters that are not allowed and you do not know what the characters are](https://design-system.service.gov.uk/components/text-input/#if-the-input-uses-characters-that-are-not-allowed-and-you-do-not-know-what-the-characters-are), in the file [src/components/text-input/index.md.njk](https://github.com/alphagov/govuk-design-system/blob/main/src/components/text-input/index.md.njk)

## Suggestion

Add guidance on what to do if the set of allowed characters is very large and/or difficult to show to the user.

**Comment by EoinShaughnessy** [comment]
Challenging example 1: A designer pointed out that following guidance would result in "Business name must only include letters, numbers, hyphens, spaces, apostrophes, exclamation marks, commas, quotation marks, ampersand, underscore, full stop, round brackets and forward slash". The consensus appeared to be that it was not desirable.

Challenging example 2: A service I worked on allowed ~180 char (it was the entire ISO-8859-15 char set). We also believed that listing the characters as per guidance wasn't desirable.

In both examples, the conclusion was to use the example from guidance ‘[whatever it is] must only include letters a to z, hyphens, spaces and apostrophes’.

Re example 1 and its solution - does this mean users ended up being told they couldn't include numbers, exclamation marks, etc., even though they could have?

**Comment by EoinShaughnessy** [comment]
@terrysimpson99 Thanks for the context - it really helped with understanding this issue!

@leona-creator Thanks for sharing your solution! We've updated our guidance to suggest a similar approach.
