### ISSUE TITLE
Don't encourage the use of "html" attribute

### ISSUE THREAD

**Issue by paroxp** [alphagov/govuk-design-system#175]
## What

We had a discussion on a design system slack channel about this documentation not to encourage the use of html parameter in macros.

## Why

It's more efficient to copy and paste a block of text without realising what it's doing. It could easily bring some XSS vulnerability into the application by accident, which we'd all like to avoid.

## Proposal

Scan all the example macro code and re-implement any mentions of "html". "text" should be sufficient in most cases.

For instance:

- [Panel Component](https://github.com/alphagov/govuk-design-system/blob/master/src/components/panel/default.njk#L9)
- [Error Summary Component](https://github.com/alphagov/govuk-design-system/blob/master/src/components/error-summary/default.njk#L16)

## Connection

It may be required to rewrite after implementing the alphagov/govuk-frontend#514

**Comment by 36degrees** [comment]
Closed by #390
