### ISSUE TITLE
DSday - create attendee pack

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#1759]
## What
Create attendee to let people know joining instructions, code of conduct and what to expect

## Why
So DSD attendees know whats going on

## Who needs to know about this
Performance analyst

## Done when

- [x] Draft attendee pack
- [x] Liaise with Code of Conduct and platform creators
- [x] Finalise and send attendee pack

**Comment by SaraC19** [comment]
https://docs.google.com/document/d/1-fq4BhrVwaJtYGXMHQ9tZ8SF4hpQZm_iAec9nWDFlxc/edit?usp=sharing
