### ISSUE TITLE
DSday - create grid, docs and meeting invites

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#1761]
## What
create grid, docs and meeting invites

## Why
So we have rooms for people to go into and docs for notes

## Who needs to know about this
product manager

## Done when

- [x] Think about which platforms we need for a certain sessions: keynote, workshops, breakout sessions
- [x]  Arrange meeting invites and notes docs
- [x]  Create the 'grid', a la UK GovCamp
- [x]  Share grid with the attendee pack team member

**Comment by trang-erskine** [comment]
https://docs.google.com/spreadsheets/d/1MMzws5bEvZnMREBwZLlYHYccfT_x6rwRO56aY36MPX8/edit#gid=320345298
