### ISSUE TITLE
DSday - Arrange keynote speaker

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#1764]
## What
Arrange keynote

## Why
So that we have an interesting talk on the day

## Who needs to know about this
Head of interaction design

## Done when

- [x] Find a speaker for DSD 21
- [x] Let them know what to expect

**Comment by Izabela-16** [comment]
@kellylee-gds to confirm with Tim if key speaker knows what to expect on the day.
