### ISSUE TITLE
Blog about Design System Day

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1783]
## What
Blog about Design System Day.

## Why
To share with the wider community.

## Who needs to know about this
Community Manager

## Done when
- [ ] Agree where blog will be hosted
- [ ] Blog approved by blog owner
- [ ] Draft blog
- [ ] Reviewed
- [ ] Published

**Comment by trang-erskine** [comment]
@ImranH-GDS it looks like you've started on this. I'll move it over to in progress.

**Comment by kellylee-gds** [comment]
@ImranH-GDS I'd also consider taking this off the board until you're able to work on it. Alternatively it's okay to not to blog about it if you don't think you'll have capacity

**Comment by trang-erskine** [comment]
Changed into something different
