### ISSUE TITLE
Write up team guidelines for reviewing and merging PRs

### ISSUE THREAD

**Issue by EoinShaughnessy** [alphagov/govuk-design-system#1787]
## What

Write or update internal doc to explain who can review / merge PRs

## Why

Following the internal docs workshop, several team members (see [page 4 of Jamboard](https://jamboard.google.com/d/1Mf-ENfXTmEXHf__fjDJ8DQRwhM9ofRW-cWjJGSSY1Pc/viewer?f=3&pli=1)) said they'd like to know:

- who can review which PRs
- who can hit the merge button, and in what circumstances

Since not knowing delays completion of work, setting down some guidelines will hopefully remove this blocker.

## Who needs to know about this

Whole team?

## Done when

- [ ] we decide whether to write a new doc or update an existing one
- [ ] content location identified (if necessary)
- [ ] content drafted
- [ ] content 2i'd

**Comment by 36degrees** [comment]
I'm going to call this done as we now have [guidance on working with pull requests](https://team-playbook.design-system.service.gov.uk/guides/version-control/pull-requests/#working-with-pull-requests-prs) in our team playbook, which includes who can review and merge PRs and in which circumstances.

:tada:
