### ISSUE TITLE
Create repository for the GOV.UK Prototype team 

### ISSUE THREAD

**Issue by Izabela-16** [alphagov/govuk-design-system#1794]
## What

The GOV.UK Prototype team are creating a separate GitHub project, and would like to have a repository for private issues.

## Why

Part of the GitHub set up. 

## Who needs to know about this

GOV.UK Prototype team, @36degrees 

## Done when

- [x] private repository is created
- [x] create a GitHub team (Trang, Izabela, Rosie, Joe, Nora, Sara)

**Comment by 36degrees** [comment]
I'd suggest:

- creating a new project board at the organisation level (https://github.com/orgs/alphagov/projects) and linking it to the existing `alphagov/govuk-prototype-kit` and `alphagov/prototype-kit-training` repos
- (if required) create a new repo for sensitive issues, ideally `alphagov/prototype-team-internal` to be consistent with the design system, and linking that as well

**Comment by lfdebrux** [comment]
I've created a GitHub team https://github.com/orgs/alphagov/teams/team-gov-uk-prototype/members, with @Izabela-16 and @trang-erskine as maintainers.

It is just awaiting approval by an org admin, perhaps you could help with that @36degrees?

**Comment by 36degrees** [comment]
> It is just awaiting approval by an org admin, perhaps you could help with that @36degrees?

Approved 👍🏻

**Comment by lfdebrux** [comment]
I've created a private repo, https://github.com/alphagov/prototype-team-internal, for private issues. 

Members of team-gov-uk-prototype have write access, admins in the Design System team have admin access to the new repo.

Do we want all members of the GOV.UK Design System team to have read access to this new repo?

**Comment by trang-erskine** [comment]
@Izabela-16 we have the board now https://github.com/orgs/alphagov/projects/15 Is this ticket is done?

**Comment by Izabela-16** [comment]
@trang-erskine - I think this ticket has now all of the component we needed/ as for. Will close the ticket and move to done.
