### ISSUE TITLE
Summarise findings and decisions of new accordion component in the Design System backlog

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#1796]
## What

[Draft doc of notes](https://docs.google.com/document/d/1hocyO_J9hZ69ciVWAjBT3ARQiRqlPxQkVTj1FfIOV0Y/edit?usp=sharing)

To be released along with accordion component as part of Frontend 4.0

## Why

The Design System team try to include the details of any accessibility testing done on components and the subsequent findings to the Design System backlog. This helps to make the Design System decision making process more transparent and helps service teams understand why certain changes were implemented and how they help users with access needs. 

## How

On Github:
- [x] add backlog comment in [Accordion issue page](https://github.com/alphagov/govuk-design-system-backlog/issues/1)

For follow-up:
- [x] prepare responses to support questions?

## Who needs to know about this

Content designer, Designers, Developers

## Done when

- [x] Briefed and key messages agreed
- [x] Messages drafted as copy deck
- [x] Feedback gathered from team members involved
- [x] 2i'ed and approved with any subject matter experts
- [x] Posted when planned

**Comment by hannalaakso** [comment]
For reference, here's the doc that contains the decisions/findings: https://docs.google.com/document/d/1aFz6VzaPeCc3u7EkAFkeaMZ34FjdUpFnEZOAE1Tyhb8/edit (there are still more things add to it so I would hold fire on trying to format it yet)

**Comment by hannalaakso** [comment]
We should also find a way to summarise our accessibility testing results which are currently here in a pretty complex spreadsheet: https://github.com/alphagov/govuk-frontend/issues/2287

**Comment by calvin-lau-sig7** [comment]
Hi Hanna, apologies for slower progress on this task!
 
In the [Google Doc, I've added some draft sentences and links on your comments](https://docs.google.com/document/d/1hocyO_J9hZ69ciVWAjBT3ARQiRqlPxQkVTj1FfIOV0Y/edit?usp=sharing) ⬆️ . Hopefully it summarises the points you wanted to include. Feel free to propose any changes to add info, etc.
