### ISSUE TITLE
Was the GOV.UK palette designed for graphs?

### ISSUE THREAD

**Issue by nacnudus** [alphagov/govuk-design-system#1814]
https://github.com/alphagov/govuk-design-system/blob/7901b4022b318c4065592a5351ed014f9d4ee545/src/styles/colour/index.md.njk#L62

The Design System says to use the [GOV.UK palette](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/settings/_colours-palette.scss) for "graphs and supporting material".  From reading some pull requests and issues, the palette was [designed by the GOV.UK graphic design community](https://github.com/alphagov/govuk-frontend/pull/1288), but subsequent discussion about the colours has been mainly (perhaps exclusively) about their use for text and components, not for graphs.

Is there more guidance available on how to use the palette for graphs?  For example, some of the colours would fail the contrast requirements of WCAG on a white background.  Is there guidance that points this out?

Have the particular needs of graphs been considered?  For example,

1. Graphs require palettes that support certain kinds of data, such as sequential, diverging or qualitative data.
2. Sequential palettes should be perceptually uniform.
3. Graphs of geographical regions require colours that contrast with each other, as well as with the background.

CC @statshan who pointed out the contrast issue.

**Comment by nacnudus** [comment]
Thanks for this response, especially the link to Slack.

**Comment by statshan** [comment]
Hiya, when you say "There’s a small community of people discussing the subject" and "there’s not loads of discussion in the backlog" - how would I go about raising it up the priorities? 

There are over 17,000 people working in government analysis (so I am told by the analysis function people) - the majority of them publish on GOV.UK and it is very likely that a lot of them will create graphs quite regularly. I work in the team supporting these analysts and we consistently gets lots of queries about charts, graphs, maps etc. People are currently just making up their own guidance. They want and need a steer. How can I make the demand known? 

Do you know how I could get stats on what percentage of GOV.UK publications are stats or analysis publications that likely involve several graphs? 

Thanks, 

Hannah

**Comment by nacnudus** [comment]
> Do you know how I could get stats on what percentage of GOV.UK publications are stats or analysis publications that likely involve several graphs?

@statshan The best that I think we can do immediately is a search for the "Research and statistics" content type, which returns [~40k](https://www.gov.uk/search/all?content_purpose_supergroup%5B%5D=research_and_statistics&order=relevance) results, but they don't necessarily include graphs.  It's theoretically possible to extract all images from all PDF, docx and HTML attachments, train a model to classify them as graph/not-graph, and count them, but there are apparently terabytes of attachments.  It might be a good Data Science Accelerator project if you know anyone looking for inspiration.

**Comment by lfdebrux** [comment]
Hi @statshan, thanks for your message. An accessible colour palette for graphs is obviously a good thing to have, unfortunately however it is unlikely to be something our team will work on in the near to medium term for the simple reason that we have many other priorities in our backlog.

That said, if guidance and/or an accessible colour palette was contributed by the community that was useful for many teams and services and of reasonable quality, we would probably be able to do the work to incorporate that into the Design System.

That is a big ask of course. If it is something you are interested in / have the time to get involved with, we can put you in touch with a couple of different groups of people who are discussing the same problems at the moment.

**Comment by statshan** [comment]
Hi, yes it would be great to get in touch with other people discussing the same problem, we are putting some work into trying to provide more prescriptive guidance on chart colour palettes.

**Comment by christopherthomasdesign** [comment]
Hi @statshan – I'd be happy to do that, what would be the best way for me to get involved?

**Comment by statshan** [comment]
Ah that's great thanks! If you can drop me an email I can invite you to our next catch up. 

hannah.d.thomas@ons.gov.uk

**Comment by statshan** [comment]
Hi I was wondering if I could reopen this conversation (if that is even a thing?!) 

We (I work for the Analysis Function support team) have now developed colour palette guidance for charts. This includes a suggested accessible colour palette for categorical data visualised in bar charts (such as the ones you can make using GovSpeak). 

It would be great if I could get this colour palette worked into the Design System. 

The current colour palette used by the charts you can create with GovSpeak does not meet the colour contrast requirements for adjacent colours.  

Here is a link to our colour guidance (it is currently still in draft but am hopefully for sign off by the end of this week): https://gss.civilservice.gov.uk/policy-store/data-visualisation-colours-in-charts/

Thank you,

Hannah Thomas

**Comment by lfdebrux** [comment]
@statshan that sounds great!

It might be best if you [open a new issue with a feature request](https://github.com/alphagov/govuk-design-system/issues/new/choose), that will make it easier for us to find your suggestion and prioritise the work to incorporate it.

**Comment by statshan** [comment]
Great, thanks, I have done this.
