### ISSUE TITLE
Should the Copy button be more standard?

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#185]
The Copy button is quite different to our standard buttons.

The standard green button is probably too much. Maybe white, but with standard design apart from that? The standard button press effect could help with the 'did it do anything' issue.

**Comment by nickcolley** [comment]
I imagine at some point we'll want to consider variants on the green button, since inverse variants already exist in the wild.

For example https://www.notifications.service.gov.uk/

**Comment by timpaul** [comment]
We can address this issue once we've created a secondary button variant. @joelanman - do you want to propose it in the backlog?

**Comment by joelanman** [comment]
@timpaul we've started discussing it on the Button pattern, as it would probably be a variant there, what you reckon?
https://github.com/alphagov/govuk-design-system-backlog/issues/34

**Comment by timpaul** [comment]
Closing this for now. We'll review the copy button again when we adopt GOV.UK Frontend 3.0 in the Design System.

**Comment by joelanman** [comment]
Just to note we did update the copy button since I raised this, for example it now has a 'press' effect
