### ISSUE TITLE
Text input error message examples could be misleading

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#1857]
The [Text Input](https://design-system.service.gov.uk/components/text-input/) page has this in the Error Messages section:

> If the input uses characters that are not allowed and you know what the characters are
> Say ‘[whatever it is] must not include [characters]’.
> For example, ‘Town or city must not include è and £’.

> If the input uses characters that are not allowed and you do not know what the characters are
> Say ‘[whatever it is] must only include [list of allowed characters]’.
> For example, ‘Full name must only include letters a to z, hyphens, spaces and apostrophes’.

This conflicts with our guidance elsewhere to accept characters - not allowing characters can be discriminatory.

The only reason I can think of for the errors above is if a service has to deal with a legacy system that cannot be changed to accept them. If thats the case and we decide to keep this, maybe we could mention that?

**Comment by calvin-lau-sig7** [comment]
Resolving this issue might involve [linking or adding this line from the Names pattern](https://design-system.service.gov.uk/patterns/names/#:~:text=Support%20all%20the%20characters%20users%20may%20need%20to%20enter%2C%20including%20numbers%20and%20symbols.):
> Support all the characters users may need to enter, including numbers and symbols.
