### ISSUE TITLE
Investigate accessible tools for community collaboration

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1869]
## What
Agreed in retro on 08/09/21 to investigate various collaboration tools for accessibility.

## Why
To have a recommended tool(s) that we use for community collaboration projects. 

## Who needs to know about this
Charlotte

## Done when
- [x] Reviewed findings of the Design community's investigation
- [x] Make a recommendation

**Comment by CharlotteDowns** [comment]
Here is [the slide deck I will be presenting at Show and Tell 14 September 2021](https://docs.google.com/presentation/d/14iyIiVp0NM9gCl6erPPIzyHs2R_dbjxLJfrsZMLMYEY/edit?usp=sharing)

**Comment by CharlotteDowns** [comment]
The recommendation is to use Google Docs, Google Slides, Padlet or Trello. 

If the outcome for the session can't be achieved in any of those tools, we could look at a business case for Mural following some [advice for boards generated by the PaaS team](https://app.mural.co/t/gaap0347/m/gaap0347/1629379337280/fb33db02870c05113ee065243dc529f53374e587?sender=u14668c1046a9bc3bfe281918).
