### ISSUE TITLE
Create a team meeting charter

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#1870]
## What
Agreed in retro on 08/09/21 to explore the scenarios in which a call would be needed vs asynchronous methods of gathering information and data from the team. As part of this, we should also think about principles and behaviours associated with these scenarios.

## Why
As the team grows it will become harder to get everyone together at one time. A charter or guide will help facilitators plan sessions.

## Who needs to know about this
Delivery Manager, Product Manager, Community Manager

## Done when
- [ ] Mapped out scenarios
- [ ] Mapped out behaviours and principles associated with each scenario
- [ ] Documented this
- [ ] Reviewed by team

**Comment by trang-erskine** [comment]
@kellylee-gds do we still need this?

**Comment by kellylee-gds** [comment]
Funnily enough this (sort of) came up in retro last week! So I'd say yeah but maybe it doesn't need to be an issue - I'm just going to write some documentation
