### ISSUE TITLE
Track user take-up of links from Design System site to accessibility criteria

### ISSUE THREAD

**Issue by EoinShaughnessy** [alphagov/govuk-design-system#1880]
## What

Set up analytics so we can get data on users clicking through to the [accessibility criteria](https://github.com/alphagov/govuk-frontend/blob/main/docs/contributing/test-components-using-accessibility-acceptance-criteria.md) from the:

- [accessibility statement](https://design-system.service.gov.uk/accessibility/)
- ['Research and develop your contribution' section of our 'Develop a component or pattern' page](https://design-system.service.gov.uk/community/develop-a-component-or-pattern/#research-and-develop-your-contribution)

## Why

We want to know how many users are navigating from the Design System site to the accessibility doc on GitHub. Also, where it is they're navigating _from_, whether they're using one link more than the other, and so on.

## Who needs to know about this

Whole team?

## Done when

- [x] we set up analytics

**Comment by EoinShaughnessy** [comment]
@trang-erskine The accessibility criteria doc is nearly through 2i. Is it ok if we publish it before we've had a chance to set up analytics on links?

**Comment by SaraC19** [comment]
@EoinShaughnessy Good news - we track all external link clicks automatically across the whole site, so this tracking is already there. I'd be happy to show you how to access this in GA if that would be helpful?

**Comment by EoinShaughnessy** [comment]
@SaraC19 Ooh yes please, that would be great 👍🏻

**Comment by SaraC19** [comment]
@EoinShaughnessy  can this be moved into done now? 

For reference for others - the data can be found already in GA and the data for [that is attached](https://docs.google.com/spreadsheets/d/1HXh9fBLGGtWm6HoSM1uZL-e6QGT4gi2vz1w4KmAkQjo/edit?usp=sharing).

**Comment by EoinShaughnessy** [comment]
@SaraC19 Good shout! Yeah, will move it to Done.
