### ISSUE TITLE
Make layout names consistent

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#1900]
## What

Issue to make layout names consistent across Design System guidance and technical docs.

## Why

A community member has raised a PR highlighting that the name of the 'two-thirds / one-third' layout is inconsistent. After a search, on the [Layout page](https://design-system.service.gov.uk/styles/layout/) alone I've seen it mentioned as:
- two-thirds and one third
- two-thirds / one-third
- two-thirds to one-third

https://github.com/alphagov/govuk-design-system/pull/1895/files

## Who needs to know about this

Content designer, technical writer, designer

## Done when

- [ ] correct name of the layout agreed
- [ ] changes to guidance, mainly the Layout page, published
- [ ] changes to technical doc published, if needed

**Comment by EoinShaughnessy** [comment]
Style guide suggests that '/' is sometimes taken to mean 'or', which we isn't what we want here. So we should probably go with either 'two-thirds and one-third' or 'two-thirds to one-third'.

The second sentence in the guidance page says 'two-thirds and one-third'. Maybe we should just use that term throughout?
