### ISSUE TITLE
id for Checkboxes - None has an extra hyphen at the end

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#1915]
The id for 'Add an option for none' has an extra hyphen at the end. I vaguely recall this happening before?

https://design-system.service.gov.uk/components/checkboxes/#add-an-option-for-none-

**Comment by vanitabarrett** [comment]
This happens if the title contains punctuation, e.g: If there are two options which are not ‘yes’ and ‘no’ ->  https://design-system.service.gov.uk/components/radios/#if-there-are-two-options-which-are-not-yes-and-no-

**Comment by 36degrees** [comment]
At some point we've changed the slugging behaviour and this is no longer an issue – the anchor for that section is now 
https://design-system.service.gov.uk/components/checkboxes/#add-an-option-for-none with no extra hyphen.
