### ISSUE TITLE
Decide where to put Task List code, how to support it

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#1941]
Task List code currently only lives in the Prototype Kit. This is not consistent with how we manage other code, which is in GOV.UK Frontend and imported into the kit. One of our principles is the the Prototype Kit is not for production code, so based on that, it shouldn't live in the Prototype Kit either.

**Comment by trang-erskine** [comment]
One of the co-design workshop @ImranH-GDS is running will potentially conclude with a task list component or components. If the workshops run as plan, we'll have an alpha prototype in the next 3-6 months. The intention is that when there is a component, we can remove it from the kit and it will be on the Design System. 

As this work is ongoing, are you okay for me to close this ticket?

**Comment by joelanman** [comment]
sounds like that covers this issue thanks, good to close
