### ISSUE TITLE
Deploy workflow runs can fail without the whole team being notified

### ISSUE THREAD

**Issue by lfdebrux** [alphagov/govuk-design-system#1956]
### Cause

When a pull request is merged, the [CI workflow](https://github.com/alphagov/govuk-design-system/blob/main/.github/workflows/ci.yaml) first runs tests to ensure that the changes have merged cleanly. If the tests fail then only the user who clicked the merge button will be notified, via email.

If the tests succeed then a deploy will be started, with a deploy notification in the #design-system-dev Slack channel showing the status of the deploy.

### Consequences

It is possible for the notified user to miss the email about the failed workflow run (see https://github.com/alphagov/design-system-team-internal/issues/527). It is also possible that the deploy is critical, or that the failure needs to be actioned by a developer (the merge can be performed by any member of the team). We should treat a failed deploy as something the whole team should be aware of.

### Impact of debt

Medium

### Reason (impact of debt)

We have flaky tests that fail fairly often, so it is not uncommon for deploys to fail without the whole team being aware. 

### Effort to pay down

Medium

### Reason (effort to pay down)

Adding a Slack notification should be possible, although we may also want to consider sending email notifications.

### Overall rating

Medium

### Reason (overall rating)

We should fix this soon, but it is perhaps not as high priority as making it impossible for the team to accidentally deploy old code https://github.com/alphagov/govuk-design-system/issues/1946

**Comment by vanitabarrett** [comment]
We've got Slack notifications for deployments of the design system website now, which tell us if they've been successful or failed. This is probably enough for now - we can re-open this if something crops up in future where those Slack messages haven't been enough.
