### ISSUE TITLE
Create alpha prototype of task-list

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#1959]
## What
Work with community to create alpha prototype of task-list component.

## Why
Part of ongoing task-list collaboration

## Who needs to work on this
Community designer
Interaction designer assigned to collaboration

## Who needs to review this
Feedback from team
Working Group - first review

## Done when

- [x] Get steering group together to filter out incompatible designs
- [x] Run a workshop to decide on 2/3 design for alpha
- [x] Plan workshop to run alpha by community
- [x] Use community feedback to decide which version of alpha to proceed with
- [x] Prototype the alpha

**Comment by vanitabarrett** [comment]
Blocked until we run a session in a few weeks.
