### ISSUE TITLE
Update patterns guidance to help users navigate to GOV.UK

### ISSUE THREAD

**Issue by EoinShaughnessy** [alphagov/govuk-design-system#1966]
## What

Update patterns guidance (for example, [National insurance numbers](https://design-system.service.gov.uk/patterns/national-insurance-numbers/), [Telephone numbers](https://design-system.service.gov.uk/patterns/telephone-numbers/)) to help users navigate to GOV.UK.

## Why

We've learned that the Design System site has been appearing in search results it does not belong in. For example, it looks like we're part of certain COVID-19 services, because of an error message taken from one of our patterns. This means some users are having confusing journeys. Also, we're receiving support queries about things we're not responsible for. [For more details, see @SaraC19's website analysis.](https://docs.google.com/presentation/d/1dIx0RQwxFovK6wAFxITZOwyn0PtgWAE_1eakodFWoxw/edit#slide=id.gf61b7945b0_0_183)

## Who needs to work on this

Technical Writer

## Who needs to review this

Content Designer, Developer, Performance Analyst

## Done when

- [x] Technical Writer drafts update
- [ ] Teammates review update
- [ ] Update published

**Comment by christopherthomasdesign** [comment]
A couple of things that might be interesting to monitor after making the content changes:
* whether the number of Zendesk tickets we receive about citizen-facing services reduces significantly
* how many users click on the links to GOV.UK straight after landing on the relevant pages

Part of me wonders if the content will stand out enough on its own, but probably worth seeing what impact it has first.

If not, could try calling it out in inset text like this:

<img width="1188" alt="Screenshot 2021-11-02 at 16 02 51" src="https://user-images.githubusercontent.com/19834460/139902915-570b8b5c-3e9b-4fd4-bc6a-9a0791af4d16.png">

Not sure the best way to do this – wait a few months and check the data? What do you think @SaraC19 ?

**Comment by SaraC19** [comment]
Sounds like a plan @christopherthomasdesign - I can pop a report together quickly and we can monitor it over time. I reckon after a month we should have enough data.
