### ISSUE TITLE
Maxlength attribute for date input fields

### ISSUE THREAD

**Issue by baarkerlounger** [alphagov/govuk-design-system#1977]
Date fields currently allow users to enter as many characters as they want but day and month input values should be at most 2 characters long, and year input fields at most 4 characters long. This could be made clearer and more user friendly with the `maxlength` attribute. Is there a design reason this isn't used?

**Comment by hannalaakso** [comment]
@baarkerlounger Thanks for getting in touch. 

If you use `maxlength` attribute on a form field to limit user input, users might not receive appropriate feedback of the limit. For instance, the user might not notice that not all the information they entered appeared in the form field, or they might be trying to enter 'December' in the year field and not understand why they cannot type above a certain number of characters, or their assistive technology such as voice recognition software might not announce that they have gone over the character limit when interacting with the field.

It is generally better to let users enter their information in a way that suits them and allow them to submit the form. The server then validates the data it receives; if it determines that there is a problem, it will reload the page with an error message to tell the user how to fix the problem in any particular form field. This allows the service team to control how users find out about errors, and to use accessible and visually consistent error messages to help users recover from them.  

There are some examples of [date input error messages](https://design-system.service.gov.uk/components/date-input/#error-messages) in the Design System that cater for various situations when there has been a problem with the format of the date that the user entered. And the wider topic of validation is covered in more detail in the pattern of [helping users recover from validation errors](https://design-system.service.gov.uk/patterns/validation/). 

If your use case requires you to tell the user about the character limit as they are entering their data, you could use the [character count component](https://design-system.service.gov.uk/components/character-count/) to do this.

I hope that this helps! I'm going to close this issue as resolved but if you have any further questions, please let us know and we can re-open the issue if necessary.
