### ISSUE TITLE
User Experience Survey 2022

### ISSUE THREAD

**Issue by RosieClayton** [alphagov/govuk-design-system#1986]
## What
We ran a user experience survey in January 2021 and it's time to run it again. This time we also want to include questions from the inclusion survey we ran in 2019. 

We also want to write a blog post alongside it to promote the survey and the changes we have made since the last one was run.
## Why
We want to understand if the work we have done over the past year has helped our users. We want to understand if there are any barriers to using the Design System and related products. 

## Who needs to work on this
User Researcher and Performance Analyst

## Who needs to review this
Product manager, Delivery Manager 

## Done when

- [x] Decide on questions to include 
- [x] Agree comms strategy 
- [x] Write blog post 
- [x] Send out survey 
- [x] Publish Blog post

**Comment by Katrina-Birch** [comment]
Survey opened 15/2 to run for two weeks.
