### ISSUE TITLE
Text for link from Design System pages to Github threads

### ISSUE THREAD

**Issue by jbuller** [alphagov/govuk-design-system#1998]
All the Design System pages have a link at the bottom

> Share your research or feedback on GitHub

That is not the reason I and others use the link. Often we are looking for insights into why the pattern is what it is. The discussion on GitHub is fantastic for that. I suspect many never realise the rich seam of information that is there.

The usefulness of mentioning GitHub in the link text is also questionable.

The link text should cater for this use case and advertise the resource.
While the current text is valid, some suggestions on Slack include additional/different text such as:
> See the rationale and how this pattern has been developed 
> See what people are saying about this pattern or ask a question.
> Discussion about [thing] pattern

**Comment by christopherthomasdesign** [comment]
Just adding that 3 other users indicated they agreed this is an issue

**Comment by EoinShaughnessy** [comment]
The bullet text "share your research or feedback on GitHub" also appears on the component pages, as well as on the pattern pages.

In all cases, it's prefaced by the stem sentence "To help make sure that this page is useful, relevant and up to date, you can". We'd probably want the updated text to follow on from that, both as a sentence and to reflect the point made in the stem, i.e., that we're looking for user input to improve the page.

So, maybe something like "take part in the [name of component or pattern]".

**Comment by EoinShaughnessy** [comment]
I don't see the 'Help improve this page' content in any of the individual component/pattern files. Is this because there's one file somewhere, from where this generic content is extracted for display across multiple pages?

**Comment by EoinShaughnessy** [comment]
Ok, so [the 'Help improve this page' content is in one file](https://github.com/alphagov/govuk-design-system/blob/b36a6bd1cd9991debef5748a9aa57d982fdb102d/views/partials/_contact-panel.njk), from where we extract it for display across multiple pages.

Maybe that suggests we should keep the update generic - "take part in the discussion"? Or "take part in the discussion on its development" (unless that could make users think that "its" refers to the page, not the component/pattern)?

**Comment by christopherthomasdesign** [comment]
Just so you know @EoinShaughnessy, you can use Nunjucks variables to pass information like the name of the page into a sentence. So if you made it say something like `share your research or feedback about {{ title }} on GitHub` it will include the title from each particular page. You can use any of those bits of information at the top of each page's markdown file – so the `description` or `section` might be useful too, depends what you want to say. Might not be the right content anyway but gives you more options 🙂

**Comment by EoinShaughnessy** [comment]
@christopherthomasdesign I didn't know that - thanks, v useful to know!

**Comment by calvin-lau-sig7** [comment]
Defo a good idea, we've been working to encourage more people to get into the Github pages. 
As @EoinShaughnessy says, changing the bullet point around "discuss" sounds good to me!

Maybe something like (though it might be slightly long?):
> To help make sure that this page is useful, relevant and up to date, you can:
> - take part in the [name of component or pattern] discussion on Github and share your research

**Comment by EoinShaughnessy** [comment]
@jbuller Thanks for reporting this issue! We've put in a fix for it.

**Comment by calvin-lau-sig7** [comment]
Thanks both! 
I'm putting in a reminder to Google Analytics in a month's time and see if we see any difference on external links to GitHub issues pages.

**Comment by jbuller** [comment]
Was there an impact of this change that can be discerned?
