### ISSUE TITLE
Update Zendesk ticket scraping script

### ISSUE THREAD

**Issue by SaraC19** [alphagov/govuk-design-system#2002]
## What
Update the code on the Zendesk support ticket scraping script so that it includes the body of the ticket. 

Zendesk script is here: https://github.com/alphagov/design-system-support/blob/main/src/zendesk/getTagsFromTicket.js
Explanation of how we pull support data is here: https://docs.google.com/document/d/1G-TN0uXeKchwhHZnmPveX5YteXi3uSl0Rf5vtg-J5l4/edit#

## Why
So we can use this in the support ticket analysis meeting next Tuesday (21 Dec)

## Who needs to work on this
Dev

## Who needs to review this
Dev, PA

## Done when
- [ ] Code has been updated
- [ ] PA understands how to do the thing
- [ ] Ticket data has been collected

**Comment by trang-erskine** [comment]
Close for now. Reopen if we still want to do this.
