### ISSUE TITLE
Guidance on where the Service Name should link to

### ISSUE THREAD

**Issue by abbott567** [alphagov/govuk-design-system#2019]
## Related documentation
[GOVUK Header Component](https://design-system.service.gov.uk/components/header/)

## Suggestion
We see inconsistencies on how the Service Name is used in the header. 
In the Design System the link is just displayed as a hash (`#`) and there is no guidance on where GDS would expect this to go.

For example, some services:
- link back to the GOVUK start page
- link back to the root page of the application
- have a Service Name which isn't a link

## Evidence (where applicable)
- linking to GOVUK start page: [Apply for a Passport](https://www.passport.service.gov.uk/filter/overseas?_ga=2.210562966.20661669.1642096654-494708344.1619536352)
- linking to root page of the application: [Check MOT History](https://www.check-mot.service.gov.uk/)
- have a Service Name which isn't a link: [Apply for Pension Credit](https://www.apply-new-style-employment-support-allowance.service.gov.uk/who-is-applying)

**Comment by 36degrees** [comment]
@abbott567 thanks for raising this. I think this might be covered by #1292. If you agree, would you mind adding a comment there instead?

**Comment by abbott567** [comment]
I agree. Commented and will close this one. Thanks @36degrees
