### ISSUE TITLE
Update Node.js to active LTS version

### ISSUE THREAD

**Issue by lfdebrux** [alphagov/govuk-design-system#2021]
## What

Update the project to use the latest active Long Term Support (LTS) version of Node.js for development, testing, and deployment.

## Why

This project currently uses Node.js version 14, which has been in maintenance since last October (2021-10-19) and won't receive new features.

## Who needs to work on this

Developer

## Who needs to review this

Developer, Tech lead

## Done when

- [ ] Update `.nvmrc`
- [ ] Update `package-lock.json` to use lockfile v2

**Comment by domoscargin** [comment]
We've encountered some issues with this change on Mac M1 devices. They appear to related to `node-sass`, which we use in our tests and with `gulp-sass`.

`gulp-sass` will not support M1 chips with the `node-sass` compiler.

We've managed to get this working on M1 machines by deleting `node_modules`, then running:

```
nvm use
npm uninstall node-sass -g && npm cache clean -force && npm install node-sass
nvm use
npm install
```

Current theories are that the issue might be related to installing with Node v14, then installing this change, and something going awry in the switch. We're going to test installing straight from this branch and see if a clean install works.

We're then going to decide whether:

* We stick to Node 14 for a while
* We push the Node 16 update and document these steps for devs to troubleshoot any issues
* We look at switching to `dart-sass`

**Comment by domoscargin** [comment]
Additionally, after updating to Node 16, `metalsmith-tagcleaner` generates a warning during `npm install`:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'metalsmith-tagcleaner@0.0.2',
npm WARN EBADENGINE   required: { node: '>=4.00' },
npm WARN EBADENGINE   current: { node: 'v16.14.0', npm: '8.3.1' }
npm WARN EBADENGINE }
```

`metalsmith` is now being actively developed: https://github.com/metalsmith/metalsmith/issues/365

So it's possible we might be able to drop this extension or get an updated version at some point.

Alternatively, we may want to look at alternatives to metalsmith.

**Comment by webketje** [comment]
@domoscargin FWIW there is now an official [`@metalsmith/sass`](https://github.com/metalsmith/sass) package you can use to replace `metalsmith-sass` (which uses node-sass under the hood). It uses Dart sass as in your proposed solution and config changes should be minimal.
