### ISSUE TITLE
Set up process to start scraping GitHub analytics to report on Design System contribution

### ISSUE THREAD

**Issue by SaraC19** [alphagov/govuk-design-system#2027]
## What
Very similar to other ticket about pulling GitHub data:  https://github.com/alphagov/govuk-design-system/issues/1845

Understand how users are contributing to the Design System by measuring comments on GitHub and pull requests. 

## Why
So we can measure over time in the centralised KPI dashboard the performance of our contributions and prioritise decisions.  

## Who needs to work on this
Dev, PA

## Who needs to review this
Dev, PA, PM

## Done when

- [ ] We have a process in place to start collecting the data

**Comment by trang-erskine** [comment]
Close for now. Reopen if we still want to do this.
