### ISSUE TITLE
Additional error message for date-input field

### ISSUE THREAD

**Issue by charlieboydellsmith** [alphagov/govuk-design-system#2029]
## Related documentation
[Date input error messages ](https://design-system.service.gov.uk/components/date-input/#error-messages)

## Suggestion
Does there need to be an error message pattern for if a user includes a year but only puts 2 digits, for example 27 3 92. 

Is it safe to assume a year from two digits, for example 92 is 1992? But then 20 could be 1920 or 2020 etc.

Should we stipulate that the field needs to be 4 digits/numbers if a user only enters 2?

**Comment by EoinShaughnessy** [comment]
@charlieboydellsmith Thanks for flagging this issue, and apologies for the late response!

We've updated the 'If the date is incomplete' section under ['Error messages'](https://design-system.service.gov.uk/components/date-input/#error-messages) on the date input page.
