### ISSUE TITLE
Example tabs are losing border on viewport resize

### ISSUE THREAD

**Issue by alex-ju** [alphagov/govuk-design-system#2042]
## Description of the issue
Minor issue: when resizing the viewport, the example tabs (HTML/Nunjucks) are loosing their border.

## Steps to reproduce the issue

1. Visit a page with a code example (e.g. https://design-system.service.gov.uk/components/button/)
2. Click on the Nunjucks tab
3. Resize the viewport to reduce the width

Result (for scenario above)
<img width="447" alt="Screenshot 2022-01-28 at 10 49 36" src="https://user-images.githubusercontent.com/788096/151534425-7a9ea049-b258-4aca-b4ee-41849dbee641.png">

Result (when the HTML tab remains selected before resizing)

<img width="462" alt="Screenshot 2022-01-28 at 10 47 40" src="https://user-images.githubusercontent.com/788096/151534675-00c6ee02-0a23-4a2e-8cf7-4159900d9742.png">

Result (when both tabs are collapsed)
<img width="462" alt="Screenshot 2022-01-28 at 10 47 50" src="https://user-images.githubusercontent.com/788096/151534686-a1211cc2-aa3b-4063-95db-e62cc8d74dfe.png">

<details>
<summary>Screen recording</summary>

https://user-images.githubusercontent.com/788096/151534053-704dbee8-2ae9-465f-aea3-e7f3deeac514.mov

</details>

## Actual vs expected behaviour
I think the intention is for these tabs to be surrounded by a thin border on small viewports.

## Environment (where applicable)

- Operating system: MacOS 12.1 (21C52)
- Browser: Google Chrome
- Browser version: Version 97.0.4692.71 (Official Build) (arm64)

**Comment by owenatgov** [comment]
From a very quick investigation, this looks to be simply a forgotten media query. Should be a simple fix.
