### ISSUE TITLE
Add an example of a select component with hint text

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-design-system#2043]
## Related documentation
https://design-system.service.gov.uk/components/select/

## Suggestion
Add a visual example of a select with hint text.

## Evidence (where applicable)

We had a question on support asking whether it's possible to add hint text for the select component like you can for radios and checkboxes. The user missed the documentation for our Nunjucks macro options (https://github.com/alphagov/govuk-design-system/issues/1085) and didn't realise you could pass hint text in the same way for the select. Perhaps a visual example would help?

**Comment by Ciandelle** [comment]
Can I confirm what type of example we want? Would it be just an image or an interactive version with the HTML and nunjucks code?

**Comment by vanitabarrett** [comment]
@Ciandelle We normally opt for an interactive version with code where possible, and images as a last resort. As the select component is something in GOV.UK Frontend I think we should add an interactive example.

**Comment by vanitabarrett** [comment]
@Ciandelle From what I remember, we can provide an example using Nunjucks (e.g: [breadcrumbs component example](https://github.com/alphagov/govuk-design-system/blob/main/src/components/breadcrumbs/default/index.njk)) and it'll automatically generate the Nunjucks and HTML code snippets for us when we reference that example in the guidance (e.g: [breadcrumbs guidance](https://github.com/alphagov/govuk-design-system/blob/main/src/components/breadcrumbs/index.md.njk#L14))

Happy to help walk you through it at some point, if that'd be helpful!

**Comment by vanitabarrett** [comment]
@Ciandelle It was originally raised by @andysellick (who is on leave at the moment), but I can't remember what he was planning to use the hint text for. Might be worth bringing up within the team or looking at guidance for other components that support hint text?

**Comment by edwardhorsford** [comment]
Here's three from my service - these are all the default view that gets progressively enhanced to an autocomplete.

<img width="559" alt="Screenshot 2022-06-08 at 12 25 10" src="https://user-images.githubusercontent.com/2204224/172609247-319e524f-6631-4f9b-8d3c-9b267ae6ba3b.png">

**Comment by sfount** [comment]
We (GOV.UK Pay) have a very similar pattern to @edwardhorsford which also gets progressively enhanced with a multi-select autocomplete.

It's a filter pattern geared at a case management/ service admin user, I'm not personally familiar with any design/ research that went into it when it was originally built. 

<img width="536" alt="Screenshot 2022-06-08 at 16 10 48" src="https://user-images.githubusercontent.com/2844572/172654227-bbbb2b77-01ab-4fe4-89ea-400d67f986eb.png">

**Comment by Ciandelle** [comment]
Thank you all for your brilliant examples - that's really helpful!

**Comment by edwardhorsford** [comment]
A slight quirk - some of these example hints probably aren't needed for selects. The reason I suspect they've been added is because with the autocomplete it's unclear you'll be able to choose from items - so the hint is more a needed for when the autocomplete is on.
