### ISSUE TITLE
Suggestion: username guidance should advise accepting caseless input

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-design-system#2055]
The [guidance on usernames](https://design-system.service.gov.uk/patterns/create-a-username/) should advise accepting input caselessly.

I can't think of a good reason you'd want cased usernames - especially if following the guidance to use an email address.

This came up as a query on cross gov slack.

**Comment by EoinShaughnessy** [comment]
@edwardhorsford Thanks for flagging this!

Just want to check my understanding - are we saying to treat usernames in a case-insensitive way?

So, they can use either upper case or lower case letters, or a mix of both.

**Comment by edwardhorsford** [comment]
@EoinShaughnessy 

I mean that when signing in, the system should compare caselessly.

So I may have signed up with a username `EdHorsford@example.com`, but if I try to sign in with `edhorsford@example.com` it still works.

**Comment by EoinShaughnessy** [comment]
@edwardhorsford Thanks for your help with this! [We've put in a fix](https://github.com/alphagov/govuk-design-system/pull/2061).
