### ISSUE TITLE
Component code examples repeat ids for default examples

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-design-system#2064]
## Description of the issue
Some components repeat the initial `default` example on the page without specifying a `titleSuffix` or using a different example name than `default`. This results in the code example blocks for both these examples to use the repeating ids (`{component name}-example-{html/nunjucks}`), thus breaking HTML rules on ids.

## Steps to reproduce the issue
- Go to the [accordion component page](https://design-system.service.gov.uk/components/accordion/)
- Open up the code example for the first example
- In the inspector, check the id of the `div` containing the code example
- Go to the second example and repeat the above steps

You should see that the ids are the same for both HTML and nunjucks code blocks of both examples.

## Proposed solution
This can be solved quite easily by adding `titleSuffix: "second"` to the example call in the component nunjucks. See the [file upload component](https://design-system.service.gov.uk/components/file-upload/) for an examples of how we're handling this positively.

It may be worth considering if we need to implement a testing strategy for this to avoid it happening in future.

**Comment by 36degrees** [comment]
I'm not 100% sure if this is an issue, as the examples are in iframes each example exists in its own HTML document with its own DOM.

Are we aware of this being flagged as an issue, or causing accessibility issues?

**Comment by owenatgov** [comment]
@36degrees This isn't happening within the iframes, it's in the tabs that contain the code blocks below said iframes. To try and illustrate a bit better, the way the code examples are formatted, very very roughly, is:

```html
{the visual code example within an iframe}

<ul class="govuk-tabs">
    <li><a href="component-example-html">HTML</a></li>
   <li><a href="component-example-nunjucks">Nunjucks</a></li>
<ul>
<div>
    <div id="component-example-html">
        {the html code block for the above example in the iframe}
    </div>
    <div id="component-example-nunjucks">
        {the nunjucks code block for the above example in the iframe}
    </div>
</div>
```

The above is happening twice for instances where we're not specifying a `titleSuffix` but are using the same `default` example.

I don't think this is causing any accessibility issues but I don't think that's a reason to not fix this. We shouldn't be breaking the html spec on our own website.

**Comment by 36degrees** [comment]
That makes sense – thank you for clarifying 👍🏻
