### ISSUE TITLE
Explain why we don't justify or right align text

### ISSUE THREAD

**Issue by marianavery** [alphagov/govuk-design-system#2075]
## Related documentation
https://design-system.service.gov.uk/styles/typography/#text-alignment-override-classes

## Suggestion
We DO left align text, but we don't say why we do. We should add something to say:

You should usually left-align text that's read left to right. Never justify blocks of text as this creates rivers of blank space, which can make it difficult to read. Remember that right-aligning text can make it difficult for magnification users to find and follow.

## Evidence (where applicable)
https://www.w3.org/TR/WCAG20-TECHS/G169.html

**Comment by EoinShaughnessy** [comment]
@marianavery Thanks for raising this - really appreciate the explanation and helpful link!

Ok, first pass at guidance update:

> You should usually left-align text that's read left to right. Right-aligned text can be hard for magnification users to find and read.
> 
> Do not 'justify' blocks of text so that they're aligned to both the left and right margins. Doing this creates blank spaces, which can also make the text hard to read.

@davidc-gds What do you think? :)

**Comment by edwardhorsford** [comment]
Would be good to be clear this is about body regular copy / body copy and not *any* text. Services may right align for ui elements or for some columns in tables, etc.

**Comment by EoinShaughnessy** [comment]
Thanks, @edwardhorsford! That's good to know.

Take #2:

> You should usually left-align body copy that's read left to right. Right-aligned body copy can be hard for magnification users to find and read.
> 
> Do not 'justify' blocks of body copy so that they're aligned to both the left and right margins. Doing this creates blank spaces, which can also make the text hard to read.

**Comment by jbuller** [comment]
Short centre aligned text is also, not only hard to find but liable to be missed entirely by people using magnification concentrating on the left side of the page. 
Multiline centred text also requires finding the start of each line in a different place, especially difficult at high magnifications.

Is justified text hard for everyone or particularly with some conditions?

**Comment by davidc-gds** [comment]
Hey @EoinShaughnessy! Thanks for tagging me, I think generally this seems like a fine direction to go 👍

I might suggest clarifying what we mean by "blank spaces" though, because left-aligning technically also makes "blank" spaces on the far-right of each line.

We could probably remove the "also" in that second line too, I think?

Something like:

> Do not 'justify' blocks of body copy so that they're aligned to both the left and right margins. Doing this creates **wider spaces between words**, which can  ~~also~~ make the text hard to read.
