### ISSUE TITLE
Code review of task-list prototype

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#2118]
## What
 Review code for prototype created by community

## Why
To check that the code is robust before we ask people to test it

## Who needs to work on this
Developer

## Who needs to review this
TL steering group

## Done when

- [x] Developer does code review
- [ ] Feed back to steering group
- [ ] Any potential issues addressed

**Comment by owenatgov** [comment]
Working off of this PR https://github.com/alphagov/govuk-frontend/pull/2261

**Comment by lfdebrux** [comment]
This looks like this is done.
