### ISSUE TITLE
Address design issues in pagination component

### ISSUE THREAD

**Issue by christopherthomasdesign** [alphagov/govuk-design-system#2119]
## What

Decide how to address the design issues raised by the working group in their review of the [pagination component](https://github.com/alphagov/govuk-frontend/pull/2419). Part of https://github.com/alphagov/govuk-design-system/issues/1985.

We already have a checklist of issues to address:
- [x] consider if the component needs to include a top border
- [x]  consider if users need the guidance and example to ‘show the total number of results’
- [x]  consider if the mobile version should be centre aligned — we said that this made sense as the component is symmetrical and nearly the width of a mobile device screen, similar to how full-width buttons appear
- [x]  make arrows and chevrons more consistent — we said that ideally, arrows should represent movement and chevrons should represent dividers, which this component works towards
- [x]  make links a consistent colour, as some are blue and some are black — we said this was to be consistent with a visual hierarchy formed around the ‘back link’ and ‘breadcrumb’ components, though we do need to document these design principles
- [x]  consider if users need the guidance and example for ‘showing large numbers of pages’

## Why

So we know what we're building and can publish the component.

## Who needs to work on this

Designer, Accessibility Specialist

## Who needs to review this

At least a designer and developer – share with the whole team before finalising decisions.

## Done when

- [x] Mocked up design decisions
- [x] Shared with the team
- [x] Made any changes based on feedback
- [x] Fed into the component in Frontend or changes to the guidance

**Comment by christopherthomasdesign** [comment]
Summary of decisions made

### Consider if the component needs to include a top border
Decision: remove the border

- It’s better not to make assumptions about what sits above the component 
- Pagination would be used above things instead of / as well as below
- Users can add borders if needed
- Maybe it could be an option in the macro – the border does work better for the prev/next variation

### Consider if users need the guidance and example to ‘show the total number of results’
Decision: remove the example and guidance

- This guidance would be more at home in a ‘search results’ pattern
- By including it in the component, we’d be taking away the freedom to put this information wherever teams want to put it – it doesn’t necessarily make sense for it to be at the bottom of the page etc
- The macro currently includes a feature for this, do we remove it?
- Even if we remove this, we should advise users not to have 100s pages of results unless they have good search and filters
- It’s dependent on the number of results you get back – you don’t need it if the total number is only a page

### Consider if the mobile version should be centre aligned
Decision: TBC – going to explore further with dev

- Currently goes centre-aligned below 640px width
- When you go to mobile sizes, 340px ish, the layout starts to look jumbled
- Action: explore different layout options for smaller screens e.g. putting prev and next on separate lines above and below the numbers

### Make arrows and chevrons more consistent
Decision: keep as-is for now

- We said that ideally, arrows should represent movement and chevrons should represent dividers, which this component works towards.
- We might want to bring other components in line with this, but it needs more thought and we don’t want to block this work
- Also need to fix bugs:
- Arrows don’t resize with fonts – use relative units instead of px
- Arrow shifts up or down when zoomed in lots

### Make links a consistent colour, as some are blue and some are black
Decision: keep pagination links blue

- Pagination is made of a mix of links and other text (i.e. current page, ellipses) – making the links black would make it harder to distinguish between them
- Back links, breadcrumbs and footer links are in black because they’re usually secondary items on a page, not the main thing the user is doing – they fade into the background a bit
- We think pagination is more likely to be part of the user’s focus and should be blue – higher in the visual hierarchy

### Consider if users need the guidance and example for ‘showing large numbers of pages’
Decision: keep in

- Broadly think it’s helpful to share the rules on implementing truncation, which can be complex
- Will people click on the ellipsis to get the numbers in between? – add this to research questions section

**Comment by owenatgov** [comment]
PR for the pagination component now available: https://github.com/alphagov/govuk-frontend/pull/2610 Closing this.
