### ISSUE TITLE
Document why the border on the character count input doesn't show as an error when the content is under the limit

### ISSUE THREAD

**Issue by christopherthomasdesign** [alphagov/govuk-design-system#2140]
## What

Document why the border on the character count input doesn't show as an error state (i.e. thick red border) when there's been an error but content is under the limit.

For example:

<img width="971" alt="Screenshot 2022-04-13 at 17 30 39" src="https://user-images.githubusercontent.com/19834460/163228141-f1c1209a-9570-4037-97b5-0d11fbee5ba3.png">

## Why

A couple of users have raised issues about this – see https://github.com/alphagov/govuk-frontend/issues/2588 and https://github.com/alphagov/govuk-frontend/issues/1858

## Who needs to work on this

Content designer, probs with accessibility specialist or frontend dev

## Who needs to review this

Anyone

## Done when

- [x] Rationale understood
- [x] Content written

**Comment by EoinShaughnessy** [comment]
We've agreed wording in the [PR](https://github.com/alphagov/govuk-design-system/pull/2188).

However, we're holding off on publishing the change until we figure out how to release it alongside the [bigger update to the same guidance](https://github.com/alphagov/govuk-design-system/pull/2181).
