### ISSUE TITLE
Build the Hide This Page research and testing prototype

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-design-system#2144]
## What
Build a prototype service using the [Hide this page component](https://github.com/alphagov/govuk-design-system/issues/1755) based on the Child maintenance service.

[Prototype code](https://github.com/Ciandelle/hidethispageprototype)

## Why
To test the Hide this page component against usability and accessibility to ensure we are delivering a useful component.

Part of:

- https://github.com/alphagov/govuk-design-system/issues/1755
- https://github.com/alphagov/govuk-design-system/issues/2085

## Who needs to work on this
@Ciandelle @davidc-gds @owenatgov

## Done when

- [x] Build initial version of the Child maintenance service
- [x] Fix issues with history scrubbing
- [x] Add second hide this page button
- [x] Add safety content
- [x] Review which websites to use
- [x] Review position in HTML hierarchy

**Comment by calvin-lau-sig7** [comment]
Just reviewed the ‘Hide this page’ prototype [against the draft doc](https://docs.google.com/document/d/1aTJ6sYEa4KYel4GhKfBoU1BeCUgWWBZOHFcTTN1MKZY/edit?usp=sharing). I’d say it’s good as-is for the purposes of testing stating on 9 May (as it does not need to be perfect fidelity).

There are a few improvements we could make, be happy to baseline the document to brief these changes (ahead of user testing) if we have time and scope.
