### ISSUE TITLE
Draft update for the character count backlog item

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-design-system#2156]
## What
Draft an update for the character count entry in the Github community backlog, explaining what changes have been made in the latest release and why

## Why
So users understand what changes have been made, what prompted those changes to be made, and what testing we've done.

## Who needs to work on this
Developers; Content; Accessibility

## Who needs to review this
Developers; Content; Accessibility

## Done when

- [x] Drafted something for the character count backlog item
- [x] Draft has been reviewed and approved by the team
- [ ] Drafted message to US Design System to also share our findings with them, as they have a similar component
- [x] (once v4.1.0 released) Message has been posted on the character count backlog
- [ ] (once v4.1.0 released) Message has been shared with US Design System

**Comment by davidc-gds** [comment]
Hey @EoinShaughnessy! I'm personally happy to add it as a post on the backlog issue at this point, but wasn't sure if we need sign-off from @vanitabarrett or anyone else before going ahead.

**Comment by davidc-gds** [comment]
This has now been posted publicly to the DS backlog 🙌 
https://github.com/alphagov/govuk-design-system-backlog/issues/67#issuecomment-1131719459

It looks like the next step is to share it with the US Web Design System team - I'll see if we have a contact for that.

**Comment by davidc-gds** [comment]
The issue has been opened with UWSDS, letting them know that we've updated our character count component! 🎉 

https://github.com/uswds/uswds/issues/4714
