### ISSUE TITLE
Release first round of tickets for Design System Day 2022

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2168]
## What
Set up a ticketing system and release first round of tickets.

## Why
So attendees can get tickets for the event

## Who needs to work on this
Kim - setting up ticketing system
Imran - ticket content

## Further detail
We used Eventbrite for Design System Day 2021.

## Done when
- [x] Decide how may attendees
- [x] Consider which groups / organisations / departments to invite
- [x] Draft ticket comms
- [x] Comms review
- [x] Set up ticketing system 
- [x] Release 200 tickets on 15 Aug to mailing list

**Comment by querkmachine** [comment]
I've got a running doc of ticketing-related questions and decisions here (internal): https://docs.google.com/document/d/1UjdCmjQ7gnj-ZR3B11q8iYyh0OcPjpGUA40_bKQI98w/edit?usp=sharing

I've also started drafting the Eventbrite event with the info we already have.
