### ISSUE TITLE
Secure community facilitators for Design System Day 2022 workshops and breakout sessions

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2169]
## What
Approach the community to facilitate workshops and breakout sessions on Design System Day 2022.

### Workshops
90-minute sessions, usually involves a presentation and audience activities
5-7 facilitators needed to run their workshop on both days

### Breakout sessions
50-minute sessions, freeform — can be a discussion, activity, anything they'd like
14-20 facilitators needed over both days (breakout sessions are not repeated)

## Why
So we can began planning the workshops and let attendees know what to expect.

## Who needs to work on this
TBC

## Dependencies
- [x] A theme for the event has been agreed
- [x] Decision needed: How can people propose ideas and volunteer to facilitate?
- [x] Clarification needed: what's facilitators need to do ([see proposed schedule](https://govukdesignsystem.padlet.org/ImHuYorks/vntxtz9vv3do3uiz))

## Done when

Call for facilitators (week of 22 August?)
- [x] Drafted comms
- [x] Comms reviewed by at least one team member
- [x] Published on appropriate platforms

Selection process
- [x] Gather and organise potential facilitators
- [x] Choose facilitators

For the event (done by 7 September)
- [x] Confirm with facilitators
- [x] Schedule facilitators, working with participant comms group

**Comment by calvin-lau-sig7** [comment]
### Next steps:

1. Decision is needed for how can people propose ideas and volunteer to facilitate? E.g. Google Form, email, Padlet board, etc.
2. Draft comms to call for facilitators — scheduled to go out around 18 August. [Doc of comms from last year](https://docs.google.com/document/d/1To43Lx3_INhFpC6bN6OfwsBvYPh3lJCmeZsw8RsKKS8/edit?usp=sharing) (of course, things might work differently this year)

**Comment by calvin-lau-sig7** [comment]
Possible leads:
- Imran Afzal, Co-op Digital
- Another gov department head

**Comment by NickColley** [comment]
Hi being nosey. I'm working at Hippo Digital so been reusing the GOV.UK Design System for client projects. (Latest one was a Surgery product).

I'd be down for running something for "How to re-brand and extend the GOV.UK Design System" but 90/50 minutes is maybe too long.

So if it was flexible enough to make it 30mins max or something could work out.

If you're interested email me at nick.colley@hippodigital.co.uk

**Comment by owenatgov** [comment]
@NickColley Thanks for offering! We've recorded the suggestion and we'll get in touch soon if you make the cut. We're planning on doing an official call for sessions soon and will be putting together an agenda once we've got a few more contributors to pick from.

**Comment by Ciandelle** [comment]
Good afternoon Nick, 
We're just looking into the sessions and wanted to confirm you would be able to do both days (20 and 21 September) if we were to do this as a workshop?
Kind regards
Ciandelle

**Comment by kellylee-gds** [comment]
I think this is done? There's another card for preparing facilitators for the event [#623](https://github.com/alphagov/design-system-team-internal/issues/623)
