### ISSUE TITLE
Announce Design System Day 2022

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2170]
## What
Let the community know we are hosting the event, similar to a 'Save the date', on 22 June.

## Why
So the community knows the event is happening.

## Who needs to work on this
Claire, Nora

# Who needs to review this
Calvin (if available) or Kelly or Imran

## Done when
- [x] We have drafted an announcement
- [x] It has been reviewed
- [x] We have agreed which channels we will post the announcement on
- [x] Announcement made

**Comment by kellylee-gds** [comment]
Hey @NoraGDS and @claireashworth. I made a few changes to this card to reflect what we want to do when announcing Design System Day(s) on 22 June. Feel free to add anything else to it.

cc @trang-erskine

**Comment by trang-erskine** [comment]
For the announcement I think we'll need 3 bits of 'official' comms. 

1) Email to the mailing list
2) Slack message to our usual x-gov and GDS channel. 
3) Draft tweet for GDS comms to send out on the day for us. 

We may also want to suggest for the Slack message, that users pass on the message to others that might be interested within their organisation. 

I will contact GDS comms to let them know what's happening. 

For people's personal twitter accounts, I'm guessing we'll leave it up to them. 

Here's also the link to Claire's doc that she started. https://docs.google.com/document/d/1f3BSOwQiS9SV6F26S3TNeELClHeUplALjWkFTQrCm2A/edit#

**Comment by kellylee-gds** [comment]
We're going to use #DSDay22

**Comment by trang-erskine** [comment]
I messaged comms, there's no conflict on the comms grid for Wed 22 June. We should be fine to make the announcements on the day.
