### ISSUE TITLE
Get a Zoom and Zoom Events account for the Design System team

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-design-system#2215]
## What
Sort out our own Zoom account for Design System Day (and one yearly license)

## Why
So we're not dependant on the GDS Zoom license which doesn't allow us to run multiple sessions, we don't have visibility of sessions and where we have to rely on the license holder to set us up as a host at the time of the meeting.

## Who needs to work on this
Vanita, Trang

## Who needs to review this
Purchase will need budget approval

## Done when

- [x] Decide if we need the large meeting add-on for a full year or ad hoc
- [x] Get spend approval
- [x] Get DPIA
- [x] Decide on a team email address to use for Zoom account
- [x] Purchase Zoom and Zoom Events (refer to [budget for exactly what to purchase and for how long](https://docs.google.com/spreadsheets/d/1txOS45CJ4iW3qXTsvKRBWidUu8obD7GHhiwJHEYU6WI/edit#gid=1814714412))
- [x] Store the credentials somewhere and make sure the right people have access

**Comment by vanitabarrett** [comment]
Zoom costs document: https://docs.google.com/document/d/1Reqk6WD6mXqGgZjsLkr5yMWHTbEaSI93YeFoGbSet7U/edit#

**Comment by kellylee-gds** [comment]
@vanitabarrett @trang-erskine I've moved this back into the backlog until we're ready to purchase the Zoom licenses

**Comment by vanitabarrett** [comment]
## Update

I've been following [Kelly's slides on how to purchase something at GDS](https://docs.google.com/presentation/d/1zGPQXEx4KXBHvQcMjFrEhVbapCZP-96VH7nS97n9AEc/edit?pli=1#slide=id.g3fa76ba11d_0_0)

I reached out to the Privacy team last week, and attended a meeting with representative from Privacy and IA on Thursday 1st September to explain our reasons for selecting Zoom Events, what we want to use it for, and how we want to use it.

At the meeting, IA requested more information on 1) audit logs within Zoom Events, and 2) how we were planning to set up the accounts. I have emailed our IA contact (see below) with answers to both.

A [DPIA has been completed](https://docs.google.com/document/d/1q75PMr52qQBS0i4q-KEvmf9uVjBf45WuP6OMOHMZ5p4/edit#) and is being reviewed. - I have given access to members of the Platforms team (David, Trang, Nora)

When I asked for an update on Tues 6th September, the estimate was that the DPIA would be completed by Thursday 8th and that they hadn't found any new risks compared to normal Zoom Meetings.

Contact in the Privacy team: Fadzai Dizanadzo
Contact in the IA team: Rashalin Vather

**Comment by vanitabarrett** [comment]
When it comes to actually purchasing things, I've written up my thoughts on [account setup/management here](https://docs.google.com/document/d/1IaDYeeHS1TAF_qNjBQlGZoxarzt0zFpIQ-ga7GEX9dE/edit#heading=h.ofypvedb4t9c). The team seem to be leaning towards Option 2.

**Comment by vanitabarrett** [comment]
Latest update: the DPIA has been approved from the Privacy team, but still needs IA to complete their section. Rashalin has been prompted to do so in an email thread which I’ll forward to the other people in the Design System team working on platforms.

The Privacy team have stated that “the issues raised in the Zoom Meetings assessments are the same issues that arise with Zoom Events” and advised that we "follow the guidance set out in the Zoom Meetings DPIA.”

Recommended actions when using Zoom:

- Recommend using the desktop version of Zoom over the Web/Phone app - already doing this
- A generic group work email or an individual work email can be used for the host licenses, but they must be CO/Gov email accounts - already planning to do this
- Zoom must not automatically sync calendars and contacts - TODO
- Meetings must have passwords - N/A Zoom Events requires registration, so may not apply in our case
- All participants must sign into Zoom - N/A again, Zoom Events requires registration with a Zoom account
- Attendees must be invited at their work accounts - N/A as is open to public
- Waiting rooms should be used to manage identification of meeting attendees as they join - TODO
- Meeting host must inform attendees if recording will take place. They must inform the meeting before recording starts and give attendees time to turn cameras off - already planning to do this
- They must link to a privacy notice in the meeting invitation - TODO
- Recordings should not be stored in the Zoom cloud. They should be stored in GDS’ Suite Cloud - already planning to do this
- If the chat function is used during the meeting and contains substantive discussion, it should be exported and saved - already planning to do this
- Guidance should be issued to advise users to change their cookie settings to exclude Advertising cookies - TODO
- Guidance should be issued to advise users not to sync calendars and contacts - N/A due to public nature of event, people may be using personal Zoom accounts configured to their preference?

**Comment by vanitabarrett** [comment]
I have added some of the recommendations noted above to https://github.com/alphagov/govuk-design-system/issues/2216

**Comment by vanitabarrett** [comment]
Note: we are planning to purchase Zoom Events for 1 month only, so should only go ahead with the purchase once we 1) have the date confirmed and 2) are under a month away from the event.
