### ISSUE TITLE
Purchase Sli.do for anonymous Q&A at Design System Day

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-design-system#2217]
## What
Investigate Sli.do as an option for Design System Day. Do we have access to an account or do we need to factor that into the budget?

## Why
We may want to give attendees the ability to ask anonymous questions during Design System Day, e.g: during the keynote.

## Who needs to work on this
@vanitabarrett 

## Who needs to review this
@trang-erskine 

## Done when

- [x] Found out how to get access to Sli.do and any cost involved
- [x] Decide if it's something we want to use
- [x] Get budget approval
- [ ] Get one-off account (might need to be one month out from Design System Day?)
- [ ] Store credentials somewhere
- [ ] Decide how we'll use it, e.g: would we give the speakers access or have someone from our team facilitating the Q&A aspect
- [ ] Factor it into the agenda/plan of the day somewhere
- [ ] Set account up ready for Design System Day

**Comment by vanitabarrett** [comment]
If there's no GDS account we can use then it's £180 for a one-off event, 1000 participants, access to advanced features e.g: moderation, replies, polls topics and quizzes, password protected.

Only 1 user allowed on the account, so we'd have a team account and we'd probably need to facilitate the Q&A discussions ourselves during the day, e.g: going through and picking the questions to ask the keynote speaker(s), reading them out for them, maybe copying them into Zoom chat too.

**Comment by vanitabarrett** [comment]
@trang-erskine confirmed with the GDS comms team that there is no GDS sli.do account (they just used a one off for the All Staff event), so if we want to use sli.do we'd need to purchase our own one-off account (cost details above)

**Comment by trang-erskine** [comment]
I've added to the budget spreadsheet. We probably need to work out how the single account will work for the event. It's fine for the keynote speakers, however if we intend to use it for workshops or breakout that wouldn't work. 

Although actually we can, we can supplement the paid with the free version for the workshop and breakout since it will be less than 100 participants.

**Comment by vanitabarrett** [comment]
Moving this to Blocked until we get budget approval.

**Comment by vanitabarrett** [comment]
This has had budget approval now. 

According to sli.do, we should be able to purchase our one-off 'event' account at any time because [it will only go live during the specific dates we set](https://community.sli.do/choosing-a-plan-33/all-about-slido-one-time-plans-when-to-purchase-how-to-test-and-collect-questions-beforehand-611). 

Moving this back into the backlog as I think we can pick this up asap.

**Comment by vanitabarrett** [comment]
I've sent an email to the privacy team asking whether it's already been approved. Moving to Blocked until we've had a response.

**Comment by vanitabarrett** [comment]
Put a call out on Slack to double check no one has an existing account we can use. Apparently GDS Recruitment team may have one, so I've got in touch and awaiting a response.

**Comment by trang-erskine** [comment]
We've made the decision to use Zoom Event Q&A instead.
