### ISSUE TITLE
Create and send backlog prioritisation survey

### ISSUE THREAD

**Issue by christopherthomasdesign** [alphagov/govuk-design-system#2219]
## What

Send out survey to the community to work out what patterns and components we should focus on for the next year.

We have [defined the criteria](https://github.com/alphagov/govuk-design-system/issues/2172) and sketched out the process, now we need to put together a survey and send it out.
 
## Why

We haven't reprioritised the backlog in over 2 years. We want to get a better idea of what our users need the most.

## Who needs to work on this

Designer, community designer

Possible input from content, research and delivery manager

## Who needs to review this

The whole team to sense-check and test the survey before sending out

## Further detail

Will probs create a separate card to analyse the results.

## Done when

- [x] get access to Smart Survey
- [x] do data protection and privacy assessments  
- [x] create the survey 
- [x] test the survey with the team
- [x] decide when to send the survey out and for how long
- [x] send out the survey through all the relevant channels

**Comment by vanitabarrett** [comment]
@christopherthomasdesign Can this card be closed?

**Comment by christopherthomasdesign** [comment]
yeah I reckon so @vanitabarrett !
