### ISSUE TITLE
Content flowing out of the container

### ISSUE THREAD

**Issue by igloosi** [alphagov/govuk-design-system#222]
![screen shot 2018-03-21 at 09 42 21](https://user-images.githubusercontent.com/3758555/37703150-9d473024-2cec-11e8-9448-63d33a66eb63.png)

**Comment by dashouse** [comment]
I'm not seeing this...

**Comment by igloosi** [comment]
.app-c-example__frame--resizable {
    /* resize: both; */
}

**Comment by dashouse** [comment]
Got a fix - PR shortly

**Comment by dashouse** [comment]
Resolved
