### ISSUE TITLE
Get support data for Feb to June 

### ISSUE THREAD

**Issue by trang-erskine** [alphagov/govuk-design-system#2223]
## What

We are planning to do support ticket analysis for the away day and need the ticket information from zendesk and github. 

## Who needs to work on this
Developer

## Done when

- [x] Developer to download bulk data for February, March, April, May and June (up to date of pulling the data) from GitHub API and Zendesk. ([How to documentation here](https://docs.google.com/document/d/1G-TN0uXeKchwhHZnmPveX5YteXi3uSl0Rf5vtg-J5l4/edit))

**Comment by owenatgov** [comment]
Zendesk data imported. Having a little trouble importing github data as the sheet has some very strict permissions.

Something worth noting is that there appears to be an undocumented step that we suspect our former PA performed after the data was generated to re-format the tag data into separate tags and confirm if we met our KPI on that particular ticket. I'm going to reach out to them and ask if this assumption is true and if they can provide insights on how they calculated if we reached our KPI or not.

**Comment by owenatgov** [comment]
Github data imported. Closing ticket.
