### ISSUE TITLE
Design and purchase swag for Design System Day 2022

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-design-system#2234]
## What

Purchase swag for attendees of Design System Day 2022, now we have spending approval. 

Continues from #2167.

## Why

So we can give attendees something following the event.

## Who needs to work on this

Designers

## Done when

- [x] Decided on what items we're including
- [x] Designs produced for each item (where applicable)
- [x] Items have been ordered
- [x] Items have been received for distribution

**Comment by CharlotteDowns** [comment]
Need to order A5 flyers without date and get them sent to distributor
