### ISSUE TITLE
Add Nova snippets extension to resources and tools page

### ISSUE THREAD

**Issue by chrisadesign** [alphagov/govuk-design-system#2256]
I've created some Nunjucks macro snippets (aka "clips") for Nova code editor. @querkmachine raised an issue on my repo suggesting I submit here to be added to the [resources and tools](https://design-system.service.gov.uk/community/resources-and-tools/#write-code) page.

The snippets are published to the Nova extension library: https://extensions.panic.com/extensions/ca/ca.GOVUKDesignSystemSnippets/

The code is published to a GitHub repo: https://github.com/chrisadesign/GOV.UK-Design-System-Nova-snippets

**Comment by querkmachine** [comment]
Hey Chris,

Thanks for submitting your extension. Someone from the team will review soon(ish!) it to make sure it meets our contribution criteria.

**Comment by querkmachine** [comment]
Hi @chrisadesign,

Sorry it's taken a while to get back to you on this. It ended up falling between the cushions of the proverbial couch.

We'll be happy to add this to our list of community resources with some additions to documentation. Specifically:

- The GitHub readme should include installation instructions for the extension. In this case, a link to the Nova extensions library page will probably suffice.
- Please include [which version of GOV.UK Frontend](https://github.com/alphagov/govuk-frontend/releases) the extension is updated for. This makes it easier for end users to see if and when the extension has been updated for new releases of Frontend, so they know they're receiving the right snippets for the version they're using.

On a more general note, I noticed that the extension includes various snippets that are specific to code in the [GOV.UK Prototype Kit](https://prototype-kit.service.gov.uk/), such as Express routing JavaScript and the Task List pattern. 

These are not strictly part of the Design System, and I'm concerned it could be confusing to some users if they try to use these outside of the Prototype Kit. It might be helpful to rename these snippets to make this distinction clearer? "GOV.UK Route" might be renamed "GOV.UK Prototype Kit Route", for example.

Also note that as of version 13 of the Prototype Kit, the Task List pattern is no longer bundled with the Kit and must be installed as a separate plugin. I don't know if this warrants changing its inclusion in the extension. 

We'll get this listed as soon as those changes have been made. Thank you for contributing to the ecosystem! 😊

**Comment by chrisadesign** [comment]
Hey @querkmachine, thanks for getting back to me.

Updates:
- added installation instructions and Frontend version to README
- appended the routes snippets with "(Prototyping)"
- added new Summary Card 

I've left the Task List as is for now, if that's alright, I'll update when the component is added to the Design System.

**Comment by querkmachine** [comment]
@chrisadesign Thanks for making those updates!

Regarding the task list, I think that's your prerogative. It's currently a separate thing to both GOV.UK Frontend an the Prototype Kit, needing to be installed separately by anyone wanting to use it, and that might need messaging to a user somehow. If or how you do that is up to you, though!

The task list's code is now hosted here: https://github.com/alphagov/govuk-prototype-kit-task-list
And is released through npm here: https://www.npmjs.com/package/@govuk-prototype-kit/task-list

**Comment by chrisadesign** [comment]
Screw it, I've taken it out
