### ISSUE TITLE
Accessibility advice on task-list prototype

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#2272]
## Why

The steering group have made a few new design decisions on the task-list component, they would love some accessibility advice.

## Who needs to work on this

Community designer
Accessibility specialist
Interaction designer

## Done when

- [x] Call set up
- [x] Feedback given to steering group
- [x] Next steps agreed with steering group

**Comment by davidc-gds** [comment]
Hey @ImranH-GDS! what would be the next step for this one? Would a call among the 3 of us (you, me, Chris) be the first place to start? Thanks!
