### ISSUE TITLE
Create documentation for localisation - passing translations via data attributes

### ISSUE THREAD

**Issue by vanitabarrett** [alphagov/govuk-design-system#2307]
## What
Documentation is needed for the work which allows users to [override hardcoded strings in our component JavaScript](https://github.com/alphagov/govuk-frontend/issues/1708)

There are two ways for users of GOV.UK Frontend to pass translations - via data-attributes or via JavaScript. The first approach (data attributes) will be documented in the Design System website, as the "primary" option for translating component JavaScript. This is what this ticket covers.

The second approach (passing translations via JavaScript) is more technical and may be less commonly used - we should document this approach in the Frontend Docs site. There is a [separate card for this work](https://github.com/alphagov/govuk-frontend-docs/issues/196)

## Why

- To allow users to pass translations via data attributes
- So we document both methods of passing in translations
- So users can see examples of translated components
- So users understand what we mean by localisation and the features and limits of our solution

## Who needs to work on this
Tech Writer; Content; Developer

## Who needs to review this
Tech Writer; Content; Developer

## Done when

- [x] Plan out rough structure of what needs to be included and where, i.e: rough content structure
- [x] Draft documentation
- [x] Examples added for each component
- [x] Developer review
- [x] 2i review
- [x] Publish

**Comment by claireashworth** [comment]
This has gone to another tech writer for 2i.

**Comment by claireashworth** [comment]
2i done and approved for publishing

**Comment by colinrotherham** [comment]
New **JavaScript API Reference** added:

* https://frontend.design-system.service.gov.uk/javascript-api-reference/
