### ISSUE TITLE
Iterate the backlog pages to show our priorities

### ISSUE THREAD

**Issue by christopherthomasdesign** [alphagov/govuk-design-system#2310]
## What

Once we've come up with a top 3-5 priorities to work on, we'll need to iterate:

- the backlog page on the Design System website
- how the existing backlog on GitHub is organised
- how these two things work together

Part of https://github.com/alphagov/govuk-design-system/issues/2220

**Work in progress:**
- [Prototype in Figma](https://www.figma.com/file/T3VVf9Bz6gopuV4iC5TvBj/Design-System-website-templates?node-id=53%3A131)
- [Draft copy in Google Docs](https://docs.google.com/document/d/1oTdAuW2-3dVooAuab8nITS0a18WdQT9z9ZsGDtYsDRs/edit?usp=sharing)

## Why

The current design will no longer be fit for purpose.

We want to highlight the things that we're most likely to work on in the future, and encourage the community to engage with those.

We also don't want to lose the discussion about other components and patterns – they still have value even if we're not going to work on them in the near future.

## Who needs to work on this

Designer, content designer, community designer

## Who needs to review this

Designer?

## Done when
Tasks updated 20/10/22

- [x] Mock up backlog page and write copy
- [x] Update all the links on the page so they all go to the right place (including community collab Slack groups)
- [x] Set up Github discussions for our 3 priorities
  - [x] Create a template for the first post on each discussion (make it clear how we want users to engage with it, what we need from them)
  - [x] Populate the 3 templates with the relevant content about each priority
- [x] Update the community backlog repo
  - [x] Consider renaming the backlog – we talked about 'Discuss components and patterns'
  - [x] Come up with a new structure for the cards on the backlog board, which removes the progress statuses
- [ ] Make a comms plan, which should include:
  - [x] These are our 3 priorities
  - [ ] We’re testing the discussion feature
  - [x] We want your designs, use cases, and user research
- [ ] Review and publish the page
- [ ] Close the old backlog project and update anything that links to it
- [ ] Send comms to update the community on the changes

**Comment by christopherthomasdesign** [comment]
WIP in Figma: https://www.figma.com/file/T3VVf9Bz6gopuV4iC5TvBj/Design-System-website-templates?node-id=53%3A131

**Comment by calvin-lau-sig7** [comment]
@Ciandelle and I caught up on 22 Aug

Over the next sprint:
Calvin will review and draft copy for the page, figure out how it fits with related pages, such as Roadmap
Ciandelle will investigate using GitHub discussions and best way to build pages to gather feedback from communityy

**Comment by kellylee-gds** [comment]
@calvin-lau-sig7 @christopherthomasdesign @Ciandelle I've popped this back into the backlog to pick up again after DSDay

**Comment by calvin-lau-sig7** [comment]
The mini journey in summary:
[Upcoming components and patterns](https://deploy-preview-2354--govuk-design-system-preview.netlify.app/community/upcoming-components-patterns/) page in the Community section
- Links to ['Help us' discussion threads](https://github.com/alphagov/govuk-design-system/discussions) (as GitHub discussions) on the Design System repo
- Also links to '[Discuss styles, components and patterns](https://github.com/orgs/alphagov/projects/43/views/1)' list of issues
