### ISSUE TITLE
Add `.govuk-link--text-colour` to docs

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#232]
This was released as part of [FE v0.0.27-alpha](https://github.com/alphagov/govuk-frontend/releases/tag/v0.0.27-alpha)

> Added a new .govuk-link--text-colour modifier to make links use the same
colour as the text.

**Comment by timpaul** [comment]
Decisions required:
- [ ] When is this an appropriate link style?
- [ ] Is this class the best way to implement that style?
- [ ] Do we want to document the class?

**Comment by timpaul** [comment]
There are currently 3 use cases for this that we know of:

- back links
- breadcrumbs
- focussed links

It's not clear that there are other valid use cases and we don't yet have design guidance for when to use black links, so we shouldn't provide this class. Closing this for now.
