### ISSUE TITLE
Replace metalsmith-env plugin with Metalsmith's inbuilt env method

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-design-system#2330]
## What

Remove `metalsmith-env` as a dependency and use Metalsmith.env() instead.

## Why

Metalsmith [2.5.0 introduces a new `env` method](https://metalsmith.io/news/2022-06-10/metalsmith-2.5-released/#highlights). It's always good to remove an uncessary dependency, and `metalsmith-env` was last updated in 2020.

## Who needs to work on this
Developer

## Who needs to review this
Developer

## Done when

- [ ] metalsmith-env is no longer a dependency

**Comment by webketje** [comment]
FWIW replacing it would be :

https://github.com/alphagov/govuk-design-system/blob/main/lib/metalsmith.js#L79

```diff
// include environment variables as metalsmith metadata
// used to e.g. detect when we're building in a preview environment
- .use(env())
+ .env(process.env)
+ .use((files, ms) => ms.metadata(ms.env()))
```
