### ISSUE TITLE
Write a blog post about the Safari text-wrapping bug

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#2331]
## What

Write a blog post about the issue we had with [text wrapping unnecessarily in Safari Technology Preview](https://github.com/alphagov/govuk-frontend/issues/2429), including:

- how we found out about the bug
- how we understood the bug enough to be able to report it
- what happened
- why the bug occurred
- what we think could have happened if we hadn't reported it

We can use the ['The Safari bug that never was' presentation](https://docs.google.com/presentation/d/1Gc0hWY31V57IO-A322MhRYc4OEuDpBoeMgV4EafObYo/edit#slide=id.g11dfc2825d6_0_0) as a starting point.

## Why

To promote the work that the Design System does, and to promote a culture of contributing to the web platform both internally and externally.

## Who needs to work on this

Developer, designer (for illustrative images), content designer?

## Who needs to review this

- Contacts at Apple (WebKit)
- Tech blog editor

## Done when

- [x] Draft written
- [x] Draft shared with team
- [x] Draft shared with WebKit engineer who worked on the bug
- [ ] Draft shared with tech blog editor for approval
- [x] Blog post published

**Comment by kellylee-gds** [comment]
Closing this issue as this blog was published.
