### ISSUE TITLE
Iterate 'Summary card' contribution

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2344]
## What
Iterate the summary card following decisions made following the working group review (https://github.com/alphagov/govuk-design-system/issues/2326)

## Why
So we know what we're building and can publish the component.

## Who needs to work on this
Designer, Content designer, Developer

## Who needs to review this
Share with the whole team before finalising decisions

## Done when
- [x] We've got any additional advice needed
- [x] Changes made based on feedback
- [x] Changes checked against recommendations
- [x] Share with the whole team to review
- [x] Improve and iterate from team feedback
- [x] Ensure accessibility best practice in component

**Comment by calvin-lau-sig7** [comment]
On 25/11, team came up with some accessibility suggestions to look at:
- allow teams to specify heading levels in the card titles
- allow better control over the "noun word" used to describe what a summary card is describing
- better distinguish the title bar and group actions from the lines (of the summary list)

We're working to iterate and improve the component and its guidance before we publish.

**Comment by christopherthomasdesign** [comment]
Update! We had a catch-up yesterday with the contributor to talk about an accessibility issue we found. Namely that it might not be clear to all users that the actions in the header apply to the whole contents of the card.

To solve this, we’re proposing to add a one-word noun to the card actions. For example, ‘delete job’, or ‘delete applicant’. That will be followed by the same visually hidden text as currently proposed, which specifies which ‘job’ or ‘applicant’ someone would be deleting.

We also proposed a couple of enhancements that could help further:

- bolding the links in the header, to emphasise that they’re higher-order actions
- allowing teams to add a caption to the card headings, in cases where the content is complex and you need to be absolutely clear what the card represents

Next steps:

- work out details of how to style and code the 2 enhancements
- add guidance to better explain how to write good card actions
