### ISSUE TITLE
Create landing page for Community section

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#2349]
## What

Create a landing page to tell users about our community activities, which could include:
- co-design workshops for Maps and Task list
- Friday catch-up call
- cross-gov Slack channels

This will also create a new top-level page for /community/, which should give this section a clearer purpose

### Work in progress:

Pull request: https://github.com/alphagov/govuk-design-system/pull/2356

[Preview page](
https://deploy-preview-2356--govuk-design-system-preview.netlify.app/community/)

[Mural board with mockups](https://app.mural.co/invitation/mural/gaap0347/1659023424168?sender=u0b59bf53328f6bc22ae10431&key=74effb79-3421-48f8-8016-24ad1854e7f6)
[Content doc for drafts](https://docs.google.com/document/d/1ACuV3jtGhfxkTaRtjdAQuPLYO1wiv0CCWYjiyPp6-p8/edit?usp=sharing)
[Padlet board](https://govukdesignsystem.padlet.org/calvinlau1/txb9ypbiz98tfwow) with ideas from the team

## Why

We do not have a place to direct people who are interested in taking part. At the moment we rely on 'push' messaging over emails and Slack.

## Who needs to work on this

Community Designer, Content Designer, Interaction Designer

## Who needs to review this

Contribution squad

## Done when

- [x] Outline drafted from Mural workshop outputs
- [x] Designs drafted to find best way to present information
- [x] Reviewed by everyone working on this
- [x] Design and build page in GitHub
- [x] Add images — create new illustrations and source images 
- [x] Reviewed by team
- [x] Tidy up commit history
- [ ] Published

**Comment by calvin-lau-sig7** [comment]
Picking up for this sprint.

I'll work on new content outline/draft [based on the Mural](https://app.mural.co/invitation/mural/gaap0347/1659023424168?sender=u0b59bf53328f6bc22ae10431&key=74effb79-3421-48f8-8016-24ad1854e7f6), updating the [existing content doc](https://docs.google.com/document/d/1ACuV3jtGhfxkTaRtjdAQuPLYO1wiv0CCWYjiyPp6-p8/edit?usp=sharing).

Will then loop in community and interaction designers to decide the best way to present this information.

**Comment by calvin-lau-sig7** [comment]
Community, content and interaction designer met to discuss continuing work from the Mural board.

We looked over the decisions from previous workshop:
- decisions agreed on the IA structure — where the new landing page sits and adding 'subsection themes' to the section.
- not sure yet on how to order and group the different 'ways to get involved'
- ...we'll work towards developing content to enable AB testing
- ...some exploration "|Different ways to order 'ways to get involved'" added to Mural board

**Comment by calvin-lau-sig7** [comment]
a few of us met to review the [Community landing page](https://deploy-preview-2372--govuk-design-system-preview.netlify.app/community/) and come up with these next steps — thanks 
@CharlotteDowns  for the notes.

- Add in different placeholder images
- Experiment with styling sections differently, for example ‘Join the conversation’ being a summary list or image tiles, ‘Collaborate and co-design’ image tiles being 1/3 width or 2/3 width
- Experiment with adding a ‘Featured’ section near the top (that can be removed if nothing featured)
- Discuss and experiment with adding jump links to the left hand ‘themed’ page nav (combining the dash list from the Styles pages with the heading structure of the Patterns pages)
- Decide whether ‘Sign up to mailing list’ section should use styles found with the Design System

Aiming for first published version in time for Design System Day, so we can promote it to as many users as possible

**Comment by christopherthomasdesign** [comment]
Had a catch-up with @calvin-lau-sig7 and @owenatgov today, noted a few things to do before we're ready to review:

- [ ] Make the layout reflow better across screen sizes – Owen
- [ ] Try make the newsletter signup section a bit shorter (and a few other content tweaks) – Calvin
- [ ] Export the illustrations / flat images as SVGs – Chris
- [ ] Try find a better image for the 'Join a Workshop' section – Chris

And before publishing:

- [ ] Work out an approach to consent for the images we want to use from Google Meets – Chris with Imran when he's back
- [ ] Review other pages in community section to make sure we haven't made any dodgy merges along the way

**Comment by calvin-lau-sig7** [comment]
I've transcribed a list of people's faces seen in [screenshots in the content doc](https://docs.google.com/document/d/1ACuV3jtGhfxkTaRtjdAQuPLYO1wiv0CCWYjiyPp6-p8/edit?usp=sharing).

If we were to get consent, we'd probably:
- try to identify anyone remaining people I haven't recognised couldn't transcribe
- cross-reference this with the list in Eventbrite for the Maps collab event
- email them if they're willing to appear on our website
- capture their response as consent

**Comment by calvin-lau-sig7** [comment]
Content's been reviewed and approved by everyone needed.
Meeting in the books to double-check the merge and commit history to get this ready to publish.
