### ISSUE TITLE
Follow up on results of Exit this Page behaviour spikes

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-design-system#2402]
## What
Review the unsolved problems that have emerged from the Exit this Page button behaviour spikes. These spikes were:

- https://github.com/alphagov/govuk-design-system/issues/2386
- https://github.com/alphagov/govuk-design-system/issues/2387
- https://github.com/alphagov/govuk-design-system/issues/2390
- https://github.com/alphagov/govuk-design-system/issues/2389

## Issues that have emerged from the spikes
All of the below issues have an impact on the others which is it why it'll likely be most valuable to talk about them all at once.

### The esc key as the sole keyboard means of activation is problematic
Over the course of these spikes and before during the first round of research, we found that the current keyboard activation method of pressing the esc key 3 times has a number of problems:

- The esc key doesn't count as [user activation](https://developer.mozilla.org/en-US/docs/Web/Security/User_activation) in the HTML spec. What we've found this means is that if a user lands on a page, doesn't trigger user interaction by interacting with the page but activates the button using 3xEsc, the browser [replaces](https://developer.mozilla.org/en-US/docs/Web/API/Location/replace) instead of adding to the history normally, meaning that previous page is lost.
- The esc key is already used in a feature in browsers that stops a page loading before it finishes loading, meaning that a user could inadvertently prevent navigation on that 3rd key press by holding it down longer than a single frame (less than a millisecond)

The latter issue has been solved by changing the event which triggers the button press from `keydown` to `keyup`, meaning that the user has already stopped pressing esc when navigation is triggered. The former issue however is still a problem. This is especially poignant for screen reader users who're using the autoread feature of screen readers where a page is opened and the screen reader starts reading the contents of a page automatically, as this doesn't count as user activation.

It's been hypothesised that this could be solved with a combination of button presses eg: esc followed by shift within the span of 3 seconds.

Discussion can be found in the details of https://github.com/alphagov/govuk-frontend/pull/2949

### How do we handle the recommendation of 2 buttons on a page?
We are recommending to service teams that they include 2 EtP buttons on a page: one visible button and one hidden one that has up until now been treated like an extra skip link. As possible solution to a problem that emerged during the button position on small screens spike where the button being at the top of the screen interfered with header navigation, we had the idea to use the hidden button as the mobile button as it would naturally start outside the page's `main` and therefore sit above navigation when the user scrolls to the top of the page.

There are a couple of unanswered questions here:

- Considering we can't have a macro which injects html into another part of the page (without js), how do we handle if a team has implemented the visual button component macro but not the full pattern with the hidden button?
- How do we style the hidden button if we want it to look like a button on mobile but a skip link on desktop?

Discussion can be found in the comments of https://github.com/alphagov/govuk-design-system/issues/2387

### Are the screen reader announcements important enough to use `role="alert"`?
The screen reader spike touched on [WCAG 4.1.3](https://www.w3.org/WAI/WCAG22/Understanding/status-messages.html) as this conveniently means we are compliant to that criterion. However, an unanswered question from that spike is if the announcements that we're delivering for the activation key being pressed and the button being activated need to be `role="alert"` or `aria-live="polite"`. WCAG 4.1.3 notes that you should only use `role="alert"` for important and time sensitive announcements which it could be argued this is as it is important when you need to use it and the activation key press functionality is time sensitive.

Discussion can be found in the comments of https://github.com/alphagov/govuk-design-system/issues/2386

## Done when

- [x] Team members working on EtP come together and discuss the issues
- [x] We have agreed how to handle these problems
- [x] We write new issues to tackle any remaining work as a result of our agreed next steps

**Comment by owenatgov** [comment]
The team met to discuss the above questions and reached the following conclusions:

## Issues with 3 x Esc keyboard activation
Status: **Still unsure**

### Actions
- Change the activation key to be shift 3 times in a row instead of esc
- Investigate checking to make that shift isn't be used any other way eg, checking if buttons had been pressed between the shifts

### Notes from discussion
- Esc is an inherently problematic key to use for this functionality due to it being used in significant actions in other software, despite being conceptually perfect
- We initially chose esc because it was being used by other escape buttons, but that doesn't mean it's the right choice
- Shift doesn't have any actions specifically mapped to just pressing shift and is on every keyboard
- Shift could be pressed 3 times in rapid succession in conjunction with other actions, but we can check for this in the js

## Styling between 2 buttons on a page
Status **Still unsure**

### Actions
- Investigate moving button outside of main so that it sits below the header instead of above it

### Notes from discussion
- Restyling components to be explicitly different between screen sizes is probably a last resort as it's going to require some extra infrastructural work to allow exporting those styles between components, in this because the top-most button uses the skip link and we'd therefore need to export both the skip link and button styles for use on a new component
- We should be conscious of weirdness around `position: sticky` and our grid system

## The severity of our screen reader announcements
Status: **Confident**

### Actions
- Add an announcement for when the keypress timer runs out
- Change announcements to use `role="status"` **except** the button activation which should still use `role="alert"`
- Experiment with increasing the timeout time eg: 5 seconds? 10 seconds?
- Content design the announcements
- Move the announcement "code" to their respective location

### Notes from discussion
- `role="status"` will mean the announcement is longer but will provide more context
- Having an announcement for when the timer runs out will help users discern if an announcement is out of date or not eg: if a keypress is announced but the timer has run out by the time the announcement actually reaches the user so it's now incorrect information

## Off topic from button behaviour but still important
Considering a lot of these actions rely on js, how do we communicate them to users who might not have js available?

**Comment by jbuller** [comment]
Consider that Sticky Keys is invoked by 5 presses of SHIFT on Windows https://www.youtube.com/watch?v=jI8dMv0LpPU

**Comment by owenatgov** [comment]
@jbuller That's a good point. This is my bad for not adding this to the notes. This did come up in the team's discussion and is a consideration as part of implementing 3xshift.

In summary, we're not too worried about sticky keys accidentally activating as we are assuming that if a user presses shift 3 times and then continues pressing it 2 more times, they'll still be safe even if sticky keys is also activated. We however have 2 things to investigate in using shift:

- Can a user still use the button if sticky keys is active?
- What if a user wants to activate sticky keys during a service journey using EtP? (I'll grant you the credit that this thought in particular was prompted by your comment here)

There's still plenty for us to consider and we'll be recording as much as we can.
