### ISSUE TITLE
Update the website to comply with WCAG 2.2 AA

### ISSUE THREAD

**Issue by dav-idc** [alphagov/govuk-design-system#2448]
## What

**Timeline:** June 2023 to September 2023
**Priority level:** 1 – what we must do legally
**Category:** Design system fundamentals

### Potential tasks

- Audit the GOV.UK Design System website to check for WCAG 2.2 AA compliance
- Review the audit results and prioritise work as needed
- Implement changes to bring the website into compliance with WCAG 2.2 AA

## Epic lead
Not yet assigned

## Why

WCAG 2.2 is set to be published in 2023. As such, we hope to bring the GOV.UK Design System website in line with WCAG 2.2 criteria within 9 months of the publish date.

## Who needs to work on this
Everyone: developers, interaction designers, user researcher, accessibility specialist, content designers, product manager.

## Who needs to review this
Just the internal team.

## Done when

- [x] Audit the GOV.UK Design System website to check for WCAG 2.2 AA compliance
- [x] Review the audit results and prioritise work as needed
- [ ] Implement changes to bring the website into compliance with WCAG 2.2 AA
- [ ] Publish the new version of the website

**Comment by owenatgov** [comment]
This has been accidentally superceded by https://github.com/alphagov/govuk-design-system/issues/3967 and https://github.com/alphagov/design-system-team-internal/issues/912 (internal repo, only visible to the team).

As those other briefs are the more active issues, I'm closing this one.
