### ISSUE TITLE
Share findings content audit research with everyone

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2490]
## What
Share the content audit findings from first round of research. 

## Why
To uncover insights and begin ideation.

## Who needs to work on this
Katrina

## Who needs to review this
Product Manager, Designer

## Done when
- [ ] Analysed findings
- [ ] Shared findings in this card, the parent epic, and made available in GOV.UK Design System shared drive
- [ ] Agreed next steps

**Comment by stevenjmesser** [comment]
I've added a link to the doc in next week's show & tell.
