### ISSUE TITLE
Move the team sprint board to the new GitHub projects feature

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2494]
## What
Github released [a new version of their projects feature](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects) earlier this year. We want to move out sprint board to this new version.

At the same time, we should consider reviewing and simplifying our labelling system and whether to utilise milestones better.

## Why
The iterated projects feature better meets our needs, for example, it has a built in analytics which can help us measure our sprints better.

## Who needs to work on this
Kelly

## Who needs to review this
The whole team

## Done when
- [x] Demo the new board features with the team
- [x] Agree most useful 'views'
- [x] Review labelling system
- [x] Review from team
- [x] Migrate board

**Comment by stevenjmesser** [comment]
I can help on this :)

**Comment by kellylee-gds** [comment]
I've been reminded of another thing to consider as part of this work - using [milestones](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/about-milestones) to host epics (we currently use them to help organise releases). @36degrees have spoken about this a few times. Will add as a done when

**Comment by kellylee-gds** [comment]
@stevenjmesser I re-read the docs on new GitHub projects feature. TLDR; I think the new version will benefit the team in terms of visibility and tracking work. 

There are several features that will help;
- creating custom fields for team processes (eg field for squads)
- better filtering (you can filter by every field on the board)
- can add ship dates / targets (eg for a release)
- can add iterations and assign issues to an iterations (eg x issue is planned for sprint 2), ceasing the need for a backlog
- dedicated README to hold information about the board
- automated archiving by custom date
- current views available; kanban or table layout (recommended for our team)

Upcoming features in private beta
- a roadmap layout with timelines
- tasklists where you can build a hierarchy of issues which we could use to host epics and related stories

The data insights aren't as helpful as I initially thought. The only feature available at the moment is a burn up chart. However I'd like to investigate whether there's data I could gather either from the GitHub API or GitHub Actions.

In tandem with this migration, I think it's also worth hosting our current epics on milestones (at least until the new hierarchal tasklists feature is available). Using milestones will mean there is a visual relationship between stories and epics on the sprint board.

Planning to do a demo of this at the L&D session on Monday for the team and then we can do the migration next week.

**Comment by stevenjmesser** [comment]
Cheers, @kellylee-gds, this looks pretty good! It looks very similar to [Linear](https://linear.app/) which I've used before and was a really good, lightweight tool for managing software projects. 

Very much agree on using milestones for epics / projects. I'd be interested to see how the iterations feature works!

I can have a go at building some charts inside the Insights feature. For example, it might be interesting to see issue age (how long an issue has been in an active sprint) but that would presumably require filtering by status and some kind of time aggregation. Not sure that's possible from the 2 minutes I spent playing around with it, but will have a go!

**Comment by kellylee-gds** [comment]
Documenting a couple issues I've run into moving our epics to be hosted on Milestones.

- Can only link issues to milestones within the same repo. There may be occasions where we open issues across multiple repos in relation to the same epic. This may prevent issues being grouped together by the same milestone on the new projects board.
- Can only link a single milestone to an issue. We often map issues to upcoming releases which will conflict with linking to an epic

## Future mitigation
Tasklist feature in GitHub projects is designed to create hierarchy amongst issues and will solve this problem. However release date unknown. We have the option of joining the waiting list to test the private beta.

## Possible current mitigation
Manually add epics via free text column on the project board so grouping remains consistent.

**Comment by joelanman** [comment]
did you have any thoughts on the lack of Notes in the new version? Our team found it to be a bit of a blocker as we use them a lot. The reaplcement, Drafts can't contain any formatted text

**Comment by kellylee-gds** [comment]
@joelanman we don't use them for anything significant so shouldn't be an issue at the mo. Hopefully they return notes in a future feature release because they can be useful for teams
