### ISSUE TITLE
Exit this page pattern proposal

### ISSUE THREAD

**Issue by Ciandelle** [alphagov/govuk-design-system#2510]
## What
Exit this page works on both a component and pattern level. Currently we are working on the component, however we have come to realise that there is a need for a pattern. The pattern would be made up of the following:

- Exit this page component[link to page]
- Exit this page hidden secondary link[link to page]
- Ghost page[link to page]
- Interruption page(s) (content type)
- Safety content page

## Why
Having a pattern for exit this page comes from a need for a standardised approach when helping users to quickly exit a service or website. 

## Who needs to work on this
Interaction Designer, Content Designer, Developers, Accessibility Specialist, User Researcher, Community Manager

Part of [Publish Exit this Page component #1755](https://github.com/alphagov/govuk-design-system/issues/1755)

**Comment by Ciandelle** [comment]
Guidance has been written for this and will be shared with team internally later this afternoon. Any feedback will be appreciated.

**Comment by kellylee-gds** [comment]
Closed as moved into done
