### ISSUE TITLE
Create guidance about sharing user research findings to the Design System

### ISSUE THREAD

**Issue by christopherthomasdesign** [alphagov/govuk-design-system#2580]
## What

Create some guidance for the Design System site that tries to introduce some guidelines and standards for writing up user research findings.

Ideally ready for when we kick off the next component or pattern.

## Why

Findings on Github are often written up with varying degrees of detail. When contributors start working on things, it be hard to understand some of it. This isn't a criticism – we've never done much to explain how to do it.

## Who needs to work on this
Designer, Product Manager

## Who needs to review this
Content designer

## Done when

- [x] First draft written and reviewed by team
- [x] Second draft mocked up on website
- [x] We know where it should fit in the website IA (and any other places to link to it from)
- [x] Get other user researchers to have a look
- [x] Detailed content review and changes
- [x] Draft a Slack announcement
- [ ] Use prioritisation survey to identify top 20 components and patterns that we haven't yet added to the Design System, and add link to the new guidance in their respective community backlog threads 
- [x] Update

## Dependencies
Publish guidance before we begin working on Navigation.

**Comment by christopherthomasdesign** [comment]
### Update on this task

Caught up with @calvin-lau-sig7 on Tuesday 28 March – he's gonna take on the work but Exit this Page is a priority in the short term so might only start in next sprint.

We've got some [draft guidance](https://docs.google.com/document/d/1MUj91I80PbBW891E_GPVsTyuOQilFbU3sRwJIqlLdxc/edit?usp=sharing) together (only viewable by team). That's been reviewed and commented on by a group of researchers at GDS to sense-check it.

We handed it over with a few pointers:
* we want to broaden the scope to be about all kinds of evidence (qual and quant), not just user research
* the audience of this guidance could be anyone using the Design System, but more like to be designers and researchers – so we need to write for people who may not be comfortable using github
* we discussed some Service Manual guidance about collecting information responsibly, it could be helpful to link to from here
* similarly there are a few specific bits about using github that should ideally link to githubs own guidance, but we'd need to check that it's clear enough

**Comment by christopherthomasdesign** [comment]
Gonna move this to blocked whilst we work on other priorities

**Comment by calvin-lau-sig7** [comment]
Put this back on blocked as a few of us are not available for the next couple weeks.

Next step is to potentially do some exploration around how to we talk about 'research findings' and other kinds if data we should encourage people to contribute. [Work in progress workshop in Mural](https://app.mural.co/invitation/mural/gaap0347/1681485689468?sender=u0b59bf53328f6bc22ae10431&key=3320ef76-6eac-40e7-be40-1c60831eefa4)

**Comment by kellylee-gds** [comment]
@christopherthomasdesign are you happy if I take this off the sprint board for now?

**Comment by christopherthomasdesign** [comment]
@kellylee-gds sure, I don't think there are any plans to pick it up in the next few weeks. I'll submit a case for it in the roadmap proposal thingy though.

**Comment by kellylee-gds** [comment]
FYI @calvin-lau-sig7 

This was suggested during Q2 pitching so @christopherthomasdesign @stevenjmesser and I met today to scope the work. The remaining steps should be covered in the Done whens. We've scheduled it for Sprint 4 for now.

**Comment by CharlotteDowns** [comment]
## Draft slack message:

📢 We've just [added some guidance on how to 'share user research' with the GOVUK Design System team and community](link) 📝.

We want to make it easier for teams to share their evidence, and this new guidance introduces some guidelines and standards for writing up user research findings. By gathering more evidence for the usability and usefulness of components and patterns, we can iterate and improve elements in the Design System much more quickly.

Thank you for getting involved 💪.

**Comment by CharlotteDowns** [comment]
## Community Backlog threads tasklist

- [ ] Navigation [#76](https://github.com/alphagov/govuk-design-system-backlog/issues/76)
- [ ] Date picker [#17](https://github.com/alphagov/govuk-design-system-backlog/issues/17)
- [ ] Autocomplete [#4](https://github.com/alphagov/govuk-design-system-backlog/issues/4)
- [ ] Filter a list [#133](https://github.com/alphagov/govuk-design-system-backlog/issues/133)
- [ ] Charts and graphs
- [ ] Table with sorting and filters
- [ ] Search [#88](https://github.com/alphagov/govuk-design-system-backlog/issues/88),[#132](https://github.com/alphagov/govuk-design-system-backlog/issues/132),[#189](https://github.com/alphagov/govuk-design-system-backlog/issues/189)
- [ ] Task list
- [ ] Multiple file upload
- [ ] Cards [#113](https://github.com/alphagov/govuk-design-system-backlog/issues/113)
- [ ] More complex tables
- [ ] Welsh/Language switcher [#99](https://github.com/alphagov/govuk-design-system-backlog/issues/99)
- [ ] Dashboard [#15](https://github.com/alphagov/govuk-design-system-backlog/issues/15)
- [ ] International addresses [#31](https://github.com/alphagov/govuk-design-system-backlog/issues/31)
- [ ] Show/hide password
- [ ] Timeline [#105](https://github.com/alphagov/govuk-design-system-backlog/issues/105)
- [ ] Maps [#75](https://github.com/alphagov/govuk-design-system-backlog/issues/75)
- [ ] Content - alt text/images
- [ ] Terms and conditions [#102](https://github.com/alphagov/govuk-design-system-backlog/issues/102)
- [ ] Time [#173](https://github.com/alphagov/govuk-design-system-backlog/issues/173)
