### ISSUE TITLE
Menu appears twice after opening and resizing

### ISSUE THREAD

**Issue by penx** [alphagov/govuk-design-system#260]
To reproduce:

1. Go to https://govuk-design-system-production.cloudapps.digital
2. Shrink browser to see mobile menu
3. Click to open menu
4. Resize browser width to between 641px and 768px
5. Notice menu appears twice

Tested in Chrome and Safari Mac.

<img width="767" alt="screen shot 2018-05-01 at 22 02 50" src="https://user-images.githubusercontent.com/1027024/39493625-74e838d4-4d8b-11e8-8d9e-864c080a4341.png">

**Comment by dashouse** [comment]
Thanks @penx. Great spot!

**Comment by dashouse** [comment]
PR here - https://github.com/alphagov/govuk-design-system/pull/261

**Comment by dashouse** [comment]
PR merged, closing issue.
Thanks again for spotting @penx
