### ISSUE TITLE
Some pages have nested <form> elements

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-design-system#2609]
## What
In #522, we wrapped all examples in a `<form>` tag to disable form validation for any inputs within the examples.

This is mostly fine, but there are some examples where we _also_ have a form inside the example code, which results in nested forms in the compiled code.

### Instances
https://github.com/alphagov/govuk-design-system/blob/d1463ea6344b521bb69144700397e40e44e2d5e2/src/patterns/cookies-page/cookies-form/index.njk#L12

https://github.com/alphagov/govuk-design-system/blob/d1463ea6344b521bb69144700397e40e44e2d5e2/src/patterns/task-list-pages/have-you-completed-this-section-error/index.njk#L9

https://github.com/alphagov/govuk-design-system/blob/d1463ea6344b521bb69144700397e40e44e2d5e2/src/patterns/task-list-pages/have-you-completed-this-section/index.njk#L9

## Why

Nested forms are not valid [according to the HTML spec](https://html.spec.whatwg.org/multipage/forms.html#the-form-element).

## Who needs to work on this
Developer

## Who needs to review this
Developer

## Done when

- [ ] The three `<form>` elements above are no longer nested

**Comment by domoscargin** [comment]
Chrome, at least, seems to account for this by just ripping out the nested `<form>` element (go here and check the difference between "inspect" and "view source": https://design-system.service.gov.uk/patterns/cookies-page/cookies-form/index.html)

**Comment by colinrotherham** [comment]
No more double nested `<form>` examples 🎉

* Want to show an example? Use `layout-example`
* Want wrap it in a form? Use `layout-example-form.njk`
