### ISSUE TITLE
Component examples don't load IE8 stylesheet

### ISSUE THREAD

**Issue by chris-gds** [alphagov/govuk-design-system#2612]
## Description of the issue

While testing v4 on GOVUK noticed the fallback icon was missing 
(_not_ an issue on GOVUK support is IE11+)

## Steps to reproduce the issue

Visit https://govuk-design-system-preview.netlify.app/ (In Browserstack > IE8)

## Actual vs expected behaviour

https://github.com/alphagov/govuk-frontend/blob/main/package/govuk/components/accordion/_index.scss#L175

![image](https://user-images.githubusercontent.com/71266765/152383316-fe5bf5a4-ab44-40a8-a931-2098a15da523.png)

vs 

Expected

![image](https://user-images.githubusercontent.com/71266765/152384476-080608e0-3403-42e6-b60a-463837b6c693.png)

## Environment (where applicable)

- Operating system: Windows 
- Browser: Internet Explorer 
- Browser version: 8
- GOV.UK Frontend Version: 4

Low Priority

**Comment by 36degrees** [comment]
Closing as the Design System website no longer supports IE8.
