### ISSUE TITLE
Start a discussion about apps and invite interested parties to contribute

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-design-system#2613]
## What

We need the community to talk about native apps: what they're working on, problems or questions arising, decisions they've made that are supported by research (or something else).

## Why

This will help us form an initial set of guidance for teams creating native apps.

## How

We could create a discussion thread on the [govuk-design-system repo](https://github.com/alphagov/govuk-design-system/discussions) (the threads in the backlog repo don't get touched).

Is there anything else we could do?

### Possible options (delete as appropriate)

On [Design System homepage](https://design-system.service.gov.uk/):
- update 'What's new' panel
- add content to <a Design system page>

On [Design System roadmap](https://design-system.service.gov.uk/community/roadmap/):
- update 'Recently shipped' column

On Github:
- add backlog comment in <Github discussion issue>
- add message in tech documentation

On Slack, post message on:
- [#gov-uk-design-system on GDS](https://gds.slack.com/archives/CAF8JA25U)
- [#gov-uk-design-system on x-gov](https://ukgovernmentdigital.slack.com/archives/C6DMEH5R6)
- [#design on x-gov](https://ukgovernmentdigital.slack.com/archives/C062GAGLW)

On email, send to list:
- Mailchimp - new and updated components and patterns
- Mailchimp - what we're working on
- Mailchimp - events and workshops
- Eventbrite

On Twitter:
- ask team to tweet
- ask @timpaul to tweet
- request tweet from @GDSTeam

For follow-up:
- mention any follow-up or linked work
- prepare responses to potential questions
- look to revisit to measure success

## Done when

- [x] Issue added to Github repo
- [ ] Shared with appropriate people:
  - [ ] CDDO app strategy team
  - [x] Programme SMT
  - [x] x-gov Slack – #design, #mobile-apps, #design-systems-community
  - [x] Design Leads on DI programme
  - [ ] People who've asked us about apps in the past (might need to dig through Zendesk)

**Comment by stevenjmesser** [comment]
My gut says we should

1. create the discussion thread
2. add a note on roadmap, and upcoming components & patterns
3. share the discussion thread on Slacks and via the mailing list
4. ask leadership to share it (as they're getting a lot of questions)

We should also allow people to send us notes and thoughts by email, for anyone who doesn't use GitHub. (Although I don't think creating an account and adding to a forum-type post is harder on GitHub compared to other platforms.)

**Comment by ImranH-GDS** [comment]
There's lots we can do on this. My initial inkling is that we should run a cross Gov kick-off session to set context of what we are looking for.

It would be good to know:

- What feedback do we want? What format does it need to be in? How detailed are we going?
- Are we synthesizing the feedback into guidance, or are we passing it on to another team?
- Are we creating, and therefore having ownership of the guidance?

We have a fairly good reputation with engagement. When we reach out to the community, we always follow up with the actions promised - even if it does take a while.
If we aren't in control of the guidance, we have to think about the effort we put into the engagement and the risk of reputational damage.

**Comment by christopherthomasdesign** [comment]
I'm leaning more to Steve's suggestion, i.e. just start by making the page on Github and inviting people to add. It’d be a bit quicker and should give us a first idea of the kinds of teams interested in this subject, and the kind of problems they face.

We're also a bit early in terms of knowing what CDDO are doing with the app strategy – I'm a bit wary of creating any suggestion that we're going to publish guidance any time soon, a lot of it will hinge on the shape of the strategy tbh.

If we get a really big response, maybe let's start facilitating some conversations. But I reckon start small for now.
