### ISSUE TITLE
Discuss tag component with DS team

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#2616]
## What
Discuss whether the tag component needs amending, following feedback from the task-list steering group.
## Why
So that the tag component and task-list are consistent.
## Who needs to work on this
Community Manager, Interaction Designer, Product Manager
## Who needs to review this
Interaction Designer, Developer, Product Manager
## Done when

- [x] Basic work scoped out
- [x] Task-list steering group feedback played back to the team
- [x] Team decide if new route is appropriate

**Comment by owenatgov** [comment]
Closing as this is covered by the tag redesign
