### ISSUE TITLE
Update tag component - as a community?

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#2617]
## What
Update tag component to match task-list
## Why
To ensure consistency across components
## Who needs to work on this
Community Designer
## Who needs to review this
Interaction Designer, Developer, PM + DM
## Done when

- [x] Run kick-off session
- [x] Build up base of user research
- [x] Run ideation session
- [x] Amend component
- [ ] Put live

**Comment by owenatgov** [comment]
The redesign of the tag component has now been merged so I'm closing this issue. Whilst it's not live yet, we know it'll be going out in 5.0 so the work is done. We can always reopen this if we decide to roll back on that but it's very unlikely.
