### ISSUE TITLE
Create materials and run task-list accessibility workshop

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#2621]
## What
Create slide deck, documents and run the task-list accessibility workshop

## Why
To show people how we do manual accessibility testing

## Who needs to work on this
Community Designer, Accessibility specialist

## Who needs to review this
Need to loop in our chat moderator(s)

## Done when

- [x] materials created
- [x] workshop run
- [x] feedback collected

**Comment by davidc-gds** [comment]
This ticket is now complete! Here's a summary of what happened:

## Materials created

- [Slide deck](https://docs.google.com/presentation/d/1a46ksgQF1eShXjwrQNpD5ZovVAnzayOgkTxrZ34PzUk/edit?usp=sharing)
- [Main Padlet board](https://govukdesignsystem.padlet.org/kellylee_gds/accessibility-testing-a-component-a-task-list-workshop-bz287y2fjhl0j3a8) (code of conduct, resources, links out to Q&A documentation)
- Padlets for gathering retrospective comments
    - [1 March retro](https://govukdesignsystem.padlet.org/ImHuYorks/accessibility-workshop-retro-zs10ygb4wbi861j1)
    - [8 March retro](https://govukdesignsystem.padlet.org/ImHuYorks/accessibility-workshop-2-retro-sr5frr1ghbd2hrfk)

## Events

- 1 March 2023 ([EventBrite for first workshop date](https://www.eventbrite.co.uk/e/accessibility-testing-a-component-a-task-list-workshop-tickets-558563146407))
    - we did not record this workshop
- 8 March 2023 ([EventBrite for second workshop date](https://www.eventbrite.co.uk/e/accessibility-testing-a-component-a-task-list-workshop-tickets-567866172007))
    - We recorded this workshop, but David lost his voice a bit

**Comment by davidc-gds** [comment]
The next steps can be found in this ticket:
https://github.com/alphagov/govuk-design-system/issues/2661
