### ISSUE TITLE
Investigate hosting and ticketing platforms for Design System Day 2023

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2626]
## What
Investigate platforms options for an online event, and appropriate ticketing platforms to use.

## Why
So we know whether what we'll need to procure, any privacy assessments we'll need to undertake, and what learning we need to do.

## Who needs to work on this
Calvin & Antoni

## Who needs to review this
DS planning group

## Done when
- [x] Investigated options
- [x] Made recommendations to planning group

**Comment by calvin-lau-sig7** [comment]
Recommendations made to group - [Google doc](https://docs.google.com/document/d/1Tj3pBgQuK_3QjtNeiwU7KsGfoN-IXhcH33NkMqyNrEM/edit?usp=sharing)
