### ISSUE TITLE
Investigate venues for Design System Day 2023

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2627]
## What
Investigate options of where an in-person element of the next Design System Day event could be hosted.

## Why
So we can book a space early.

## Who needs to work on this
Ciandelle, Nora & Imran

## Who needs to review this
DSDay planning group

## Done when
- [x] Venues explored
- [x] Accessibility of the venues investigated
- [x] Venue accessibility verified
- [x] Prices collected
- [x] Recommendation made

**Comment by davidc-gds** [comment]
I've added a recommended 'done when' for checking the accessibility of the venue. Happy to chat more if that's too vague!

**Comment by Ciandelle** [comment]
Site visits arranged for Birmingham, Edinburgh and Glasgow for week commencing 08/05/2023 - see card [2769](https://github.com/alphagov/govuk-design-system/issues/2769)

**Comment by kellylee-gds** [comment]
Closing this card as we have chosen venue for the event
