### ISSUE TITLE
Page weight due to Base64 encoded fonts

### ISSUE THREAD

**Issue by Nooshu** [alphagov/govuk-design-system#263]
After working with the service worker PR I did a little investigation around the cause of the large amount of data being cached by the service worker. The root cause of this is the Base64 encoding of the font being embedded into the CSS.

As an example I have highlighted a typical route through the styles section of the site (from a clean cache):

* Initial page load on homepage (/) - **347KB** (1 CSS 206KB, JS file 100KB)
* Navigate to styles (/styles/) - 5KB (mostly cached assets)
* Navigate to colour (/styles/colour/) - 6.2KB (mostly cached assets)
* Navigate to images (/styles/images/) - **690KB** (3 CSS Files 200kb each)
* Navigate to layout (/styles/layout/) - **2.2MB** (11 CSS files 200KB each)
* Navigate to spacing (/styles/spacing/) - **208KB** (1 CSS file 200KB)
* Navigate to typography (/styles/typography/) - 15.4KB (mostly cached assets)

Each of the individual iframes is triggering a CSS load. The layout page is particularly bad coming in at 2.2MB to load.

It is worth noting that after visiting these pages most of the assets for the site are already cached so a users expereince beyond this point should be very quick. The only other pages beyond this point that trigger a larger download I found to be:

* Fieldset (/components/fieldset/) - **208KB** (1 CSS 200KB)
* Address (/patterns/addresses/) - **327KB** (1 CSS 200KB each, 1 GIF 100KB)
* Start pages (/patterns/start-pages/) - **408KB** (2 CSS 200KB each)

**Comment by 36degrees** [comment]
The intention is to update to use the new font loading strategy, hopefully in the next sprint or two.

**Comment by Nooshu** [comment]
This issue has now been fixed by [PR 309 - Update to Frontend 0.0.31](https://github.com/alphagov/govuk-design-system/pull/309). DS is now using the new font loading strategy so the size of CSS files has been reduced massively.
