### ISSUE TITLE
Plan how to gather feedback from users after publishing iterated Images guidance using the experimental tag

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2630]
## What
Using the experimental tag, make a plan of how we will get feedback from users following publishing iterated Images guidance.

## Why
- so we can explain why the experimental tag is being used
- so we know how the guidance is being used in services

## Who needs to work on this
Calvin

## Who needs to review this
Accessibility expert, Interaction designer

## Done when
- [x] Draft experimental message — what are we testing?
- [x] Decide how to implement 'experimental' tag
- [x] Decide on ways users can respond

**Comment by calvin-lau-sig7** [comment]
We are looking to potentially publish this update with an experimental tag. 

This is because we do not know enough about:
- how relevant some of the detailed guidance in the “Avoid images that contain text” section is for service teams
-- it seems rare for citizen-facing services to use images
-- In fact, working on this guidance, the team had difficulty finding examples in live services
- how practical the guidance is — we’re unsure how service teams create and source the images they’d include in a service
-- can they decide on types of images they need (style, file format, etc.) and get it created? 
-- are service teams ever asked to use images they have little creative control over?
-- how helpful is this guidance in their decision-making process?

Decision needed: decide whether to apply the experimental tag to the entire page or only the accessibility-related sections.

**Comment by calvin-lau-sig7** [comment]
I've some draft copy and answers the Done Whens of this ticket [in the Google doc](https://docs.google.com/document/d/1c8axV52ECFzn077hcMwlHfMOobQBRLpTEHy8v0d8-Kw/edit#bookmark=id.px4isndfdhzw).

Pasted below, but please refer to the doc for the latest version.

> ## Experimental notification banner
> 
> This page is currently experimental because [we want to hear feedback](https://docs.google.com/document/d/1c8axV52ECFzn077hcMwlHfMOobQBRLpTEHy8v0d8-Kw/edit#) on how useful this guidance is for service teams.
> 
> ## Research on this guidance, and/or backlog comment - draft copy
> 
> In March 2023, we updated this page to better help service teams use images in their services. In particular, we added a section on how to use images and ensure they’re as accessible as possible — giving advice to teams on how to meet relevant WCAG AA guidelines and even surpass them in line with [our accessibility strategy](https://design-system.service.gov.uk/community/accessibility-strategy/).
> 
> To help us validate that this guidance is useful and practical for service teams across government, we want to get more feedback and examples of images from you.
> 
> We want to hear about any of these areas:
> - how you use images to give information to users
> - examples of images used in services
> - how you create and choose images to use in your service
> - how images are implemented (for [frontend performance](https://www.gov.uk/service-manual/technology/how-to-test-frontend-performance))
> 
> Give us your feedback and examples by [posting a comment on the ‘Images’ discussion on GitHub](https://github.com/alphagov/govuk-design-system-backlog/issues/70).
> 
> ## Channels to communicate
> - ‘Research on this component’ heading on page
> - Post on backlog issue
> - Email to accessibility experts in government(?)
> - Ways users can respond
> 
> The backlog issue is probably the best way, especially as responses will likely include screenshots and annotation.

**Comment by davidc-gds** [comment]
> * guidance

Hey @calvin-lau-sig7! I wouldn't be opposed to having the 'experimental' tag on the whole page at least for a while. I can think of three reasons why:

- we did make a lot of changes across the page (including illustrations guidance)
- it might encourage people to look over other parts of the page and perhaps catch something we missed?
- as far as I know, we only have precedent for an 'experimental' tag on a full page, and not on a portion of a page.

And here are two reasons why just adding it to the relevant section might be good
- it would focus attention on the portion we're really looking for feedback on
- it won't weaken the effect of the other guidance on the page (our other stuff isn't 'experimental')

My proposed option based on this:
- mark the whole page as experimental
- have a callout near the top of the page that links down to the section that explains what feedback we're looking for?

**Comment by calvin-lau-sig7** [comment]
@ImranH-GDS says it'd be good to do some activity to 'show and tell' some of this work. It'll be useful to:
- Find our audience for this guidance (however will need to carefully communicate scope of some of these edits, as images cover a lot)
- Get feedback on whether it's useful (and answer some of the questions we have!)
