### ISSUE TITLE
Finalise safety guidance for Exit this Page pattern

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2631]
## What
Draft a a safety content page which links from the Interruption Page in the component.

## Why
- to help users understand what will happen when they use the Exit this Page button
- to help user stay safe online

## Who needs to work on this
Calvin, Ciandelle

## Who needs to review this
Katrina, David, Owen, Beeps

## Done when
**First draft**
```[tasklist]
- [x] Drafted guidance
- [x] Reviewed guidance with team
- [x] Reviewed at community crit
```
**Final iterations for mvp**
```[tasklist]
- [x] Publish a template of safety content for teams in mvp
```

**Comment by calvin-lau-sig7** [comment]
Decision made for the community consultation:
- During the asyncronous consultation and at the hackathon, we provide a template of safety content in the pattern
