### ISSUE TITLE
WCAG 2.2: File upload || Redundant entry

### ISSUE THREAD

**Issue by dav-idc** [alphagov/govuk-design-system#2664]
## What
Investigate whether there's a technical method for storing uploaded files for the duration of a service journey, to ensure that people don't need to re-upload or re-submit a file partway through the journey.

Scenarios to consider:

- Making sure the file is stored for the duration of the service journey (24h+ perhaps?)
- Only deleting the file if they cancel the journey and don't have a way to return
- Offering a method to re-select the file if needed during a later portion of the process
- Not requiring someone to re-enter information included in the file upload (for example, re-entering your entire resume)

I have a feeling a lot of the solutions we come up with to meet 'Redundant entry' for files will be content / guidance, but I'm hoping we can do a technical investigation first, to see what's feasible and possible.

### Resources

- [File upload component guidance page](https://design-system.service.gov.uk/components/file-upload/)
- [WCAG 2.2 criterion for 'Redundant entry'](https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html)

## Why
The new WCAG 2.2 criterion 'Redundant entry' says: 

> Information previously entered by or provided to the user that is required to be entered again in the same [process](https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html#dfn-process) is either:
> 
> - auto-populated, or
> - available for the user to select.

File uploads and the information contained within the files would presumably be within scope, for the duration of the 'process' (service journey).

## Who needs to work on this
Developer

## Who needs to review this
Accessibility specialist, content designer or technical writer

## Done when

- [ ] Technical feasibility investigation is complete for the scenarios outlined in the 'What' section above
- [ ] Results of the investigation are posted to this issue
- [ ] Results are discussed with the accessibility specialist
- [ ] Connect with a content designer to discuss content updates
- [ ] Decision is made on what actions to take (including likely guidance updates)
- [ ] Implement any agreed upon code or guidance updates

**Comment by dav-idc** [comment]
This has been added to the ['WCAG 2.2 content updates' document](https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit?usp=sharing).

**Comment by calvin-lau-sig7** [comment]
Closing issue – content has been drafted, reviewed and added to pull request #3090 as part of https://github.com/alphagov/govuk-design-system/issues/3276.
