### ISSUE TITLE
Add/update documentation for new `.govuk-input--extra-letter-spacing` class

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-design-system#2665]
## Related documentation
Directly affects: 
- [Text input](https://design-system.service.gov.uk/components/text-input/) component

Probably affects:
- [Bank details](https://design-system.service.gov.uk/patterns/bank-details/) pattern
- [National Insurance numbers](https://design-system.service.gov.uk/patterns/national-insurance-numbers/) pattern
- [Confirm a phone number](https://design-system.service.gov.uk/patterns/confirm-a-phone-number/) pattern

May affect:
- [Payment card details](https://design-system.service.gov.uk/patterns/payment-card-details/) pattern
- [Telephone numbers](https://design-system.service.gov.uk/patterns/telephone-numbers/) pattern

## Suggestion
The next version of GOV.UK Frontend, which is currently intended to be the last feature release for v4, has introduced a new class for text inputs: `.govuk-input--extra-letter-spacing`

This class intends to provide easier to read formatting for form inputs requiring numeric and alphanumeric strings. It does this by increasing the space between each character and by enabling [tabular number styling](https://www.fonts.com/content/learning/fontology/level-3/numbers/proportional-vs-tabular-figures), which modifies how numbers are spaced out and changes the appearance of the number 1 to be wider and more visually distinct. 

This is intended for "non-word" inputs that a user is unlikely to have memorised and may benefit from being able to easily distinguish each individual character, such as:

- Security and OTP codes
- National Insurance numbers
- Bank card numbers, sort codes, BIC and IBAN codes
- Reference and application numbers
- (Potentially) telephone numbers

We should consider documenting this new class and the intended use cases for it. We should also update any examples of the above use cases to include it.

**Comment by stevenjmesser** [comment]
This needs a review from a designer and content designer.
