### ISSUE TITLE
Update accessibility statement for 2023

### ISSUE THREAD

**Issue by davidc-gds** [alphagov/govuk-design-system#2666]
## What
Update our accessibility statement as soon as possible

Here's the pull request: https://github.com/alphagov/govuk-design-system/pull/2752

### Resources

- [GOV.UK Design System Accessibility Statement](https://design-system.service.gov.uk/accessibility/)
- [govuk-frontend accessibility note](https://github.com/alphagov/govuk-frontend#accessibility)
- [Service Manual guidance on accessibility statements](https://www.gov.uk/service-manual/helping-people-to-use-your-service/publishing-information-about-your-services-accessibility)

## Why
Our accessibility statement is intended to be reviewed and updated every year. The last posted update for our accessibility statement was 30 June 2021

## Who needs to work on this
Accessibility specialist, content designer / technical writer, interaction designer (potentially)

## Who needs to review this
delivery manager, product manager

Will also seek advice from developers and interaction designers

## Done when

- [x] Accessibility statement draft update is created
- [x] Draft is reviewed by team
- [x] PR for the update is created
- [x] Final review
- [x] Publish the updated statement

**Comment by 36degrees** [comment]
@davidc-gds is this done?

**Comment by davidc-gds** [comment]
Heya! Yes this is done. Apologies for not closing the ticket sooner.

**Comment by davidc-gds** [comment]
The updated accessibility statement was published live on 27 April, 2023. Woot!
https://design-system.service.gov.uk/accessibility/
