### ISSUE TITLE
Create slide deck to tell the story of Exit this Page

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2675]
## What
Create a slide deck to be presented in the hackathon.

## Why
To explain to participants;
- where the contribution originated
- user personas
- research findings and iterations

This can also be re-used / added to for future show & tells.

## Who needs to work on this
TBC

## Who needs to review this
Ciandelle, Katrina

## Done when
- [ ] Slide deck created
- [ ] Reviewed

**Comment by davidc-gds** [comment]
Hey there! Do we know if this is unblocked now and back in progress?
