### ISSUE TITLE
Create pseudo service prototype to be used in the Exit this Page hackathon

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2676]
## What
Create a pseudo service to be used in the Exit this Page hackathon.

## Why
So participants have a service to implement the component.

## Who needs to work on this
Designer

## Who needs to review this
Designer

## Done when
- [x] Prototyped a service
- [x] Reviewed

**Comment by Ciandelle** [comment]
Pseudo service for the community exit this page ‘hackathon’ has been created in line with the parameters of the service. I have removed the interruption page, the secondary skip link, the ETP button and the loading overlay. Link to the prototype: https://community-exit-this-page.herokuapp.com/
