### ISSUE TITLE
Create coded examples to be added to Exit this Page component guidance

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2677]
## What
Create coded examples of Exit this Page component to be used in the hackathon.

## Why
So participants can fulfil the ask of implementing the component into a service.

## Who needs to work on this
Designer

## Who needs to review this
Designer, Content Designer

## Done when
- [x] Create examples
- [x] Examples added to component guidance

**Comment by Ciandelle** [comment]
We did this a group session between @owenatgov, @calvin-lau-sig7 and myself. We've checked that it's showing up on non-local versions too. It's finally in the guidance 🎉
