### ISSUE TITLE
Review feedback from Exit this Page consultation

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2679]
## What
Review findings from the hackathon and consultation. Decide if any blockers to publication and plan future iterations.

## Why
To improve the component and pattern.

## Who needs to work on this
Katrina, Kelly

## Who needs to review this
Design System squad

## Done when
- [x] Feedback collated
- [x] Presented to squad
- [x] Analysed
- [x] Agreed next steps

**Comment by stevenjmesser** [comment]
Blocked as waiting for Kelly to get back from leave, so she can review findings with team and agree next steps.

**Comment by kellylee-gds** [comment]
Running an async MoSCoW exercise to determine iterations to mvp. Deadline for responses is Fri 2 June

**Comment by kellylee-gds** [comment]
Myself and Steve have reviewed the comments from the community and team following the consultation. We have agreed to make the following iterations to the guidance before shipping:

- add coded examples
- add content to explain this implementation has been researched and tested with users with lived experience of domestic abuse and built in response to the needs identified with this user group, and not other use cases
- add information about how the component is published as experimental, which aspects are not tested, and where teams will need to do research
- add encouragement for teams to share feedback on how they have implemented on static pages that aren't part of a transactional service to 'Known issues and gaps' section
- publish a template of safety content for service teams to use
- do not publish a template of an interruption page, instead include guidance on what this content should include
