### ISSUE TITLE
Discuss if task-list steering group want to work on tag component 

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#2686]
## What
Find out if the task-list steering group want to update the tag component
## Why
To ensure the task-list ‘status’ is consistent with the tag component in the design system
## Who needs to work on this
Community designer, Interaction designers (optional)
## Who needs to review this
-
## Done when

- [ ] Session arranged
- [ ] Feedback given
- [ ] Decision reposrted to the team

**Comment by owenatgov** [comment]
I'm closing this now as since making this there has been an explicit recommendation by the working group to update the tag component and a PR (as Beeps said above) to update the tag component by the task list steering group.
