### ISSUE TITLE
Prevent iframe-resizer from trying to resize iframes that are not loaded yet

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-design-system#2716]
## What

Avoid unnecessary attempts at resizing iframes while iframes are not yet loaded, which leads to console warnings and unnecessary code execution.

## Why

Our iframes are lazy-loaded, but it seems iframe-resizer is not aware of this and tries to communicate with iframes that are not loaded yet. It clogs the console output, and is extra JavaScript that's running and may slow down less powerful machines.

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] Iframes yet to be loaded are resized

**Comment by CharlotteDowns** [comment]
Yesterday we had two users on x-gov slack experiencing this problem in chrome.

User 1
> When loaded in my Chrome browser https://design-system.service.gov.uk/components/radios/ crashes and gives a "Page unresponsive error"
Workd in Edge though.

User 2
> I get that a lot in chrome. Close the tab and open a new one. Out of interest, how many tabs do you have open? I always assumed that was why design system tabs become unresponsive for me. (48 tabs) 

User 1
> I have a few different Chrome windows with different profiles. It doesn't work in windows with 1 and sevearl tabs.

User 2
> Same - I have two Chrome windows with 2 different profiles, plus an incognito window going. One of the profiles has 48 tabs (that's the one I try to use it in) and the other has around 40. But it does usually work if I close all my [GOV.UK](http://gov.uk/) tabs (unresponsive or not) then open a new tab....

**Comment by CharlotteDowns** [comment]
Doesn't seem related to this fix but we had another user on support experience loading issues on the checkbox component and I'm not sure where to capture

> Hello. I keep getting an 'unresponsive' error on this page https://design-system.service.gov.uk/components/checkboxes/ . All other design system pages seem fine.

**Comment by domoscargin** [comment]
Thanks @CharlotteDowns - I've added these comments to the open issue: #2594
