### ISSUE TITLE
Analyse findings from citizen and service team testing of Exit this Page button, component guidance and pattern

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2732]
## What
Analyse findings from round of testing with citizens and service teams, and agree iterations.

## Why
To know if we need to iterate anything before shipping mvp, and what can be a later iteration of the component / pattern.

## Who needs to work on this
Katrina, Ciandelle

## Who needs to review this
Calvin, Imran, Steve, Kelly, beeps, Owen, David

## Done when
- [ ] Findings have been collated
- [ ] Findings have been mapped with the team
- [ ] Iterations have been agreed

**Comment by Ciandelle** [comment]
As there is not available budget for user research we are unable to undertake this testing. Instead we are focusing our efforts analysing feedback from the community consultation, and planning iteration touch points with service teams who implement the component

**Comment by Katrina-Birch** [comment]
There is no budget available at the moment for research, I am in the process of applying for it (will take 6 weeks). Although it's clear we won't be doing research before publication of EtP, we've not decided not to do research after publication or what we're doing with service teams. Please move this to backlog until we've had a discussion with Kelly when she's back.

**Comment by kellylee-gds** [comment]
Closing this issue now but keeping #2726 and #2731 open as we agreed to explore this later in the year when teams have started using Exit this Page in services.
