### ISSUE TITLE
Share Exit this Page with GDS colleagues and the wider community

### ISSUE THREAD

**Issue by Ciandelle** [alphagov/govuk-design-system#2781]
## What do we want to achieve?
Host a series of show & tells with GDS and the community when the component is shipped.

## Why do this?

- Promote and demo the component
- Share our research and development findings
- Provide an opportunity for the community ask us questions

## Epic
[Publish an Exit this Page component.](https://github.com/alphagov/govuk-design-system/issues/1755)

## Is there documentation required?
No

## Estimated lead time
July 2023

## Who needs to lead on this?
Kelly & Ciandelle

## Who needs to review this?
Steve, Katrina

**Comment by Ciandelle** [comment]
I like the idea of combining option 2 and 3 so that we do an internal show the thing with time for questions and then do a show and tell for the cross gov community say a week later. It feels like we could use that component to revitalise the show the thing a little that way too?

**Comment by kellylee-gds** [comment]
Things to consider for a community show & tell / Q&A

- hosting platform (Google Meet or Zoom)
- attendee limit? (150 if using Google)
- ticket the event?
- question facilitation
- record the event?
- repeat if high demand?

**Comment by stevenjmesser** [comment]
Perhaps a bit late now.
