### ISSUE TITLE
Create stickers to celebrate publishing Exit this Page

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2847]
## What
Design and print stickers to be shared with the team and contributors.

## Why
To celebrate publishing Exit this Page.

## Who needs to work on this
Ciandelle, Chris

## Who needs to review this
DS team

## Done when
- [x] Hosted a sticker design workshop
- [x] Team has selected a sticker
- [x] Sent to supplier to print
- [ ] Shared amongst team and contributors

**Comment by christopherthomasdesign** [comment]
Stickers approved by team, sent to print this morning
