### ISSUE TITLE
Create a GitHub Discussions space for Exit this Page

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2848]
## What
Create a GitHub Discussions space to collect user feedback and research findings on specific aspects of Exit this Page component and pattern.

## Why
so we can learn how it is being used in services and iterate accordingly.

## Who needs to work on this
Kelly

## Who needs to review this
Steve, Katrina

## Done when
- [x] Revisited GitHub discussions documentation
- [x] Identified appropriate host location
- [x] Agreed discussion threads
- [x] Published

**Comment by calvin-lau-sig7** [comment]
Summary of what I reckon how the links for #2848 and #2849 will look on the component and pattern pages:

On the ‘Help improve this component/pattern section’, replace the link to the backlog issue page [(example)](https://github.com/alphagov/govuk-design-system-backlog/issues/1) to a new GitHub discussion category [(example)](https://github.com/alphagov/govuk-design-system-backlog/discussions/categories/prioritised-components-and-patterns) page.
- Discussion category will be the main space for users to discuss Exit this page and for the team to make announcements, making use of the discussion features
- Backlog issue page will probably still be needed for consistency and findability for people browsing the backlog repo, but will be locked down and with text redirect users to the discussion category. This is to reduce duplication and confusion on where to go.

In the same section, also add a button to a survey or form tool
- Survey or form will collect info about their implementation of Exit this Page, also service name, organisation, contact email, and questions asking which other components and patterns the use.

**Comment by kellylee-gds** [comment]
[Draft Discussions content](https://docs.google.com/document/d/1scOZU2pms5zMv0plW9T6fAKlNEOb1NtvkAWA9UsEnOk/edit#heading=h.jdtbk3a17q8v)

**Comment by kellylee-gds** [comment]
@calvin-lau-sig7 your above proposal sounds great for mvp. If we see users are struggling to find the appropriate place to share feedback on EtP, then we can reconsider and iterate 👍🏻

**Comment by calvin-lau-sig7** [comment]
No problem, I'll work with @Katrina-Birch on this to [post the discussions](https://docs.google.com/document/d/1VUmj_lJZzrINr1wQUeUTQ7TGGOU2gUjSDpheg4E7Vjk/edit?usp=sharing) we need.
