### ISSUE TITLE
Create comms to assist teams in auditing their services against the new typography scale

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-design-system#2863]
## What
Document the experience of updating our components (https://github.com/alphagov/govuk-design-system/issues/2299) and our website (https://github.com/alphagov/govuk-design-system/issues/2862) and distribute this to the community.

## Why
To give the community an idea of what to expect when updating their own services and to provide frameworks for testing said service(s).

Part of https://github.com/alphagov/govuk-design-system/issues/2289. Requires the above 2 testing issues to be completed.

## Who needs to work on this
Designers, content designers, developers

## Who needs to review this
Team members working on the typography epic, content designers

## Done when

- [x] Figure out what form this could take eg: blog, website page
- [x] Write up testing and fixing experience
- [x] Distribute to community

**Comment by owenatgov** [comment]
Thoughts from the team following a show and tell of the prototype of this work:

- Should we rename the "Get started" section to "Guides"? This would enable us to have a place to put instructive content that isn't tied to a specific style, component or pattern and doesn't fit into some of the guides in the community section. A team member anecdotally mentioned that they "don't go to the Get started section because I don't know what I need to get started with".
- How do we perpetuate this guide for different user scenarios? For example: Govuk-frontend is at release, say, 6.3.1 so the typography has been launched for some time in govuk-frontend "latest", a user is upgrading an old service from 4.7.0 and they want to implement the updated typography scale. We should therefore keep the comms alive but think about how we communicate that a given guide is for a specific audience.

Additionally, nobody on the team has expressed concerns over the form that this content takes as a page on the website, therefore I'm going to presume the form question is answered going forward.

**Comment by calvin-lau-sig7** [comment]
Re: website sections, a vague plan I'd had with @claireashworth was to rename 'Get Started' into something like 'Resources' to give a home for new pages (like v4/v5 documentation) and also some pages that don't quite fit in 'Community' (like community resources [despite the name] and 'blog posts, videos and podcasts'.

I'd say we could definitely do with some user research or card sorting to get this right though.

If we need something more immediate to accommodate typography and v4/v5 though, I reckon a straightforward rename from 'Get started' to 'Guides' is probably fine.

**Comment by calvin-lau-sig7** [comment]
On the 2nd bullet point re: promoting and pointing at the 'update typography' guide page.

I'd reckon the '[Staying up to date with changes](https://frontend.design-system.service.gov.uk/updating-with-npm/#update-using-node-js-package-manager-npm)' page in Frontend docs should have a link.

In release comms and emails ([example](https://us1.campaign-archive.com/?e=__test_email__&u=ada1bae4b177beb9e03502ced&id=c51e8bcdd5)), we can also add a link alongside the typical "Find out how to update to the latest version" link that's at the end.

**Comment by owenatgov** [comment]
It looks like we're in a place where we're happy with the format and content of the prototype for now. I do have a concern about assumptions made in the content of the prototype around feature flags and the idea that we may release "breaking changes" behind the feature flag as we haven't defined this. I'm going to be exploring this more in https://github.com/alphagov/govuk-frontend/issues/4086.

I'm moving it into blocked until we're in a position to start releasing this.

**Comment by owenatgov** [comment]
Whilst this hasn't been distributed to the community yet, the guide itself has been moved into the PR raised for https://github.com/alphagov/govuk-design-system/issues/2300 so I'm calling this closed.
