### ISSUE TITLE
WCAG 2.2: Passwords ‖ Accessible Authentication (Minimum)

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-design-system#2867]
## What

Update our guidance on passwords to emphasise that:
- Developers should allow users to copy and paste values into the password field.
- Developers should use [the `autocomplete` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)'s `current-password` and `new-password` values to allow password managers and user agents to automatically populate the password field.

As we are suggesting the use of particular HTML attributes, we may also want to provide a code example on the guidance page.

### Resources

- [Passwords guidance page](https://design-system.service.gov.uk/patterns/passwords/)
- [WCAG 2.2 criterion for 'Accessible Authentication (Minimum)'](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum)

## Why

The new WCAG 2.2 Level AA criterion 'Accessible Authentication (Minimum)' says: 

> A [cognitive function test](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum#dfn-cognitive-function-test) (such as remembering a password or solving a puzzle) is not required for any step in an authentication [process](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum#dfn-process) unless that step provides at least one of the following: 
> 
> [...] 
> 
> **Mechanism**
>   A [mechanism](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum#dfn-mechanism) is available to assist the user in completing the cognitive function test.
> 
> [...]
> 
> Examples of mechanisms that satisfy this criterion include:
> 1. support for password entry by password managers to reduce memory need, and
> 2. copy and paste to reduce the cognitive burden of re-typing.

Processes that require passwords, such as logging in or authenticating one's identity, are thus within scope of this criterion.

Doing this also satisfies the Level AAA criterion, ['Accessible Authentication (Enhanced)'](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-enhanced.html).

## Who needs to work on this
- Content designer or technical writer
- Developer (if example added)

## Who needs to review this
- Accessibility specialist
- Content designer or technical writer
- Developer (if example added)

## Done when

- [ ] Decision has been made on whether to include a code example
- [ ] Code example has been produced, if required
- [ ] Guidance has been updated

**Comment by dav-idc** [comment]
This has been added to the ['WCAG 2.2 content updates' document](https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit?usp=sharing).

**Comment by calvin-lau-sig7** [comment]
Closing issue – content has been drafted, reviewed and added to pull request #3090 as part of https://github.com/alphagov/govuk-design-system/issues/3276.
