### ISSUE TITLE
WCAG 2.2: Header ‖ Focus Not Obscured (Minimum)

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-design-system#2869]
## What

Add to our guidance on the header component to explain why the header does not use 'dropdown' or 'popover' style elements, in order to avoid the risk of elements overlapping other focused elements.  

### Resources

- [Header component page](https://design-system.service.gov.uk/components/header/)
- [WCAG 2.2 criterion for 'Focus Not Obscured (Minimum)'](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html)

## Why

The new WCAG 2.2 Level AA criterion 'Focus Not Obscured (Minimum)' says: 

> When a [user interface component](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html#dfn-user-interface-component) receives keyboard focus, the component is not entirely hidden due to author-created content.

It is common for service teams to adapt the header according to their own needs, including developing bespoke navigation structures. We likely want to provide guidance against using 'popover' style elements in the header, such as a dropdown menu that appears on pointer hover, as it would create the risk of obscuring a focused element behind the dropdown.

## Who needs to work on this
- Content designer or technical writer

## Who needs to review this
- Accessibility specialist
- Content designer or technical writer

## Done when

- [ ] Guidance has been updated

**Comment by dav-idc** [comment]
This has been added to the ['WCAG 2.2 content updates' document](https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit?usp=sharing).

**Comment by calvin-lau-sig7** [comment]
Closing issue – content has been drafted, reviewed and added to pull request #3090 as part of https://github.com/alphagov/govuk-design-system/issues/3276.
