### ISSUE TITLE
WCAG 2.2: Task list ‖ Dragging Movements

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-design-system#2870]
## What

Update our guidance around the task list component/pattern to include a note about not depending upon interactions that require dragging (e.g. drag and drop reordering), if the task list has been modified to use it. 

### Resources

- [Task list guidance page](https://design-system.service.gov.uk/patterns/task-list-pages/)
- [WCAG 2.2 criterion for 'Dragging Movements'](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html)

## Why

The new WCAG 2.2 Level AA criterion 'Dragging Movements' says: 

> All [functionality](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html#dfn-functionality) that uses a [dragging movement](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html#dfn-dragging-movement) for operation can be achieved by a [single pointer](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html#dfn-single-pointer) without dragging, unless dragging is [essential](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html#dfn-essential) or the functionality is determined by the [user agent](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html#dfn-user-agent) and not modified by the author.

Although we do not ship the task list with the ability to re-order items via drag and drop, similar components developed elsewhere in GDS do, such as [GOV.UK's reorderable list component](https://components.publishing.service.gov.uk/component-guide/reorderable_list). 

We may want to pre-emptively warn service teams against relying on dragging movements in their task list interfaces and encourage them to provide alternate methods of ordering items. 

## Who needs to work on this
- Content designer or technical writer

## Who needs to review this
- Accessibility specialist
- Content designer or technical writer

## Done when

- [ ] Guidance has been updated

**Comment by dav-idc** [comment]
This has been added to the ['WCAG 2.2 content updates' document](https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit?usp=sharing).

**Comment by calvin-lau-sig7** [comment]
Closing issue – content has been drafted, reviewed and added to pull request #3090 as part of https://github.com/alphagov/govuk-design-system/issues/3276.
