### ISSUE TITLE
WCAG 2.2: Confirmation pages ‖ Dragging Movements

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-design-system#2874]
## What

Add sentence to confirmation page guidance to ensure that users are able to select and copy information from the page, particularly reference and application numbers, without obstruction. 

### Resources

- [Confirmation pages guidance](https://design-system.service.gov.uk/patterns/confirmation-pages/)
- [WCAG 2.2 criterion for 'Dragging Movements'](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html)

## Why

The new WCAG 2.2 Level AA criterion 'Dragging Movements' says: 

> All [functionality](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html#dfn-functionality) that uses a [dragging movement](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html#dfn-dragging-movement) for operation can be achieved by a [single pointer](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html#dfn-single-pointer) without dragging, unless dragging is [essential](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html#dfn-essential) or the functionality is determined by the [user agent](https://www.w3.org/WAI/WCAG22/Understanding/dragging-movements.html#dfn-user-agent) and not modified by the author.

As the action of selecting text is typically performed using dragging movements, either with a mouse cursor on desktop or with a finger on touchscreens, we're opting to highlight it here, as this is a situation where is a user is more likely to want to select and copy information.

Even though text selection is typically a user agent function rather than something in authored code, we want to ensure that service teams know not to interfere in the typical user agent behaviour. 

## Who needs to work on this
- Content designer or technical writer

## Who needs to review this
- Accessibility specialist
- Content designer or technical writer

## Done when

- [ ] Guidance has been updated

**Comment by dav-idc** [comment]
This has been added to the ['WCAG 2.2 content updates' document](https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit?usp=sharing).

**Comment by calvin-lau-sig7** [comment]
Closing issue – content has been drafted, reviewed and added to pull request #3090 as part of https://github.com/alphagov/govuk-design-system/issues/3276.
