### ISSUE TITLE
WCAG 2.2: Create accounts ‖ Accessible Authentication

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-design-system#2875]
## What

Update our guidance on creating accounts to emphasise that teams should ideally avoid using [CAPTCHA tools](https://en.wikipedia.org/wiki/CAPTCHA) to restrict the creation of accounts or, if they do, that they must provide an alternative means of creating an account that does not use them.

We may also want to identify specific CAPTCHA tools that we have confirmed to be accessible and compliant with the Level AA criterion.

This guidance may be temporary, pending the creation of specific guidance around proving the user is a real person.

### Resources

- [Create accounts guidance page](https://design-system.service.gov.uk/patterns/create-accounts/)
- [WCAG 2.2 criterion for 'Accessible Authentication (Minimum)'](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum)
- [WCAG 2.2 criterion for 'Accessible Authentication (Enhanced)'](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-enhanced)

## Why

The new WCAG 2.2 Level AAA criterion 'Accessible Authentication (Enhanced)' says: 

> A [cognitive function test](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum#dfn-cognitive-function-test) (such as remembering a password or solving a puzzle) is not required for any step in an authentication [process](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum#dfn-process) unless that step provides at least one of the following: 
> 
> **Alternative**
> Another authentication method that does not rely on a cognitive function test.
> 
> **Mechanism**
> A [mechanism](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum#dfn-mechanism) is available to assist the user in completing the cognitive function test.

CAPTCHA technologies are largely non-compliant with the Level AAA version of the criterion. In this situation, a team would have to provide another mechanism to limit the effectiveness of spam registrations or otherwise validate a user's personhood.

The Level AA criterion 'Accessible Authentication (Minimum)' adds two more exceptions: 

> **Object Recognition**
> The cognitive function test is to recognize objects.
> 
> **Personal Content**
> The cognitive function test is to identify [non-text content](https://www.w3.org/WAI/WCAG22/Understanding/accessible-authentication-minimum#dfn-non-text-content) the user provided to the Web site.

Only certain CAPTCHA technologies comply with the Level AA criterion. The behavioural and object recognition CAPTCHA that is employed by services like [reCAPTCHA](https://developers.google.com/recaptcha/) and [hCAPTCHA](https://www.hcaptcha.com/) would appear to be compliant, the specifics of their technical implementation notwithstanding. 

CAPTCHAs that employ spacial puzzles, such as [AWS WAF](https://docs.aws.amazon.com/waf/latest/developerguide/waf-captcha-puzzle.html) or [Arkose MatchKey](https://www.arkoselabs.com/arkose-matchkey/) are probably not compliant. 

Traditional CAPTCHAs that require a user to manually transcribe distorted text or audio are not compliant. 

## Who needs to work on this
- Content designer or technical writer
- Accessibility specialist (if auditing CAPTCHAs to recommend)

## Who needs to review this
- Accessibility specialist
- Content designer or technical writer
- Developer (if example added)

## Done when

- [ ] Decision has been made on whether to recommend specific CAPTCHAs
- [ ] An comparative audit of various CAPTCHA tools has been carried out
- [ ] Guidance has been updated

**Comment by dav-idc** [comment]
This has been added to the ['WCAG 2.2 content updates' document](https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit?usp=sharing).

**Comment by calvin-lau-sig7** [comment]
Closing issue – content has been drafted, reviewed and added to pull request #3090 as part of https://github.com/alphagov/govuk-design-system/issues/3276.
