### ISSUE TITLE
WCAG 2.2: Create accounts ‖ Redundant Entry 

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-design-system#2878]
## What

Update our guidance on creating accounts to emphasise that developers should use [the `autocomplete` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) to allow password managers and user agents to automatically populate fields.

As we are suggesting the use of particular HTML attributes, we may also want to provide a code example on the guidance page.

This is a suggested usability enhancement and is not strictly needed for WCAG 2.2 compliance. 

### Resources

- [Create accounts guidance page](https://design-system.service.gov.uk/patterns/create-accounts/)
- [WCAG 2.2 criterion for 'Redundant Entry'](https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry.html)

## Why

Although the 'Redundant Entry' criterion makes exceptions for instances of users providing new information, some password managers have the ability to fill out forms—such as registration forms—using information the user has previously provided.

1Password, LastPass and Bitwarden all allow users to proactively create 'identities' that include features such as name, username, date of birth, gender identity, postal address, job title, organisation, and contact information. A user has the option of selecting an identity from their password manager and having all compatible fields on the form automatically filled out. 

By encouraging use of the `autocomplete` attribute, even in situations where a user may be providing information for the first time, we can help the password managers to autofill the forms correctly.

## Who needs to work on this
- Content designer or technical writer
- Developer (if example added)

## Who needs to review this
- Accessibility specialist
- Content designer or technical writer
- Developer (if example added)

## Done when

- [ ] Decision has been made on whether to include a code example
- [ ] Code example has been produced, if required
- [ ] Guidance has been updated

**Comment by dav-idc** [comment]
This has been added as an amendment on the existing drafted guidance in the 'WCAG 2.2 content updates' doc:
https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit#heading=h.hz7v81tfwgdi
