### ISSUE TITLE
Hold an Exit this Page team retro 

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2952]
## What
Run a team retro to reflect on designing, building and publishing Exit this Page.

## Why
So we can identify key learnings which will improve future components and patterns we build.

## Who needs to work on this
Izabela

## Who needs to review this
Kelly

## Done when
- [x] Scheduled date (Sep 2023)
- [x] Asked team to note reflections whilst still fresh
- [x] Planned format
- [x] Run retro and agreed actions

**Comment by dav-idc** [comment]
This retro was run with the available team members on 13 September 2023. For anyone on the team looking for access to the retrospective Padlet board, feel free to ask Izabela.
