### ISSUE TITLE
Collate early feedback from users regarding Exit this Page

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#2954]
## What
Look at:
- Slack comments
- social media
- GitHub discussions
- survey responses

## Why
So we have some feedback to know where to focus our iteration outreach.

## Who needs to work on this
Kelly

## Who needs to review this
Steve

## Done when
- [x] recorded feedback from various sources
- [x] shared with team

**Comment by stevenjmesser** [comment]
Here's [feedback collected from Twitter](https://stevenjmesser.notion.site/Twitter-feedback-on-Exit-this-Page-804c6e1f32e3459c9e63da220235a421).
