### ISSUE TITLE
Button prevent-double-click does not seem to be working in Edge

### ISSUE THREAD

**Issue by AnthonyEdmonds** [alphagov/govuk-design-system#2963]
## Description of the issue

The `data-prevent-double-click` attribute does not seem to be working with Edge.

I have been receiving reports of form double-submissions, but only from a limited subset of users.

Upon investigation, double-click prevention on buttons is working in Firefox and Chrome, but not in Edge.

I am looking to see what I can do from my end, and I'll see whether I can pinpoint the issue with the JavaScript in Edge.

## Steps to reproduce the issue

1. Rapidly and repeatedly press the submit button with the `data-prevent-double-click` attribute, as per [the docs](https://design-system.service.gov.uk/components/button/#stop-users-from-accidentally-sending-information-more-than-once), as part of a form viewed in Edge.

2. Check the backend for duplicated submissions.

## Actual vs expected behaviour

Expected: The form only submits once

Actual: The form submits as many times as the user can click before the next page loads

## Environment (where applicable)

- Operating system: Windows 10
- Browser: Edge
- Browser version: 114.0.1823.82

**Comment by AnthonyEdmonds** [comment]
Seems that Edge is propogating the event to the form, so while the button isn't doing anything the form is.

```js
let clicks = 0;

B.prototype.debounce = function (t) {
    clicks++;
    console.log("Received click", clicks);
    
  if (this.config.preventDoubleClick) {
      console.log("Double click prevention is on");

        if (this.debounceFormSubmitTimer) {
            console.log("Prevented extra click", t);
            t.stopPropagation();
            return t.preventDefault(), !1;
        }
        
        this.debounceFormSubmitTimer = setTimeout(
            function () {
                this.debounceFormSubmitTimer = null;
            }.bind(this),
            Z * 1e3
        );

        console.log("Debounce activated");
  }
};
```

**Comment by AnthonyEdmonds** [comment]
Have tested adding `t.stopPropagation();` in Edge, Firefox, and Chrome, and all is now working as expected. Will raise a PR with this fix for review.

**Comment by AnthonyEdmonds** [comment]
Looks like the code for this is over in the govuk-frontend repo, so I will raise it over there.

https://github.com/alphagov/govuk-frontend/pull/3992

**Comment by 36degrees** [comment]
@AnthonyEdmonds we can transfer this issue there and reopen it, if you prefer?
