### ISSUE TITLE
Define next steps following WCAG 2.2 Guidance Design Sprint

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#2971]
## What

All the activities to finish the WCAG 2.2 Guidance Design Sprint 17 July 2023 and document what we acheived. This relates to the epic [WCAG 2.2 AA updates to guidance to comply, and help teams to comply, with new criteria #2729](https://github.com/alphagov/govuk-design-system/issues/2729).

## Why

We want to determine what type of guidance we need and how it will look in the Design System for when WCAG 2.2 is published later this year.

## Who needs to work on this

Interaction Designer, Content Designer 

## Who needs to review this

The Design Sprint participant team (Accessibility specialist, Content Designer, Designer, Developer, Technical writer, User researcher)

## Useful links

[Design Sprint for WCAG 2.2 Content Updates](https://docs.google.com/document/d/1nSp_EZW3BBZyASXgg05sla8N-WQa-GD3Hmdyf0tE0qM/edit#
)

## Done when for Sprint w/c 25 July 2023

- [x] Slides for show and tell 25/07/2023
- [x] Document all items that were moved to the carpark and a decision log why they weren't taken forward in this time frame
- [x] Prepare ‘sign up if you’re interested’ form/thing (pre-filled email link)  ([see planning doc](https://docs.google.com/document/d/1rzgApgrHzb5n6Os5Mq7M7WXyaAtqxcCCmAxvevqbeSs/edit?usp=sharing))
- [x] Find channels for sending expression of interest
- [x] Get feedback from team about how the 3 day sprint went/ pull in thoughts on hybrid/inperson/online
- [x] Check all confidentiality and consent information around expression of interest and notes from interviews etc.
- [x] Determine what results from engagement with users will look like and what they will inform
- [x] Review [discussion guides](https://docs.google.com/document/d/1pQRDRIBqH3MaZhTVW7LDoq6zLPbCcxIg0AHYIu2KQzA/edit?usp=sharing) for half user research/half usability testing

**Comment by kellylee-gds** [comment]
Closed and opened new card for the research #3073
