### ISSUE TITLE
Recruit more organisers for DSDay 23

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#2983]
## What
Recruit more organisers

## Why
We have more work than the small organising committee can manage

## Who needs to work on this
Epic Lead
DSDay organising team

## Who needs to review this
Steve, Kelly?

## Done when

- [x] Call for organisers put out
- [x] Roles filled

**Comment by Ciandelle** [comment]
Recruited another 2 people for design system day roles
