### ISSUE TITLE
Run an AMA session to recruit DSDay organisers

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#2984]
## What
Run an Ask Me Anything session to recruit DSDay organisers from GDS

## Why
We need more organisers

## Who needs to work on this
Epic Lead

## Who needs to review this
-

## Done when

- [x] Session scheduled
- [x] Organisers recruited
- [x] Session promoted
- [x] Session planned
- [x] Session run successfully

**Comment by Ciandelle** [comment]
Imran ran this week commencing 31/07/2023
