### ISSUE TITLE
Create DSDay planning documentation

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#2985]
## What
Create DSDay update documents and share with planning team

## Why
To enable asynchronous updates

## Who needs to work on this
Epic Lead

## Who needs to review this
-

## Done when

- [x] Documentation created
- [x] Documentation shared
- [x] People actually start using it

**Comment by Ciandelle** [comment]
Documentation can be found in the Design System Day 23 folder and all team members have been informed about it.
