### ISSUE TITLE
Code blocks need bottom margin

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#299]
If you create a code block in markdown in the guidance for a component or pattern, it's missing a bottom margin, like this:

![image](https://user-images.githubusercontent.com/1590604/40929320-4835fb2c-681c-11e8-97f5-eafe853cfd09.png)

**Comment by igloosi** [comment]
you solved that by wrapping it in a paragraph right?

**Comment by timpaul** [comment]
I did indeed 'solve' it :-)

It actually looks better too.

**Comment by igloosi** [comment]
good, close this?

**Comment by 36degrees** [comment]
There are two ways to do code blocks in Markdown - [using a single backtick (\`) creates `inline` code snippets](https://daringfireball.net/projects/markdown/syntax#code) - e.g. if you're mentioning a method name.

Using [three backticks (\```) will create an actual code block](https://daringfireball.net/projects/markdown/syntax#precode) which is what you should use in the example above.

It's the difference between `this` and:

```
this
```

There should be no need to wrap any code blocks in paragraphs.

**Comment by 36degrees** [comment]
Sorry Tim, I closed this prematurely – it looks like you were using the triple backticks and switched to single backticks _because_ it didn't have a bottom margin?

My bad! I'll re-open this.
