### ISSUE TITLE
Organise the third WCAG 2.2 inspection workshop (Accessible authentication)

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3003]
## What
Plan the third WCAG 2.2 workshop with the community focused on Accessible authentication criterion.
 
## Why
Some criterion in WCAG 2.2 can be complicated to test for and teams will need to do more than update to the latest version of Frontend to ensure they meet it. 

We want to build a consistent approach to meet WCAG 2.2 so we’re giving the community early opportunity to feed into our work.

## Who needs to work on this
Lead facilitator: David
Co-facilitator: Steve
Chat moderator: Kelly
Admin: Kelly

## Who needs to review this
N/A

## Done when
**Planning**
## Done when
**Planning**
- [x] Selected a date **Thursday 26 October 11:00am**
- [x] Decided on roles **David presentation, Imran facilitator, Kelly chat moderator, Imran TicketTailor & Comms**
- [x] Agreed ticket release strategy **TailorTicket**
- [x] Drafted promotional comms
- [x] Agreed on actions if / when tickets sell out
- [x] Created an Eventbrite page
- [x] Emailed the community

**Comment by kellylee-gds** [comment]
Decided to host this in September when we have the answers to a few outstanding questions regarding this criterion.

**Comment by dav-idc** [comment]
With the workshop happening tomorrow, all these tasks are done!

Files and slides can be found in this [Accessible Authentication workshop Google Drive folder (restricted access)](https://drive.google.com/drive/folders/1ZjkFUFKDr_npZN6Flo8JaoWkVMiXMavI?usp=share_link).

Work will now begin on the next issue:
- https://github.com/alphagov/govuk-design-system/issues/3066
