### ISSUE TITLE
Investigate options for DSDay ticketing

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#3019]
## What
Investigate options for ticketing now that Eventbrite charges

## Why
Eventbrite charges for free events now. Also it didn't fulfil all our needs anyway.

## Who needs to work on this
Imran, Antoni

## Who needs to review this
PM & DM

## Done when
- [x] Alternative platforms investigated
- [x] Proposal pitched to DSDay team - [Google doc](https://docs.google.com/document/d/1DpafOy2-ZQc24uSIIsYpf0l_uhfsCaoRgO12D8KDQdU/edit?usp=sharing)
- [ ] Test events created to demonstrate attendee experience
- [ ] Dependency: Needs to be compatible on agreed payment mechanism https://github.com/alphagov/govuk-design-system/issues/3016
- [ ] New ticketing platform selected

### Options
- [Ticket Tailor](https://www.tickettailor.com/)
- [Humanitix](https://humanitix.com/au/accessible-events)

[Investigation doc](https://docs.google.com/document/d/1DpafOy2-ZQc24uSIIsYpf0l_uhfsCaoRgO12D8KDQdU/edit?usp=sharing)

**Comment by davidc-gds** [comment]
Offering Humanitix as a option, if they're available in the UK.

It's an Australian events ticketing company that seems to have a strong focus on accessibility: https://humanitix.com/au/accessible-events

**Comment by calvin-lau-sig7** [comment]
One idea we could (re)visit is using Hopin for ticket registration, and billing with its [Hopin's paid ticketing feature](https://support.hopin.com/hc/en-us/articles/360058568011-Stripe-Direct-Billing).

It's worth considering as the previous issue with ticket rushes would probably be smoothed out if there's a payment involved. Probably enough that we can probably manage through support.

It'd require working with a Stripe account, which feature-wise is pretty well-regarded.

Con however, is that the ticketing fee is quite steep for the 'starter' plan, nearly 10% total. The fees are also non-refundable so we need to be clear we'd only be able to issue partial refunds minus the fees.

**Comment by calvin-lau-sig7** [comment]
I've filled out the current batch of options and added requirements I'm aware of.

Thanks @davidc-gds, Humanitix looks promising — it has the "pending tickets" functionality which only Eventbrite seemed to have (to manage high demand for tickets and equal opportunity for people to get tickets)! I can see UK paid events so presumably it's possible for us to use!

**Comment by calvin-lau-sig7** [comment]
Added an extra step proposed by Antoni to create test events in our top 2 choices — Ticket Tailor and Humanitix — for DSDay team to better see what the attendee experience looks like.
