### ISSUE TITLE
Publish video of the third WCAG 2.2 inspection workshop (Accessible authentication)

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3067]
## What
Publish subtitled video the third WCAG 2.2 workshop with the community focused on Accessible authentication criterion.
 
## Why
Some criterion in WCAG 2.2 can be complicated to test for and teams will need to do more than update to the latest version of Frontend to ensure they meet it. 

We want to build a consistent approach to meet WCAG 2.2 so we’re giving the community early opportunity to feed into our work.

## Who needs to work on this
TBC

## Who needs to review this
GDS YouTube owner

## Done when
**Post-workshop**
- [x] Moved notes into suitable format for sharing
- [x] Recruited 6 volunteers to edit transcript
- [x] [Edited transcript](https://docs.google.com/document/d/1jd6YkYqP1kPYmqBghnK8kNRKPpH2ONGMQPziOsM24QQ/edit#heading=h.k013ezqhxyyz)
- [x] Shared edited transcript and recording with GDS Comms to add captions and upload
- [x] Comms drafted in Mailchimp
- [x] Recording sent to mailing list
- [ ] Added video to [Blogs, posts, videos and podcasts website page](https://design-system.service.gov.uk/community/blogs-talks-podcasts/) https://github.com/alphagov/govuk-design-system/pull/3394

**Comment by dav-idc** [comment]
Here are the files for this work:
- [Main folder with video files](https://drive.google.com/drive/folders/13tqpb4UQMmJvhgjsDv3BolIqqpKm0w0c?usp=drive_link)
- [Video description (to put under the YouTube video)](https://docs.google.com/document/d/19o3f2VqtY4wEBsG_3ciOoAEsndeZxc5ETsYFeu8PZRo/edit?usp=drive_link)
- [Unedited video](https://drive.google.com/file/d/1RAeDGPs4bVUA3AtSzHDNH4CwyOLztnSf/view?usp=drive_link)
- [Video thumbnail](https://drive.google.com/file/d/1UDp0f58rrxRfx-AezPLNkyt9X1ctG6w6/view?usp=drive_link)

**Comment by dav-idc** [comment]
Here's an edited version of the video, with all the workshop stuff removed (and removing the time my internet crashed)
- [Edited video](https://drive.google.com/file/d/1spYclgLelW85umi0Owca1yp-DzxYh5D4/view?usp=drive_link)
- [VTT file for the edited video](https://drive.google.com/file/d/1gdWcRxwtd9mJ-PFugF71Ie9u-myRtLTu/view?usp=drive_link) (from YouTube auto-transcription)

The captions / transcript still need to be cleaned up, but everything else needed is now in that Google Drive folder!
[Main folder with video files](https://drive.google.com/drive/folders/13tqpb4UQMmJvhgjsDv3BolIqqpKm0w0c?usp=drive_link)

**Comment by kellylee-gds** [comment]
[Shared editing doc here.](https://docs.google.com/document/d/1jd6YkYqP1kPYmqBghnK8kNRKPpH2ONGMQPziOsM24QQ/edit)

**Comment by kellylee-gds** [comment]
Currently blocked whilst Nikitas uploads video and captions to YouTube

**Comment by kellylee-gds** [comment]
Sent chasing email
