### ISSUE TITLE
Organise and publicise the WCAG 2.2 Detective Skills workshop

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3068]
## What
To coincide with the release of WCAG 2.2 on Thu 24 August, we want to release tickets for a workshop with the community.

## Why
The Detective Skills workshop helps users inspect elements to understand if they are impacted by WCAG 2.2.

## Who needs to work on this
David, Kelly

## Who needs to review this
GDS Social Media lead

## Done when
- [x] Selected a date for the workshop
- [x] Designed new cover photo
- [ ] Reviewed retro feedback from previous workshops and made changes
- [x] Checked Eventbrite can still be used
- [ ] Draft social media posts to publicise workshop and release of WCAG 2.2
- [x] Understood how to send an email via MailChimp
- [ ] Drafted comms
- [ ] Released tickets

**Comment by dav-idc** [comment]
This will, at most, be a blog post. Cancelled due to a shift in strategy.
