### ISSUE TITLE
Run a round of research to understand what users need to know about WCAG 2.2

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3073]
## What
Following the design sprint, research with users to understand what they need to know about WCAG 2.2.

## Why
So we can provide that help.

## Who needs to work on this
Charlotte, Kelly, David (facilitators)

## Who needs to review this
Calvin, Ciandelle, Chris, Imran (notetakers)

## Done when
- [x] Prepare prototypes for testing 
- [x] Determine user journey of prototypes for research
- [x] Determine which channels we can recruit users through
- [x] Recruit volunteers for user research with prototypes
- [x] Let down additional volunteers
- [x] Find facilitators of the research sessions within the team
- [x] Find notetakers of the research sessions within the team
- [x] Test with users
- [x] Decide whether we want to use other more informal channels to collect feedback

## Stretch goals
- [x] (Stretch) Walkthrough discussion guide with user researcher (at end-sprint)

**Comment by kellylee-gds** [comment]
@CharlotteDowns is this card done, or do things need moving into a new card?

**Comment by CharlotteDowns** [comment]
@kellylee-gds yep this is done
