### ISSUE TITLE
Gather examples and contributions for passwords

### ISSUE THREAD

**Issue by stevenjmesser** [alphagov/govuk-design-system#3092]
## What

Gather examples, insights and contributions for passwords in a document. 

## Why

So that we

- can find out what we already know from existing research and analytics
- have a good range of design examples to work from
- can work out what questions we still have (e.g. about use cases, usability, accessibility, technical constraints)
- can keep those in one place and collaborate as a team

## Who needs to work on this
Developer, Designer, 

## Who needs to review this
Product Manager, Delivery Manager, Content Designer, Accessibility Specialist

## Done when

- [x] [document](https://docs.google.com/document/d/1yzlBTH-CCpCQQHiU-RU6TM9lJ4RXVz-9fZTnpwuIDVs/edit) has full details of all contributions that we are aware of relating to passwords

**Comment by davidc-gds** [comment]
@Ciandelle and @querkmachine heres the issue for compiling all the show/hide password prototypes and research!

I believe Ciandelle has a draft doc. Could that be added to this issue's description? Woot woot!
