### ISSUE TITLE
Analyse findings from Design Sprint research

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3096]
## What
Analysis of the design sprint research to understand what we need to do to help our users update to WCAG 2.2.

### Goal for the Project:
To support existing users in understanding WCAG 2.2 and ensuring their services meet the WCAG guidelines.

## Why
So that teams using the design system can be compliant.

## Who needs to work on this
Charlotte, Volunteers

## Who needs to review this
The whole team

## Done when
- [x] highlight research notes that help us solve the goal of project
- [x] add highlighted items to padlet under specific themes

**Comment by CharlotteDowns** [comment]
Here is the [Padlet board for grouping themes from the research](https://www.alltrails.com/en-gb/trail/wales/powys/brecon-to-pencelli-canal#:~:text=Experience%20this%2017.9%2Dkm%20out,h%2015%20min%20to%20complete.)

**Comment by stevenjmesser** [comment]
That's a link to AllTrails, @CharlotteDowns 😉 Looks like a good route though!
