### ISSUE TITLE
Error messages: add new guidance on matching error message text to input label

### ISSUE THREAD

**Issue by dav-idc** [alphagov/govuk-design-system#3097]
## What
Add new guidance on matching error message text to input label.

It'll go in the [error message component guidance](https://design-system.service.gov.uk/components/error-message/), just above the 'Be clear and concise' heading.

Other details:
- it'll have its own heading
- it'll replace the 3rd paragraph in the ['be consistent' section](https://design-system.service.gov.uk/components/error-message/#be-consistent)

## Why
In a recent DAC audit they noted a usability issue with our error summary link text not matching the labels for inputs.

Here's the preview page that DAC tested:
- https://govuk-frontend-pr-3503.herokuapp.com/full-page-examples/what-is-your-address

And here's the GitHub issue that was created based on the DAC audit report:
- https://github.com/alphagov/govuk-design-system/issues/2801

While the issue DAC identified had more to do with old content for error messages in our GOV.UK Frontend review app not being updated, it pointed to a bigger gap in our guidance. We decided it would be best to expand our guidance on how exactly to match error messages to input labels.

This issue has a sibling issue that will add examples of error messages to the address pattern:
- [Update to addresses pattern to include more error examples](https://github.com/alphagov/govuk-design-system/pull/3105)

## Who needs to work on this
David

## Who needs to review this
Calvin, Charlotte

## Done when

- [x] Content is drafted in this issue
- [x] PR is made with the changes
- [ ] PR is reviewed by reviewers and team
- [ ] PR is merged

**Comment by CharlotteDowns** [comment]
@dav-idc is there anything I can do to move this along?

**Comment by dav-idc** [comment]
Here's my draft of the content @CharlotteDowns and @calvin-lau-sig7!

I'm going to re-assign this ticket to Charlotte now. 🙇‍♂️ 

**Add this directly above the 'Be clear and concise' section:**
> ### Match up error messages to labels
> Error messages should directly include language from the question or fieldset label. This helps match up the error message with the form field for which it applies.
> Here are some examples of label and error message pairs.
> Example 1:
> - Label: ‘How many hours do you work a week?’
> - Error message: ‘Enter how many hours you work a week’
> Example 2:
> - Label: ‘Address line 1’
> - Error message: ‘Enter address line 1, typically the building and street’
 

**Remove this from the 'Be consistent' section:**
> ~Use the question or form label in the error to provide context. For example, ‘Enter how many hours you work a week’ for ‘How many hours do you work a week?’~
