### ISSUE TITLE
Track WCAG 2.2 task completion and timing estimates

### ISSUE THREAD

**Issue by dav-idc** [alphagov/govuk-design-system#3128]
## What
Create a spreadsheet that helps to show all the stuff we're working on for WCAG 2.2 updates, and rough estimates of how long each of those things will take.

Here's the spreadsheet: [Estimated delivery timescales for WCAG 2.2](https://docs.google.com/spreadsheets/d/1HcpZg_G9T-ub9_-3zYDAstTFHtHfMoEQ-vaAp0USQTE/edit?usp=sharing)

## Why
Leadership is hoping to be able to track our progress. Additionally, we'd like to align our sprint velocity more closely with our roadmap.

The hopeful end result is a better view of:
- what we're working on for WCAG 2.2
- whether we're on-track
- when we might be ready to publish

## Who needs to work on this
David (accessibility), Steve (Product management)

## Who needs to review this
Epic leads for WCAG 2.2 work

## Done when

- [x] 'Tracker' is drafted
- [x] Reviewed by Steve
- [x] Reviewed by WCAG 2.2 epic leads
- [x] Updated by David for Q2 sprint 5
- [x] Updated by David for Q2 sprint 6
- [x] Updated by David for Q3 sprint 1
- [x] Updated by David for Q3 sprint 2
- [x] Handed over to a new person to manage
- [x] Updated by Steve for Q3 sprint 3
- [x] Updated by Steve for Q3 sprint 4
- [ ] Updated by Steve for Q3 sprint 5
- [ ] Updated by Steve for Q3 sprint 6

**Comment by dav-idc** [comment]
Hi @stevenjmesser! I've updated this tracker to be as accurate as I can get it before my departure.

I've also added a new column for 'epic lead' to help you figure out who to nudge on various items. I think it's accurate, but there is a small chance I mixed up some leads for some things.

https://docs.google.com/spreadsheets/d/1HcpZg_G9T-ub9_-3zYDAstTFHtHfMoEQ-vaAp0USQTE/edit?usp=sharing

**Comment by kellylee-gds** [comment]
@stevenjmesser to close this card and create a card about working out what's left to do with WCAG 2.2 guidance updates.

**Comment by kellylee-gds** [comment]
I reckon we can close this @stevenjmesser after Friday's chat?
