### ISSUE TITLE
Extract heading IDs using `getHeadingList()` from Marked

### ISSUE THREAD

**Issue by colinrotherham** [alphagov/govuk-design-system#3171]
## Context

Our Markdown heading ID plugin `marked-gfm-heading-id` has been updated with a new new export `getHeadingList()` which means we could remove [`extractPageHeadings()`](https://github.com/alphagov/govuk-design-system/blob/a8a868badf95530066fb0dc015287a8dc7d8bc15/lib/extract-page-headings/index.js#L11) in future

Raising this issue so we don't lose track of it

## Additional information (if applicable)

* https://github.com/markedjs/marked-gfm-heading-id/pull/413
* https://github.com/alphagov/govuk-design-system/pull/3167#issuecomment-1733615390

**Comment by domoscargin** [comment]
I had a look at this from the perspective of getting rid of the `extractPageHeadings` plugin.

`getHeadingList` is only useful/available within the `marked` call, so there's some scoping issues getting it to work within the `metalsmith-markdown` call in the metalsmith build (and thus avoid the need to loop the files again).

By the time I had it starting to work, I was pretty deep in the weeds with closures and the like, and had generated a lot of extra code, which made it seem like either a bigger piece of work (I didn't get near testing everything).

I then got distracted by cycle work and forgot this task existed, so I'll unassign myself for now. Maybe fresh eyes will spot a simpler way to get it working.

**Comment by patrickpatrickpatrick** [comment]
Closed by #3793.
