### ISSUE TITLE
Draft and publish summary of Day 2 of DSDay23 on website page

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3239]
## What
Share a summary of Day 2 of Design System Day 2023 on the website.

## Why
The day wasn't recorded so we want to share details.

## Who needs to work on this
Kam (chase slide decks)
Kelly (website updates and comms)

## Who needs to review this
Anyone can 2i

## Done when

**Slide decks received from**
- [x] Oliver Binns
- [x] Chris Choy
- [x] Helena Trippe
- [ ] Katherine Beer
- [x] Abigail & Chloe Baldwin
- [ ] Sacha Zarb
- [x] Simone di Fresco
- [x] Laura Smith
- [x] Slyvie Abookire
- [x] Ciandelle Hughes
- [x] Ashley Watson-Nolan
- [x] Louis Chenais
- [x] Debra Churchill
- [x] Valentine Makhouleen
- [ ] Hassan Nawaz
- [x] James Carleton

**Page update**
- [ ] Content drafted
- [ ] Content reviewed

**Comment by Kam-Nijjar** [comment]
Request for slide decks sent to remainder of guest speaker

**Comment by Kam-Nijjar** [comment]
A reminder/chaser email was sent to Sacha, Sylvie, and Hassan

**Comment by Kam-Nijjar** [comment]
Reminder sent to Sacha, Katherine & Hassan for slide decks by COP 20/11/23

**Comment by Kam-Nijjar** [comment]
Steve has suggested we publish what we have so far

**Comment by kellylee-gds** [comment]
Thanks @Kam-Nijjar. I'll pick this up now and publish what we've got

**Comment by kellylee-gds** [comment]
We have decided not to proceed with publishing the slide decks from day 2. Instead we can share on an ad hoc basis when we receive a request.
