### ISSUE TITLE
Draft a blog about DSday23 trauma informed panel discussion

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3242]
## What
Draft a blog about the trauma informed panel discussion hosted by Katrina at Design System Day 2023.

## Why
- to celebrate
- to work in the open
- to inform

## Who needs to work on this
Katrina

## Who needs to review this
UR peeps, Content Designer or Tech Writer, panelists

## Done when
- [x] Agreed scope of blog
- [x] Submitted request for blog post to GDS blog owner
- [x] Drafted blog
- [x] Blog with Tech/content writer,  panellists, UR for review

**Comment by Katrina-Birch** [comment]
I've split this into complete draft and publication
