### ISSUE TITLE
Publicise DSday23 Day 1 recordings

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3243]
## What
When video of Day 1 has been published on YouTube, update the website with details of talks and speakers. Also draft comms to promote the content.

## Why
So the community is aware and can watch the talks if they weren't able to attend.

## Who needs to work on this
Imran

## Who needs to review this
Steve (website content 2i), Nora (comms 2i)

## Done when
- [x] Website update drafted (#3286 #3286)
- [x] Website content reviewed
- [x] Comms drafted and reviewed (in Mailchimp)
- [x] Video consent collected from all day 1 speakers
- [x] Website content published
- [x] Add links to updated website content to Mailchimp comms
- [x] Comms sent on Mailchimp
- [x] Comms sent to ticket holders on Eventbrite

**Comment by kellylee-gds** [comment]
Update [this page](https://design-system.service.gov.uk/community/design-system-day-2023/speaker-information/#day-1-speakers) with videos for each session

**Comment by kellylee-gds** [comment]
Handing this over to @ImranH-GDS whilst I'm on leave.

Videos are ready to be published. All consent forms received. Comms has been drafted.

All that's remaining is updates to the website. They're in the draft PRs attached to this issue.

**Comment by stevenjmesser** [comment]
I've merged the PRs and added a link to the P&S weeknote, but we still need to publicise via the mailing list and other channels.
