### ISSUE TITLE
WCAG 2.2: Cookie banner || Focus not obscured

### ISSUE THREAD

**Issue by dav-idc** [alphagov/govuk-design-system#3256]
## Description of the issue

As part of my [testing and calculations for the WCAG 2.2 'Focus not obscured' criteria (restricted document)](https://docs.google.com/spreadsheets/d/1PpKvhCGZJb1j0ZUUY2ZuA0CBQeu04yFD1bumiL8wGX8/edit?usp=sharing), I tested the GOV.UK Design System [cookie banner](https://design-system.service.gov.uk/components/cookie-banner/).

I found that while our [cookie banner](https://design-system.service.gov.uk/components/cookie-banner/) doesn't use any 'sticky' or fixed positioning, its an element that's at high risk of being made sticky by others. Similar to our assessment of the phase banner being at risk of being made sticky.

## Recommended action
Add guidance on not making cookie banners sticky.

Copy the format from the 'Phase banner' drafted WCAG 2.2 guidance we've been working on, which is in the big [WCAG 2.2 content guidance document (restricted document)](https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit#heading=h.rndfhdctk9w0).

## Initial draft
**`WCAG 2.2`** Do not make the cookie banner ‘sticky’ to the top of the page by using `position: fixed` or any other method. This is to make sure it does not cover or obscure any content which has a focus applied. This is to comply with WCAG 2.2 success criterion [2.4.11 Focus not Obscured (minimum)](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum.html).

### Recommend guidance placement
Add at the bottom of the ‘How it works’ section under the final line: “Position the cookie banner after the opening `<body>` tag and before the ’skip to main content‘ link. If you’re using the Nunjucks page template, use the `bodyStart` block.”]

**Comment by dav-idc** [comment]
This has been added to the ['WCAG 2.2 content updates' document](https://docs.google.com/document/d/1nIxIKgVUheC8zvVdqWIcqtVPCl7oTN4hv11R9rDwdvM/edit?usp=sharing).

**Comment by calvin-lau-sig7** [comment]
Closing issue – content has been drafted, reviewed and added to pull request #3090 as part of https://github.com/alphagov/govuk-design-system/issues/3276.
