### ISSUE TITLE
Use a custom markdown renderer to avoid scoped styling.

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#327]
Following on from the conversation at https://github.com/alphagov/govuk-design-system/pull/324#discussion_r195431793

We currently have scoped styling the default markdown output does not add anything we can hook onto for styling.

If we added a custom renderer we could add the classes we require and avoid the need to use scoping.

To see how this would work see an example of overriding headings to make them anchorable: https://github.com/alphagov/govuk-design-system/compare/markdown-heading-ids-linkable

We would add a lightweight custom renderer for each element that adds a class.

**Comment by igloosi** [comment]
made a similar thing for the Prototype kit that uses highlightjs (liek the DS)
```
var hljs = require('highlight.js')
  var renderer = new marked.Renderer()

  // add highlight classes to code block
  renderer.code = function (code, language) {
    language = language || 'bash'
    return '<pre><code class="hljs ' + language + '">' +
      hljs.highlight(language, code).value +
      '</code></pre>'
  }
  return marked(document, { renderer: renderer })
```

**Comment by nickcolley** [comment]
Going to close this for now.

I did managed to successfully do this: https://govuk-frontend-markdown.glitch.me/
