### ISSUE TITLE
Configure Netlify to use GOV.UK branded 404 pages

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#3281]
## What

In anticipation of moving the Design System to Netlify, configure Netlify to use our [custom error page](https://github.com/alphagov/govuk-design-system/blob/main/src/errors/404.njk) for 404s.

For example, visiting https://govuk-design-system-preview.netlify.app/foo should display the same GOV.UK branded 404 page as seen at https://design-system.service.gov.uk/foo.

Leave the existing nginx config for error pages on PaaS, as it's still needed until we've finished the migration.

## Further reading

- [Existing nginx config for error pages](https://github.com/alphagov/govuk-design-system/blob/146fad78f2e84daa371faa287ab2c38a7a5de00a/deploy/nginx.conf#L140)
- [Netlify's docs on configuring custom 404 pages](https://docs.netlify.com/routing/redirects/redirect-options/#custom-404-page-handling)

## Why

So that anyone encountering a broken link or attempting to access a non-existent page sees a GOV.UK branded page that reassures them they are on the right site, and directs them somewhere useful.

## Who needs to know about this

Developers

## Done when

- [ ] https://govuk-design-system-preview.netlify.app/foo displays a GOV.UK branded 404 page

**Comment by colinrotherham** [comment]
Looking good: https://govuk-design-system-preview.netlify.app/foo
