### ISSUE TITLE
Remove the 'archive' banner from the deployment of the `main` branch

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#3289]
## What

Our Netlify deployments currently always include a banner just below the navigation:

<img width="1147" alt="Screenshot 2023-11-06 at 14 05 46" src="https://github.com/alphagov/govuk-design-system/assets/121939/1095f846-99e8-4dd4-9170-cf29d49ab9d3">

For [deploy previews](https://docs.netlify.com/site-deploys/deploy-previews/), the banner says:

> **PREVIEW** This is a preview of a proposed change to the Design System.

For [branch deploys](https://docs.netlify.com/site-deploys/overview/#branch-deploy-controls), the banner says:

> **ARCHIVE** This is an archived version of the [branch-name] branch for the [Design System](https://design-system.service.gov.uk/).

This also includes our Netlify 'production' deploy (which is different to our actual production deploy to PaaS), which currently says:

> **ARCHIVE** This is an archived version of the [main](https://github.com/alphagov/govuk-design-system/tree/main) branch for the [Design System](https://design-system.service.gov.uk/).

Remove the banner from the **production deploy only**.

## Why

When we migrate the Design System to Netlify, we don't want the banner to appear on our production instance (https://design-system.service.gov.uk/)

## Further detail

The logic for the banner currently checks for the existence of the `PULL_REQUEST` environment variable, which [always exists when deploying to Netlify](https://docs.netlify.com/configure-builds/environment-variables/#git-metadata), but not when to deploying to PaaS (production)

https://github.com/alphagov/govuk-design-system/blob/8543fce13ca7862e3b385eb483dcf23792062199/views/partials/_banner.njk#L1-L15

We'll need to update this to omit the banner when deploying production, potentially using the `CONTEXT` environment variable.

## Who needs to know about this

N/A

## Done when

- [ ] The banner does not display on the Netlify 'production' deploy at https://govuk-design-system-preview.netlify.app/
- [x] The banner continues to display on branch and deploy previews

**Comment by colinrotherham** [comment]
Didn't intend to pick this up but it was the same fix as https://github.com/alphagov/govuk-design-system/pull/3307

* https://github.com/alphagov/govuk-design-system/pull/3308
