### ISSUE TITLE
Deployments of the Design System can result in a broken styled page.

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#333]
When deploying the breaking change migration https://github.com/alphagov/govuk-design-system/pull/325 I noticed on the first visit to the page I received a page where the CSS has not loaded.

I think this is can be explained with:

1. The HTML page is cached on my machine
2. When the deployment succeeded the assets for the cached HTML page are no longer available and are not cached.
3. When I refreshed again I received the new HTML page, which points at assets that exist.

**Comment by igloosi** [comment]
was it not due to an uncompiled css because of #331 ?

**Comment by nickcolley** [comment]
When master failed it did not deploy the website.

When we fixed master, what is described in this issue happened.

I believe this will happen anytime our CSS doesn't match our markup.

**Comment by 36degrees** [comment]
I think this was fixed by #352 – going to close this. Please re-open if you see it happen again.
