### ISSUE TITLE
Run AMA session to attract organisers

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#3330]
## What
Run an Ask Me Anything session for any questions people may have about DSDay

## Why
It has worked well for the design community in the past

## Who needs to work on this
Epic Lead

## Who needs to review this
Organising team

## Done when

- [ ] Session scheduled
- [ ] Organisers recruited
- [ ] Session promoted
- [ ] Session run

**Comment by 36degrees** [comment]
I think this is done, as Design System Day is in the past, but please re-open if I'm wrong about that!
