### ISSUE TITLE
Send out the 2024 Design System UX survey

### ISSUE THREAD

**Issue by Katrina-Birch** [alphagov/govuk-design-system#3331]
## What
Create list of questions for 2024 survey to understand user's experience of using the design system and send it out by 19 Jan.

## Why
To decide whether we want to repeat questions form previous surveys or discover something new.

## Who needs to work on this
User researcher 

## Who needs to review this
Product manager

## Done when
- [x] Ask the team to look through last year's UX survey in order to source new questions
- [x] Scope what we want to achieve
- [x] We have a list of questions
- [x] The survey has been drafted
- [x] The survey has been sent out

**Comment by sstrubberg** [comment]
Greetings from the Carbon Design System! We're big fans of the gov.uk design system over here and as I was cruising through your site and now your Github, I ran across this issue and was super interested in learning more about the kinds of questions you ask as I'm tackling an identical problem with a survey of our own. Happy to jump on a call at your convenience to chat more if that is of interest to you.

**Comment by stevenjmesser** [comment]
Hi @sstrubberg! Great to hear from you. Drop me a line through govuk-design-system-support@digital.cabinet-office.gov.uk and I'll set up a chat.

**Comment by stevenjmesser** [comment]
I've had a look at the draft and it looks pretty good!

**Comment by kellylee-gds** [comment]
Sent out on 19 Jan.
