### ISSUE TITLE
Update the accessibility statement and strategy after our WCAG 2.2 release

### ISSUE THREAD

**Issue by dav-idc** [alphagov/govuk-design-system#3332]
## What
Once the GOV.UK Frontend code and the guidance content for WCAG 2.2 are released, we'll need to update our [accessibility statement](https://design-system.service.gov.uk/accessibility/) and our [accessibility strategy](https://design-system.service.gov.uk/community/accessibility-strategy/).

This will include:
- Changing the standard we aim for from WCAG 2.1 to WCAG 2.2
- Listing any WCAG 2.2 non-compliance pieces in our accessibility statement
- Making sure any links to WCAG W3C documentation go to the 2.2 version

## Why
Once we release our WCAG 2.2 update, we'll want to let people know that our intent is to now meet WCAG 2.2 AA. So we need to include that in our statement and list any ways we might not yet be meeting that standard.

## Who needs to work on this
Accessibility specialist

## Who needs to review this
Developer, interaction designer or content designer (a second set of eyes)

## Done when

- [x] Draft content update for accessibility statement
- [x] Draft content update for accessibility strategy
- [x] Get statement updates reviewed
- [ ] Get strategy updates reviewed
- [x] Make PRs
- [ ] Publish

**Comment by claireashworth** [comment]
Accessibility statement amended in PR '[WCAG 2.2 guidance updates #3090](https://github.com/alphagov/govuk-design-system/pull/3090/commits/573f1367d4222311556628672ae9207ffe24aab6)'
@calvin-lau-sig7 @CharlotteDowns for info/to review

**Comment by claireashworth** [comment]
The accessibility statement amendment is also tracked by #3129, so this might be a duplicate issue.

**Comment by stevenjmesser** [comment]
Accessibility statement is done. Strategy may need looking at.
