### ISSUE TITLE
Draft guidance for password input component

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-design-system#3352]
## What

Draft guidance for a prospective Password Input (aka, show/hide password) component. https://github.com/alphagov/govuk-frontend/issues/4063

Related to:
- #3353

## Why

As a new component, it will have a guidance page on the Design System website. We want to draft what this guidance might look like to help with user testing and inform the direction the component takes.

We already have pattern guidance for [asking users about passwords](https://design-system.service.gov.uk/patterns/passwords/). We likely want to move some of the content from this page onto the component's page.

## Who needs to work on this

- Content designer

## Who needs to review this

- Content designer
- Technical writer
- Developers

## Done when

- [ ] We have a PR that demonstrates a password input guidance page

**Comment by 36degrees** [comment]
We have a draft that has been sent to the working group, so we can close this now.

Iterating the draft and getting it into a publishable state will be part of a future epic.
