### ISSUE TITLE
Hold a Task List show & tell

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3404]
## What
Arrange a show & tell to demo the new Task List component by 19 Jan (hard deadline).

## Why
To celebrate the release and publicise the component.

## Who needs to work on this
Imran, Kam

## Who needs to review this
Frankie (contributor)

## Done when
- [x] Date selected
- [x] Publicised
- [x] Planned with Frankie

**Comment by Kam-Nijjar** [comment]
Launch event booked for Tue 23 Jan 2024 1:00 PM - 2:15 PM GMTAgenda:

Show & tell (30 mins):
More about GOV.UK FrontEnd version 5.0 - (task-list was launched as part of this)
How a co-design collaboration created a new component for the design system
Workshop (45 mins):
Using task lists in your services with Frankie Roberto[
](https://www.tickettailor.com/events/govukdesignsystem/1117624/r/xgsl#)

**Comment by Kam-Nijjar** [comment]
[[[]](https://www.tickettailor.com/events/govukdesignsystem/1117624/r/xgsl)][(https://www.tickettailor.com/events/govukdesignsystem/1117624/r/xgsl)](url)
