### ISSUE TITLE
Check other government department libraries and design systems for navigation component/patterns

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-design-system#3474]
## What

Review [design systems from other departments across government](https://x-govuk.github.io/#design-systems%2C-patterns-and-components) for components and patterns related to navigation, and add them to our research collection.

## Why

This'll give us a view of what other departments may already have done on the topic of navigation to inform our work.

## Done when

- [x] [Digital Land Design System](https://digital-land.github.io/design-system/)
- [x] [Digital Scotland Design System](https://designsystem.gov.scot/)
- [x] [DWP Design System](https://design-system.dwp.gov.uk/index)
- [x] [GOV.WALES components](https://gov.wales/govwales-components)
- [x] [HM Land Registry Design System](https://hmlr-design-system.herokuapp.com/)
- [x] [HMRC Design Patterns](https://design.tax.service.gov.uk/hmrc-design-patterns/)
- [x] [Home Office Design System](https://design.homeoffice.gov.uk/)
- [x] [Ministry of Justice Pattern Library](https://design-patterns.service.justice.gov.uk/)
- [x] [MOD.UK Design System](https://design-system.service.mod.gov.uk/)
- [x] [NHS Design System](https://service-manual.nhs.uk/design-system)
- [x] [NICE Design System](https://design-system.nice.org.uk/)
- [x] [Office for National Statistics Design System](https://ons-design-system.netlify.app/)
- [x] [Transport for West Midlands Design System](https://designsystem.tfwm.org.uk/)
- [x] [Hackney Design System](https://design-system.hackney.gov.uk/)
- [x] [Croydon design and content guidelines](https://www.croydon.gov.uk/design-and-content-guidelines)

**Comment by romaricpascal** [comment]
Added a look at [GOV.UK Prototype Component](https://x-govuk.github.io/govuk-prototype-components/) and [GOV.UK Publishing Components](https://components.publishing.service.gov.uk/component-guide/)

**Comment by CharlotteDowns** [comment]
All investigation have been [added to document](https://docs.google.com/document/d/1WMMgbnxriRekaDPfrudXDOyyCMgFBky6ymbK_vsNn7c/edit?pli=1)
