### ISSUE TITLE
Desk research of how accessibility intersects with navigation

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-design-system#3476]
## What

Research which impact accessibility has in the realm of navigation: this could mean in ways of interacting with the navigation components (keyboard, screen-readers) or accessing the navigation (landmarks, screen-reader shortcuts...).

## Why

The sooner we identify accessibility impacts, the better we can plan to create an accessible experience.

**Comment by romaricpascal** [comment]
Maybe some things to dig into around duplicating content for navigation visibility at different viewport widths (eg. navigation inside collapsible menu on narrow viewports, but visible in a different element on desktop).

**Comment by CharlotteDowns** [comment]
Speak to accessibility specialist when we are clearer on the scope.
