### ISSUE TITLE
Desk research of the technical things to enable navigation

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-design-system#3478]
## What

Collect technical concepts related to navigation, like [the `navigation` role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Navigation_Role) or [`aria-current`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current).

## Why

Having an overview of what browsers can offer can help inform future designs.

**Comment by romaricpascal** [comment]
Progressive enhancement will definitely be on that list as well. Investigating other design systems, there's a good few ways to make a sidebar navigation available on mobile (collapse in a menu, have another page...), so that'll probably be worth a look.

**Comment by CharlotteDowns** [comment]
[Moving to next cycle](https://github.com/alphagov/govuk-design-system/issues/3567)

**Comment by domoscargin** [comment]
I've added some notes to the doc.
