### ISSUE TITLE
Spike to create a common input component (stretch goal)

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3480]
## What

Spike creating an internal 'input' Nunjucks macro that can be imported and used by other components, and update those components to use it.

Timeboxed to a week, but ideally should only be a couple of days of effort.

## Why

During the initial development of the Password input component it was initially decided not to extend the existing Text input component.

This was because it did not provide as much flexibility as the Password input might need—as the Text input component comes with various elements, such as labels, hints and error messages, built in—whilst simultaneously introducing functionality that could conflict with or compromise the Password input—e.g. prefix/suffix HTML, using `pattern` to restrict password formats.

It also introduced a future maintenance burden, as changes to the Text input may have inadvertent effects on the Password input. 

Whilst these issues could be partially addressed by further extending the Text input component's parameters, a proposed solution to this was to have the `<input>` element of Text input separated into its own internal macro. Text input, Password input, and other components could then inherit it without the additional elements. 

## Who needs to work on this

- Developers

## Who needs to review this

- Developers

## Done when

- [x] An internal input macro has been created
- [x] At least one other component has been updated to use the new macro
- [x] (Stretch goal) The internal macro could also generate textareas, as these share many common attributes with text inputs

**Comment by querkmachine** [comment]
This was spiked in #4702 but was not progressed, as it was superseded by the decision to inherit the Input component in #3479.
