### ISSUE TITLE
Make changes based on working group suggestions

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3485]
Design System working group is currently reviewing the Password input component.

[Working group review speadsheet](https://docs.google.com/spreadsheets/d/13GSCOUFUqiGhL9Insq3s229Z47_49RAauGEtBWmma-g/edit?usp=sharing)

## What

Gather comments and suggestions from the working group, and incorporate them into the Password input component and pattern before publish.

## Why

Ensure we take on suggestions to improve our published component.

## Who needs to work on this

Content designer, designer, developers

## Who needs to review this

Wider team?

## Done when
- [x] Gather comments from working group
- [x] Organise meeting with working group to agree and consolidate varying views or suggestions, if possible
- [x] Decide on improvements to make based on suggestions

### Make needed changes to code ( now #3552)
- [ ] Investigate how the component interacts with similar functionality in browsers, password managers and similar tools
- [ ] Make any needed mitigations into code
- [ ] Add summary of our work and open questions to 'Research on this component' section of the [guidance](https://docs.google.com/document/d/1J1BphCxT5Rw3xXGbevTmfWSN216Xb0kXTNJUBQAdeiw/edit?usp=sharing).

### Make needed changes to guidance content (now #3535)
- [ ] Consider adding guidance or rationale about using with ‘confirm password’ fields as #3535, using issue to capture our rationale and work
- [x] Add guidance being clear about copyable text (Done in 'Allow users to paste their password' heading)

**Comment by calvin-lau-sig7** [comment]
Working group conversation was on 5 Feb.

Actions that came out of the conversation:
- Investigate how the component interacts with similar functionality in browsers, password managers and similar tools
- Consider adding guidance about using with ‘confirm password’ fields 
- Consider adding guidance being clear about copyable text

**Comment by Izabela-16** [comment]
@calvin-lau-sig7 agreement was to close this ticket and create a separate action tickets. Will require beeps & Ciandelle input to add more context once on the board.
