### ISSUE TITLE
Enable Tudor crown after 19th February

### ISSUE THREAD

**Issue by querkmachine** [alphagov/govuk-design-system#3529]
## What

Enable the Tudor Crown in the website header (and any examples where it isn't already) on or after the 19th February.

## Why

GDS properties are expected to update to using the new crown before 1st March.

## Who needs to work on this

- Developer

## Who needs to review this

- Developer
- Designer

## Done when

- [x] The crown in the header has been updated 
- [x] Favicons, sharing icons and OpenGraph images have been updated
- [x] Any code examples that feature the header or crown have been updated

**Comment by 36degrees** [comment]
Looks like this has been done.
