### ISSUE TITLE
Investigate usefulness of ‘confirm password’ fields

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3535]
Working group review #3485 of the Password input component advised that we add guidance around using 'Confirm password' fields.

## What

We'd like to gather evidence to:
- see if 'confirm password' fields are needed with a show/hide password button
- outline a recommended approach
- add any needed guidance
- build a body of evidence for future support queries.

## Why

Follow working group recommendation, build confidence in our approach and anticipate queries from services.

## Who needs to work on this

Interaction designer, content designer

## Who needs to review this

Developer, delivery manager

## Done when

- [x] Gather existing evidence from our backlog
- [x] Gather existing implementations from services and other design systems
- [x] Ask and discuss with contributor (Andy Sellick)
- [x] Decide on recommend approach

**Comment by Ciandelle** [comment]
@calvin-lau-sig7 I've written up some [documentation](https://docs.google.com/document/d/1HgHLFNtZGOpv7N67bxsaOAjwFN5pFL1h5O4jS6opq9A/edit) for this issue

**Comment by Izabela-16** [comment]
@Ciandelle agreed to share document with Andy Sellick by end today. It looks that Calvin already had a look at it and is happy with the content.

**Comment by querkmachine** [comment]
Going to close this off as we've seemingly decided on our approach. Last step is to integrate it with the guidance, which I think is covered by #3484.
