### ISSUE TITLE
Communicate with password input contributors

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3536]
## What

Now that we've picked up work in 'Password input', we should get back in touch with Andy Sellick, who originally [developed this contribution with GOV.UK Accounts](https://technology.blog.gov.uk/2021/04/19/simple-things-are-complicated-making-a-show-password-option/).

[See background notes](https://docs.google.com/document/d/1cLCAinAYfvzCtlzv--MQEOqcnuuTmAhw3fTDydrB4dw/edit?usp=sharing) 

## Why

We need to keep contributors informed, and they could also help us with some of our questions.

## Who needs to work on this

Epic lead, all team

## Who needs to review this

All team

## Done when

- [x] Say hello
- [x] Decide on best channel and method to keep in touch

**Comment by Izabela-16** [comment]
Decide on best channel and method to keep in touch - meeting scheduled on the 12th Feb at 11am.

**Comment by Izabela-16** [comment]
Channel - slack is the preferred option to communicate with our contributors 

Method -  pending if it will be ready for the 5.2 release. It is planned for the 22/23rd Feb. 

We need to understand what steps need to be taken as part of the release. 

The feeling is not to be rushed. Need to make sure that code/content are in the good place 

If that is ready:
- reach out for the heads up with the contributors 
- senior interaction designer at DI group would be happy to look at it - high impact
- Andy Selik - original contributor (low interest but would be good to keep him in touch) 
- put together a plan/summary - kanban board to share as an idea
- Calvin to start the document (plan/summary) and then Beeps/Colin to contribute where we are with the code
- decision was to mention that this might be part of the 5.2 release but not guaranteed 
- we could do show & tell if needed to explain a bit more
