### ISSUE TITLE
Split and plan things we want to know from users / community (Charlotte)

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3540]
## What
Plan a 90min workshop with the community with the following aims:

- Build a consensus on what a Navigation component/pattern is?

## Done when
- [x] Items we want to know from users are agreed and split into a survey and an open session with users
- [ ] Prepare the survey 
- [ ] Choose channels to share the survey and prepare the message we send with it
- [ ] Send the survey
- [ ] Prepare a ['lesson plan' using a template](https://docs.google.com/document/d/1b-kvhec9Z9EXuREoTMi_C3e4fxDnqiYIVU5vHh6K4Zw/edit?pli=1) for the open session

**Comment by CharlotteDowns** [comment]
We have the following things we want to know from users which we hope to split between a survey we share on slack and an open session which we ask users to attend.

## What we want to know
- how our users are currently solving navigating the end-user around their services 
  - how many navigation points do they have in their navigation (how was it categorised?)
  - does their navigation link to internal or external links or a mixture of the two?
  - how many levels of navigation do they have?
  - what else do they have on the screen before the main content
  - has there been any challenges, responsiveness, accessibility? 
- what user research have they done to support their navigation approach
- whether they feel the solution they have is fulfilling the service and its end users needs

## Why we want to know it?
- to find out what navigation looks like across different services
- whether the navigation component is backed up and/or validated with user research
- whether it is replicated from another service or taken from another library
- what the appetite would be for users to have a navigation component

**Comment by mia-allers-gds** [comment]
@CharlotteDowns I've made a working doc for us to refine the plan (easier to make suggestions and track changes) 

https://docs.google.com/document/d/1YJmzPPf3m_iaolMtUx4IcnhF-rA_StjQiwozEmRm3AA/edit

**Comment by CharlotteDowns** [comment]
We've parked this as we feel contacting users and the community is better placed for the next stage of the contribution process. In this first cycle and stage we were trying to determine what 'Navigation' means to our users, we already have a lot of information available for us to go through on what that is. In [our next cycle we will be narrowing the scope and forming a steering group](https://github.com/alphagov/govuk-design-system/issues/3567,) we will engage with our community as part of that.
