### ISSUE TITLE
Decide what the format of DSDay24 is. Are we doing multiple events?

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#3575]
## What
Decide on how we will split DSDay 2024, as 2023's 2-day event was a bit full-on and fatiguing for the team.

## Why
So that the team can manage the event better, and so that the community can benefit throughout the year.

## Who needs to work on this
Community Designer, Snr Delivery Manager, Snr Product Manager, Assct Delivery Manager

## Who needs to review this
DM & PM

## Done when

- [ ] Scope out Design & election events throughout the year
- [ ] Plan spread of f2f and online events
- [ ] Think about capacity and timings of other work
- [ ] Think about & write justification for the purpose of each event - DSDay after summer to rejuvenise community
- [ ] Create presentation for PM & DM
- [ ] Agree cadence of events with PM & DM

**Comment by Kam-Nijjar** [comment]
Pre-election period (Purdah) info
2024 local elections
A number of councils will have elections on Thursday 2 May 2024.
The latest date that the pre-election period can start for the local elections is Tuesday 26 March 2024.
For the Mayor of London and London Assembly elections the latest date that the pre-election period can start is Tuesday 19 March 2024.
The date may change in the event of days being appointed for public thanksgiving or mourning.

**Comment by Kam-Nijjar** [comment]
Design System monthly chats planned for the last week of the month
Government Design Systems Assembly currently planned as a quarterly event (1st meeting 05/03/24)

**Comment by Kam-Nijjar** [comment]
[Early DSDay 2024 decisions](https://docs.google.com/presentation/d/1X4-MHPg8FEIu6YQQoh-Htn489PZM6mc_nPCgoiWjcLE/edit#slide=id.g2be7dfa8709_0_0
