### ISSUE TITLE
Agree on tentative timeframes for DSDay 2024

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#3576]
## What
Decide when the DSDay24 events are going to happen in the year

## Why
So that we can plan team capacity to plan and host the events

## Who needs to work on this
Community Designer, Assct DM

## Who needs to review this
DM & PM

## Done when

- [ ] Scope out other events in the annual calendar
- [ ] Think about the purpose of our events and when they will fit
- [ ] Think about planning cycles for each event and how much break in between
- [ ] add to presentation for PM & DM
- [ ] agree with PM & DM

**Comment by Kam-Nijjar** [comment]
Pre-election period (Purdah) info
2024 local elections
A number of councils will have elections on Thursday 2 May 2024.

The latest date that the pre-election period can start for the local elections is Tuesday 26 March 2024.

For the Mayor of London and London Assembly elections the latest date that the pre-election period can start is Tuesday 19 March 2024.

The date may change in the event of days being appointed for public thanksgiving or mourning.

**Comment by Kam-Nijjar** [comment]
Design System monthly chats planned for the last week of the month
Government Design Systems Assembly currently planned as a quarterly event (1st meeting 05/03/24)

**Comment by Kam-Nijjar** [comment]
[Decision log for Design System Day 2024](https://docs.google.com/spreadsheets/d/1N4koNsGskJPJYKwszE09NsxJel3NJqyQEjnyeKzpc4A/edit#gid=0)
