### ISSUE TITLE
Create a plan for community workshop 

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3601]
## What

A draft agenda and plan for a 90 min workshop with the community.

## Why

To engage our community and form a steering group to help with our work on a navigation contribution.

## Done when
- [x] 90 mins is broken down into a icebreaker, presentation and two breakout tasks – the agenda is written
- [x] Objectives of what we want to achieve from the session are written
- [x] A space/tool for the community to share notes and screenshots is decided on
- [x] Check that the space/tool can be accessed by our community
- [x] Prepare the tool to help our community members take part
- [x] Share agenda in workshop invite

**Comment by mia-allers-gds** [comment]
[Questions for the community](https://docs.google.com/document/d/1pGtNCFj0x-vdTURW-Zt-LMDNAxIefolCSG31JSO6N6U/edit) document

**Comment by domoscargin** [comment]
Potential off-the-top-of-my-head ideas for workshop activities:

1. Some kind of card sorting exercise. We give folks generic content that might get linked to from various bits of the navigation, and they sort that content into groups and label them.
2. Giving users a big ol' collection of items that might appear in navigation ("GOV.UK logo", "Service logo", "Menu", "Search Bar", "Page title/link", etc) and get them to group and order in terms of importance.
3. "What's missing?": present users with a really basic example of a navigation (how basic?), ask them to jot down what's missing that they need.

**Comment by mia-allers-gds** [comment]
https://github.com/alphagov/govuk-design-system/issues/3602#issuecomment-1971287509

**Comment by CharlotteDowns** [comment]
Space/tool for workshop will be a combination of [this Google Doc](https://docs.google.com/document/d/1Xd6As0d2M6Yw6f0ssolJmKUPd4phxeoUJtP8nN3E1Vc/edit#heading=h.6r5an2fcnuxo) (for the warmer and Exercise 1) and [this Padlet board](https://govukdesignsystem.padlet.org/charlottedowns1/navigation-workshop-exercise-2-ggbs8y3c9z48xdij) (for Exercise 2).

**Comment by CharlotteDowns** [comment]
We should use a version of this [retro board](https://govukdesignsystem.padlet.org/ImHuYorks/design-systems-monthly-chat-february-2024-retro-uvx34g2qm6z7u34w) for consistency with previous events.
