### ISSUE TITLE
Draft questions for the community to answer in breakout 1 around navigation

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3602]
## What

As part of our agenda we want to run an exercise for community members to enter a breakout room and discuss what our structuring of level 1 and 2 navigation means to them and whether they understand it. 

## Why

We want to know what constraints/pain points of level 1 and level 2 navigation our community have. 

Questions we have:

- What is our community's approach to navigation and how that informed their design? 
- How do we work to fit in with their workflow?
- What would our community put in level 1 and level 2 of navigation? 
- How do the community conceive their site structure?

## Done when

- [x] All [questions have been added to a document](https://docs.google.com/document/d/1pGtNCFj0x-vdTURW-Zt-LMDNAxIefolCSG31JSO6N6U/edit)
- [x] 1-3 Questions have been prioritised 
- [ ] Prioritised questions have been moved to the workshop tool we have decided upon

**Comment by mia-allers-gds** [comment]
Following discussion of the '[Research on levels 1 and 2 roundup](https://docs.google.com/document/d/1FNZtIPNTg-8mHODXfE366AD_-N557SdnvVShlApFIPY/edit)' with @domoscargin and @romaricpascal:

- We'd like to know whether users are mainly relying on the [existing nav components supplied in the X-Gov Design System](https://x-govuk.github.io/govuk-prototype-components/primary-navigation/) — and if there is anything missing from this
- We are interested in figuring out whether it would be useful to iterate how the GOV.UK brand/ logo is presented on service and product domains (the current branding is very prominent, could we scale it back?)

For the second Q, it might be good to get some GOV.UK designers into the workshop as they have a view on how the branding will change in the coming months
