### ISSUE TITLE
Create, confirm and promote the navigation workshop with the community

### ISSUE THREAD

**Issue by mia-allers-gds** [alphagov/govuk-design-system#3604]
```[tasklist]
### Create workshop
- [ ] Compile questions we want answered in the workshop
```

```[tasklist]
### Promote with community
```

**Comment by domoscargin** [comment]
Closing in favour of:

https://github.com/alphagov/govuk-design-system/issues/3601
https://github.com/alphagov/govuk-design-system/issues/3602
https://github.com/alphagov/govuk-design-system/issues/3608
https://github.com/alphagov/govuk-design-system/issues/3612
