### ISSUE TITLE
Decide on how our users can engage asynchronously

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3608]
## What 
Possibly GitHub discussions, google form, smart survey, slack? This will help on how we want our users to interact with one another.

## Done when
- [x] Summarise the workshop on GitHub discussions
- [x] Setup GitHub discussion with [questions we want to ask the community]()
- [x] Setup GitHub discussion with [our proposal](https://github.com/alphagov/govuk-design-system/issues/3611)

**Comment by domoscargin** [comment]
I've added Slack and GitHub Discussion content to the doc: https://docs.google.com/document/d/1R7_syLwFYXifWY4OopkthF8oDkSvxKOmeC2_2ZHYa_A/edit#heading=h.o9dpmiqjxjdd
