### ISSUE TITLE
Write the proposal for the component to take to the community

### ISSUE THREAD

**Issue by domoscargin** [alphagov/govuk-design-system#3611]
## What
A proposal that we can share with the community that provides:

- Background of our research
- What we believe navigation should be, could be, should not be
- Our definition of the level of navigation we wish to provide a solution
- What we've decided not to consider
- What we want from users

## Why
To provide a guiding direction for the creation of a Navigation component.

## Done When
- [x] A proposal is written
- [x] Proposal is reviewed by squad
- [x] Proposal is translated to [community workshop slide deck](https://github.com/alphagov/govuk-design-system/issues/3613)

**Comment by mia-allers-gds** [comment]
Working document — [Navigation component: initial proposal](https://docs.google.com/document/d/14No0jeRnTrfkVXxwNQ7emhojZKSXf_ip_r1QFYjvGS4/edit)
