### ISSUE TITLE
Analyse quantitative data

### ISSUE THREAD

**Issue by Katrina-Birch** [alphagov/govuk-design-system#3615]
# What
Analyse the quantitative questions from the 2024 US survey. 

## Why
To see if there are any insights or findings that we can conclude, areas that need further research or trends we want to monitor over time

## Who needs to work on this
Trang, Katrina

## Who needs to review this
Trang, Katrina

## Done when
- [x] We have analyses all the quant related questions
- [x] We have compared them to previous surveys

**Comment by trang-erskine** [comment]
This is the spreadsheet with the data. Restricted access. https://docs.google.com/spreadsheets/d/1GuN02WKO7DtUGraWJrlQxxeMJmgOgguru_elNDvqvIY/edit#gid=85041526
