### ISSUE TITLE
Create a presentation

### ISSUE THREAD

**Issue by Katrina-Birch** [alphagov/govuk-design-system#3620]
# What
Create a presentation deck to present the information back to the team. Some of it will be shared in a research recap, most will in the deck for the team to explore on their own time

## Why
Share the insights we find with the Design System team and others

## Who needs to work on this
Trang, Katrina

## Who needs to review this
Trang, Katrina

## Done when
- [x] Added information about the survey
- [x] Added quant analysis into the deck for every question
- [ ] Added information about whether there is / isn't a trend
- [ ] Added insight from free text analysis
- [ ] Added trends to continue monitoring
- [ ] Added recommendations

**Comment by trang-erskine** [comment]
Link to the presentation. Access restricted https://docs.google.com/presentation/d/1enlxH2QFKxBEBhD3bHf_TLowZjfvTd-6hrJgKxVYPlk/edit?pli=1#slide=id.g10372e0cd7_2_16
