### ISSUE TITLE
Improve the link text used in phase banner examples

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#3650]
## What

The link text in our examples isn’t very good (it’s just the word ‘feedback’ that’s linked):

![Phase banner, with the text 'This is a new service – your feedback will help us to improve it.' Only the word feedback is linked.](https://github.com/alphagov/govuk-design-system/assets/121939/16ae1d72-de21-4419-9f86-110cb918b890)

Explore updating the examples to use better word. At the same time, we may also want to add in the fact that feedback links are likely to open in new windows.

## Why

'Feedback' by itself is ambiguous and so it's unclear where the page takes you – it could be a way to view feedback that the service has received, for example.

As the surrounding paragraph does provide enough context to make it clear I believe this still meets [WCAG 2.2 2.4.4:
Link Purpose (In Context)](https://www.w3.org/TR/WCAG22/#link-purpose-in-context) (A) but would not be sufficient to pass [2.4.9 Link Purpose (Link Only)](https://www.w3.org/TR/WCAG22/#link-purpose-link-only) (AAA).

Compliance aside, we can do better here.

## Who needs to work on this

Content designers, designers, accessibility specialist?

## Who needs to review this

Content designers, accessibility specialist?

## Done when

- [ ] The examples for the phase banner component have been updated to include better link text.

**Comment by 36degrees** [comment]
As a starter for 10, we could consider something like:

> This is a new service – [give us feedback (opens in new tab)](#) to help us to improve it.

**Comment by calvin-lau-sig7** [comment]
Some light thoughts based on best practice:

The call to action itself should mention whatever the action for the link is, so "Email us" or "Tell us" (explained in 'Add a feedback link')
And then ideally put the link at the end of the sentence to keep it tidy.

So maybe it can look like this:
> This is a new service. Help us improve it and [give your feedback by email](#).

> This is a new service. Help us improve it and [give your feedback (opens in new tab)](#)
