### ISSUE TITLE
Prepare comms and content to support component release

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3653]
## What

Prepare and plan for various pieces of content that will need to be published to support the release of the Password input component

Includes steps in [Tasks before publishing a new release of GOV.UK Frontend
](https://github.com/alphagov/govuk-frontend/blob/main/docs/releasing/before-publishing-a-release.md)

[Draft document for Comms](https://docs.google.com/document/d/1JZYJNAZY-V7T38EN-1e7Ud8tl6MWzwsx_U4XzMqSOIs/edit?usp=sharing)

[Draft document for release notes](https://docs.google.com/document/d/1sgs3RolAY8F5mQgMh-mnW1H_CNuhFKQ7ec5NMKt-Ads/edit?usp=sharing)

## Why

We want to make sure that users know:
- that we've released the new component
- what to do to use it
- our rationale and decision-making
- our testing

## Who needs to work on this

Content designer, tech lead

## Who needs to review this

Wider squad

### Draft

```[tasklist]
- [ ] Changelog is up to date
- [ ] Updated roadmap and 'What's new' messages drafted
- [ ] Release notes for new version of GOV.UK Frontend drafted
```

### Publish

```[tasklist]
- [ ] Release notes published
- [ ] https://github.com/alphagov/govuk-design-system-backlog/issues/240 converted into 'current component' discussion with new pinned post, and status changed to 'published'
- [ ] 'Second password rationale' posted in backlog discussion
- [ ] Accessibility testing summary posted in backlog discussion
- [ ] 'What's new' message updated
- [ ] Roadmap updated
```

**Comment by querkmachine** [comment]
This has probably inadvertently ended up having a lot of overlap with the release issues #4875 and #4876. 

This issue can probably be trimmed down to remove the duplication.

**Comment by calvin-lau-sig7** [comment]
I'll take the release issues you've raised as canon and close this as a duplicate – only thing I need to do is add the backlog-type posts as "channels" on #4975

**Comment by calvin-lau-sig7** [comment]
Duplicated by release tickets, as mentioned above.
