### ISSUE TITLE
Organise a working group review of Navigation mvp

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3680]
## What
Organise a working group review of mvp prototype, defined by the outcomes of #3678.

The working group review will run between 15-19 April (one week).

## Why
For the working group members to assess whether the proposal is a useful and unique contribution to the Design System.

## Who needs to work on this
Trang

## Who needs to review this
Nav squad (Charlotte, Mia, Brett, beeps, Calvin, Kelly)

## Dependencies
#3678 
Prototype

## Done when
- [x] we have informed the working group of the upcoming review
- [x] we have identified a date for the feedback session (early cycle 3)
- [x] we have prepared supporting materials for the review
- [x] we have made the wider Design System team aware that a working group review is taking place
- [x] we start the review on 15 April

**Comment by trang-erskine** [comment]
Messaged the working group on https://ukgovernmentdigital.slack.com/archives/C0216FD6YMP

> Hello working group.
You may have heard, we’ve started working on the [navigation](https://github.com/alphagov/govuk-design-system-backlog/issues/76) component.
Just a heads up, we’re going to send the proposal your way for the first review. It’s planned for 15 April and will be open for a 1 week review period. We hope you can make time for it.
The first review asks, “Is the proposal useful and unique?” You can brush up on the full contribution criteria here: https://design-system.service.gov.uk/community/contribution-criteria/
We would also like to run a followup session to discuss the feedback you provided on Navigation the week after. Can you please select all the times you are available so we can pick a time that suits most people. https://rallly.co/invite/JVMcjw6cLubC
Thanks.

**Comment by trang-erskine** [comment]
Emailed the Working Group for availability today

**Comment by CharlotteDowns** [comment]
We have sent out the Navigation proposal to the Working Group on Monday 15 April 2024. We are planning the Working Group video review for Tuesday 23 April 2024, 2:00 - 3:00pm.
