### ISSUE TITLE
Consult someone from GOV.UK about the functionality of the GOV.UK logo

### ISSUE THREAD

**Issue by mia-allers-gds** [alphagov/govuk-design-system#3683]

**Comment by CharlotteDowns** [comment]
## Reaching out to teams

We have proposed three scenarios in the homepage-and-navigation-govuk GDS slack channel for review and suggestion. This is the message we posted on 27 March 2024:

> The current [GOVUK Header component](https://design-system.service.gov.uk/components/header/) we provide to service teams often uses the GOVUK logo as a link to the GOVUK Homepage, our belief is that this may create less than ideal journeys for users of these services. As part of our work we have a few potential scenarios under consideration:

> - **Scenario 1:** advise service teams to point the GOVUK logo to the service homepage (and potentially add a link to GOVUK homepage into the footer component)
> - **Scenario 2:** our team creates a design (currently in progress) which presents the service name as its own very obvious link but still seperate fork the GOVUK logo link
> - **Scenario 3:** our team does nothing and accepts this is potentially really rubbish for users (maybe a user research activity for the future)

> I'd also be really interested if your team collects analytics or data around where folks come from before reaching the homepage and whether folks who come from 'services' have a higher drop off (or anything else significant) than others?

## Responses from teams
The replies are extremely useful to the investigation.

### Reply 1
>Hi Charlotte! Interesting challenge right? I think it would be great to know what users who are logged in to a service expect to happen when they click on the govuk logo. Do they expect to go to govuk or to the service home? I am sure they need a way to go to the service home, but would be great to understand in which instances they may need to go to [GOV.UK](http://gov.uk/) from the service. That could help inform how prominent the access to the govuk homepage should be imo.

>Also, I noticed that some services have the service name next to the logo, but sometimes they don’t. When they don’t, wouldn’t it be weird to link to the service homepage?

>About the data, I think our team has data available that allows us to see what pages users come from when they land on the homepage, but that alone won’t help with drawing a clear picture of the actual journey. For example, are users getting to the homepage from 'transaction done' pages or via the header? 

### Reply 2
>Thanks Charlotte for sharing this. It sounds like a really interesting area to look into further and understand what's going on with the journeys and what users are trying to do.

>Agree with Reply 1, feels like there’s a need to look at data and do user research in order to understand these user journeys in detail. GA shows previous page paths and external sources easily but would be good to know at what point are users leaving a service to go to the govuk homepage - eg in the middle of the service or at the end. If at the end, can’t remember from the top of my head if the ‘done’ pages only link to govuk from the header or is there another to govuk homepage on there (if more than one link, which one do they most commonly click).

>Also why are users clicking on that link - what are the trying to do - eg get to the start of the service, get help, go to govuk to complete another task. Could it be that different services need a different solution - eg ones where you can do more than one thing or where doing the thing takes a long time vs other more straightforward ones?

>You might have already done this but sounds like it'd be also useful connect with some of the gov service teams to find what what data and user research they have on this.

>A thought on **Scenario 1**, Not sure users differentiate between a service and govuk website. For many they're one thing so this type of solution could create an inconsistent experience for them around where the logo takes them and break that mental model for what happens when you click on it.

### Reply 3
>What do you mean by "the service homepage"?
In my experience services don't always have a "homepage". For example, some start with a set of filtering questions.
If you mean the service's [GOV.UK](http://gov.uk/) start page, this could also be problematic, as some services (visa application service for example) have a large number of different start pages for the same service.

>The [Content Design Analytics dashboard has a "Navigation" tab](https://lookerstudio.google.com/u/0/reporting/9030f1f9-8c67-4644-8ae7-934bc206413c/page/LqQoB) which you can filter to the homepage (by entering "/" in both of the boxes at the top. (Also set the date range you're interested in at the top tight.)
The bottom table on the left will then show you where users come to the homepage from.

>It's actually relatively easy to differentiate between a referral from within a service (which looks like: vehicletax.service.gov.uk / referral) from a referral from a done page (which looks like: /done/vehicle-tax).
In the [data that I downloaded](https://docs.google.com/spreadsheets/d/19RPcKke2dp3_u2NEcL_ecTkmTKo7jSDN3xUhhH5T3ro/edit#gid=0) from the dashboard, which covered the most common 80% of referrals to the homepage in the last month, referrals from within a service made up 17.6% of referrals to the homepage, whereas referrals from done pages made up 3.2%

>You'd need the help of a performance analyst to cross reference the different types of referral pages with the associated exit rates.
As an example, [this slide](https://docs.google.com/presentation/d/1bz9A1ruLEm64jYOnMr-T6nM-K6XjcG_h1LTVCpu9gjU/edit#slide=id.g1337cfc1f1a_0_157) shows some data that a PA prepared for me to help answer a similar question about why bounce rates were high on visa related browse pages.

>Just anecdotally, I previously looked at [some feedback that people left on the homepage](https://docs.google.com/spreadsheets/d/1te61_ksSaLx9ibol8Bql8t_PA45bL09iDMTy_Hx3d64/edit?pli=1#gid=0) and lots people leaving feedback on the [GOV.UK](http://gov.uk/) homepage were reporting issues they were having with using services. This gives me the impression that users are often ending up on the homepage when they're having issues with services.

**Comment by CharlotteDowns** [comment]
## Notes from call with Senior Product Manager, GOV.UK Homepage & Navigation and Lead Product Manager – User Experience, GOV.UK

We discussed:

- Emphasis to keep GOVUK one connected experience (probs shouldn't muck with the logo)
- Sitewide in context to the menu bar was referring to pages excluding services (documentation and starting pages mainly) so didn't seem to be a requirement to get it into the Design System
- Showed them [our latest prototype](https://govuk-frontend-pr-4915.herokuapp.com/components/header) and they can see why we would like to make a distinction between service specific and GOVUK wide content across two bars. It seemed to make sense to them
- Want to discourage our users incorporating search into services (again for joined up GOVUK reasons), they've been doing a lot of work to improve GOVUK search using Google vertex search and are looking to include ai summarisation. Basically a GOVUK wide search is more desirable that service specific search
- Seemed interested in 'common content' across navigation elements in GOVUK
