### ISSUE TITLE
Confirm time and date for the event

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3688]
## What
Confirm the date and times for the first event. We will likely hold it in May 2024.

## Why
So we can secure speakers.

## Who needs to work on this
Imran

## Who needs to review this
Event speakers, DSDay organising group

## Done when
- [ ] we have agreed the date and time

**Comment by Kam-Nijjar** [comment]
Proposed agenda for 15th May 2024 Online Event 1 (online)
 
10:00 am: Intro & DS system showcase
11:00 am: Session 1
12:00 pm: Session 2
12:45 pm: Lunch
1:30 pm: Session 3
2:30 pm: Session 4
4:00 pm: Closing & retro

**Comment by Kam-Nijjar** [comment]
The new date for the first event is 21/05/2024
avoid clashing with GDS L & D Day
Imran to contact Kate Thomas & Betty Mwema
Kam to contact Gordon Guthrie and Daniel Fontaneda to check their availability

**Comment by Kam-Nijjar** [comment]
Session 1 - 11-12 Daniel Fontaneda - will need to plan contingency as partner is due to have baby 02/06/24
