### ISSUE TITLE
Get in contact with Design System Day 2023 speakers who couldn't deliver their sessions

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3690]
## What
Contact speakers who couldn't deliver their show & tell at Design System Day 2023 and ask them to speak at first event this year.

## Why
So we provide a platform for their work.

## Who needs to work on this
Imran

## Who needs to review this
N/A

## Done when
- [x] we have approached each speaker and confirmed attendance

**Comment by Kam-Nijjar** [comment]
The following speakers were unable to deliver on DSDay 2023:-
Kate Thomas - Paypal
Daniel Fontaneda - Bumble
Jane Martin & Betty Mwema - GDS
Gordon Guthrie - Scottish Government
[Speakers and Facilitators
](https://docs.google.com/spreadsheets/d/1N4koNsGskJPJYKwszE09NsxJel3NJqyQEjnyeKzpc4A/edit#gid=1742376273)

**Comment by Kam-Nijjar** [comment]
Draft email for speakers[Call for speakers
](https://docs.google.com/document/d/1KjcrKtQOArTHbEfxHw-NqPUtnnQbtObdcPQYg3udN4Y/edit)

**Comment by Kam-Nijjar** [comment]
Emails sent to all candidates
Kate Thomas - has resigned from Paypal
Gordon Guthrie has accepted and can present at anytime

**Comment by Kam-Nijjar** [comment]
Daniel Fontaneda from Bumble has accepted (FYI - his baby is due 1st week in June, if the baby comes early he will not be able to present)

**Comment by Kam-Nijjar** [comment]
Reminder email sent to Daniel Fontaneda to confirm time slot

**Comment by Kam-Nijjar** [comment]
GDS learning Day booked for 15th May 2024
May need to reconsider the date

**Comment by Kam-Nijjar** [comment]
Jane Martin has moved to Open University

**Comment by Kam-Nijjar** [comment]
Imran to contact Kate Thomas via Linked - to see if she would still like to do a presentation
Imran to contact Betty (GDS) to see if she is happy to do a presentation on her own or with someone else

**Comment by Kam-Nijjar** [comment]
New date for the first event 21/05/2024
emailed Gordon Guthrie, Daniel Fontaneda & Betty to check availbility

**Comment by Kam-Nijjar** [comment]
Session 1 - 11-12 Daniel Fontaneda (confirmed)- will need to plan contingency as the partner is due to have baby on 02/06/24
