### ISSUE TITLE
Run an induction session with confirmed speakers

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3691]
## What
Run an induction session with confirmed speakers for first Design System Day 2024 event.

## Why
So we can ensure they can access and use Zoom, and to set expectations for the event.

## Who needs to work on this
Imran

## Who needs to review this
N/A

## Done when
- [x] we have booked a time for the induction session
- [x] we have sent invitations to speakers
- [x] we have issued tickets to each speaker

**Comment by Kam-Nijjar** [comment]
Induction booked for Friday 3rd May 2024 10:30
