### ISSUE TITLE
Run spikes and tests to determine a prototype to build

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3696]
## What

We want to show some 'things' to the Navigation steering group on the 8 April 2024 for a crit. 

We are looking to base our starting point off the Navigation bar used on the Design System website, as this was mentioned in the Backlog prioritisation survey and has been seen in many examples. Including [x-gov prototype components, primary navigation](https://x-govuk.github.io/govuk-prototype-components/primary-navigation/). It also helps us build our own website to the same high standards as our contribution process.

### High priority questions we want to answer with spikes and prototype work
- How does navigation fit in with our existing header component? Can we extend our current header component rather than knock up something new? (list out the needs then pass to developer to spike)
- What do we display on smaller views? How does the smallest view expand to the largest view? (design)
- How do we enable “add-ons” like search and account stuff? (design, developer - two tasks)
- How easy will it be to upgrade? (developer)
- Can we provide some consistency to how links are treated in the existing header? How do we communicate where the links link to to our users (design and conversations with other teams incl. steering group)

### Lower priority questions we want to answer with spikes and prototype work
- Do we want to spike what level 3 might look like? (design, developer)
- Can level 2 nav be left-side? (design, developer)

### Outcomes

- Investigate any early accessibility issues
- What does our MVP look like? (just copy the DS nav bar wholesale?)

## Why

We want to have a better idea about our contribution ahead of the working group review w/c 15 April 2024

## Who needs to work on this
Brett, Mia, Anika, Charlotte (possibly the steering group)

## Who needs to review this
The squad, 2pm on 3 April 2024

## Further detail

We have started a Google Document that lists out our needs [Spike: Header component](https://docs.google.com/document/d/1XUgtfGpnEWXjWBqouZs2FYDZrGHhhr1KPxoT68poHDA/edit
)

We have added 3 spike issues to track our progress on answering the above questions

```[tasklist]
### Spikes and tests
- [ ] #3714
- [ ] #3715
- [ ] #3716 
```

## Done when

- [x] Collected all suggestions for spikes/prototypes 
- [x] Prioritised the suggestions
- [x] Start running spikes and/or collaborating on designs
- [x] Published spikes to main cycle board as tasks

**Comment by domoscargin** [comment]
Nice to investigate any early accessibility issues: https://docs.google.com/document/d/1WMMgbnxriRekaDPfrudXDOyyCMgFBky6ymbK_vsNn7c/edit#heading=h.y8esn6wmdany

**Comment by CharlotteDowns** [comment]
Here we have listed out our needs in a google document for the [Spike: Header component](https://docs.google.com/document/d/1XUgtfGpnEWXjWBqouZs2FYDZrGHhhr1KPxoT68poHDA/edit
)

**Comment by CharlotteDowns** [comment]
<img width="1469" alt="Screenshot of Design System header component with x-govuk primary nav example" src="https://github.com/alphagov/govuk-design-system/assets/56260216/d6467b75-a850-4ca2-9a37-8971c30dc0ee">

Running this experiment has helped me understand some changes we may need to make to the [existing header component in the design system](https://design-system.service.gov.uk/components/header/).

- If we want the content of the Navigation elements to align with the logo we will have to apply the blue border-bottom to a different container
- We still do not address the issues with linking back to a homepage

**Comment by domoscargin** [comment]
We've prioritised the following 3 investigative spikes, aiming to be completed for the steering group crit on 8 April:

- #3714 
- #3715 
- #3716
