### ISSUE TITLE
Create decision log for Navigation work and document early scoping decisions

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3711]
## What
Create a decision log to record decisions as we develop Navigation component(s).

There are also key scoping decisions to be made in this cycle.

## Why
A decision log if useful to reference our rationale and help us identify further comms we need to do.

We also need to make key decisions so we know what mvp is.

## Who needs to work this
Kelly, Trang, designers, developers

## Who needs to review this
Nav squad

## Done when
- [x] we have created a decision log
- [x] we have decided and documented which services this component will be typically used for (eg services, products, internal services, not campaigns and not complex content heavy websites
- [x] we have decided and documented how many components and / or patterns we will build
- [x] we have decided and documented how things will look on mobile? (eg what is the bare minimum thing we can show, mobile first approach)
- [x] we have decided and documented potential future iterations (eg search bar)
- [x] we have made a decision on navigation and documented our rationale

**Comment by kellylee-gds** [comment]
(Restricted to GOV.UK Design System team) [Nav decision log ](https://docs.google.com/spreadsheets/d/1zduTR-kZc5j28PFMi98-KNoP8W8S-8iJtisf9nLAbIM/edit#gid=1037439525)
