### ISSUE TITLE
Hovering over an item in a nav different to current item in a nav scrolls page to the top

### ISSUE THREAD

**Issue by kubabartwicki** [alphagov/govuk-design-system#374]
This happens on Safari 11.1 on every page. To reproduce, go to https://design-system.service.gov.uk/styles/layout/ or any other page on design system, scroll down, then hover over a main nav item that isn't the current one. In case of the Layout page, hovering over Get started / Components / Patterns / Community will trigger this behaviour.

Can't observe in Chrome

**Comment by nickcolley** [comment]
@kubabartwicki thanks for these issues! :)
