### ISSUE TITLE
Make design suggestions based on working group feedback

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3777]
## What
Following the feedback from the working group review we identified some specific design actions.

## Why
These actions could improve the Navigation contribution, it's usability, and adoption.

## Done when
- [x] Explore how to show a greater visual distinction between a service name with and without a link
- [x] Revisit the impact of reducing space within the header, service name and navigation proposals
- [x] Investigate organisation switchers and location of Phase banner in relation to service name and navigation
- [x] Investigate whether or not the main navigation takes a vertical position instead of horizontal beneath the header
- [ ] Consider One Login Header users that may not operate a service, for example, GOV.UK email notifications
- [ ] Consider colour contrast and font weight  of Navigation elements

**Comment by CharlotteDowns** [comment]
Thank you @onupama1 this is really appreciated. The two examples are a really nice case to extend our guidance, the journeys both seem quite linear, I'd love to determine why they both chose a different approach to linking the service name. The points you make about allowing for this in these types of service are interesting too, I wonder if users of either of these services click the GOVUK logo and the expectations around that journey too.

**Comment by onupama1** [comment]
> Thank you @onupama1 this is really appreciated. The two examples are a really nice case to extend our guidance, the journeys both seem quite linear, I'd love to determine why they both chose a different approach to linking the service name. The points you make about allowing for this in these types of service are interesting too, I wonder if users of either of these services click the GOVUK logo and the expectations around that journey too.



> Thank you @onupama1 this is really appreciated. The two examples are a really nice case to extend our guidance, the journeys both seem quite linear, I'd love to determine why they both chose a different approach to linking the service name. The points you make about allowing for this in these types of service are interesting too, I wonder if users of either of these services click the GOVUK logo and the expectations around that journey too.

@CharlotteDowns thank you for the feedback. To answer why they chose different approach, I think one way of figuring that out will be to do a quick audit of all the services with and without links and see where the links take to and why. To understand the 'why' we might be ale to either speak to a service designer or designer if available or there might be some design documents in the services. Gov.uk slack is quite helpful in reaching out to people. I can help with that if you send me a list of all gov.uk services. But will need help re slack. To narrow down the work you might start with services with linear journeys and incrementally look into services with non linear journeys e.g. developmental home loan applications.

Re clicking on GOVUK logo, we have 2 core groups of users (broader term again) - in/experienced with GOVUK. I would assume experienced users aware of where GOVUK logo takes hence not clicking without need. Inexperienced might get confused as usually it takes [here](https://www.gov.uk/). But then again there are 3 search buttons users are faced with:
a) already often a search button on the service page they are on. Though this is not consistent through all the pages of all services
b) clicking on GOVUK logo take to [this](https://www.gov.uk/) search page.
c) On the link above on (b), there is another search logo on the right hand top leading to [here](https://www.gov.uk/)

Again the question from user perspective, what is the point of these journeys? Are user using them to search for different things (in which case quite pertinent). What I am trying to say is understanding the categories user use the GOVUK logo for. 




I would assume the experienced users will know

**Comment by Ciandelle** [comment]
> # Design Exploration
> ## Explore how to show a greater visual distinction between a service name with and without a link
> This is in order to help users know that the service name is or is not a link. Here are some suggestions
> 
> ### Idea 1 – Persistent blue underline
> <img alt="The black service name has a blue underline" width="1064" src="https://private-user-images.githubusercontent.com/56260216/328447496-41f109cb-bf2b-46ea-b5c9-cd5a0bdaba42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTA5NzAsIm5iZiI6MTcxNTA5MDY3MCwicGF0aCI6Ii81NjI2MDIxNi8zMjg0NDc0OTYtNDFmMTA5Y2ItYmYyYi00NmVhLWI1YzktY2Q1YTBiZGFiYTQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE0MDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMDY4ZjU3ODM3NDE2M2EyMDgyMDVkYTc1Nzc1MDk5YjUxN2Y2MGEyNmMyZDU3ZTI1Y2I3NDgxY2JmMGFiMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gxTtVra9MsKM2Z5cIeQFljKZpfCTSB3dFSefkdHjWQ0"> Thoughts: How will this look with the rest of page content, could it look busy?
> ### Idea 2 – Persistent underline in the same colour as the text
> <img alt="The black service name has a black underline" width="1061" src="https://private-user-images.githubusercontent.com/56260216/328454308-2f4b225c-244f-4d95-8aab-682831978925.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTA5NzAsIm5iZiI6MTcxNTA5MDY3MCwicGF0aCI6Ii81NjI2MDIxNi8zMjg0NTQzMDgtMmY0YjIyNWMtMjQ0Zi00ZDk1LThhYWItNjgyODMxOTc4OTI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE0MDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkZTY2ZjVmMTM5ZTI0NWRkMzUxZjgxNThjNzNmNDI3NTEyODhiZjg5NmQ1YzQxNTYwZjljZjhmODNmOTEzY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZMB-gHWaPkCOgHIMrZWOPIQ3YfQBy1qnGdlNxSiQRFk"> Thoughts: What would the hover style look like? Does it need to be differentiated now?
> ### Idea 3 – Persistant thick underline with greater offset in the same colour as the text
> <img alt="Screenshot 2024-05-07 at 09 51 25" width="1049" src="https://private-user-images.githubusercontent.com/56260216/328455486-22cf1440-15e0-498e-a6fe-47b87935af35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTA5NzAsIm5iZiI6MTcxNTA5MDY3MCwicGF0aCI6Ii81NjI2MDIxNi8zMjg0NTU0ODYtMjJjZjE0NDAtMTVlMC00OThlLWE2ZmUtNDdiODc5MzVhZjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE0MDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2NTZjYWE3YWZjZTczYjQwOTJkYjU2MDg3M2JkYjQyMzg2MmI2OGI2ZGQyZTZkYWU5YzY1ZGIxYjQwNTU4YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kf7Aoe9eImIZLknOyRYGZ3ATKVSxJQIV1HToroZOZRY"> Thoughts: I like this one but it seems to be the one that messes with convention the most.

My personal preference is for idea 3 out of those - it feels the most visually appealing out of all of them. 

The space between the text and underlining signposts it's a service name to me and I would expect it to take me to start of the service, however I'd want to get some testing done with users to see if that's the case from our end users.

**Comment by CharlotteDowns** [comment]
## Decisions

-  ### Explore how to show a greater visual distinction between a service name with and without a link
We have decided to ensure that all services make the service name a link in our guidance and therefore are going to keep the name without an underline unless interacted with. [We also have assessed a list of services and mapped the behaviour of the service name](https://docs.google.com/spreadsheets/d/1vWDmQBA66lbdHi4YLxvQ8wCBI4l9xryQonUL2DoijVU/edit?usp=sharing).
-  ### Revisit the impact of reducing space within the header, service name and navigation proposals
We have chosen spacing that is consistent with the existing header component.
-  ### Investigate organisation switchers and location of Phase banner in relation to service name and navigation
We have built 'slots' into our current design and we may be able to introduce a full width one between the service name and navigation items.
-  ### Investigate whether or not the main navigation takes a vertical position instead of horizontal beneath the header
This is difficult to make work with some 2/3 layouts and therefore will maintain the horizontal position at the top of the page to allow for greater consistency.
