### ISSUE TITLE
Prepare slide deck (create main deck, write MC notes, get slide decks from speakers, it'd be good to mention why we've selected these speakers for this event)

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3798]
## What
Design System team presenters/facilitators to create the main deck for the DSDay online event - to include speaker decks
## Why
Preparation for the main online event on 21st May 24. Speakers and facilitators are aware of the agenda.
## Who needs to work on this
Community Lead/ ADM / PM / Interaction Designer / Frontend Developer
## Who needs to review this
PM & Community lead
## Done when

- [x] Trang/Romaric/Charlotte update the main deck
- [x] Imran to update main deck
- [x] Speaker deck added
- [x] Retro info added

Update main deck [DSDay Showcase ](https://docs.google.com/presentation/d/1qZ5btzk4lKi2-NV260vCPYoNe3sNOShBDNyPh123glA/edit#slide=id.g2dd78349067_0_0)

**Comment by 36degrees** [comment]
Closing this as it's in 'Done'.
