### ISSUE TITLE
Final prep for speakers (ensure they know how long they have, the running order, etc)

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3799]
### What
Reach out to speakers to make sure they feel supported and fully prepared for the event.

### Why
To ensure a good speaker experience.

### Who needs to work on this
Kam, Imran

### Who needs to review this
PM & DM

### Done when

- [x] Arrange session time
- [x] Invite speakers
- [x] Run session, talking through tech, audience, agenda and slides

**Comment by 36degrees** [comment]
Closing this as it's in 'Done'.
