### ISSUE TITLE
Set up Zoom platform (check links are correct, graphics have been added, etc)

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3800]
### What
Make sure the event platform is set up properly.

### Why
So that the team/event comes across as professional.

### Who needs to work on this
Kam, Imran, speakers

### Who needs to review this
PM & DM

### Done when

- [x] Backgrounds and images uploaded
- [x] Check links
- [x] Add presenters and co-host permissions
- [x] Run tech check-ins]
- [x] Prep troubleshooting tips

**Comment by Kam-Nijjar** [comment]
[Zoom background
](https://drive.google.com/drive/folders/1s279ZKJj92JEg77UUMA3WnicFDYFtxoI)

**Comment by 36degrees** [comment]
Closing this as it's in 'Done'.
