### ISSUE TITLE
Send post-event thanks to attendees and speakers

### ISSUE THREAD

**Issue by ImranH-GDS** [alphagov/govuk-design-system#3802]
### What
Say thank you to attendees for supporting us and the speakers for taking a prominent role in making the day a success.

### Why
To create a good impression and leave a positive vibe in the speaker's mind.

### Who needs to work on this
Kam, Imran

### Who needs to review this
PM & DM

### Done when

- [x] Run event
- [x] Draft thank you comms and share with team
- [x] Send thank you comms

**Comment by mia-allers-gds** [comment]
@ImranH-GDS will this be done via Mailchimp? Just wondering if you need any graphics?

**Comment by Kam-Nijjar** [comment]
https://drive.google.com/drive/folders/1UAS6Rj94UQzsGxM87whfFNiw-kZf8Q7Q

**Comment by Kam-Nijjar** [comment]
Draft comms
[Eventbrite](https://docs.google.com/document/d/1Br1OZpBWEhDLMPbNnoKPxRIBmvPiKVW22XzA-dBYCuU/edit)
