### ISSUE TITLE
Build variants to present in the component pages

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3823]
## What
Building examples of the header component and service header navigation component for the Design System guidance pages. Base our examples on the work done in the [Navigation guidance draft  Google document.](https://docs.google.com/document/d/1lpnrD3Dv2PUHqxPx6bBZDGSWosjlUeBuU1Go90gAHSk/edit#heading=h.rmrcwmgcg7f6)

## Why
Examples help users use our components in the way we intend for them to be used.

## Done when

Header guidance page examples
- [x] Default header with no service name
- [x] Header with service header navigation component
- [x] Header with One Login as we created in [SPIKE #4915](https://github.com/alphagov/govuk-frontend/pull/4915)

Service header navigation examples (all with header bars for context)
- [x] Default service header
- [x] Service header with basic navigation
- [x] Service header with service name and navigation

**Comment by querkmachine** [comment]
Is there a difference between "Header with service header navigation component" and "Service header with basic navigation"? The two would seem to be the same thing at a glance.

**Comment by CharlotteDowns** [comment]
Yes, that's close to correct. "Header with service header navigation component"  and "Default service header" are the same.  The former will live as an example on the GOV.UK Header component page and the latter will live at the top of the Service header navigation component page
