### ISSUE TITLE
Decide on which quote we will go with and share with Bizops and procurement team and arrange PO

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3840]
## What
Decide on which caterer we will use for the F2F event in Liverpool on 5th September 2024 (venue option already decided)

## Why
We need to provide refreshments for the event for our guests and facilitators

## Who needs to work on this
Community Manager, Associate Delivery Manager, Procurement Lead

## Who needs to review this
Delivery Manager, Procurement Lead

## Done when
- [x]  Final decision is made for suitable caterers for the event
- [ ] Share option with Bizops and procurement team
- [ ]  Procurement team have raised a purchase order number
- [ ] Send purchase order number to venue and caterers for invoicing

**Comment by Kam-Nijjar** [comment]
[Budger tracker](https://docs.google.com/spreadsheets/d/1PYD7z-7w2pDA4HGMV29AeJeypNvQpYd63NphNjD8O_8/edit?pli=1&gid=1184150292#gid=1184150292)
Quoted options tab

**Comment by Kam-Nijjar** [comment]
catering option
[Totally Dvine 11382](https://docs.google.com/document/d/1c9wagpgjbkQXUprMF8Jt7T2EcKIcZ-5zezwAiwedUSM/edit)
A follow-up email with the catering request sent on 01/07/24
Included details for invoicing

**Comment by Kam-Nijjar** [comment]
Imran is negotiating with the catering supplier to reduce costs

**Comment by trang-erskine** [comment]
This is now included in https://github.com/alphagov/govuk-design-system/issues/3839
