### ISSUE TITLE
Draft ticket release comms

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3842]
## What
Whilst there is a comms embargo due to the general election, we should draft all ticket release comms in preparation for when the embargo is lifted, however, we should be able to send comms privately to known contacts. Release the agreed number of tickets (saving tickets for community, stakeholders, SMT and when we make the big announcement publicly. 

## Why
To announce the release of tickets for the F2F DSDay 2024.

## Who needs to work on this
Senior Delivery Manager, Community Manager

## Who needs to review this
SDM & PM

## Done when

- [x] Draft message prepared for all channels of communication
- [x] Message 2i
- [x] Decide on how many tickets are to be released initially
- [x] Decide on date to share comms

**Comment by Kam-Nijjar** [comment]
[F2F Comms grid](https://docs.google.com/document/d/1AA5HQMbsBaMK7qMZY8XtlpxNrIKZuuSbmpoq70nN6cs/edit)

**Comment by Kam-Nijjar** [comment]
Meeting with Keiron Fletcher & Gareth Price - 4th July 2024
Can put comms on own DS page from Monday
Official channels have to go via the Cabinet Office Press Office (external sign-off required)
Can promote own personal channels early next week

**Comment by Kam-Nijjar** [comment]
Social posts
Slack
The #DSDay24 call for speakers is open!
We’re looking for keynote speakers and workshop hosts for Design System Day 2024.
Come join us on Thursday 5 September in Liverpool and make 2024’s event our biggest and best yet!
Find out about what we’re looking for and how to apply: https://design-system.service.gov.uk/community/call-for-speakers-2024/
LinkedIn
The Design System Day 2024 call for speakers is open!
We’re looking for keynote speakers and workshop hosts for Design System Day 2024, on 5 September 2024.
Come join us on Thursday 5 September in Liverpool and make 2024’s event our biggest and best yet!
Find out about what we’re looking for and how to apply: https://design-system.service.gov.uk/community/call-for-speakers-2024/

**Comment by Kam-Nijjar** [comment]
Ciandelle has also done this post on [linkedIn](https://www.linkedin.com/posts/ciandelle-hughes-8065aa76_the-design-system-day-2024-call-for-speakers-activity-7216817022335168513-FGo7?utm_source=share&utm_medium=member_desktop) and happy for people to copy it

**Comment by Kam-Nijjar** [comment]
[website](https://design-system.service.gov.uk/community/call-for-speakers-2024/)

**Comment by Kam-Nijjar** [comment]
1st round - 200 tickets 23/07
2nd round - 175 tickets 01/08

50 hidden tickets for staff/speakers
Blog posts for release of tickets following scouting visit to the venue.

**Comment by trang-erskine** [comment]
@Ciandelle is this done? Do you still need a 2i?

**Comment by Ciandelle** [comment]
@trang-erskine we just needed confirmation of exactly when we're releasing tickets but otherwise it's ready to go out

**Comment by Ciandelle** [comment]
Actually can I get a 2i on this [doc](https://docs.google.com/document/d/114IPxLzYp1xRGCljkNWGmqRIcMeTxS6ng3dBdgW3oNw/edit?pli=1)? Then can do the ticket tease release
