### ISSUE TITLE
Confirm working group review call date (week 1)

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3847]
## What
We have created a rally poll to track when our working group members can attend a call to discuss their feedback on the Navigation proposal.

## Why
To get a majority present to discuss their feedback.

## Done when 
- [x] Poll sent out to working group via email
- [x] Poll prompt on x-gov slack
- [x] Email prompt Thurs 20 June
- [x] Decision made
- [x] Call arranged

**Comment by Izabela-16** [comment]
Call is scheduled for the 3rd July at 11:30 based on the responses received so far.
