### ISSUE TITLE
Organise and chat with One Login developers (week 1)

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3850]
## What
Have conversation, document actions and next steps for integrating a One Login component into the work on Navigation.

## Why
To allow both sets of users to have a consistent experience across services.

## Done whens
- [x] Meeting created in [Establish relationship with One Login coded examples (week 1) #3846](https://github.com/alphagov/govuk-design-system/issues/3846)
- [x] Notes taken in call
- [ ] Direction decided
- [ ] Guidance decisions passed onto the squad
- [ ] Development work to achieve decision completed

**Comment by querkmachine** [comment]
We've had a meeting, but One Login have asked for more time to mull over their options before deciding on a direction.

**Comment by CharlotteDowns** [comment]
## Notes from the call on 21 June 2024

The way forward we got to is that we show a visual example of One Login in the black header to the Help users to navigate a service pattern. We provide a contact to their team (similarly to the Step-by-step navigation pattern) for implementation.

Meanwhile we share with them our npm preview branch and pull request code so they can work out how to use our slots with their custom css, js and form work that underpins the component they have.

We also mentioned we'd like them to update their guidance to include that the Service name should be a link.

From the technical perspective, this sounds like they're happy to use the slot and we won't need to include any code specific to One Login in govuk-frontend.

(This is good because they're going to be changing the HTML structure for the One Login elements soon, which otherwise would have been a blocker for us.)

Rather than having service teams use the slot directly, however, their plan is to create a package that inherits govuk-frontend and uses our Header and Service Header components; and injects their code into the slot at that point, as well as requisite CSS/JS.

Service teams would install the One Login Header as an npm package and use it in place of the DS Header.

## Further conversation after the call 21 June 2024

They think they should actually think through the options in some more detail. They may need to revisit the broad decision  made on that call

(waiting to hear back on updates)

**Comment by CharlotteDowns** [comment]
Checked in with One Login this morning, I've sent them a copy of our current guidance and how we are speaking about using their component.

Here's [what the current guidance looks like](https://deploy-preview-3859--govuk-design-system-preview.netlify.app/patterns/navigate-a-service/), we reference the One Login header under ## Plan your GOV.UK header

> The [GOV.UK](http://gov.uk/) header component should only be used to show the [GOV.UK](http://gov.uk/) logo and any GOV.UK-wide tools used in your service, such as [GOV.UK](http://gov.uk/) One Login.
>
> Also see [GOV.UK](http://gov.uk/) One Login guidance to [Let users navigate to their ](https://www.sign-in.service.gov.uk/documentation/design-recommendations/let-users-navigate-sign-out)[GOV.UK](http://gov.uk/)[ One Login and sign out easily](https://www.sign-in.service.gov.uk/documentation/design-recommendations/let-users-navigate-sign-out).
>
> Services do not need to duplicate the menu bar used in the [GOV.UK](http://gov.uk/)[ homepage](https://gov.uk/) and mainstream guidance pages.

**Comment by CharlotteDowns** [comment]
A meeting has been scheduled for 16/07/2024. In retro 09/07/2024 we suggested detaching One Login involvement as a dependency to our work in order to remain agile.
