### ISSUE TITLE
Preview branch of Design System website (week 1)

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3852]
## What
Create a preview branch of the GOV.UK Design System website with the updated GOV.UK Header component, new Service header navigation component and Help users navigate a service pattern. We will take the [DRAFT guidance document for content and structure](https://docs.google.com/document/d/1lpnrD3Dv2PUHqxPx6bBZDGSWosjlUeBuU1Go90gAHSk/edit).

## Why
It is easier to get feedback and visualise our intent with a preview version of the changes.

## Done when
- [x] Read how to [pull in latest version of the code from this slack thread](https://gds.slack.com/archives/C011V7RAAKY/p1717404146695849)
- [x] Create new branch
- [x] Make changes locally
- [x] Push to remote
- [x] Add examples from preview of GOV.UK Frontend
- [x] Get squad to review

**Comment by calvin-lau-sig7** [comment]
When you're ready to add into the branch, here's the content draft done up as Markdown code. I can add too when it's up as a PR.
[govuk-header-scratch.md](https://github.com/user-attachments/files/15888153/govuk-header-scratch.md)
[navigate-service-scratch.md](https://github.com/user-attachments/files/15888154/navigate-service-scratch.md)
[service-header-navigation-scratch.md](https://github.com/user-attachments/files/15888155/service-header-navigation-scratch.md)

**Comment by CharlotteDowns** [comment]
@calvin-lau-sig7 Should we create a new backlog item for Service header navigation and Help users to navigate a service?

**Comment by CharlotteDowns** [comment]
We need to add a new layout template to allow both the component examples to be within the `<header>`

**Comment by querkmachine** [comment]
@CharlotteDowns We might want to hold off on doing that, as recent discussions in Slack have been around removing the Service Header from the `<header>` element, as having it there is proving quite verbose for screen reader users.
