### ISSUE TITLE
Understand and document existing variables, triggers, and tags

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-design-system#3853]
## What

Gather a list of the [variables](https://tagmanager.google.com/#/container/accounts/341497290/containers/8094879/workspaces/1000024/variables), [triggers](https://tagmanager.google.com/#/container/accounts/341497290/containers/8094879/workspaces/1000024/triggers), and [tags](https://tagmanager.google.com/#/container/accounts/341497290/containers/8094879/workspaces/1000024/tags) we currently use on Google Tag Manager and document what they're used for.

## Why

To get a picture of how things are set up right now so we can decide what to replicate as is, what to change and what to drop in GA4

## Who needs to work on this

Developers

## Who needs to review this

Developers
## Done when

- [ ] We have a document/spreadsheet/other-format where we can review what is set up and what for

**Comment by owenatgov** [comment]
We've finished documenting our tags, triggers and variables in their current form [in this spreadsheet](https://docs.google.com/spreadsheets/d/1iKMYn1cAZ91OZGZpfEZ5ynHOTrv1Liwgg2g77fT1hl8/edit?pli=1&gid=610987860#gid=610987860) (internal only)
