### ISSUE TITLE
Decide on data structure for events in GA4

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-design-system#3854]
## What

Design a data structure for the events we'll be collecting in GA4. The [performance analysts migration guide](https://docs.data-community.publishing.service.gov.uk/guides/implement-ga4/#decide-what-do-you-want-your-data-to-look-like) encourages to use a similar structure as [GOV.UK's events](https://docs.publishing.service.gov.uk/analytics/schema.html) for consistency across services.

## Why

GA4 is more flexible regarding the shape of events collected, so we need to decide on how we'll structure ours

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] We have agreed on a structure for the analytics events we'll send to GA4

**Comment by patrickpatrickpatrick** [comment]
I made a spreadsheet of proposed event structure based on existing GOV.UK event structure. It can be added to later but for now it's a good enough starting point to be able to close this issue.
