### ISSUE TITLE
Arrange for the team to attend the accessibility audit in-person

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3862]
## What
DAC have offered the team the opportunity to attend the audit in-person at their testing centre in Neath, South Wales.

## Why
To get first hand experience of our work being tested.

## Who needs to work on this
Kelly or Charlotte

## Who needs to review this
DAC

## Done when
- [ ] we know who is attending
- [ ] we have shared these details with DAC

**Comment by querkmachine** [comment]
@CharlotteDowns Is this good to close now?
