### ISSUE TITLE
Verify that GTM keeps respecting user's consent for collecting data

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-design-system#3863]
## What

GTM is currently set to:
- only collect data when users have accept cookies in the cookie banner
	- [checking that cookies are set on page load before injecting the GTM snippet](https://github.com/alphagov/govuk-design-system/blob/main/src/javascripts/application.mjs#L34-L37)
	- [enabling analytics when users accept cookies in the banner](https://github.com/alphagov/govuk-design-system/blob/b3223714d8f2e9564b7e9d2ca703a3f902bf1ce8/src/javascripts/components/cookie-banner.mjs#L95)
- [stop collecting if people disable cookies on the cookies page](https://github.com/alphagov/govuk-design-system/blob/b3223714d8f2e9564b7e9d2ca703a3f902bf1ce8/src/javascripts/components/cookies-page.mjs#L94)
- [start collecting if people enable cookies on the cookies page](https://github.com/alphagov/govuk-design-system/blob/b3223714d8f2e9564b7e9d2ca703a3f902bf1ce8/src/javascripts/components/cookies-page.mjs#L94)

We need to make sure this keeps happening when set up for GA4. Noticeably, we have [some code to disable/enable collection](https://github.com/alphagov/govuk-design-system/blob/main/src/javascripts/components/cookie-functions.mjs#L177-L186) using `ga-disable-<MEASUREMENT_ID>` which might need looking into.

## Why

To keep respecting people's consent and privacy

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [x] We have the same safeties around GA4 as we had around UA to protect people's privacy.

**Comment by owenatgov** [comment]
We've rearchitected our consent in https://github.com/alphagov/govuk-design-system/pull/3866 and https://github.com/alphagov/govuk-design-system/pull/3868. Currently we still have UA and GA4 cookie management running in parallel to ensure nobody is getting reported to either property if they've withdrawn consent.

With this in mind I suggest leaving this open for now. On July 1st when our UA properties are shut down OR if we shut them down ourselves beforehand, we can then remove UA bits from our consent code.

**Comment by owenatgov** [comment]
Change of plan: closing this as the cleanup work can be done as part of https://github.com/alphagov/govuk-design-system/issues/3870
