### ISSUE TITLE
Migrate search queries tracking to GA4

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-design-system#3865]
## What

Set up tracking of search queries for GA4, for now alongside the UA tracking. It may be that events already get sent to GA4 as the code for tracking [search queries uses the dataLayer](https://github.com/alphagov/govuk-design-system/blob/main/src/javascripts/components/search.tracking.mjs). If it does, we'll need to devise some strategy to have the new format sent to GA4 and the old format to UA.

## Why

So we can keep tracking how users search on the Design System website once we have migrated to GA4

## Who needs to work on this

Developers

## Who needs to review this

Developers

## Done when

- [ ] Events related to search are collected by both UA and GA4 😊

**Comment by patrickpatrickpatrick** [comment]
This has been done on Google Tag Manager without needing any code modification.
