### ISSUE TITLE
Finalise design, spacing and function (week 1 / 2)

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#3873]
## What
Interogate the design in detail and make any final adjustments

## Why
To refine the design of the components to deliver the best thing we can at this point in time based on what we know.

## Done when
- [x] Documented Design suggestions from the working group
- [x] Reviewed the design on desktop
- [x] Reviewed the design on mobile
- [x] Completed design actions discussed in [Navigation decision log](https://docs.google.com/spreadsheets/d/1zduTR-kZc5j28PFMi98-KNoP8W8S-8iJtisf9nLAbIM/edit?gid=1037439525#gid=1037439525&fvid=663609223)
- [x] Suggest how to address suggestions from the working group

**Comment by CharlotteDowns** [comment]
## Design suggestions from the working group (still ongoing)
- [ ] Trial a 25% or 50% lighter tint of the #f3f2f1 grey for the Service Header Navigation bar
- [ ] Remove the link style for tabs of Navigation that are active

**Comment by CharlotteDowns** [comment]
Had a go at restyling the active tab. 

<img width="1416" alt="Active navigation link is black with black underline" src="https://github.com/alphagov/govuk-design-system/assets/56260216/472fcc68-fa44-47ed-a0b8-514f8c1ce949">

**Comment by selfthinker** [comment]
Regarding restyling the active tab to increase differentiation between other nav items, when the active item as a link and a non-link are both black, there won't be any differentiation anymore between being a link and not being a link.

**Comment by CharlotteDowns** [comment]
I've started building a table of screenshots of what our current version of the Navigation contribution would look like across services, using [the x-gov.uk list of services ](https://govuk-digital-services.herokuapp.com/)as a starting point.

### [Here is the document, Navigation in service examples](https://docs.google.com/document/d/1O2wmEVwMbQQricW2P8hs5ofuUrsC6QJqaXjcj6EUbVU/edit#heading=h.w649hylvn2pt)

**Comment by CharlotteDowns** [comment]
I have written [a proposal for the actions](https://docs.google.com/document/d/17zNS4dkZ6QnOaIY0-AxU4pKNLzdupTzfjcAmV0-_bk0/edit?pli=1#heading=h.u10u29dk2rip) I think we can take in order to build confidence with the working group.
