### ISSUE TITLE
Consider adding a section on 'navigation vs task lists' to better illustrate use case for navigation

### ISSUE THREAD

**Issue by calvin-lau-sig7** [alphagov/govuk-design-system#3909]
## What

In the 'Help users navigate a service' pattern, add some information to help services decide whether they need navigation – and suggest task list as an alternative if appropiate.

From working group member:
> I feel like there must be something around services that use task lists here. Could this be used in conjunction with a service that uses a task list or not? Not sure. There needs to be more thought around this and how they relate to task lists before I can see this going into the design system.

[Working Draft Guidance Google document](https://docs.google.com/document/d/1lpnrD3Dv2PUHqxPx6bBZDGSWosjlUeBuU1Go90gAHSk/edit#heading=h.7o9egbqanjt)

## Why

Currently header and navigation assume that services have already decided, however some guidance can help services avoid unclear and unnecessary navigation menus.

## Who needs to be involved

Content designer, interaction designer

## Who needs to review

Team

### Tasks
- [x] Decide whether to do
- [x] Gather information
- [x] Draft content in guidance document
- [x] Review content
```

**Comment by selfthinker** [comment]
I reviewed the draft guidance. The only feedback I left on two places was regarding making it clearer that neither navigation nor task list is necessary if your service consists of only a single end-to-end journey.
