### ISSUE TITLE
Order posters, banners to signpost event at venue

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3927]
## What
Design and order wayfinding and informational posters for the event. Include display items that can be reused for other events (stands, sandwich boards etc)

**1x A1 Design System Day 2024 poster**
To be displayed outside the venue at the entrance. Venue will provide frame for this.

Order from Solopress and deliver to Chris B-T address. Order by 9 August.

**3x reusable Design System Day pull up banners**
One will be displayed in the social / catering area, plus two in the main auditorium. This is so attendees and any members of the public know this is a private event space.

Order from Solopress and deliver to Chris B-T address. Order by 9 August.

**10x horizontal A3 wayfinding posters**
- “Quiet room this way”
- “Auditorium this way”
- 2x “Toilets this way”
- Disclaimer for cloakroom “Design System Day Cloakroom: Belongings are left here at their own risk”
- 2x right arrows
- 2x left arrow
- Event code of conduct

The venue have brass frames we can use during the event. The venue will also print these. 

**2x horizontal A4 informational posters**
- "Design System Day: Quiet room"
- "Design System Day Green room"

Order from Solopress and deliver to Nora's address to bring up on the day.

## Why
So people can find their way around the event venue!

## Who needs to work on this
Mia, Kam

## Who needs to review this
Imran, Ciandelle, Kam or Kelly (for spend approval)

## Drive links
[For sign off](https://drive.google.com/drive/folders/1b3jQdiyo846w25fsiboRuV9ofnlqB-ac?usp=drive_link
)
## Done when
- [x] Determine wayfinding needs for the venue
- [x] Propose reusable display elements for review
- [x] Order reusable display elements
- [x] Design wayfinding signage
- [x] Cost all options and share with Kelly or Kam
- [x] Spend approved and card details received
- [x] Orders made

**Comment by mia-allers-gds** [comment]
Update on this: I've got the core elements together, they just need a bit of jazzing up. @Kam-Nijjar when would we like to send to print?

**Comment by Kam-Nijjar** [comment]
@mia-allers-gds ASAP, we have to get them delivered to WCB initially to be couriered to the venue along with any other merch
FYI - when ordering - Delivery address WCB - FAO Nora Brodian 
FYI @NoraGDS

**Comment by mia-allers-gds** [comment]
Here are the A3 wayfinding posters — **for sign off, NOT print:**
- Toilets
- Auditorium/ concert hall
- Green room
- Quiet room
- Cloakroom
- 10 minute sign
- 5 minute sign
- WIFI sign

**Comment by mia-allers-gds** [comment]
Here is a proposal for the outdoor A1 signage
[DSD24 A1 entrance signage.pdf](https://github.com/user-attachments/files/16602888/DSD24.A1.entrance.signage.pdf)

**Comment by mia-allers-gds** [comment]
Here are the A4 signs:
- Green room
- Quiet room

[DSD24 A4 info signage.pdf](https://github.com/user-attachments/files/16610168/DSD24.A4.info.signage.pdf)
