### ISSUE TITLE
Draft and publish an event code of conduct

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3933]
## What
Write and publish a code of conduct for attendees of Design System Day 2024

## Why
So attendees are aware of expected behaviour

## Who needs to work on this
@Ciandelle 

## Who needs to review this
@kellylee-gds 

## Done when

- [x] Draft is written
- [x] Draft is reviewed
- [x] CoC is published

**Comment by Ciandelle** [comment]
Hey @kellylee-gds I do have [done](https://docs.google.com/document/d/1XYVStxSyByZbtTwcnIETh-8oawYvvx1F5b1sM4ItgMQ/edit) this already done as I've just updated last year's one

**Comment by kellylee-gds** [comment]
@Ciandelle great! We're thinking of publishing it to the website but we can do that closer to the time though

**Comment by Ciandelle** [comment]
This has been done and published
