### ISSUE TITLE
Create floorplan for the venue to be added to attendee booklet

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3934]
## What
Create a floorplan to be added to the attendee booklet.

## Why
To help attendees navigate the venuw.

## Who needs to work on this
Imran

## Who needs to review this
Mia, Kelly

## Done when
- [x] floor plan designed
- [x] reviewed
- [x] put into a format appropriate for attendee booklet

**Comment by Kam-Nijjar** [comment]
Imran to contact Dan (event manager) for the floor plan
or draw a floor plan if required

**Comment by Kam-Nijjar** [comment]
email request for a floor plan sent to Dan Warburton

**Comment by Kam-Nijjar** [comment]
https://www.bopss.co.uk/meetings/bopss-2014-liverpool/floor-plan/

**Comment by mia-allers-gds** [comment]
@ImranH-GDS I've traced what I've been able to make out of the floor plan, I need a bit of help with a couple of details

**Comment by Kam-Nijjar** [comment]
All done - and Zine has been ordered
