### ISSUE TITLE
Add 'html' details example to guidance

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#396]
Often times the details component has HTML within it, we should add an example similar to:

```
{% set detailsHtml %}
We need to know your nationality so we can work out which elections you're entitled to vote in. If you can't provide your nationality, you'll have to send copies of identity documents through the post. <img src='#' class='call-out-image' alt=''/>
{% endset -%}

{{ govukDetails({
 summaryText: "Help with nationality",
 html: detailsHtml
}) }}
```

**Comment by dashouse** [comment]
Hey @nickcolley, do you think this is still relevant after the Nunjucks options table was released?

If we want to include a `html` version we should probably find an example that requires `html` for something that couldn't be achieved with `text`?

**Comment by nickcolley** [comment]
Not sure there's a need for this anymore with the options table
