### ISSUE TITLE
Edit transcripts for Design System Day event 1 videos

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#3965]
## What
Edit the transcripts for all recordings from the first Design System Day event so they are accurate.

## Why
So we can publish the videos

## Who needs to work on this
Volunteers

## Who needs to review this
Kelly

## Done when
- [x] we have edited [the Design System showcase](https://docs.google.com/document/d/1DqP9dPsXwlHiOUmhMW0dg7idA1Z2xa__J5NxswgQ-H4/edit#heading=h.l8re0we4llap)
- [x] we have edited [Vicky's session](https://docs.google.com/document/d/1jjWnF4jGAqrkBqQnGHDK-Ta_R56wzB9EI5kFhgEjCVc/edit#heading=h.l8re0we4llap)
- [x] we have edited [Daniel's session](https://docs.google.com/document/d/1sMFjz3quRBvnYTiYj77GLqpsqYRMjtyAA2vTVXxZc8U/edit#heading=h.l8re0we4llap)
- [x] we have edited [Gordon's session](https://docs.google.com/document/d/1w1RXmKfChRW8scKADV36mD_vmx6LQvMab0A7MBdPZW4/edit#heading=h.l8re0we4llap)
- [x] we have Youtube thumbnail images for all sessions
- [x] we have sent these to comms to be published

**Comment by Kam-Nijjar** [comment]
All edits completed and sent to comms to upload onto GDS Youtube

**Comment by Kam-Nijjar** [comment]
sent to comms to upload onto GDS Youtube
