### ISSUE TITLE
Write out email link for support

### ISSUE THREAD

**Issue by owenm6** [alphagov/govuk-design-system#397]
Currently on the homepage you have a mailto link for the support email. I would guess most people around Government use something like gmail or Office365. 

Maybe write out the email address as part of the link. Then people can copy it instead of it opening up the mail app on their device, and then copying it from there.

**Comment by igloosi** [comment]
@TechPunk316 can you advise on teh most elegant way to write this out?
it's this section https://design-system.service.gov.uk#support

**Comment by TechPunk316** [comment]
The GOV.UK Design System is maintained by the Government Digital Service. 

If you need help using any of the GOV.UK Design System features you can:

email govuk-design-system-support@digital.cabinet-office.gov.uk
get in touch on [Slack](https://ukgovernmentdigital.slack.com/messages/govuk-design-system) [(open in app)](slack://channel?team=T04V6EBTR&id=C6DMEH5R6)

Note: Not sure why but that 'open in Slack' link isn't working for me

**Comment by igloosi** [comment]
closing as now live
