### ISSUE TITLE
Link to prototype examples of patterns that are not in the design system

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#398]
For patterns like 'Check your answers' we could link to the prototype kit equivalent https://govuk-prototype-kit.herokuapp.com/docs/examples/check-your-answers-page

**Comment by dashouse** [comment]
Agree, but would like to carry on the "Where does patterns code live" conversation

**Comment by joelanman** [comment]
Yeah for now this is meeting a user need but really the source of truth shouldn't be the prototype kit. We need to be free to make changes there to make prototyping easier.

**Comment by igloosi** [comment]
done in https://github.com/alphagov/govuk-design-system/pull/452
