### ISSUE TITLE
Prepare speaker's information pack

### ISSUE THREAD

**Issue by NoraGDS** [alphagov/govuk-design-system#3983]
## What

Draft a speakers information pack for presenters and panel members to include event, speaker and engagement information

## Why

To give guests who will be presenting or speaking at DS Day practical information about event arrangements

## Who needs to work on this

Nora

## Who needs to review this

Ciandelle, Imran, organiser crew

## Done when

- [x] Draft information pack
- [ ] Review information pack and made amends
- [ ] Put content into event branded document
- [ ] Send information pack to speakers

**Comment by NoraGDS** [comment]
DRAFT https://docs.google.com/document/d/1iUBWlyILG6ebaV_RTRmyOPiM_hWY1LTQpLQmfvA3U8g/edit?usp=sharing

**Comment by Kam-Nijjar** [comment]
completed
