### ISSUE TITLE
Publish speaker bios on the website

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3986]
## What
Promote the event and the guest speakers 
## Why
Publicity for the event and speakers
## Who needs to work on this
Ciandelle, Imran
## Who needs to review this
Nora
## Done when
Published on all platforms
- [x] Contact speakers and get bios
- [ ] Check the bios format and make fit remit (word length etc.)
- [x] 2i bios
- [x] publish on platforms

**Comment by Ciandelle** [comment]
We're just waiting on a bio from Chris from Nomensa and this will be done :)

**Comment by Ciandelle** [comment]
Awaiting new bios from new speakers, however this is mostly done so going to close ticket
