### ISSUE TITLE
Publish full agenda and session information on the website

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3987]
## What
Full agenda to be shared ahead of the event
## Why
Promote the event and attendees are aware of the schedule
## Who needs to work on this
Imran, Ciandelle, Nora, Kelly, Kam
## Who needs to review this
SDM/PM
## Done when

- [x] Agreed timings with speaker
- [x] final agenda set
- [ ] shared on on website

**Comment by kellylee-gds** [comment]
Draft content for PR https://docs.google.com/document/d/1yOZJSoJYB-IBuBpsHCMsh2cMVvD2_VtQA1XD77_j_2s/edit

**Comment by Ciandelle** [comment]
It's on the website and looking great. Thanks to @NoraGDS for all her amazing work on the 2i process with this!
