### ISSUE TITLE
Arrange accommodation for non gov speakers

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3988]
## What
Accommodation for 1 day for speakers if required
## Why
To keep our costs down and within budget, we will organise accommodation for non-gov speakers
## Who needs to work on this
Ciandelle, Nora
## Done when

- [x] Contact non-gov speakers for accommodation requirements
- [x] Book accommodation via Nora
- [ ] notify individuals of booking

**Comment by Kam-Nijjar** [comment]
Ciandelle will send emails to non-gov speakers if accommodation required
Alexandra & 3rd panel member

**Comment by Kam-Nijjar** [comment]
Booked for Chikako Masuda

**Comment by Ciandelle** [comment]
Emails sent to Alessandra Ballina and Chris Lightfoot, asking if they want accommodation for one night

**Comment by Kam-Nijjar** [comment]
1 night booked Chika Masuda £88
1 night booked Chris Lightfoot £88
1 night booked Alessandra Balliana £132

**Comment by Kam-Nijjar** [comment]
@NoraGDS to change Chris Lightfoot's accommodation for Zainab Daodu

**Comment by Ciandelle** [comment]
all non-gov speakers are now booked
