### ISSUE TITLE
Document check in process for attendees and prepare registration sheet

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3989]
## What
Check-in process for attendees to capture who has attended the event.  (Eventbrite)
## Why
Reception people and back-up team members need to be made aware of the process to capture attendees
## Who needs to work on this
Ciandelle, Nora
## Done when

- [x] Ciandelle to set up a meeting with team members on reception and any further volunteers
- [x] Everyone is aware of the process
- [x] Answer any questions for the reception check-in process

**Comment by Kam-Nijjar** [comment]
Unable to do via the app - Ciandelle will follow up for future events (Eventbrite for Organisers - rejected by Information Assurance in 2019)
Ciandelle will set up Eventbrite show-and-tell

**Comment by Ciandelle** [comment]
This was done in the [show and tell](https://drive.google.com/file/d/1aI_wcLp6vkHSJby22JelgAo_Tby-30rZ/view), check in team can have a secondary session if the team feels this is necessary? @kellylee-gds @Kam-Nijjar

**Comment by Kam-Nijjar** [comment]
@Ciandelle as suggested - can we do a session during one of our L & D sessions

**Comment by NoraGDS** [comment]
I think this ticket is something different to the eventbrite. It's how we'll manage the check in and registration at the front desk on the day.

**Comment by Ciandelle** [comment]
Full attendee list is also on the Access needs / Dietary Requirements spreadsheet, most up to date export has been added 30/8

**Comment by Kam-Nijjar** [comment]
export attendee sheet Tuesday 3/09

**Comment by Kam-Nijjar** [comment]
completed
