### ISSUE TITLE
Draft and send joining instructions to attendees

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#3995]
## What
Write and send joining instructions to attendees 

## Why
So that they know where to go and any instructions they may need to follow.

## Who needs to work on this
Ciandelle 

## Who needs to review this
@NoraGDS 

## Done when

- [x] Instructions have been written 
- [x] Instructions have been updated to include any new updates needed for the event
- [x] Instructions have been 2i'd
- [ ] Instructions have been sent/scheduled to be sent

**Comment by Kam-Nijjar** [comment]
update with google links - map/agenda/start time etc.

**Comment by Ciandelle** [comment]
Done and sent on 30/8
