### ISSUE TITLE
Who from SMT will be attending, and allocating tickets (Ciandelle following up) and check they have T-shirts

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#4000]
## What
Ask members of DSP SMT who is attending and ask if they have T-shirts from last event

## Why
So that we have some additional support from senior management

## Who needs to work on this
Ciandelle 

## Who needs to review this
Anyone in team

## Done when

- [x] DSP SMT invited
- [x] DSP SMT confirmed
- [x] we get confirmation of t-shirts ownership

**Comment by Ciandelle** [comment]
Tim P and Will P are attending, we won't have enough t-shirts for at least one of these attendees, do we want to tell them to come in their own clothes?

**Comment by Ciandelle** [comment]
All done, message sent on 30/8 to confirm that neither should wear Design System Day t-shirts as it would identify them as volunteers.
