### ISSUE TITLE
Low colour contrast of focused links in the contact panel

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#402]
> The usage of .app-contact-panel on various pages uses a .govuk-link:focus link focus style #005ea5 on #ffbf47 which has a color contrast ratio of 4.07:1. I believe #0055a5 is the closest color that maintains 4.50:1.

As originally reported by @AutoSponge in https://github.com/alphagov/govuk-design-system-backlog/issues/55#issuecomment-400029693

**Comment by nickcolley** [comment]
We're intending to fix this alongside https://github.com/alphagov/govuk-frontend/issues/944
