### ISSUE TITLE
Create a vocabulary list for captions

### ISSUE THREAD

**Issue by NoraGDS** [alphagov/govuk-design-system#4035]
## What

Create a vocabulary list of peoples names and specialist terms to be included in the captions programming

## Why

This will help the auto generated captions to correctly produce words like names or specialist terms

## Who needs to work on this

Nora

## Done when

- [x] Compile terms
- [x] Send list to MSP (Sam)

**Comment by NoraGDS** [comment]
https://docs.google.com/document/d/1bWjPD_mABem7-_1UqhK-l4MCiY2L1qEKPQohEdfRSsY/edit

**Comment by Kam-Nijjar** [comment]
completed
