### ISSUE TITLE
Rename grey bar to 'Service navigation'

### ISSUE THREAD

**Issue by CharlotteDowns** [alphagov/govuk-design-system#4038]
## What

We are renaming the Service header navigation component to Service navigation. 

## Why

As part of the 'agile' version release we are prioritising the navigational aspects to the new 'grey bar' component.

## Done when
- [x] Change in [guidance doc](https://docs.google.com/document/d/1lpnrD3Dv2PUHqxPx6bBZDGSWosjlUeBuU1Go90gAHSk/edit#heading=h.dgvb6zxdostq)
- [x] Change name in new pull request of guidance
- [x] Double check all links to this component use the right name 
- [x] Add rationale to Github discussion 'Why have we called it Service navigation'

**Comment by calvin-lau-sig7** [comment]
Moved last backlog writing item to #4052
