### ISSUE TITLE
Investigate what changes to make for using the new Service Navigation component

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-design-system#4085]
## What

Investigate and build a spike of changes we'd need to make for using the new [Service Navigation component](https://design-system.service.gov.uk/components/service-navigation/). The aim is to understand if possible to use the new component considering the bespoke feature the Design System site has, especially:
- what to do with the search bar, currently in [our custom header](https://github.com/alphagov/govuk-design-system/blob/main/views/partials/_header.njk)
- distinguishing between a navigation item representing the current page itself or a parent of the current page, which we don't do at the moment
- how to do with our current navigation which offers two levels on mobile, with accordion for expanding/collapsing

## Why

Now we've released a new component to help users navigate, it'd be great to use it for our own site, unless our bespoke features prevent us to.

## Who needs to work on this

Developers, mostly, but designer/content folks will likely need to be involved when looking at the mobile navigation

## Who needs to review this

Developers, mostly, but designer/content folks will likely need to be involved when looking at the mobile navigation

## Done when

We've documented either:
- [ ] The changes we could tidily implement to use the Service Navigation component
- [ ] What's preventing us to use the Service Navigation component at the moment

**Comment by CharlotteDowns** [comment]
Also tracked by Update Design System website to use Service navigation component #4239

**Comment by romaricpascal** [comment]
Closing so we only track through #4239
