### ISSUE TITLE
Stats on attendees, diversity

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#4102]
## What
Check last year's list of attendees and this year's for the number of attendees (consolidate). For repeat non-attender's decide action for future events (do we cancel their tickets)
## Why
The event is taxpayer's money and we want the right people to attend
## Who needs to work on this
Kelly/Nora
## Who needs to review this
Imran/Kelly
## Done when

- [x] Consolidate list for 2024
- [x] Check list for 2023/2024 for regular non-attenders
- [ ] decide how we will move forward for future events

**Comment by Kam-Nijjar** [comment]
List of attendees and non-attendees
https://docs.google.com/spreadsheets/d/1Q3_47HSzQUEL91NiFJZtmQ05w-_mi2DWL96dt77lSzk/edit?gid=286017687#gid=286017687
334 people registered to attend on the day (guests not speakers or staff)
duplicates marked as ‘no’ in blue
speakers at end of list
team volunteers not included (can add as have the data)
several people came without eventbrite registrations - either swapping with a colleague or a guest of a speaker

**Comment by kellylee-gds** [comment]
[Attendee metrics here](https://docs.google.com/spreadsheets/d/19y1YyEfL-Kne5yFjKuNStpA0UbtPBTXeGiOI7QHlZ58/edit?gid=0#gid=0) (restricted document).

Diversity information not available.
