### ISSUE TITLE
Add Open Graph meta tags to pages

### ISSUE THREAD

**Issue by Nooshu** [alphagov/govuk-design-system#415]
Very minor update that the team may want to add. Missing og:title and og:description according to this automated tool: https://richpreview.com/?url=https://design-system.service.gov.uk/. There may be other og tags that would be worth considering too (og:url, og:image, og:url, og:type).

It also gives an idea of what the shared link looks like below the results.

**Comment by igloosi** [comment]
https://trello.com/c/1efxP93R/1139-social-media-sharing-tweaks

**Comment by dylmye** [comment]
The following file needs to be changed: https://github.com/alphagov/govuk-frontend/blob/master/package/template.njk
