### ISSUE TITLE
Failed to load resource: https://design-system.service.gov.uk/javascripts/iframeResizer.map

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#417]
_From @davehaigh on June 29, 2018 14:23_

I'm getting a failed to load resource error 404 : https://design-system.service.gov.uk/javascripts/iframeResizer.map 

Using a MacBook, safari 11.1.1. 

Example page it's occurring on: https://design-system.service.gov.uk/components/panel/ 

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/23551105/42097507-337d188a-7bb0-11e8-8ef4-c81f754a69ff.png">

_Copied from original issue: alphagov/govuk-design-system-backlog#143_

**Comment by igloosi** [comment]
this file is for debugging.
either we copy it fo that folder from node_module package or modify the js to remove the line where it's being called
