### ISSUE TITLE
Make contact with prioritised services in Top 75 list and plan research sessions

### ISSUE THREAD

**Issue by Katrina-Birch** [alphagov/govuk-design-system#4172]
## Brief
We believe the services in CDDO's Top 75 list have great potential as candidates for testimonials on the value of the Design System, as well as helping us understand how teams use our products and what training needs exist.

We'll first need to identify which services in the Top 75 list we'd like to learn more about. Then we'll need to identify an appropriate contact in those services teams to arrange a research session.

In the research we'd like to understand:
- how / if they use the Design System
- what blockers they experience when using our products
- how they communicate with other digital teams in their department
- how they engage with the design system community
- whether they are potential candidates for testimonials

At the end of this cycle, we should have:
- identified which services we want to make contact with first
- liaised with our contact in CDDO to make contact with service owners / product managers / leads in those service teams
- created a research brief with clear objectives

Ideally we'd like the research sessions to take place in cycle 11 (4-22 Nov). These can be arranged during this brief once contact has been made with each service team.

## Epic lead
Katrina

## Supporting roles
Trang, Kelly — to identify which services to prioritise in the first cohort.
```[tasklist]
### Tasks
- [ ] https://github.com/alphagov/design-system-team-internal/issues/911
- [ ] https://github.com/alphagov/govuk-design-system/issues/4216
```

**Comment by Katrina-Birch** [comment]
Kelly's suggestions of services to approach, Monday 14th October.

Apply for a deceased person’s military record (Ministry of Defence)
Pay your Self Assessment (HMRC)
Claim Attendance Allowance (DWP)
Sign up for flood warnings (DEFRA)
Renew your driving licence (DfT / DVLA)

Rationale:
I've mostly gone for variety and where the most interesting learnings could be.
We rarely get to speak to digital folks at the MoD
Self-assessment is within HMRC tax portal which might be interesting to learn about as it seems different teams manage different services within it. It'd be interesting to understand how they manage consistency for all services in the portal
Claim attendance allowance is a smaller DWP service compared to others in that department — does this impact them?
I think flood warnings uses other DSP products as well — potential joint testimonials
Driving services are a real mixed bag - some are GOV.UK branded, some aren't. I think it'd be interesting to talk to DVLA about how they manage their digital services to better understand the inconsistency

**Comment by Katrina-Birch** [comment]
Trang's amendments:

I'm thinking of these 2 to replace similar one on your list 
 Simply because [CDDO are already speaking to them and it might be logistically easier.
Book a theory or practical driving test - this might be interesting. According to the CDDO spreadsheet, they are trying to improve the journey for deaf users. They are not [gov.uk](http://gov.uk/) branded and don’t Design System, but are presumably struggling with accessibility.
Apply for child benefits - they recently moved from paper based to fully digital and are on v5.4. There’s probably lots we can learn about how they use the Design Systems to build their services, especially in today's context.

**Comment by Katrina-Birch** [comment]
I'm hoping to speak to Ireti Olugwagbemi with GOV.UK app on Tuesday who is also working with the Top 75. James Peart is keen not to overwhelm services with requests as engagement will go through them.

**Comment by kellylee-gds** [comment]
Next brief: #4251
