### ISSUE TITLE
Submit a budget request for event 3

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#4177]
## What
Estimate total cost for event 3 and submit request to DSP SMT for approval.

## Why
To get budget sign-off so we can proceed with procuring suppliers (platform)

## Who needs to work on this
Kelly 

## Who needs to review this
Imran, SMT, DD, DSP

## Done when
- [x] costs have been estimated
- [x] estimate has been shared with SMT
- [x] decision has been made and shared with squad

**Comment by Kam-Nijjar** [comment]
tea/coffee/merch and lunch for budget request

**Comment by Kam-Nijjar** [comment]
Kelly to request £300 for event 3 to cover costs

**Comment by kellylee-gds** [comment]
Blocked whilst awaiting a response from SMT.
