### ISSUE TITLE
Explain why the header example is in French before example

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-design-system#419]
As a user browsing the Page template page, it's not immediately obvious why one of the examples is in French.

<img width="650" alt="screen shot 2018-07-02 at 11 45 18" src="https://user-images.githubusercontent.com/23356842/42159950-7c349c6c-7ded-11e8-9e71-24a3cbb4b93b.png">

I think we need to have an introductory paragraph above this example to explain what it's illustrating.

**Comment by igloosi** [comment]
fixed with #427
