### ISSUE TITLE
Edit transcripts and publish videos from Design System Day 2024 event 2

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#4192]
## What
Edit the transcripts for all recordings from the face to face Design System Day event so they are accurate.

## Why
So we can publish the videos

## Who needs to work on this
Nora

## Who needs to review this
Gareth Pryce, Lucky Nwosu (comms)

## Done when
- [x] we have edited Greg Macoy's talk
- [x] we have edited Chika's talk
- [x] we have edited the content panel recording
- [x] we have edited Duncan's talk
- [x] we have edited Michael & Alessandra's dual narrative recording
- [x] we have edited Ishmael's talk
- [x] we have Youtube thumbnail images for all sessions
- [x] we have sent these to comms to be published

**Comment by Kam-Nijjar** [comment]
https://docs.google.com/spreadsheets/d/1GoB91TII6Rp6NtDXxQA_bdIjwgw4CaDMk39Pz67dkdQ/edit?gid=1503972698#gid=1503972698
[Captions edited
](https://docs.google.com/document/d/147zStxS6LzFF5rMtjM6PAiOc_HEP-4VjKwL-pthtzkI/edit?tab=t.0)

**Comment by Kam-Nijjar** [comment]
sent to lucky.nwosu@digital.cabinet-office.gov.uk in comms team
