### ISSUE TITLE
DS monthly chat November/December Christmas special 24

### ISSUE THREAD

**Issue by Kam-Nijjar** [alphagov/govuk-design-system#4266]
## What
Set up and prepare for the November/December Christmas special for 2024 Design System monthly chat

## Why
The event is a proactive use of everyone's time and effort

## Who needs to work on this
Imran, Mia, Kelly, Trang, Romaric & Kam

## Who needs to review this
Imran & Kelly

## Done when

- [ ] Slide deck prep
- [x] Topic agreed with team leads
- [ ] Team members on rotas are aware of their role
- [ ] Do we need volunteers  
- [ ] Call for speakers if required
- [ ] Eventbrite set up and sent out
- [ ] Set up padlet for the event if required

**Comment by Kam-Nijjar** [comment]
leads meeting 05/11/24
[leads meeting notes](https://docs.google.com/document/d/1doE00b_YSum7rgNXO4c3ivM6TQR29Ack893yMVTTt2U/edit?tab=t.0)

**Comment by Kam-Nijjar** [comment]
[Christmas wish list Padlet board](https://govukdesignsystem.padlet.org/kamnijjar1/christmas-special-design-system-monthly-chat-december-2024-5fr5xtsjqaybz3mo)

**Comment by Kam-Nijjar** [comment]
Draft [slide deck](https://docs.google.com/presentation/d/1DICG7SwyrMaaM_utIZEEEB6a9-gEvO73XMogWbVf8PY/edit#slide=id.g30fd158124a_1_8)

**Comment by Kam-Nijjar** [comment]
date changed to 10th December 2024

**Comment by kellylee-gds** [comment]
This has been cancelled due to team capacity
