### ISSUE TITLE
Update the website's accessibility statement

### ISSUE THREAD

**Issue by owenatgov** [alphagov/govuk-design-system#4269]
## What and why
Update our [accessibility statement](https://design-system.service.gov.uk/accessibility-statement/) following work to address the 2024 DAC audit of the GOV.UK Design System website and our investigations revisiting known issues with vendors. Specific things for us to update are:

- the [Other identified and tracked accessibility concerns section](https://design-system.service.gov.uk/accessibility-statement/#other-identified-and-tracked-accessibility-concerns) where we can potentially remove or amend the 2 listed GOV.UK Frontend concerns and may want to add concerns for the website for issues we decided we weren't going to fix.
- anywhere on the site we mention WCAG 2.1 compliance, now that we can confidently say we're 2.2 compliant.

## Who needs to work on this
Accessibility specialist

## Who needs to review this
content designer

## Done when

- [x] Updates to do to the statement have been decided
- [x] Updates have been drafted
- [ ] Updates have been published

**Comment by selfthinker** [comment]
PR created: https://github.com/alphagov/govuk-design-system/pull/4322
