### ISSUE TITLE
Signage for the day

### ISSUE THREAD

**Issue by mia-allers-gds** [alphagov/govuk-design-system#4279]
Figure out how to sign post people to the hack day
- Downstairs reception roller banner
- GDS reception roller banner and desktop sign in notice
- Garage signage
- Info on where the quiet room, prayer space and toilets are
- Board game social

**Comment by Kam-Nijjar** [comment]
Inc wifi info / code of conduct etc

**Comment by mia-allers-gds** [comment]
[DSD Hackday posters.pdf](https://github.com/user-attachments/files/17828507/DSD.Hackday.posters.pdf)

**Comment by mia-allers-gds** [comment]
Hopefully the final posters for print, @NoraGDS 

Please print the 'Hackday posters' at A3, the rest can be done A4 I think

[DSD Hackathon door signs.pdf](https://github.com/user-attachments/files/17868878/DSD.Hackathon.door.signs.pdf)
[DSD Hackday posters.pdf](https://github.com/user-attachments/files/17868879/DSD.Hackday.posters.pdf)
[Pizza signs.pdf](https://github.com/user-attachments/files/17868880/Pizza.signs.pdf)
