### ISSUE TITLE
Design System does not use same structure for 'beforeContent' examples.

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#428]
From the X-GOV Slack channel:

> Hey. I found another example where the kit and online instructions don't match in a way that helps a newbie like me. I end up having to search around and scratch my head a lot. 

> On the question page (https://design-system.service.gov.uk/patterns/question-pages/) it has the full html and nunjunks for how to create the page. However, I'm using the kit so the neither the html or the nunjunks work for what I need. E.g. it is not clear where I would put my back link when using the proto kit as the structure isn't the same. Luckily in this instance the kit has a version of the Question page and I can see where the back link goes. However, not all instances can be found in both.

> For me it would be useful to see a version of the page on the website using the kit format alongside the full HTML and full Nunjunks version. Am I making sense?!

---

> it is not clear where I would put my back link when using the proto kit as the structure isn't the same.

With the question page example we have a Nunjucks example: (https://design-system.service.gov.uk/patterns/question-pages/)

```
{% from "back-link/macro.njk" import govukBackLink %}
{% from "date-input/macro.njk" import govukDateInput %}
{% from "button/macro.njk" import govukButton %}

<div class="govuk-width-container">

{{ govukBackLink({
  text: "Back"
}) }}

  <div class="govuk-main-wrapper">
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <form action="/form-handler" method="post">

          {{ govukDateInput({
            id: "dob",
            name: "dob",
            fieldset: {
              legend: {
                text: "What is your date of birth?",
                isPageHeading: true,
                classes: "govuk-fieldset__legend--xl"
              }
            },
            hint: {
              text: "For example, 31 3 1980"
            },
            items: [
              {
                name: "day"
              },
              {
                name: "month"
              },
              {
                name: "year"
              }
            ]
            })
          }}

          {{ govukButton({
            text: "Continue"
          }) }}
        </form>

      </div>
    </div>
  </div>
</div>
```

However in the kit we are using 'beforeContent'.

We could update examples to look something like:

```
{% from "back-link/macro.njk" import govukBackLink %}
{% from "date-input/macro.njk" import govukDateInput %}
{% from "button/macro.njk" import govukButton %}

{% beforeContent %}
{{ govukBackLink({
  text: "Back"
}) }}
{% endblock %}

{% content%}
    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <form action="/form-handler" method="post">

          {{ govukDateInput({
            id: "dob",
            name: "dob",
            fieldset: {
              legend: {
                text: "What is your date of birth?",
                isPageHeading: true,
                classes: "govuk-fieldset__legend--xl"
              }
            },
            hint: {
              text: "For example, 31 3 1980"
            },
            items: [
              {
                name: "day"
              },
              {
                name: "month"
              },
              {
                name: "year"
              }
            ]
            })
          }}

          {{ govukButton({
            text: "Continue"
          }) }}
        </form>

      </div>
    </div>
  </div>
{% endblock %}
```

The 'beforeContent' was introduced so users did not have to understand the wrapper elements, is it more complicated now? Or if these examples are consistent will that address this problem?

**Comment by dashouse** [comment]
but 'beforeContent' was added after all of the examples were already made...

**Comment by igloosi** [comment]
wip #430

**Comment by nickcolley** [comment]
Will keep this in my mind but we have solved the initial problem with: https://github.com/alphagov/govuk-design-system/pull/444
