### ISSUE TITLE
Is there anything useful we can add to Updating your code page for $gutter?

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#431]
$gutter is a variable in Frontend Toolkit. If users are moving from that to Frontend, is there a useful section of the design system we can point them at to replace $gutter in their code?

**Comment by igloosi** [comment]
i guess that `$gutter` is now `$govuk-gutter`

https://github.com/alphagov/govuk-frontend/blob/master/src/settings/_measurements.scss

**Comment by igloosi** [comment]
having thought about it, i don't think `gutter` would have been customised and used across pages, like say for example class names.

**Comment by dashouse** [comment]
It's a good point, we really only use `$govuk-gutter` as a variable for the actual grid now, where as it was often used as a variable within other components to hang off the grid spacing as a unit.

I don't think any of the components use `$govuk-gutter` in this way, if they do they should probably be updated to use the spacing scale.

**Comment by joelanman** [comment]
So what should we say to users who were using $gutter in their own code, in the old world?

**Comment by dashouse** [comment]
They can use `$govuk-gutter` and `$govuk-gutter-half` if they just want to swap like for like...but I'd suggest they switch to to use the spacing scale...

If they want static 30px spacing `margin-bottom: govuk-spacing(6)`
If they want responsive 30px / 20px spacing `@include govuk-responsive-margin(6, "bottom");`
