### ISSUE TITLE
Should we make it clear that by Slack we mean cross-govenment slack?

### ISSUE THREAD

**Issue by igloosi** [alphagov/govuk-design-system#433]
cc @amyhupe

**Comment by amyhupe** [comment]
where are you referring to?

**Comment by igloosi** [comment]
get in touch on Slack

**Comment by joelanman** [comment]
Some screenshots for reference

Home page:
![image](https://user-images.githubusercontent.com/1132904/42509988-7c0607f4-8445-11e8-86b8-0085075aee8e.png)

Feedback page:
![image](https://user-images.githubusercontent.com/1132904/42510022-8c642c16-8445-11e8-81c0-a8b49488a242.png)

**Comment by amyhupe** [comment]
Do we have evidence to suggest this is causing confusion?

**Comment by igloosi** [comment]
two zendesk tickets from non-gov domains asking for access

**Comment by nickcolley** [comment]
I think this is a wider question, should we be using a closed slack channel?

**Comment by igloosi** [comment]
closing as there are wider questions as outlined above
