### ISSUE TITLE
Google is showing unexpected titles in search results

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#445]
If you search for 'gov.uk design system checkboxes' you get this title in Google:

**Components Checkboxes - Checkboxes – GOV.UK Design System**

Similarly, a search for 'gov.uk design system typography' gets:

**Styles Typography - Typography – GOV.UK Design System**

Google appears to be combining the H1 and the Title on these pages, not sure why.

Scroll down to 'Why the search result title might differ from the page's <title> tag'
https://support.google.com/webmasters/answer/35624

**Comment by joelanman** [comment]
As an aside, are 'Styles Typography' or 'Components Checkboxes' good H1s? They read slightly unclearly to me, I'd find just 'Typography' or 'Checkboxes' clearer, personally.

**Comment by igloosi** [comment]
needs someone with access to Google Search Console

**Comment by nickcolley** [comment]
This doesnt seem to be an issue for the patterns "gov.uk design system confirmation" googled gets me the title as I'd expect.

Maybe if we updated the component titles to be "Button component - GOV.UK Design System", that'd be enough.

**Comment by 36degrees** [comment]
I believe Google is trying to 'merge' the H1 with the page title. I can't work out for the logic for this – it's done inconsistently for both components and patterns:

<img width="653" alt="screen shot 2018-07-25 at 09 07 13" src="https://user-images.githubusercontent.com/121939/43187740-353888a0-8fea-11e8-92a4-103e6c600a0c.png">

<img width="657" alt="screen shot 2018-07-25 at 09 06 49" src="https://user-images.githubusercontent.com/121939/43187735-321e256c-8fea-11e8-8866-5a9122253987.png">

In most use cases the caption is distinct from the page title, and shouldn't be treated as part of it. From talking with @dashouse we think we should move the caption spans outside of the `H1` across the board, so:

```html
<h1 class="govuk-heading-xl">
  <span class="govuk-caption-xl">govuk-caption-xl</span>
  govuk-heading-xl
</h1>
```

becomes:

```html
<span class="govuk-caption-xl">govuk-caption-xl</span>
<h1 class="govuk-heading-xl">govuk-heading-xl</h1>
```

I've tested this in the Frontend review app and moving the span outside of the h1 makes no difference to the way the caption and heading are presented.

I think this would fix the issue.

Thoughts?
