### ISSUE TITLE
Grouped components in the components pane

### ISSUE THREAD

**Issue by simonneb** [alphagov/govuk-design-system#494]
I really like that the Patterns are now ["grouped" in the left hand pane](https://design-system.service.gov.uk/patterns/) into categories based on use cases. It makes it far easier to find the appropriate pattern.

Could a similar grouping be applied to the (growing) list of components? I have had a crack at grouping them:

**Navigation**

- Back link
- Breadcrumbs
- Skip link
- Tabs

**Interaction**
- Button
- Checkboxes
- Date input
- Fieldset
- File upload
- Radios
- Select
- Text input
- Textarea

**Information**
- Details
- Error message
- Error summary
- Footer
- Header
- Inset text
- Panel
- Phase banner
- Table
- Tag
- Warning text

**Comment by dashouse** [comment]
Hi Simon,

Thanks for raising this. 

During both Discovery and Alpha phases of the Design System we tried many different ways to categorise the components and patterns. We ran card sorting exercises, an online tree test and lots of rounds of usability research sessions. 

While there was some common groupings from the card sort and tree test we found many usability issues when the components were grouped into themes. For some components the groupings were very obvious, however for a significant amount of components the themes actually caused a barrier to finding them.

This was down to a few reasons:

a) For something like Accordions, we consider this to only be used for navigation purposes, however most people would expect this to be within an "expandables" group. There were plenty of examples of this type of thing

b) When themes contain a lot of items it's not obvious there is more than one theme within a section. Users looked at the alphabetised list within a theme, didn't see the thing they were looking for and navigated to a different section.

c) There was almost always a "leftovers / misc" theme with items that didn't really fit neatly into any particular theme ended up

For these reasons we decided to have a single alphabetical list for the components section.

Regarding the change to Patterns, this was a slightly different way to cut the content. Previously we tried noun-based themes, such as "form inputs" however patterns by their nature are based around a specific user scenario. 

We decided verb based theming for the majority of patterns would help, the alphabetical organisation wasn't doing us as many favours in the patterns section as the components as most of the patterns were "Ask", "Help" or "Check" something. Hence moving to themes around "Ask users for..." and "Help users to..."  so the main content such as "Email address" has more prominence.

The exception to all of this is actually the "Pages" section within patterns. It's not an ideal solution and have considered moving back to this being it's own section, which is something we tried in a previous round.

You can see some of our early prototypes using category themes here - https://govuk-design-system-prototypes.cloudapps.digital/ u: designsystem p: prototype — I believe the most recent version using them was v6.

We will be continually reviewing the navigation, we may well look at component themes again as the product matures.

**Comment by dashouse** [comment]
Closing this issue for now, if you have any more questions about it please feel free to re-open
