### ISSUE TITLE
Update the Task List pattern with issues we've heard from the community

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#517]
There are various issues people have found with the Task List.

https://github.com/alphagov/govuk-design-system-backlog/issues/72

Should we update the Research section of the pattern with these?

**Comment by ignaciaorellana** [comment]
@amyhupe and I have collected the feedback from the GitHub issue in the community backlog. It contains:
- A summary
- Known issues and gaps
- A list of services using the pattern
- Next steps

We've also included the "discuss" link in the research section as well to encourage more conversations. 

What would be the next steps for this? @joelanman @amyhupe

**Comment by joelanman** [comment]
Research has been added to the page, and an action added to the github thread
