### ISSUE TITLE
Conditional reveal radio component has aXe errors

### ISSUE THREAD

**Issue by injms** [alphagov/govuk-design-system#524]
The aXe accessiblity tool flags two issues when using the conditional reveal radio component. Running aXe on the [example page](https://design-system.service.gov.uk/components/radios/conditional-reveal/index.html) shows the following issues:

---

#### Elements must only use allowed ARIA attributes

```markup
<input class="govuk-radios__input" id="how-contacted-conditional-1" name="how-contacted" type="radio" value="email" aria-controls="conditional-how-contacted-conditional-1" aria-expanded="false">
```

To solve this violation, you need to:

Fix the following:

 - ARIA attribute is not allowed: aria-expanded="false"

#### Radio inputs with the same name attribute value must be part of a group

```markup
<input class="govuk-radios__input" id="how-contacted-conditional-1" name="how-contacted" type="radio" value="email" aria-controls="conditional-how-contacted-conditional-1" aria-expanded="false">
```

To solve this violation, you need to:

Fix at least one (1) of these issues:
 - All elements with the name "how-contacted" do not reference the same element with aria-labelledby
 - Fieldset contains unrelated inputs

---

I think the expected behaviour would be to have no critical issues flagged by aXe - unless this is a false alarm or is found not to have any impact after testing in the empathy lab.

**Comment by nickcolley** [comment]
I have moved this issue, thanks for raising :)
