### ISSUE TITLE
User testing on BBC tabs

### ISSUE THREAD

**Issue by detlevhfischer** [alphagov/govuk-design-system#526]
Hi,
I hope this is the right place - I had promised to include the BBC tabs in out next user testing. Had a test with a relatively unskilled long-time blind (or nearly blind) iPhone user which I have uploaded here on Youtube:
https://www.youtube.com/watch?v=6lVLHGOsylU
I hope you can work out what happens without me translating the German captions...

**Comment by ignaciaorellana** [comment]
Thanks for sharing this @detlevhfischer this is very useful! I have moved the comment to our community backlog under 'tabs' https://github.com/alphagov/govuk-design-system-backlog/issues/100#issuecomment-418424158
