### ISSUE TITLE
Header element doesn't allow expanding the menu on mobile

### ISSUE THREAD

**Issue by alex-ju** [alphagov/govuk-design-system#532]
### Steps to reproduce
1. Go to: https://design-system.service.gov.uk/components/header/with-service-name-and-navigation/index.html
2. Resize for a mobile viewport
3. Click menu button

### Result
The menu expands and contracts

### Expected result
The menu expands and stays expanded until further interaction

### Preview

<details>
<summary>Show animated preview (fast-moving image)</summary>

<img src="https://user-images.githubusercontent.com/788096/45310621-afed2200-b51e-11e8-8faa-d209073968d8.gif" alt="kapture 2018-09-10 at 17 25 42">
</details>

### Note
I would self assign myself to investigate and raise a PR, but I don't have permissions

**Comment by 36degrees** [comment]
Will be fixed by https://github.com/alphagov/govuk-frontend/pull/994.

**Comment by 36degrees** [comment]
I've hidden your preview behind a `<details>` because it was making my eyes hurt – hope that's OK with you! 😁🙈

**Comment by 36degrees** [comment]
(Also, thanks very much for raising this! Funnily enough, I think we must have spotted it at pretty much the same time. Sorry for the terse initial reply, rushing to wrap everything up at the end of the day…!)

**Comment by alex-ju** [comment]
I was looking into it and realised the default type is the cause of it.
Thanks for fixing it @36degrees! Faster that expected, definitely 🥇

**Comment by igloosi** [comment]
This has been with in #565
