### ISSUE TITLE
Change link in blog post to redirect to 'community' section 

### ISSUE THREAD

**Issue by ignaciaorellana** [alphagov/govuk-design-system#535]
The link in this blog post https://gds.blog.gov.uk/2018/06/22/introducing-the-gov-uk-design-system/  is broken as we no longer have a "https://design-system.service.gov.uk/community/how-you-can-contribute/" page. We need to redirect to the 'community' section in the Design System:

https://design-system.service.gov.uk/community/

Issue raised by a user through Zendesk

**Comment by kellylee-gds** [comment]
Email sent to GDS blog owner to amend.

**Comment by igloosi** [comment]
post has been updated with the correct link

**Comment by nickcolley** [comment]
Thanks @kellylee-gds, there's another issue to explore doing redirects better in the future: https://github.com/alphagov/govuk-design-system/issues/536
