### ISSUE TITLE
Figure out process for updating and redirecting URLs

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#536]
## What
Ideally we should be redirecting URLs when we change them so we do not break the web.

This could be done with something like https://github.com/aymericbeaumet/metalsmith-redirect

I'm not sure how we'd remember to do this, maybe there's an automated way to warn people when they're changing URLs for existing documents...?

## Why
TBC

## Who needs to know about this
Developers, Stephen

## Done when

**Comment by dashouse** [comment]
Closing for now, we will address this when it becomes a problem

**Comment by nickcolley** [comment]
For what it's worth I think I raised this based on a problem where we failed to redirect and broke our initial blog post link: https://github.com/alphagov/govuk-design-system/issues/535

**Comment by nickcolley** [comment]
Ran into this when looking to remove the cookies page
