### ISSUE TITLE
Search aliases are case sensitive

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#580]
I believe that is just in the matching for the output in the UI, and that the search index itself is not case sensitive since even though you cannot see the aliases in with a capital, it shows something that is aliased.

<img width="343" alt="screen shot 2018-10-12 at 12 56 01" src="https://user-images.githubusercontent.com/2445413/46867847-406c9a00-ce1e-11e8-8928-efbef8f5af35.png">
<img width="335" alt="screen shot 2018-10-12 at 12 55 56" src="https://user-images.githubusercontent.com/2445413/46867849-406c9a00-ce1e-11e8-9ef8-9ef72796d227.png">

**Comment by igloosi** [comment]
yeah, i guess best to compare both in lowercase 
<img width="679" alt="screen shot 2018-10-12 at 13 09 53" src="https://user-images.githubusercontent.com/3758555/46868437-3f3c6c80-ce20-11e8-859b-613a39fd5e34.png">
