### ISSUE TITLE
Add "phone" as an alias of "telephone" in the "Telephone numbers pattern

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-design-system#583]
Add "phone" as an alias of "telephone" in the "Telephone numbers pattern

<img width="345" alt="screen shot 2018-10-15 at 11 38 58" src="https://user-images.githubusercontent.com/23356842/46946212-eca4bf80-d06e-11e8-91d8-a32130d17f51.png">

Submitted by a user through Zendesk

**Comment by igloosi** [comment]
ideally we'd have  `wildcard: lunr.Query.wildcard.LEADING | lunr.Query.wildcard.TRAILING` but that produces a lot of results
![search](https://user-images.githubusercontent.com/3758555/46948699-d8fd5700-d076-11e8-8df2-6c896578c57a.gif)

**Comment by joelanman** [comment]
Maybe 'phone number' should be the main title, and 'telephone number' the alias?

![image](https://user-images.githubusercontent.com/1132904/47007962-41107380-d131-11e8-8564-19a7b55fcb1a.png)

**Comment by joelanman** [comment]
Given the GOV.UK Style guide uses 'Telephone number', and Google very probably finds 'telephone' when you search for 'phone', maybe we just stick with 'Telephone' and add 'Phone' as an alias, as originally suggested.

**Comment by igloosi** [comment]
this was already resolved it seems in #584

<img width="324" alt="screen shot 2018-10-31 at 11 13 52" src="https://user-images.githubusercontent.com/3758555/47784651-1fe97e80-dcfe-11e8-8384-132b4ea39000.png">
