### ISSUE TITLE
Department names probably shouldn't be headings

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#604]
In the research section, department names are h4s. This means they appear as headings in VoiceOver, but they're not really headings for sections of content (screenshot below). Maybe we could use `<strong>` instead

![screenshot of voiceover rotor](https://user-images.githubusercontent.com/1132904/47371520-e43c2c80-d6df-11e8-9eb8-243c70a21a49.png)

**Comment by joelanman** [comment]
I used this on Step by step:

```
**Driver and Vehicle Standards Agency**<br/>
Learn to drive a car

**Department for Work and Pensions**<br/>
Employ someone<br/>
What to do when someone dies

**UK Visas and Immigration**<br/>
Visit the UK on a Standard Visitor visa

**Department for Transport**<br/>
Get a Blue Badge
```

**Comment by dashouse** [comment]
PR here https://github.com/alphagov/govuk-design-system/pull/650 - Closing this issue
