### ISSUE TITLE
Run aXe on the GOV.UK Design System

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#620]
When we last got the Design System website audited, we found a lot of the issues would have been caught with running aXe on the pages.

I'm not sure we wrote up an issue for this and I think it's important to do automating testing where possible.

Note: This is the design system website itself, not the GOV.UK Frontend components.

**Comment by Jagordon** [comment]
Found a 'critical' issue on the Radio buttons with conditional reveal component 

> Fix the following:
ARIA attribute is not allowed: aria-expanded="false"
