### ISSUE TITLE
Examples in the Design System without code tabs are displaying an empty box

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#622]
Below the example box there's now an empty panel - this should not appear.

![image](https://user-images.githubusercontent.com/1590604/47996850-d7610500-e0f1-11e8-8e79-830e7a33dfc2.png)

**Comment by igloosi** [comment]
@nickcolley i' have a solution of you're working on this

<img width="843" alt="screen shot 2018-11-06 at 08 49 28" src="https://user-images.githubusercontent.com/3758555/48052845-fc608100-e1a0-11e8-9c5b-0f48132d6b38.png">
