### ISSUE TITLE
In page navigation causes page to break in Safari

### ISSUE THREAD

**Issue by dashouse** [alphagov/govuk-design-system#624]
In Safari 11.1.2 (and also an earlier version I have at home)

In-page anchor links within styles > layout / typography / spacing cause the entire page to jump, not just the main content pane. The header and navigation disappear and cannot be scrolled back to. The user will need to refresh in order to carry on navigating the site.

<img width="1493" alt="screen shot 2018-11-06 at 09 22 18" src="https://user-images.githubusercontent.com/23356842/48054601-962a2d00-e1a5-11e8-9734-f17403457335.png">

**Comment by igloosi** [comment]
something to do with fixed layout, as it doesn't happen here https://center-layout--govuk-design-system-preview.netlify.com/styles/layout/#example-combinations
