### ISSUE TITLE
Broken links in backlog markdown files

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#630]
In https://github.com/alphagov/govuk-design-system-backlog/blob/master/docs/CONTRIBUTING.md there's a few links that don't go to the right place.

**Comment by igloosi** [comment]
@nickcolley is this the right repo for it?

**Comment by nickcolley** [comment]
@igloosi no but I dont want to clutter the backlog issues since they are used for backlog stuff.

**Comment by igloosi** [comment]
https://github.com/alphagov/govuk-design-system-backlog/pull/172

**Comment by igloosi** [comment]
merged
