### ISSUE TITLE
Versioning releases of the Design System

### ISSUE THREAD

**Issue by holloway** [alphagov/govuk-design-system#674]
When it comes to versioning releases I'd appreciate a machine-readable versioning system... perhaps expressed using `package.json`'s `version` property?

(a very short Issue, but there isn't much else to say)

**Comment by 36degrees** [comment]
Hi Matthew,

Thanks for raising this. Just in case it's not clear, the Design System (which is just the _guidance_) is not currently versioned – it's continuously deployed whenever the `master` branch changes.

The actual code that teams would use in their service can be found in [GOV.UK Frontend](https://github.com/alphagov/govuk-frontend) which _is_ versioned as you'd expect.

Does that help?

Thanks,

Ollie

**Comment by dashouse** [comment]
Closing as the issue creator has reacted with 👍
