### ISSUE TITLE
Improve the way we acknowledge contributions

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#689]
## What

We need a fair and consistent approach to acknowledging contributions to the Design System. We've done some thinking about this but we need to finish the work and document it.

Contributions include things like:
- new components or patterns
- ports of GOV.UK Frontend
- pull requests for bug fixes
- content updates
- users research

## Why

Acknowledging contributions is a way to thank people for volunteering their time. It improves the contribution experience and makes people more likely to contribute again. It also lets other potential contributors see that contribution is possible, making them more likely to volunteer themselves.

## Tasks

- [ ] Develop a process for acknowledging contributions
- [ ] Document the process

## Related links

- [Draft process doc](https://docs.google.com/document/d/1WW1c61MHr04BbO9X7KRBw5WWpt3JTGPvbcyV-bLkW5M/edit)

**Comment by trang-erskine** [comment]
Contributors are acknowledge in release notes and Slack messages.
