### ISSUE TITLE
Decide on and document our approach to smaller external contributions

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#690]
## What

We have a well established process for supporting and assuring contributions of whole new components or patterns. We don't yet have one for people who want to make an improvement to an existing thing. We want our users to understand that we value all forms of contribution, large or small, and help them know how to go about doing this.

## Why

Doing this will lower the barrier for people who want to make contributions, will help us increase the amount of contribution we get, and will help make our community of contributors more representative.

### Must
- [x] Decide which contributions need to be reviewed by cross-government working group
- [x] Create a journey map for making changes or updates to existing things

### Should
- [x] Support content designers to fix small issues

### Could
- [ ] Find a way to turn backlog findings into changes/guidance (close the gap)

**Comment by kellylee-gds** [comment]
Closed issue as its in the done column on the Kanban board
