### ISSUE TITLE
Decide on and document our approach to internal contributions

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#691]
## What

We need to explain how we decide to develop styles, components or patterns within the team, and how we assure them.

## Why

We've already done this a few times. To be fair and transparent we need a consistent process, and to make this process public

### Must

- [x] Decide criteria for when things should be developed internally
- [x] Decide how internal contributions should be assured
- [x] Publish guidance explaining the decisions above

**Comment by kellylee-gds** [comment]
Closed issue as its in the done column on the Kanban board
