### ISSUE TITLE
Update the Design System page templates

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#699]
## What

Update the Design System page templates so that:

- they have a fixed width
- the left navigation isn't sticky

## Why

Doing this work will bring the Design System more in line with the standard GOV.UK page templates, and will improve the accessibility of the Design System. 

## Done when

- [x] No flexbox layout on IE isn't broken
- [x] JS for back to top has been refactored
- [x] Browser tested

**Comment by dashouse** [comment]
Closing as this work is complete
