### ISSUE TITLE
Iterate our contribution model

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#700]
## What

Iterate our contribution model, based on:

- the team contribution retro
- the diversity and inclusion survey ideation session
- [the contribution and assurance ideation session](https://docs.google.com/document/d/19a0lR6ip5nlqdqnbXeTQyeoTq72WGNCIaNUw_yZXLSM/edit)

## Stories

- [ ] create a 'to-be' journey map for contribution
- [ ] write and prioritise stories

**Comment by kellylee-gds** [comment]
@timpaul @amyhupe Amy & I spoke about this yesterday. Moving this to the backlog as not priority for next sprint. Will need to look at this before March working group review session

**Comment by timpaul** [comment]
Duplication of [#154](https://github.com/alphagov/design-system-team-internal/issues/154)
