### ISSUE TITLE
Develop a process for reviewing content in the Design System and backlog

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#702]
## What
Develop a process for reviewing content in the Design System and backlog.

## Why
Now that the Design System and backlog have been public for 6 months, we need a process for regularly reviewing content in them, to make sure that it's still relevant and true.

### Done when

We've decided when and how:
- [ ] content in the Design System is reviewed
- [ ] backlog items are reviewed
- [ ] experimental labels are removed
- [ ] experimental label are added
- [ ] content is retired
- [ ] to communicate any updates we make

**Comment by trang-erskine** [comment]
Covered in other tickets and activities the team is doing.
