### ISSUE TITLE
Copy button perfectly obscures markup

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-design-system#704]
I wanted to see the class applied on something in the design system - but the copy button perfectly aligns to prevent reading it. Wider my screen didn't help - as the class I wanted was always on the far right.

![copy-button-in-the-way](https://user-images.githubusercontent.com/2204224/51199618-22b44280-18ef-11e9-8138-f19887e7a570.gif)

Suggestion: Move the button so it doesn't overlap with text. The text content area already has quite a bit of padding - so there may be space on the edge. Else it could go in the tab with the two language selectors?

**Comment by aliuk2012** [comment]
This was also picked up in the last Accessibility audit (see page 38)

**Comment by aliuk2012** [comment]
Another accessibility issue identified in the audit:

> The ‘copy’ link is not descriptive to users that rely on audio feedback and navigate out of
the context of the page.

**Comment by nickcolley** [comment]
We've addressed the immediate problems, and may update this again in the future, thanks for the help :)
