### ISSUE TITLE
December analytics report

### ISSUE THREAD

**Issue by Daisy25** [alphagov/govuk-design-system#705]
## What
Analyse December's analytics data

## Done when

- [x] Analyse the data
- [x] Look at action notes from last month
- [x] Prepare the datastudio dashboard
- [x] Present findings

**Comment by kellylee-gds** [comment]
@Daisy25 is there anything further to do on this card (like follow up actions from the show & tell) or can I move it to "Done"?

**Comment by Daisy25** [comment]
I'll move it to Done & create a series of new cards for the new questions that came up

**Comment by kellylee-gds** [comment]
Closed issue as its in the done column on the Kanban board
