### ISSUE TITLE
User needs for the GOV.UK Design System

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#719]
This issue tracks the high level user needs for the GOV.UK Design System.

When all the items are checked we'll know that the service is ready to go live.

#### 01. I can see that live services are successfully using the Design System

- [x] 1.1 The Design System is being used by live services
- [x] 1.2 There are case studies explaining how teams have used the Design System

#### 02. I can find the styles, components and patterns that I need to design my service

- [ ] 2.1 The most needed components and patterns have been published
- [x] 2.2 New or updated components and patterns can be published as needed
- [x] 2.3 People can easily find things that have been published in the Design System
- [ ] 2.4 People can easily find things that are still being worked on
- [ ] 2.5 People can easily find out when something new has been or will be published

#### 03. I can be confident that everything in the Design System is usable and accessible

- [x] 3.1 There are published criteria for usability and accessibility
- [x] 3.2 Components and patterns are independently assured against those criteria
- [x] 3.3 Everything in the Design System has been tested against WCAG 2.1
- [ ] 3.4 The most needed components and patterns are no longer experimental

#### 04. I can use the Design System products with minimal support from the Design System team

- [ ] 4.1 People can use components and patterns in their prototype or service
- [ ] 4.2 People can install the Prototype Kit and make a simple prototype
- [ ] 4.3 People can integrate GOV.UK Frontend into their codebase

#### 05. I can get additional design and technical support when I need it

- [x] 5.1 The products are well supported by a permanent team
- [x] 5.2 People can get support from the community when they need it

#### 06. I can easily develop and share my own components and patterns

- [ ] 6.1 There’s an open standard for developing your own components and patterns
- [ ] 6.2 There’s guidance on how to develop your own components and patterns
- [ ] 6.3 It’s easy to install custom components in your prototype or service

#### 07. I can easily migrate my service to use the Design System

- [ ] 7.1 There’s guidance on how to migrate your service to GOV.UK Frontend
- [x] 7.2 There’s a case study explaining how a team migrated to GOV.UK Frontend

#### 08. I can easily update my service to the latest version of the Design System

- [ ] 8.1 There’s guidance on how to update GOV.UK Frontend
- [x] 8.2 There’s guidance on how to update the Prototype Kit
- [ ] 8.3 The process of updating the Prototype Kit is simple
- [ ] 8.4 It’s easy to see what’s changed in each version of GOV.UK Frontend

#### 09. I can easily contribute back to the Design System

- [ ] 9.1 People know how they can contribute to the design system
- [ ] 9.2 People can easily make successful contributions

#### 10. I can pass a service assessment using the Design System

- [ ] 10.1 Services that use the Design System have passed assessments
- [ ] 10.2 Teams understand how the Design System is used to assess services
- [ ] 10.3 Assessors understand how to use the Design System to asses services

**Comment by trang-erskine** [comment]
Documented elsewhere https://docs.google.com/spreadsheets/d/12dIae75aAiGy28ZLVAK8Z58ZouZx1f5OV0N-y6kSe0M/edit#gid=0
