### ISSUE TITLE
Plan and prepare for the Working Group Session

### ISSUE THREAD

**Issue by amyhupe** [alphagov/govuk-design-system#722]
## What

Plan the working group session on 31 January and prepare an agenda. 

## Why

We are not taking any contributions to review during this session, so we need to plan an agenda to follow instead. 

## Who needs to know about this
Amy, Tim, team

## Further detail

We'd like to use the session to:

- discuss the results of the backlog prioritisation exercise we asked the group to do using a [Google form](https://docs.google.com/forms/d/1cfe-SxrcqdKQUhqKqJZ5HGZ9vDQ4RMjeXaw5UCixVCw/edit#responses)
- propose a process for assuring changes / additions / updates to the Design System (ie smaller forms of contribution than whole components or patterns) and get agreement from the group

## Done when

- [x] reminder to complete the form sent out on 28 January
- [x] all responses to the form received
- [x] process for assuring changes drafted
- [x] process for assuring changes reviewed by Design System team
- [x] discussion guide / agenda prepared

**Comment by kellylee-gds** [comment]
Closed issue as its in the done column on the Kanban board
