### ISSUE TITLE
Blog about Design Resources Discovery

### ISSUE THREAD

**Issue by amyhupe** [alphagov/govuk-design-system#723]
## What

Write a blog about the design resources discovery we carried out in November 2018, describing the research, findings, the workshop on 6 December and next steps.

## Why

The research we carried out has impacted our roadmap for the next 12 months and will affect our users and people we work with across government.

We should blog about this work so they know what we learned, how we're planning to address the needs we identified, and to help government design system authors know what's expected. 

## Who needs to know about this

Amy, Tim

## Done when

- [x] Blog post drafted
- [x] Post reviewed and approved by @timpaul 
- [x] Post reviewed and approved by Head of Design
- [x] Post reviewed and approved by creative team
- [x] Blog published

**Comment by kellylee-gds** [comment]
Closed issue as its in the done column on the Kanban board
