### ISSUE TITLE
Plan and run Learn GitHub for content designers training session

### ISSUE THREAD

**Issue by amyhupe** [alphagov/govuk-design-system#725]
## What

Run a [GitHub training session for content designers](https://www.eventbrite.co.uk/e/learn-github-for-content-designers-tickets-55155944916?aff=eemailordconf&utm_campaign=order_confirm&utm_medium=email&ref=eemailordconf&utm_source=eb_email&utm_term=viewevent) as part of Services Week.

## Why

We want to enable more people to contribute, and to make it easier to make smaller contributions to the Design System.

By training content designers to use GitHub, we'll:

- raise awareness of the Design System and the fact you can contribute to it
- encourage a more diverse group of people to contribute (most of our previous contributors have been developers and interaction designers)
- remove one of the technical / confidence barriers to contribution
- use the session to create a step-by-step guide to raising PRs to help more people contribute

## Who needs to know about this

Amy, Nick

## Done when

- [x] Agree a session structure
- [x] Send out invitation (Both)
- [x] Write agenda with timings (Both)
- [x] Write step by step guide for updating content (Nick)
- [x] Book time to pilot instructions with a content designer (Amy)
- [x] [Create issues to use in the session](https://github.com/alphagov/govuk-design-system/issues?q=is%3Aissue+is%3Aopen+label%3A%22Learn+GitHub+for+content+designers%22) (Both)
- [x] Draft introduction slides (Both)
- [x] Book time to review slides (Both)
- [x] Enlist volunteers for the session (Both)
- [x] Close tickets end of Friday (Nick)
- [x] Email reception a list of attendees (Tim)
- [x] Email attendees to remind them to setup a GitHub account, get GovWifi / tether on phone, bring laptop (Both)
- [x] Session has been run (Both)

**Comment by kellylee-gds** [comment]
Closed issue as its in the done column on the Kanban board
