### ISSUE TITLE
Updating sass-exports npm module breaks lib/colours.js

### ISSUE THREAD

**Issue by aliuk2012** [alphagov/govuk-design-system#731]
# First timers only
This issue is reserved for people who have never contributed to the GOV.UK Design System before, please only pick this up if you're a new contributor.

## Description
After updating sass-exports (`npm install sass-export@1.0.3`), when you try run `npm test` or `npm start` the following error appears:

> TypeError: Cannot read property 'reduce' of undefined

paletteMap is returning `undefined` and therefore on [this line](https://github.com/alphagov/govuk-design-system/blob/master/lib/colours.js#L28) `reduce` method fails.

If you remove `.mapValue` (https://github.com/alphagov/govuk-design-system/blob/master/lib/colours.js#L25), paletteMap returns a value but not in the correct format.

### 1. Claim this issue

Comment below to let other people know that you're working on this issue.

### 3. Edit [`colours.js`](https://github.com/alphagov/govuk-design-system/blob/master/lib/colours.js) file

`palette` should set to 

```json
{
  "black":"#0b0c0c",
  "blue":"#005ea5",
  "bright-purple":"#912b88",
  "bright-red":"#df3034",
  "brown":"#b58840",
  "green":"#006435",
  "grey-1":"#6f777b",
  "grey-2":"#bfc1c3",
  "grey-3":"#dee0e2",
  "grey-4":"#f8f8f8",
  "light-blue":"#2b8cc4",
  "light-green":"#85994b",
  "light-pink":"#f499be",
  "light-purple":"#6f72af",
  "orange":"#f47738",
  "pink":"#d53880",
  "purple":"#2e358b",
  "red":"#b10e1e",
  "turquoise":"#28a197",
  "white":"#ffffff",
  "yellow":"#ffbf47"
}
```

### 5. Done

We'll review the Pull Request and let you know if any changes are needed.

## Questions

If you’ve got a question, you can comment in this issue or email the Design System team on [govuk-design-system-support@digital.cabinet-office.gov.uk](mailto:govuk-design-system-support@digital.cabinet-office.gov.uk)

**Comment by fearn2001** [comment]
I think I've done it but I can't create a pull request.

**Comment by cmccrea23** [comment]
Hello! Has anyone completed this task yet? I'm happy to help 😄

**Comment by aliuk2012** [comment]
Hi @cmccrea23,

If you would like to pick this up then please feel free to work on it.

So sorry @sog01, some how we missed your message but seeing as its been almost a month, I'm assuming you might not be available to work on this which is why I offering it to @cmccrea23.

Thank you to all you have volunteered 👏

**Comment by nickcolley** [comment]
Hey everyone,

I've had a look into this issue and it seems like the [issue is in the sass-exports library and should be fixed there](https://github.com/plentycode/sass-export/pull/53) rather than our application.

We’re going to close this issue now as we no longer think it’s something that could easily be picked up and worked on.

If you're still interested in learning how GitHub works, [we have some content related issues that you might want to pick up](
https://github.com/alphagov/govuk-design-system/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22).

Nick
