### ISSUE TITLE
Add Dragon bug to date input guidance

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#782]
https://github.com/alphagov/govuk-frontend/issues/1101 is not a problem with our implementation but with Dragon and [it's been reported to them](https://github.com/alphagov/govuk-frontend/issues/1101#issuecomment-449400420). We should try to reproduce this to confirm the Dragon versions and browsers affected and then document the problem. I spoke to Amy and we agreed that it would be good to put this under "Known issues and gaps" in the date input guidance, [similar to what we do with the character count](https://design-system.service.gov.uk/components/character-count/#known-issues-and-gaps).

**Comment by 36degrees** [comment]
I think once we've tackled https://github.com/alphagov/govuk-frontend/issues/1449 we can close this without updating the guidance as the Dragon bug will no longer affect the date input component.

**Comment by 36degrees** [comment]
As documented in https://github.com/alphagov/govuk-frontend/issues/1101 this has now been fixed, so we do not need to document it.
