### ISSUE TITLE
Expand error message / validation guidance

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#783]
We've had queries (for instance [here](https://github.com/alphagov/govuk-design-system-backlog/issues/47#issuecomment-432396823)) on the reasoning behind [When not to use error messages](https://design-system.service.gov.uk/components/error-message/#when-not-to-use-this-component), specifically in terms of why we error messages shouldn't be shown before user submits the form. This will probably keep coming up since many frameworks and libraries implement client side validation.

Should we consider expanding on the reasoning in the guidance? The reasons discussed [here](https://github.com/alphagov/govuk-design-system-backlog/issues/47#issuecomment-432589332) seem valid. Additionally, we could mention that since any necessary validation will need to be also done on the server, this could lead to duplicated effort and extra work in ensuring that the client and server validation rules stay in sync.

**Comment by stevenaproctor** [comment]
@hannalaakso Happy to take a look at updating the guidance based on the comments in [error message](https://github.com/alphagov/govuk-design-system-backlog/issues/47).

**Comment by 36degrees** [comment]
We should also document our stance on in-browser validation, as discussed in #522 (this came up again today on x-gov Slack)

**Comment by paulwaitehomeoffice** [comment]
Also known as HTML5 validation (which is what I unsuccessfully searched for here, trying to find documentation).

**Comment by adamszymaszczyk** [comment]
Our team supports services which have client-side and service-side form validation. We validate forms on submission only, not on field focus change as some comments mention.

I would like to see a page discussing GDS stand on client-side validation as it will help the team to decide on the future of our client-side validation.

**Comment by joelanman** [comment]
Started a draft on validation guidance here, comments welcome:
https://docs.google.com/document/d/1vRy53ybNsI_JusO35Gqm7VFzSvhW1oByEUNIR1AtTtI/edit#
