### ISSUE TITLE
Make it easier for users to find things in the community backlog

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#788]
## What
Help users find the work in progress and valuable discussions in the backlog more easily, by exposing more of the backlog in the Design System (for example, in navigation or search results)

## Why
We know that there's a lot of valuable content in the backlog, but that not everyone knows about it or finds it easy to navigate.

**Comment by edwardhorsford** [comment]
I don't know if this is relevant - but 6 weeks back in to government, I'm still rather fuzzy _which_ repo I should be looking in for these things. This one, frontend, govuk-design-system-backlog.

I imagine there's a split between bugs and commenting on patterns and components - but mostly I just guess and visit each one in turn.
