### ISSUE TITLE
Write guidance for multiple form submission feature

### ISSUE THREAD

**Issue by amyhupe** [alphagov/govuk-design-system#797]
## What

We need to document [a new feature](https://github.com/alphagov/govuk-frontend/pull/1018) which allows services to prevent multiple form submissions when a user double clicks.

## Why

The feature is opt-in, so services need to know that it's available, as well as why and when to use it. 

## Who needs to know about this
Amy, Nick

## Further detail

Initially we're thinking this should live at the bottom of the buttons page as that's where a user will need to include the feature.

## Done when

- [x] guidance drafted
- [x] fact-checked by developer
- [x] 2i by second content designer / tech writer
- [x]  guidance published

**Comment by kellylee-gds** [comment]
Closed issue as its in the done column on the Kanban board
