### ISSUE TITLE
Example page templates are too wide

### ISSUE THREAD

**Issue by edwardhorsford** [alphagov/govuk-design-system#798]
The [example page templates](https://design-system.service.gov.uk/styles/page-template/custom/index.html) appear to have the wrong site width. I'm pretty sure the default should be 960px unless something has changed since I left.

**Comment by dashouse** [comment]
Nice catch, the examples aren't actually set to this size. If you used them in your app they would be 960px. The design system has overridden the width variable for the general layout and it's affected the full page examples un-intentionally.

**Comment by edwardhorsford** [comment]
In our case I'd referred my devs to it as an example to compare our app against - a reference implementation. It's fine now we know the width is an error.
