### ISSUE TITLE
Kick off Prototype Kit information architecture work

### ISSUE THREAD

**Issue by amyhupe** [alphagov/govuk-design-system#799]
## What

Following the Prototype Kit discovery in November 2018 and recent discussions, we want to kick off a piece of research to better understand what it would take to move the kit's docs into the Design System, and the impact on our users.

## Why

Moving the documentation into the Design System, although quite a bit of work in the short-term, would have a number of long-term benefits for us as a team and, indirectly, our users. For example, it would make it easier for us to track user journeys across the Design System and the kit and make improvements to the content.

However, we need to explore how this would work in practice, and assess the impact on both users of the Prototype Kit and the Design System before we proceed.

## Who needs to know about this

Everyone

## Further detail

- [Notes on the information architecture discussion between Joe, Tim and Amy](https://docs.google.com/document/d/1MVaDtyMUj8aZV4fwtDIpfpzyNl-WZ8pN7WTBM-YU6rA/edit?usp=drive_web&ouid=107066608114851766008)
- [Detailed plan for work](https://docs.google.com/document/d/1gb6o6x7EWsj5f2r2I5mkrJhQlkQO-kbblAXpDT9SNus/edit) 

## Done when

- [x] Team briefed on work
- [x] Team kick off meeting on 20 Feb
- [x] Sketching session run

**Comment by kellylee-gds** [comment]
Closed issue as its in the done column on the Kanban board
