### ISSUE TITLE
Kick off the Ethnicity pattern contribution

### ISSUE THREAD

**Issue by amyhupe** [alphagov/govuk-design-system#806]
## What

Have a kick off session to plan the [ethnicity pattern contribution](https://github.com/alphagov/govuk-design-system-backlog/issues/83). 

## Why

A designer from Cabinet Office has researched a way of asking for user's ethnicity as part of their service.

They have offered to contribute it to the Design System, so we need to kick off the work and make a plan of action to develop it and take it to the working group.

## Who needs to know about this

Amy, Nick, Dave

## Further detail

[The designer has already blogged about the research on design notes](https://designnotes.blog.gov.uk/2019/01/29/researching-how-we-ask-users-about-their-ethnicity/) and has been documenting their research on the backlog.

## Done when

- [x] Kick off meeting booked in
- [x] Kick off meeting had
- [x] Next steps planned in

**Comment by kellylee-gds** [comment]
Closed issue as its in the done column on the Kanban board
