### ISSUE TITLE
Kick-off cookies proposal

### ISSUE THREAD

**Issue by amyhupe** [alphagov/govuk-design-system#807]
## What

The cookies work is close to being ready, so we should have a kick off session to plan the work and discuss if it needs to go to a review session.

## Why

This work is a high priority for the organisation to ensure we are providing guidance and best practice for GDPR. 

## Who needs to know about this

Amy, Joe, the rest of the team

## Done when

- [ ] Joe has booked a kick off session
- [ ] Kick off session run
- [ ] A plan for the work is written

**Comment by joelanman** [comment]
This is on hold while we discuss with various stakeholders

**Comment by timpaul** [comment]
Closing, as this work is now being done on a different team
