### ISSUE TITLE
Write guidance on how to extend and modify components

### ISSUE THREAD

**Issue by amyhupe** [alphagov/govuk-design-system#810]
## What

Add guidance explaining how to correctly extend or modify existing components outside of the options the Design System provides.

## Why

We've had a number of queries on our support channels about how to do this, and as long as we're not providing guidance on this, there's a risk that users will do it wrong and may break something.

## Further detail

Consideration will need to be given to how we include this information in the Design System. It could be some boilerplate guidance and / or an example on every component page, or it could be a central guide that the component pages link to. 

It's probably a good idea to start with one component as an example. 

## Who needs to know about this

Pete, Hanna / Nick, Dave, Amy

## Done when

- [x] Session booked with Pete, Dave and Hanna or Nick to draft guidance
- [x] Session has been run
- [x] Guidance drafted
- [x] Amy has reviewed guidance
- [ ] Guidance published

**Comment by adamsilver** [comment]
I'm very interested in this. Things that I'd like to know about include:

1. What class names and prefixes should be used. `app-` or `hmcts-` or ?
2. With (1) if our department specific design system does this say with `hmcts-button--secondary` it seems like it should belong in “styles” as opposed to “components” like this: http://hmcts-design-system.herokuapp.com/styles/secondary-button
3. If creating a new component that depends on an existing component. For example, I've been looking at creating a currency input for HMCTS. And I'm wrestling with the following options:

a) to depend on the text input component and override bits of it.
b) to duplicate the underlying macro/html and try and keep the params for both currency input and text input the same.

**Comment by nickcolley** [comment]
Frankie: "It'd be helpful, at some point (not immediately) to have some guidance on good and bad names for components. E.g generic names like 'banner' or 'hero' might not be as descriptive as 'version-history' or 'bar-chart'?"

Something to think about in the future...
