### ISSUE TITLE
Suggested synonyms for section-break

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#818]
Just tried to search for 'separator', also 'hr' and 'horizontal rule' makes sense as synonyms.

Apparently this can't currently be done easily as Section break is a heading, not a page.

From our search stats (Dec - Feb):

6 zero results searches for 'hr'
3 for 'horizontal' or 'horizontal rule'
1 for separator (not including me :)

**Comment by nickcolley** [comment]
I also searched for 'horizontal rule', let's see if any of our users run into this too...

**Comment by 36degrees** [comment]
I've created a new issue #821 to allow us to add aliases for individual sections.

This issue is blocked until that work is done.

**Comment by querkmachine** [comment]
It looks like this was resolved in #2291, which added the 'horizontal rule' and 'hr' aliases.
