### ISSUE TITLE
Update contribution guidelines to include how we review changes to existing components and patterns

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#820]
## What
Following an [agreed approach to reviewing changes to existing components and patterns in the Design System](https://github.com/alphagov/govuk-design-system/issues/690), the team now needs to update the [contribution guidelines](https://design-system.service.gov.uk/community/) on the website.

## Why
So the information is publicly available

## Who needs to know about this
Amy

## Done when

- [ ] Thing to do

**Comment by trang-erskine** [comment]
No longer relevant. Either done or process has changed since this ticket was created.
