### ISSUE TITLE
Allow for aliases to be defined for sections within a page

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#821]
We can currently define aliases at the page level, so that users searching for e.g. 'reveal' will be able to find the details component.

We don't currently have any equivalent functionality for sections on the page, so we can't e.g. alias section break as horizontal rule.

Adding this would help us to make sections within some of our longer pages more discoverable.

**Comment by christaylor-hod** [comment]
Some feedback to add to the experience of using search:

- When searching for the override classes (i.e. ‘govuk-!-margin-bottom-9’ etc - I can never remember the format)  the only entry in the search facility is the width override (which is further down the page). I’d expect to see multiple results for the different types of override classes
- Also when I’m looking for horizontal rule, it’s listed under spacing. I think I’d expect to be able to search on the word horizontal.
- I also wondered if you’ve considered tried adding support for searching for html tags, and then listing results for any component that uses that. For example searching ‘h1’ would give me a result for the heading page

**Comment by edwardhorsford** [comment]
Like @christaylor-hod I frequently struggle to find the margin and padding override classes and the horizontal rules.

I've slowly learnt to search for 'width' to get the margin overrides, but this is somewhat counterintuitive.

**Comment by 36degrees** [comment]
Looks like this was closed by #2291 🎉
