### ISSUE TITLE
Publish an accessibility statement for GOV.UK Design System

### ISSUE THREAD

**Issue by kellylee-gds** [alphagov/govuk-design-system#824]
## What
We need to publish an accessibility statement.

## Why
There are 2 main requirements:

**meet accessibility standards** - this means making your website ‘perceivable, operable, understandable and robust’ for all users - you can achieve this by making sure it meets the international accessibility standard, WCAG 2.1 AA or its European equivalent, EN301 549

**publish an accessibility statement** - this must be based on a template statement that will be provided by early 2019

## Who needs to know about this
Amy, Tim, Mark

## Further detail
I think we could do this in a progressive way by including this as part of the "How we've made the Design System accessible" we have discussed in the team.

Potentially it might be worth linking to GitHub issues with 'accessibility' as well, as these are a dynamic up to date record of the known accessibility issues we have.

## Done when

- [x] Statement drafted
- [x] DAC retest results have been received and checked against statement
- [x] Changes made to statement if needed
- [x] 2i'd by tech writer community
- [x] Shared with accessibility compliance team
- [x] Approved by Portfolio head of product
- [x] Published statement

**Comment by hannalaakso** [comment]
We had feedback from a user. They were looking for info on `aria` attributes on components but didn't find this page in the Design System. We could consider adding a link to it to the homepage itself or even the navigation.

**Comment by amyhupe** [comment]
I haven't finished this yet, but [the draft I've started is here](|https://docs.google.com/document/d/1wjAV-_SUXwu576xa7lnZk9uGJdeb9_q0JtOqhnUC0FU/edit).

**Comment by kellylee-gds** [comment]
@m-green @amyhupe we discovered yesterday there's an additional approval process we have to go through before we publish our statement. I've added the extra steps to the 'done whens'.

**Comment by amyhupe** [comment]
Thanks Kelly 👍

**Comment by m-green** [comment]
Thanks @kellylee-gds - will we also need that step for accessibility info in Frontend?

**Comment by kellylee-gds** [comment]
@m-green I don't think so, as it isn't a 'statement' in the traditional sense.

**Comment by amyhupe** [comment]
Blocked while we work through the issues that came up in the retest
