### ISSUE TITLE
Headings immediately following a pre element don’t get a top padding

### ISSUE THREAD

**Issue by fofr** [alphagov/govuk-design-system#838]
## Example
https://design-system.service.gov.uk/get-started/extending-and-modifying-components/#small-modifications-to-components

https://github.com/alphagov/govuk-design-system/blob/91c2624ec535dfff908f27cc51570160197d1e89/src/get-started/extending-and-modifying-components/index.md.njk#L98-L104

### Screenshot
![Screen Shot 2019-03-26 at 16 31 14](https://user-images.githubusercontent.com/319055/55015383-9f952400-4fe4-11e9-9f76-5d191ca6c297.png)

## Reason
This list of styles doesn't include `pre` elements:
https://github.com/alphagov/govuk-frontend/blob/b52474c4c1c98c9886b48caafa3746bf7782859d/package/core/_typography.scss#L178-L189

**Comment by dashouse** [comment]
Hey Paul,

Thanks for raising. When we first looked at the contextual adjustments in the typography styles we somewhat drew a line under anything other than a heading or paragraph.

We expect an amount of tweaking will need to be done (using the spacing overrides) by a designer or dev based on any component or standard HTML element inserted into text content in this way.

While any component in the design system will have an additional 10px margin-bottom compared to a paragraph, the undefined HTML elements do not. This would be true of `<pre>` but also things like `<blockquote>`, `<figure>` etc so we would need to decide what would be useful.

As it stands we can make this change on the design system itself, adding some extra styling to the markdown container will not have an effect on anyone else. However I think we'd be resistant to adding it to frontend without having some better rules or guidance for components and other undefined HTML elements being included in long from text.

I'm going to close this issue, make the change to the Design System itself but keep it front of mind when we get to a larger discussion around how we might be able to apply contextual adjustments to components.

**Comment by fofr** [comment]
Thanks for the update and fix @dashouse.
