### ISSUE TITLE
Update the Design System website to use the new GOV.UK Frontend WCAG 2.1 styles and to use the new focus styles on any custom components

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#839]
Depends on https://github.com/alphagov/govuk-frontend/issues/1263

Checklist

- [ ] Include new GOV.UK Frontend styles as a pre-release
- [ ] Update any custom components to use the same focus styles

**Comment by 36degrees** [comment]
This is now covered by #956, #961, #960 and #958
