### ISSUE TITLE
Ensure that the IDs for macro options links are unique

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#848]
We currently generate the ids for the anchor links within component macro options tables from [`title`](https://github.com/alphagov/govuk-design-system/blob/add1f099c34f8632dcbda5c1cbd8e6484eb1b53b/src/components/header/with-service-name/index.njk#L2) in frontendmatter. There are some ones that are not unique which breaks the links as the same id is used multiple times on the page. See https://github.com/alphagov/govuk-design-system/issues/836

We used to use the [example parameter from the template](https://github.com/alphagov/govuk-design-system/blob/add1f099c34f8632dcbda5c1cbd8e6484eb1b53b/src/components/header/index.md.njk#L40) to do this but now that we use the frontend matter titles we should think about either having some tests to ensure that these are unique, or consider whether we should go back to using the `example` parameter as combined with `titleSuffix`, or some combination thereof.

**Comment by nickcolley** [comment]
I think this is actually fixed, the ids are now unique.
