### ISSUE TITLE
Indicate where Error summary should be placed in the page

### ISSUE THREAD

**Issue by hannalaakso** [alphagov/govuk-design-system#851]
We had a question from a user about whether the error summary should be inside or outside `<main>`. 

We should explain the placement in the guidance or have a full page example.

Edit: this has also previously come up on the backlog: https://github.com/alphagov/govuk-design-system-backlog/issues/46#issuecomment-464783199

**Comment by MattFielding** [comment]
It would also be good to add guidance on where a back link should sit when an error summary is shown. The guidance suggests both sit at the top of the page.

**Comment by kellylee-gds** [comment]
Closed as moved to done
