### ISSUE TITLE
Add guidance on errors in conditional fields

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#863]
See this thread:

https://github.com/alphagov/govuk-design-system-backlog/issues/59#issuecomment-485778739

**Comment by 36degrees** [comment]
This came up again today in a conversation in the #prototype-kit channel on x-gov Slack.

**Comment by edwardhorsford** [comment]
Came up again today - my devs asked me how it should work, and I couldn't immediately find an example for them.

In the end, I looked up a previous project, where we did it like this: 
![Screenshot 2020-11-06 at 15 01 40](https://user-images.githubusercontent.com/2204224/98380850-06901100-2041-11eb-94db-888d666af9a5.png)

**Comment by samuelholyhead** [comment]
This has come up again in HMRC live services. We are following what @edwardhorsford suggested above.

**Comment by edwardhorsford** [comment]
Here's another example from my service that's a bit different. I'm not entirely sure this was intentional, but I don't mind it.

<img width="706" alt="Screenshot 2022-01-20 at 18 00 05" src="https://user-images.githubusercontent.com/2204224/150395689-77a9ddda-42b1-41a0-975e-d9884d52dd13.png">
