### ISSUE TITLE
Write guide on new focus styles

### ISSUE THREAD

**Issue by amyhupe** [alphagov/govuk-design-system#876]
## What

Write a new guide explaining:

- WCAG 2.1 AA text and non-text contrast requirements
- how the new focus styles meet these
- that they're included in Frontend components
- how to apply them if you are not using Frontend components (in custom stuff and services not using Frontend at all)
- (maybe) how legacy mode works

## Why

- The new focus styles are more complex to apply than our existing ones so we need to clearly explain to users the principles behind them and how to apply them in practice. 

## Who needs to know

Amy, Dave, Mark, Nick

## Further detail

This needs to go live with the v3 release. 

- Amy to work with Dave on creating the guidance on the principles
- Mark to work with Nick and Dave on creating the guidance on how to apply the styles in your service

**Comment by nickcolley** [comment]
Started something for the technical side here: https://docs.google.com/document/d/1OQWSytG-Od9bI5grduEpmtVEqaKrN1xHAyq3hd9iiqY
