### ISSUE TITLE
Update colours page

### ISSUE THREAD

**Issue by amyhupe** [alphagov/govuk-design-system#877]
## What

Update the [colours page](https://design-system.service.gov.uk/styles/colour/) in the Design System to with new colours and updated guidance where necessary (e.g. focus colours)

## Why

We need to make sure the colours page reflects the current palette and that the guidance on usage is still up to date. 

## Who needs to know about this

Amy, Dave

## Further detail

This needs to go live with the v3 release

**Comment by nickcolley** [comment]
Spoke to Amy and this can be closed now that v3.0.0 is out.
