### ISSUE TITLE
Update GOV.UK Design System to use GOV.UK Frontend 3.0

### ISSUE THREAD

**Issue by aliuk2012** [alphagov/govuk-design-system#878]
## What
GOV.UK Frontend 3.0 relates to WCAG 2.1 (Focus colour, colour platte updates and more). 

## Why
GOV.UK Design System needs to be updated to use GOV.UK Frontend 3.0 so that it can help support those changes and look consistent with the new styles 

## Who needs to know about this
Dave, Tim and developer

## Done when

- [ ] Test it with a pre-release of GOV.UK Frontend 3.0
- [ ] Fix any identified issues
- [ ] Potentially write up new documentation (Might not be necessary)

**Comment by 36degrees** [comment]
I think this is either done or replaced by other cards.
