### ISSUE TITLE
Update the image on the 'Check a service is suitable' pattern

### ISSUE THREAD

**Issue by timpaul** [alphagov/govuk-design-system#879]
Update the image on the '[Check a service](https://design-system.service.gov.uk/patterns/check-a-service-is-suitable/) is suitable' pattern to that:

- it uses the new [thumbnail templates that Dave created](https://github.com/dashouse/govuk-design-system-flow-diagrams)
- it's more generic
- it can be viewed at a larger size

**Comment by nickcolley** [comment]
The thumbnail templates are used here: https://design-system.service.gov.uk/patterns/ethnic-group/ for reference.

Might want to consider moving Dave's files into this repository as well...

**Comment by Ciandelle** [comment]
An image has been created in figma and saved as a PNG file. We need is a big version that's easier to read, but not too big to download - waiting on one of the developers to advise on a good balance?

**Comment by Ciandelle** [comment]
Linked to issue #2133 - the image has now been updated and closed
