### ISSUE TITLE
Review main-wrapper guidance based on simplifications

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#887]
We may be able to simplify the guidance that explains the wrappers based on improvements in a newer version of GOV.UK Frontend, which means for many cases the large modifier can be replaced with the auto spacing modifier.

- Guidance: https://design-system.service.gov.uk/styles/layout/#page-wrappers
- GOV.UK Frontend improvement: https://github.com/alphagov/govuk-frontend/pull/1493

**Comment by nickcolley** [comment]
Need to check the release notes as we're linking to this section, for example if the heading changes.

**Comment by nickcolley** [comment]
This isnt a requirement for release, but would be nice to get done.

Removing this from the milestone...

**Comment by 36degrees** [comment]
Done in #993
