### ISSUE TITLE
Review 'Updating your code' guide for accuracy

### ISSUE THREAD

**Issue by amyhupe** [alphagov/govuk-design-system#890]
## What

Review [Updating your code](https://design-system.service.gov.uk/get-started/updating-your-code/) for accuracy.

## Why

It's likely more people will be visiting this page after we do the release of Frontend v3 and so we should make sure it's up to date and accurate.

## Who needs to know about this

A developer to review, with Mark / Amy to review any content changes.

## Further detail

We'd like to do a more comprehensive update on this guide to include more general guidance on a migration strategy, but that should be dealt with separately. This is the minimum work required for release. 

## Done when

- [x] Someone assigned to work
- [x] Check carried out
- [x] Any needed updates made
- [ ] Amy / Mark has reviewed
- [ ] Updates published

**Comment by hannalaakso** [comment]
This looks good to me, no changes needed as the APIs we list here haven't changed.

As mentioned under "Further detail" above, we'll look at improving this page separately. It would be good to link to https://github.com/alphagov/govuk-frontend/blob/master/docs/installation/installing-with-npm.md#using-govuk-frontend-with-old-frameworks to give signposts for the installation journey

**Comment by amyhupe** [comment]
Thanks Hanna.
