### ISSUE TITLE
Provide guidance on how to migrate to GOV.UK Frontend from Elements, Frontend Toolkit and Template.

### ISSUE THREAD

**Issue by amyhupe** [alphagov/govuk-design-system#892]
## What

Update the [Updating your code](https://design-system.service.gov.uk/get-started/updating-your-code/) guide with more general guidance on how to migrate from one of the older codebases to GOV.UK Frontend.

## Why

We currently have this guide on updating your code but it only shows the mapping between the old code and the new and is lacking more general guidance about how to migrate.

Though it shouldn’t block shipping, we should aim to fill this gap as close to the release as we can because:

- we have done lots of work to make the migration path easy but haven’t documented it for users 
- the updates we’re making might strengthen the incentive / need to migrate

## Who

Mark to own this, with support from a developer

## Done when 

- [ ] Run planning session to agree what the migration guidance should cover
- [ ] Updates drafted
- [ ] Content reviewed by a developer
- [ ] Tech writer 2i
- [ ] Content reviewed by Amy
- [ ] Published

**Comment by hannalaakso** [comment]
It would be great if the guidance could also take into account that services who are only partially migrating to GOV.UK Frontend and intend to continue using legacy codebases alongside for some time.

This would require:
- Stating that yes, you can do a partial migration and have GOV.UK Frontend and legacy code in the same app. Not everyone might be aware that this a thing, they might think that they have to fully migrate to GOV.UK Frontend to avoid code conflicts.
- Explaining compatibility mode, especially the colours and the font.
- Explaining the order in which order GOV.UK Frontend and legacy stylesheets and scripts should be included on the page.
