### ISSUE TITLE
Add guidance on use of maxlength

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-design-system#916]
We had a support request:

> is there any guidance on using the `maxlength` attribute on input boxes? The design system page on text inputs (https://design-system.service.gov.uk/components/text-input/) talks a lot about making them visually the appropriate size/width, but doesn't talk about restricting the number of characters you can enter

> For example, if a field can only be 30 characters long because of a legacy database column length, do you restrict the input with `maxlength`, or leave it unrestricted and catch it with form validation?

I think our recommendation would be to avoid `maxlength` and use validation. That way users get feedback if they make a mistake - `maxlength` gives no feedback.

**Comment by terrysimpson99** [comment]
In some cases the front end user input exceeds back end limit because of characters that can be discarded (e.g. extra spaces or punctuation in a postcode) before being sent to the back end. If you can do that, it's better than failing validation.

**Comment by joelanman** [comment]
another point about avoiding `maxlength` - it allows users to paste too many characters, then edit it down. `maxlength` will truncate what's pasted and the user may not even realise that's happened.

**Comment by hannalaakso** [comment]
This is related: https://github.com/alphagov/govuk-design-system/issues/1977
