### ISSUE TITLE
Review website page title content for consistency

### ISSUE THREAD

**Issue by NickColley** [alphagov/govuk-design-system#922]
While doing https://github.com/alphagov/govuk-design-system/pull/919 I realised most of our page titles are inconsistent.

Some use a format like `subcategory - category`, others are a single sentence.

This will improve the experience for users of assistive technologies: https://github.com/alphagov/govuk-design-system/issues/901

**Comment by vanitabarrett** [comment]
I think this issue is mainly talking about page titles for our component examples. Other pages in the design system follow the same pattern of "page title - GOV.UK Design System"

**Comment by querkmachine** [comment]
I've given this a quick look today.

## Content page titles

It seems that the content pages is mostly quite consistent at this point, universally being formatted as `[H1 heading text] – GOV.UK Design System`, the title not including any captions and experimental labels from the H1.

The only exception of the homepage, which doesn't use the H1 text and is instead simply titled `Home – GOV.UK Design System`. 

## Code examples

The iframes that host code examples are much less consistent in how they're titled. Just from a subset of examples checked (around 100), a few different formats being used arose: 

- `[example name] – [style/component name] – Example - GOV.UK Design System`, for example:
  - Common two-thirds – Layout – Example - GOV.UK Design System
  - Overriding input width – Spacing – Example - GOV.UK Design System
  - Headings for pages with long form content – Typography – Example - GOV.UK Design System
  - Word count – Character count – Example - GOV.UK Design System
  - Error message with Legend – Example - GOV.UK Design System
- `[component name] – Example - GOV.UK Design System`
  - Date input – Example - GOV.UK Design System
  - Details – Example - GOV.UK Design System
  - Exit this page – Example - GOV.UK Design System
- `Default – [component name] – Example - GOV.UK Design System`
  - Default – Cookie Banner – Example - GOV.UK Design System
- `[component name and example name as a sentence] – Example - GOV.UK Design System`
  - Checkboxes with 'none' option – Example - GOV.UK Design System
  - Small checkboxes – Example - GOV.UK Design System
  - Breadcrumbs that collapse on mobile – Example - GOV.UK Design System
  - Full page example – Example – GOV.UK Design System (this is an Error Summary example)
- `GOV.UK - [text]`
  - GOV.UK - The best place to find government services and information (page template example)
  - GOV.UK - Customised page template (page template example)

Of these, combining two of the options—having both a static style/component name and a more prosaic example name—might be a nice compromise.
