### ISSUE TITLE
Open links in a new window or tab

### ISSUE THREAD

**Issue by stevenaproctor** [alphagov/govuk-design-system#935]
## What

When and how to open links in a new window or tab.

## Why

It is used by more than one service in HMRC and in services across government. It has recently been discussed twice on cross-government Slack. There is nothing in the Design System about it or any content guidance. Although there is [content design link guidance](https://www.gov.uk/guidance/content-design/links) but it does not mention opening links in a new window or tab.

## Anything else

HMRC already has [documentation about this in our design system](http://hmrc.github.io/assets-frontend/components/open-links-in-a-new-window-or-tab/index.html) that gives advice about:

- when to use
- when not to use
- how it works
- an example
- code
- a Welsh translation
- research based on the Web Content Accessibility Guidelines

**Comment by spattisson** [comment]
Thanks for your input on this subject via xGov slack @joelanman. Just to draw it all into one place here, I'll quote you:

> We don’t yet have official guidance on this, but WCAG do
> https://www.w3.org/TR/WCAG20-TECHS/G200.html
> summary: avoid opening links in new tabs, and if you do, warn the user as per
> https://www.w3.org/TR/WCAG20-TECHS/G201.html

**Comment by hannalaakso** [comment]
This keeps coming up on user support so let's look at it again.

**Comment by timpaul** [comment]
A pull request for this work (https://github.com/alphagov/govuk-design-system/pull/1179) has been raised and approved by the Design System working

**Comment by Fenwick17** [comment]
I am aware this issue has been marked as closed, but I have a scenario that isn't specifically mentioned in the guidance for links in a new window or tab.

At NHS we have been looking into a situation where we are providing users with directions to a location as part of a transactional journey. This directions link is currently using Google Maps.

In regards to the content being used there are a couple of options "Get directions (opens in a new window or tab)" or "Get directions (opens in Google Maps)".
I think there is benefit to informing the user that it will open in Google maps, whether that is a tab, a window or an app in the case of android. But in that scenario we aren't telling a user about the new window or tab.

Wondering what peoples thoughts would be. Go with window/tab, google maps, or combine them both into something like "Get directions (opens in Google maps or a new window or tab)" but that is pretty wordy.

**Comment by vanitabarrett** [comment]
Hi @Fenwick17  - thank you for raising this. Unfortunately, as a team we’re not sure we have all the research and information to answer that question. 

I would suggest re-posting your comment on the [Typography backlog issue](https://github.com/alphagov/govuk-design-system-backlog/issues/64) to get the views of the community. Someone in the community may have come across this issue before and be able to share their own solution to the problem.

**Comment by hannalaakso** [comment]
We had a question support about whether it would be more appropriate to use "opens in new tab or window" (instead of the current "opens in new tab") in the link text since some users might have set their browser to open links in a new window rather than a tab.

I'm adding the below decision record for future reference:
> We wanted to keep the text as short as possible, and we think that most people read "new tab" as shorthand for "new tab or window", and not think that we're not doing something that will override their browser preferences. But if teams see something that suggests otherwise, it would be great if they could let us know.
