### ISSUE TITLE
Search button disappearing can be confusing for some users

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#937]
This issue is from a May 2019 external accessibility audit report.

**WCAG Reference**: Usability recommendation
**Issue ID**: DAC_4
**URL**: All pages

## Summary
The behaviour of the search button disappearing can cause confusion for users.

## Screen Shot
![](https://user-images.githubusercontent.com/2445413/58793362-d80d3b80-85ed-11e9-88ec-caac8d465823.png)

## Cognitive user comments
> “I was confused why the search button appeared before the search box as I would expect to enter search text then go to the button to perform the search. But when I entered text the button disappeared; I was confused by this.”

**Comment by nickcolley** [comment]
> “I was confused why the search button appeared before the search box as I would expect to enter search text then go to the button to perform the search. But when I entered text the button disappeared; I was confused by this.”

In regards to the cognitive user comments, I think we've had some feedback before that the icon is a bit confusing in the past...

We could consider making it a bit like DuckDuckGo: https://duckduckgo.com/?q=&t=hd

<img width="613" alt="Screen Shot 2019-06-18 at 17 55 27" src="https://user-images.githubusercontent.com/2445413/59703661-46f3b280-91f2-11e9-8e9e-d54317ebf47f.png">

When the input is not being used there's a search icon, if clicked on it'll focus the overall input.
<img width="318" alt="Screen Shot 2019-06-18 at 17 49 38" src="https://user-images.githubusercontent.com/2445413/59703367-9f768000-91f1-11e9-9e1a-11509498303b.png">

Different to DuckDuckGo the icon would not turn into a button, and just stick around.

<img width="339" alt="Screen Shot 2019-06-18 at 17 55 13" src="https://user-images.githubusercontent.com/2445413/59703649-3d6a4a80-91f2-11e9-9ed6-27157de0d8bc.png">

Here's an example of a few interactions:

![design-system-inline-icon-idea](https://user-images.githubusercontent.com/2445413/59703972-f761b680-91f2-11e9-8989-24e40a3edfe3.gif)

**Comment by aliuk2012** [comment]
GOV.UK Search has two different patterns : https://www.gov.uk/search/news-and-communications
![image](https://user-images.githubusercontent.com/3441519/60972199-adfe1600-a31d-11e9-9f77-67a54917c09b.png)
