### ISSUE TITLE
Beta banner is confusing when placed in between menu button and menu items

### ISSUE THREAD

**Issue by NickColley** [alphagov/govuk-design-system#939]
This issue is from a May 2019 external accessibility audit report.

**WCAG Reference**: Usability feedback
**Issue ID**: DAC_4
**URL**: All pages

## Summary
When using a screen reader it is confusing to find the beta banner after the menu button instead of the menu items.

> While swiping through the page with VoiceOver for iPhone I located a button which read as ‘Toggle mobile menu’. I selected the button and discovered that content opened further down the page. Although an indication was provided that the content had expanded, I needed to swipe multiple times to locate the new content, with the beta information situated between the menu button and the menu content. This could mean that users do not immediately locate the information and may become confused. Ensuring that either the users focus is taken to the menu, or alternatively that the user is able to locate the menu on the next swipe forward will avoid this potential confusion.”

## Screenshot
<img width="479" alt="" src="https://user-images.githubusercontent.com/2445413/60201691-c7dd2a80-9840-11e9-819c-dc4b36930f0a.png">

**Comment by nickcolley** [comment]
Had a quick peak at this and if you only move this for the mobile navigation it's not too difficult...
