### ISSUE TITLE
Sass syntax errors are not surfaced in dev environment

### ISSUE THREAD

**Issue by 36degrees** [alphagov/govuk-design-system#985]
If you e.g. make a typo and use a variable name incorrectly, you'll no longer be able to view pages in the dev environment, instead you'll just see:

```
Cannot GET /styles/page-template/
```

The Sass error is not surfaced in the console.

The only way to find out what the error is is to kill the running `npm start` process and re-start it, at which point the Sass error will finally be visible in the console and `npm start` will exit with an error code.

**Comment by webketje** [comment]
Sass error terminates the process in latest main

**Comment by 36degrees** [comment]
It'd be better I think if it didn't terminate the process, but I'm not sure what the behaviour should be in the browser – maybe the Sass error should be surfaced there?

But I do think the issue as described here is resolved so we can close this out.

**Comment by webketje** [comment]
@36degrees unverified, but if I'm not mistaken this can be changed at the user's end in the build callback, e.g.
```js
metalsmith .build(function(err, files) {
  if (err) {
    // inaccurate example, find the proper distinguishing factor for Sass errors
    if (err.name === 'SASS') { console.log(err) }
    else throw err
  }
})
```
