### ISSUE TITLE
Investigate if navigation styles should use new focus hover

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-design-system#987]
When updating the navigation styles to the new focus we remove the hover state from links, is this what we want to do or should we keep them simple and consistent with the dark blue hover?

https://github.com/alphagov/govuk-design-system/pull/977#issuecomment-513244512

**Comment by dashouse** [comment]
Sorry I saw this issue after the other comment: 

"No, I was trying to follow the Header / Footer behaviour for navigation.

Inline links: Underline, dark blue on hover, purple visited
Navigational links: No underline, underline on hover, border(style) current state, no visited state"

**Comment by nickcolley** [comment]
Makes sense thanks for the clarification.
